My Project: SpotLight Class Reference
SpotLight Class Reference
#include <SpotLight.hpp>
Public Member Functions
SpotLight ()
Construct a new Spot Light object.
SpotLight (GLuint shadowWidth, GLuint shadowHeight, GLfloat near, GLfloat far, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity, glm::vec3 position, glm::vec3 direction, GLfloat constant, GLfloat linear, GLfloat exponent, GLfloat edge)
Construct a new Spot Light object.
void UseLight (GLuint ambientColorLoc, GLuint ambientIntensityLoc, GLuint diffuseIntensityLoc, GLuint positionLoc, GLuint directionLoc, GLuint constantLoc, GLuint linearLoc, GLuint exponentLoc, GLuint edgeLoc) const
Enables the spotlight by passing uniforms to the shader.
void SetFlash (glm::vec3 pos, glm::vec3 dir)
Sets the position and the direction of the spotlight.
Public Member Functions inherited from PointLight
PointLight ()
Construct a new Point Light object.
PointLight (GLuint shadowWidth, GLuint shadowHeight, GLfloat near, GLfloat far, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity, glm::vec3 position, GLfloat constant, GLfloat linear, GLfloat exponent)
Construct a new Point Light object.
void UseLight (GLuint ambientColorLoc, GLuint ambientIntensityLoc, GLuint diffuseIntensityLoc, GLuint positionLoc, GLuint constantLoc, GLuint linearLoc, GLuint exponentLoc) const
Enables the light by passing uniforms to the shader.
std::vector< glm::mat4 > CalculateLightTransform () const
Calculates the light transform matrices.
GLfloat GetFarPlane () const
Get the Far Plane.
glm::vec3 GetPosition () const
Get the Position.
~PointLight ()
Destroy the Point Light object.
Public Member Functions inherited from Light
Light ()
Default constructor.
Light (GLuint shadowWidth, GLuint shadowHeight, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity)
Parameterized constructor.
ShadowMap * GetShadowMap () const
Returns a pointer to the shadow map.
virtual ~Light ()
Destructor.
Private Attributes
glm::vec3 m_direction
GLfloat m_procEdge
Additional Inherited Members
Protected Attributes inherited from PointLight
glm::vec3 m_position
Position of the light.
GLfloat m_constant
Equation of the light.
GLfloat m_linear
GLfloat m_exponent
GLfloat m_farPlane
The far plane.
Protected Attributes inherited from Light
glm::vec3 m_color
The color of the ambient lighting.
GLfloat m_ambientIntensity
The intensity of the ambient lighting.
GLfloat m_diffuseIntensity
The intensity of the diffuse lighting.
glm::mat4 m_lightProj
The light projection.
ShadowMap * m_shadowMap
Shadow map.
Detailed Description
Definition at line 9 of file SpotLight.hpp.
Constructor & Destructor Documentation
SpotLight() [1/2]
SpotLight::SpotLight ()
Construct a new Spot Light object.
Definition at line 3 of file SpotLight.cpp.
     : PointLight(), m_direction(glm::vec3(0.0f, -1.0f, 0.0f)), m_procEdge(0.0f)
 {}
References PointLight::PointLight(), and SpotLight().
Referenced by SpotLight().
SpotLight() [2/2]
SpotLight::SpotLight (GLuint shadowWidth, GLuint shadowHeight, GLfloat near, GLfloat far, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity, glm::vec3 position, glm::vec3 direction, GLfloat constant, GLfloat linear, GLfloat exponent, GLfloat edge)
Construct a new Spot Light object.
Parameters
shadowWidth
shadowHeight
near
far
color
aIntensity
dIntensity
position
direction
constant
linear
exponent
edge
Definition at line 7 of file SpotLight.cpp.
     : PointLight(shadowWidth, shadowHeight, near, far, color, aIntensity, dIntensity, position, constant, linear, exponent),
         m_direction(glm::normalize(direction)), m_procEdge(cosf(glm::radians(edge)))
 {}
Member Function Documentation
SetFlash()
void SpotLight::SetFlash (glm::vec3 pos, glm::vec3 dir)
Sets the position and the direction of the spotlight.
Parameters
pos
dir
Definition at line 35 of file SpotLight.cpp.
 {
     m_position = pos;
     m_direction = dir;
 }
UseLight()
void SpotLight::UseLight (GLuint ambientColorLoc, GLuint ambientIntensityLoc, GLuint diffuseIntensityLoc, GLuint positionLoc, GLuint directionLoc, GLuint constantLoc, GLuint linearLoc, GLuint exponentLoc, GLuint edgeLoc) const
Enables the spotlight by passing uniforms to the shader.
Parameters
ambientColorLoc
ambientIntensityLoc
diffuseIntensityLoc
positionLoc
directionLoc
constantLoc
linearLoc
exponentLoc
edgeLoc
Definition at line 17 of file SpotLight.cpp.
 {
     glUniform3f(ambientColorLoc, m_color.x, m_color.y, m_color.z);
     glUniform1f(ambientIntensityLoc, m_ambientIntensity);
     glUniform1f(diffuseIntensityLoc, m_diffuseIntensity);
     glUniform3f(positionLoc, m_position.x, m_position.y, m_position.z);
     glUniform1f(constantLoc, m_constant);
     glUniform1f(linearLoc, m_linear);
     glUniform1f(exponentLoc, m_exponent);
     glUniform3f(directionLoc, m_direction.x, m_direction.y, m_direction.z);
     glUniform1f(edgeLoc, m_procEdge);
 }
Member Data Documentation
m_direction
glm::vec3 SpotLight::m_direction private
Definition at line 65 of file SpotLight.hpp.
m_procEdge
GLfloat SpotLight::m_procEdge private
Definition at line 67 of file SpotLight.hpp.
The documentation for this class was generated from the following files:
View/Renderer/OpenGL/Objects/SpotLight.hpp
View/Renderer/OpenGL/Objects/SpotLight.cpp