My Project: DirectionalLight Class Reference
DirectionalLight Class Reference
A directional light that provides global illumination.
#include <DirectionalLight.hpp>
Public Member Functions
DirectionalLight ()
Default constructor.
DirectionalLight (GLfloat shadowWidth, GLfloat shadowHeight, glm::vec3 color, GLfloat aIntensity, glm::vec3 direction, GLfloat dIntensity)
Parameterized constructor.
void UseLight (GLuint ambientColorLoc, GLuint ambientIntensityLoc, GLuint directionLoc, GLuint diffuseIntensityLoc) const
Enables the light by passing the uniforms to the shader.
glm::mat4 CalculateLightTransform () const
Calculate the transformation matrix of the light.
~DirectionalLight ()
Destructor.
Public Member Functions inherited from Light
Light ()
Default constructor.
Light (GLuint shadowWidth, GLuint shadowHeight, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity)
Parameterized constructor.
ShadowMap * GetShadowMap () const
Returns a pointer to the shadow map.
virtual ~Light ()
Destructor.
Private Attributes
glm::vec3 m_direction
The direction the light is facing.
Additional Inherited Members
Protected Attributes inherited from Light
glm::vec3 m_color
The color of the ambient lighting.
GLfloat m_ambientIntensity
The intensity of the ambient lighting.
GLfloat m_diffuseIntensity
The intensity of the diffuse lighting.
glm::mat4 m_lightProj
The light projection.
ShadowMap * m_shadowMap
Shadow map.
Detailed Description
A directional light that provides global illumination.
Definition at line 9 of file DirectionalLight.hpp.
Constructor & Destructor Documentation
DirectionalLight() [1/2]
DirectionalLight::DirectionalLight ()
Default constructor.
Definition at line 3 of file DirectionalLight.cpp.
     : Light(), m_direction(glm::vec3(0.0f, -1.0f, 0.0f)) {}
References DirectionalLight(), and Light::Light().
Referenced by DirectionalLight().
DirectionalLight() [2/2]
DirectionalLight::DirectionalLight (GLfloat shadowWidth, GLfloat shadowHeight, glm::vec3 color, GLfloat aIntensity, glm::vec3 direction, GLfloat dIntensity)
Parameterized constructor.
Parameters
shadowWidth
shadowHeight
color
aIntensity
direction
dIntensity
Definition at line 6 of file DirectionalLight.cpp.
     : Light(shadowWidth, shadowHeight, color, aIntensity, dIntensity) {
     m_direction = direction;
     m_lightProj = glm::ortho(-10.0f, 10.0f, 10.0f, -10.0f, 0.1f, 100.0f);
 }
References DirectionalLight().
Referenced by DirectionalLight().
~DirectionalLight()
DirectionalLight::~DirectionalLight ()
Destructor.
Definition at line 30 of file DirectionalLight.cpp.
 {}
Member Function Documentation
CalculateLightTransform()
glm::mat4 DirectionalLight::CalculateLightTransform () const
Calculate the transformation matrix of the light.
Returns
glm::mat4
Definition at line 25 of file DirectionalLight.cpp.
{
     return m_lightProj * glm::lookAt(-m_direction, glm::vec3(0.0f, 0.0f, 0.0f),
                                      glm::vec3(0.0f, 1.0f, 0.0f));
 }
UseLight()
void DirectionalLight::UseLight (GLuint ambientColorLoc, GLuint ambientIntensityLoc, GLuint directionLoc, GLuint diffuseIntensityLoc) const
Enables the light by passing the uniforms to the shader.
Parameters
ambientColorLoc
ambientIntensityLoc
directionLoc
diffuseIntensityLoc
Definition at line 15 of file DirectionalLight.cpp.
{
     glUniform3f(ambientColorLoc, m_color.x, m_color.y, m_color.z);
     glUniform1f(ambientIntensityLoc, m_ambientIntensity);
     glUniform3f(directionLoc, m_direction.x, m_direction.y, m_direction.z);
     glUniform1f(diffuseIntensityLoc, m_diffuseIntensity);
 }
Member Data Documentation
m_direction
glm::vec3 DirectionalLight::m_direction private
The direction the light is facing.
Definition at line 56 of file DirectionalLight.hpp.
The documentation for this class was generated from the following files:
View/Renderer/OpenGL/Objects/DirectionalLight.hpp
View/Renderer/OpenGL/Objects/DirectionalLight.cpp