My Project: Body Class Reference
Body Class Reference
#include <Body.hpp>
Public Member Functions
void init ()
Initialises the body object.
void setCreator (bool val)
Sets if the object is a creator (true) or destructor (false). A creator should be one of the fist game objects while a destoryer should be one of the last.
void update (float delta_time)
Updates the body object using a delta time value.
void add_draw_call ()
NOT CURRENTLY USED.
void draw (std::shared_ptr< Shader > shader)
NOT CURRENTLY USED.
void physicsDebugger ()
Adds all possible physic debugger options.
void physicsWorldDestroyer ()
Destoryes physic world.
void save_object () override
Saves the object to lau file.
~Body ()
Destructor.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
bool creator = true
True if creator, false if destroyer
Additional Inherited Members
Public Attributes inherited from GameObject
struct {
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01
};
Detailed Description
Definition at line 8 of file Body.hpp.
Constructor & Destructor Documentation
~Body()
Body::~Body ()
Destructor.
Precondition
Must be destoryer body object variant
Postcondition
Body object deleted
Definition at line 44 of file Body.cpp.
 { physicsWorldDestroyer(); }
References physicsWorldDestroyer().
Member Function Documentation
add_draw_call()
void Body::add_draw_call () inline virtual
NOT CURRENTLY USED.
Precondition
Nothing
Postcondition
Nothing
Implements GameObject.
Reimplemented in PhysicsObject, Player, and BodyRigid.
Definition at line 44 of file Body.hpp.
 {}
draw()
void Body::draw (std::shared_ptr< Shader > shader) inline virtual
NOT CURRENTLY USED.
Parameters
shader - the shader
Precondition
Nothing
Postcondition
Nothing
Implements GameObject.
Reimplemented in PhysicsObject, Player, and BodyRigid.
Definition at line 53 of file Body.hpp.
 {}
init()
void Body::init () virtual
Initialises the body object.
Precondition
Must be creator body object variant
Postcondition
Body object created
Implements GameObject.
Reimplemented in BodyRigid, and Player.
Definition at line 3 of file Body.cpp.
                 {
     if (creator == true) {
         Physics::createWorld();
     }
 }
References Physics::createWorld(), and creator.
Referenced by GameAssetFactory::loadBody().
physicsDebugger()
void Body::physicsDebugger ()
Adds all possible physic debugger options.
Precondition
Object initialised
Postcondition
Physic objects added
Definition at line 23 of file Body.cpp.
{
     Physics::setDebuggerToActive(true);
     Physics::setDebuggerValues(1, true);
     Physics::setDebuggerValues(2, true);
     Physics::setDebuggerValues(4, true);
     Physics::setDebuggerValues(8, true);
     Physics::setDebuggerValues(16, true);
 }
References Physics::setDebuggerToActive(), and Physics::setDebuggerValues().
physicsWorldDestroyer()
void Body::physicsWorldDestroyer ()
Destoryes physic world.
Precondition
Must be destroyer body object variant
Postcondition
Body object destroyed
Definition at line 17 of file Body.cpp.
{
     if (creator == false) {
         Physics::destoryWorld();
     }
 }
References creator, and Physics::destoryWorld().
Referenced by ~Body().
save_object()
void Body::save_object () override virtual
Saves the object to lau file.
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Reimplemented in BodyRigid, PhysicsObject, and Player.
Definition at line 35 of file Body.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "Body");
     ObjectSaving::addComma();
     ObjectSaving::addValue("creator", creator, true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::addComma(), ObjectSaving::addValue(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), creator, and ObjectSaving::openFile().
setCreator()
void Body::setCreator (bool val)
Sets if the object is a creator (true) or destructor (false). A creator should be one of the fist game objects while a destoryer should be one of the last.
Parameters
val - true for creator, false for destructor
Precondition
Object initialised
Postcondition
Creator set
Definition at line 33 of file Body.cpp.
 { creator = val; }
References creator.
Referenced by GameAssetFactory::loadBody().
update()
void Body::update (float delta_time) virtual
Updates the body object using a delta time value.
Parameters
delta_time - The time between the last call
Precondition
Object initialised
Postcondition
Object updated
Implements GameObject.
Reimplemented in BodyRigid, PhysicsObject, and Player.
Definition at line 9 of file Body.cpp.
{
     if (creator == true) {
         if (GenericFunctions::getIfPaused() == false) {
             Physics::updateWorld(delta_time);
         }
     }
 }
References creator, GenericFunctions::getIfPaused(), and Physics::updateWorld().
Member Data Documentation
creator
bool Body::creator = true private
True if creator, false if destroyer
Definition at line 91 of file Body.hpp.
Referenced by init(), physicsWorldDestroyer(), save_object(), setCreator(), and update().
The documentation for this class was generated from the following files:
Model/GameObject/Body.hpp
Model/GameObject/Body.cpp