My Project: Physics Namespace Reference
Physics Namespace Reference
Functions
void createWorld ()
Creates the world for the physic objects.
void updateWorld (float delta_time)
Updates the world for the physic objects.
void setDebuggerToActive (bool val)
Sets which debugger to active.
void setDebuggerValues (int type, bool val)
Can set different debug values to be returned.
void destoryWorld ()
Creates the world for the physic objects.
PhysicsCommon & getPhysicsCommon ()
Returns physics common game object.
PhysicsWorld * getPhysicsWorld ()
Returns physics world game object.
bool WorldExsists ()
Returns if the physics world is created or not.
Function Documentation
createWorld()
void Physics::createWorld ()
Creates the world for the physic objects.
Precondition
Nothing
Postcondition
World is created & ready to use
Definition at line 6 of file Physics.cpp.
{
     if (created == false) {
         world = physicsCommon.createPhysicsWorld();
         created = true;
     }
 }
References created.
Referenced by Body::init().
destoryWorld()
void Physics::destoryWorld ()
Creates the world for the physic objects.
Precondition
World is created
Postcondition
World is destoryed
Definition at line 35 of file Physics.cpp.
{
     if (created == true) {
         physicsCommon.destroyPhysicsWorld(world);
         created = false;
     }
 }
References created.
Referenced by Body::physicsWorldDestroyer().
getPhysicsCommon()
PhysicsCommon & Physics::getPhysicsCommon ()
Returns physics common game object.
Returns
&PhysicsCommon - The physics common object
Precondition
Nothing
Postcondition
Nothing
Definition at line 42 of file Physics.cpp.
 { return physicsCommon; }
getPhysicsWorld()
PhysicsWorld * Physics::getPhysicsWorld ()
Returns physics world game object.
Returns
*PhysicsWorld - The physics world
Precondition
Nothing
Postcondition
Nothing
Definition at line 44 of file Physics.cpp.
 { return world; }
setDebuggerToActive()
void Physics::setDebuggerToActive (bool val)
Sets which debugger to active.
Parameters
val - true if you want it activated
Precondition
World has been created
Postcondition
Debugger activated/deactivated
Definition at line 20 of file Physics.cpp.
{
     if (created == false) {
         return;
     }
     world->setIsDebugRenderingEnabled(true);
 }
References created.
Referenced by Body::physicsDebugger().
setDebuggerValues()
void Physics::setDebuggerValues (int type, bool val)
Can set different debug values to be returned.
Collider AABB = 1 Collider Broadphase AABB = 2 Collision Shape = 4 Contact Normal = 16 Contact Point = 8
Parameters
type - The type of debugger to add
val - true if you want to add it / use it
Precondition
Nothing
Postcondition
Debugger will use/not use the value
Definition at line 27 of file Physics.cpp.
{
     if (created == false) {
         return;
     }
     DebugRenderer& debugRenderer = world->getDebugRenderer();
     debugRenderer.setIsDebugItemDisplayed((DebugRenderer::DebugItem)type, val);
 }
References created.
Referenced by Body::physicsDebugger().
updateWorld()
void Physics::updateWorld (float delta_time)
Updates the world for the physic objects.
Parameters
delta_time - Time since the last update
Precondition
World has been created
Postcondition
World has been updated
Definition at line 13 of file Physics.cpp.
{
     if (created == false) {
         return;
     }
     world->update(delta_time);
 }
References created.
Referenced by Body::update().
WorldExsists()
bool Physics::WorldExsists ()
Returns if the physics world is created or not.
Returns
bool - If the physics world exsists
Precondition
Nothing
Postcondition
Nothing
Definition at line 46 of file Physics.cpp.
 { return created; }
References created.
Referenced by BodyRigidPhysics::~BodyRigidPhysics().