addGameObject("scripts/creator.lua")
addGameObject("scripts/Cat.lua")
addGameObject("scripts/Water.lua")
addGameObject("scripts/CatPhysics.lua")
addGameObject("scripts/CatPhysics2.lua")
addGameObject("scripts/destroyer.lua")