loadTextureRGB("water", "textures/water.png")
loadModel("cat", "models/12221_Cat_v1_l3.obj")
loadModel("tree","models/Tree_Dry_1.obj")
loadModel("rock","models/rock1.obj")
loadModel("human","models/Soldier.obj")
loadModel("arrow","models/Arrow.obj")
loadModel("bow","models/bowOBJ.obj")
loadModel("boat","models/boat1obj.obj")
loadModel("lighthouse","models/Beacon.obj")