baseObject = {
	type = "PhysicsObject",
	xPos = camera_pos_x() + camera_look_x() * 2,
	yPos = camera_pos_y() + camera_look_y() * 2,
	zPos = camera_pos_z() + camera_look_z() * 2,
	xRotation = camera_look_x(),
	yRotation = camera_look_x(),
	zRotation = camera_look_x(),
	angle = -90,
	xScale = 1,
	yScale = 1,
	zScale = 1,
	modelName = "arrow",
	material_name = "shiny",
	rbType = 2,
	gravity = 1,
	xForce = camera_look_x() * 25,
	yForce = camera_look_y() * 25,
	zForce = camera_look_z() * 25,
	xTorque = 0,
	yTorque = 0,
	zTorque = 0,
	linearDamping = 0.1,
	angularDamping = 0.1,
	sleep = 1,
	numOfColliders = 1
}

collider1 = {
	colliderType = "Box",
	xPos = 0,
	yPos = 0,
	zPos = 0,
	xBox = 1,
	yBox = 1,
	zBox = 1,
	bounciness = 0.5,
	friction = 0.5
}
