
if get_help_menu() then
	gui_setWindowSize(250, 260, 1)
	gui_setWindowPos(300, 0, 1)
	gui_begin("Help Menu")
	gui_text("Controls:")
	gui_text(" - Pause 		: esc")
	gui_text(" - Help		: m")
	gui_text(" - Exit		: x")
	gui_text(" - Wireframe	: k")
	gui_text(" - Movement	: WASD")
	gui_text(" - Look		: Mouse")
	gui_text(" - Shoot		: Space")
	gui_text(" - Networking	: n")
	gui_text(" - PvP		: p")
	gui_text("Objective:")
	gui_text(" - Make it off the island")
	gui_text(" - Shoot to distract ducks")
	gui_text(" - Find the boat")
	gui_end()
end