add_game_object("scripts/ECSScene/Cat.lua")
add_game_object("scripts/ECSScene/moonlight.lua")
add_game_object("scripts/ECSScene/player.lua")
add_game_object("scripts/ECSScene/flashlight.lua")
add_game_object("scripts/ECSScene/boat.lua")
add_game_object("scripts/ECSScene/escape_boat.lua")
add_game_object("scripts/ECSScene/lighthouse.lua")
add_game_object("scripts/ECSScene/water.lua")
add_game_object("scripts/ECSScene/big_arrow.lua")

Skybox.use_skybox("nightsky")
