ICT397 Assignment 2: Skybox Class Reference
Skybox Class Reference
A skybox.
#include <Skybox.hpp>
Public Member Functions
Skybox ()
Construct a new Skybox object.
Skybox (const std::vector< std::string > &faceLocations)
Construct a new Skybox object.
void DrawSkybox (glm::mat4 projectionMatrix, glm::mat4 viewMatrix)
Renders the skybox given a projection and view matrix.
Private Attributes
Mesh * m_skyMesh
The mesh of the skybox.
Shader * m_skyShader
The shader of the skybox.
GLuint m_textureID
The locations of the faces of the skybox.
GLuint m_uniformProjection
The uniform projection and view.
GLuint m_uniformView
Detailed Description
A skybox.
Definition at line 21 of file Skybox.hpp.
Constructor & Destructor Documentation
Skybox() [1/2]
Skybox::Skybox ()
Construct a new Skybox object.
Definition at line 3 of file Skybox.cpp.
 {}
Skybox() [2/2]
Skybox::Skybox (const std::vector< std::string > & faceLocations)
Construct a new Skybox object.
Parameters
faceLocations The locations of the faces of the skybox.
Definition at line 5 of file Skybox.cpp.
{
     m_skyShader = new Shader();
     m_skyShader->CompileFile("shaders/skybox.vert", "shaders/skybox.frag");
     m_uniformProjection = m_skyShader->GetProjectionLocation();
     m_uniformView = m_skyShader->GetViewLocation();
     glGenTextures(1, &m_textureID);
     glBindTexture(GL_TEXTURE_CUBE_MAP, m_textureID);
     int width, height, bitDepth;
     for (size_t i = 0; i < 6; ++i) {
         unsigned char* texData =
             stbi_load(faceLocations[i].c_str(), &width, &height, &bitDepth, 0);
         if (!texData) {
             std::cout << "Failed to load image " << faceLocations[i]
                       << std::endl;
             return;
         }
         glTexImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, GL_RGB, width,
                      height, 0, GL_RGB, GL_UNSIGNED_BYTE, texData);
         stbi_image_free(texData);
     }
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     // Mesh Setup
     const uint32_t skyboxIndices[] = {// front
                                       0, 1, 2, 2, 1, 3,
                                       // right
                                       2, 3, 5, 5, 3, 7,
                                       // back
                                       5, 7, 4, 4, 7, 6,
                                       // left
                                       4, 6, 0, 0, 6, 1,
                                       // top
                                       4, 0, 5, 5, 0, 2,
                                       // bottom
                                       1, 6, 3, 3, 6, 7};
     const float skyboxVertices[] = {
         -1.0f, 1.0f,  -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
         -1.0f, -1.0f, -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
         1.0f,  1.0f,  -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
         1.0f,  -1.0f, -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
         -1.0f, 1.0f,  1.0f,  0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
         1.0f,  1.0f,  1.0f,  0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
         -1.0f, -1.0f, 1.0f,  0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
         1.0f,  -1.0f, 1.0f,  0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
     m_skyMesh = new Mesh();
     m_skyMesh->CreateMesh(skyboxVertices, skyboxIndices, 64, 36);
 }
References Shader::CompileFile(), m_skyShader, Shader::Shader(), and Shader::uniformLightMatrices.
Member Function Documentation
DrawSkybox()
void Skybox::DrawSkybox (glm::mat4 projectionMatrix, glm::mat4 viewMatrix)
Renders the skybox given a projection and view matrix.
Parameters
projectionMatrix The projection matrix.
viewMatrix The view matrix.
Definition at line 68 of file Skybox.cpp.
{
     viewMatrix = glm::mat4(glm::mat3(viewMatrix));
     glDepthMask(GL_FALSE);
     m_skyShader->UseShader();
     glUniformMatrix4fv(m_uniformProjection, 1, GL_FALSE,
                        glm::value_ptr(projectionMatrix));
     glUniformMatrix4fv(m_uniformView, 1, GL_FALSE, glm::value_ptr(viewMatrix));
     glActiveTexture(GL_TEXTURE0);
     glBindTexture(GL_TEXTURE_CUBE_MAP, m_textureID);
     m_skyShader->Validate();
     m_skyMesh->RenderMesh();
     glDepthMask(GL_TRUE);
 }
References m_skyShader, Shader::UseShader(), and Shader::Validate().
Member Data Documentation
m_skyMesh
Mesh* Skybox::m_skyMesh private
The mesh of the skybox.
Definition at line 45 of file Skybox.hpp.
m_skyShader
Shader* Skybox::m_skyShader private
The shader of the skybox.
Definition at line 48 of file Skybox.hpp.
Referenced by DrawSkybox(), and Skybox().
m_textureID
GLuint Skybox::m_textureID private
The locations of the faces of the skybox.
Definition at line 51 of file Skybox.hpp.
m_uniformProjection
GLuint Skybox::m_uniformProjection private
The uniform projection and view.
Definition at line 54 of file Skybox.hpp.
m_uniformView
GLuint Skybox::m_uniformView private
Definition at line 54 of file Skybox.hpp.
The documentation for this class was generated from the following files:
src/View/Renderer/OpenGL/Objects/Skybox.hpp
src/View/Renderer/OpenGL/Objects/Skybox.cpp