ICT397 Assignment 2: Water Class Reference
Water Class Reference
A water game object.
#include <Water.hpp>
Public Member Functions
Water (std::string &text)
Constructor used to set a texture and leave rest as default.
Water (std::string &text, glm::vec3 pos, glm::vec3 scale, glm::vec3 offMult)
Constructor used to set a texture, pos, scale & offMult.
void init () override
Initialises the water.
void update (double delta_time) override
Updates the water object.
void fixed_update (double delta_time) override
Updates the body object with fixed delta time.
void add_draw_call () override
Adds a draw call for the water object.
void draw (std::shared_ptr< Shader > shader) override
Initialises the water.
void setIntensity (glm::vec3 scale)
Initialises the water.
void setOffsetMult (glm::vec3 offMult)
Initialises the water.
void setTotalTime (float time)
void save_object () override
Saves the object to lau file.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
double m_time = 0
Total time run
glm::vec3 m_pos = {0, 0, 0}
Position of the new water after update
glm::vec3 m_intensity = {5, 10, 5}
Intensity of the water movement
glm::vec3 m_offsetMult = {1.1, 1.2, 1.7}
Multipler for the water offset
std::string m_textureName
The texture of the water
Mesh m_mesh
The mesh of the water
Mesh m_mesh_under
Underneath mesh of the water
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Detailed Description
A water game object.
Definition at line 14 of file Water.hpp.
Constructor & Destructor Documentation
Water() [1/2]
Water::Water (std::string & text)
Constructor used to set a texture and leave rest as default.
Parameters
&text - The texture you want to add
Precondition
The texture has been created
Postcondition
A water object will be ready
Definition at line 5 of file Water.cpp.
{
     m_textureName = text;
     init();
 }
References init().
Water() [2/2]
Water::Water (std::string & text, glm::vec3 pos, glm::vec3 scale, glm::vec3 offMult)
Constructor used to set a texture, pos, scale & offMult.
Parameters
&text - The texture you want to add
pos - The position of the center of the water
scale - The intensity of the water movement (i.e. how height/to the side it moves)
offMult - Offset multiplier, change how fast it moves on each axis for more random look
Precondition
The texture has been created & pos, scale, offMult have all been set
Postcondition
A water object will be ready
Definition at line 10 of file Water.cpp.
{
     m_time = 0;
     position = pos;
     setIntensity(scale);
     m_offsetMult = offMult;
     m_textureName = text;
     init();
 }
References init(), and m_time.
Member Function Documentation
add_draw_call()
void Water::add_draw_call () override virtual
Adds a draw call for the water object.
Parameters
No param
Returns
Void
Precondition
Water object has been created
Postcondition
Adds to draw call
Implements GameObject.
Definition at line 50 of file Water.cpp.
{
     DrawCall draw_call = [=](std::shared_ptr<Shader> shader) { draw(shader); };
     ReflexEngine::get_instance().renderer_.add_draw_call(draw_call);
 }
draw()
void Water::draw (std::shared_ptr< Shader > shader) override virtual
Initialises the water.
Parameters
shader - the shader in use
Returns
Void
Precondition
Water object is created & draw call has been added
Postcondition
Water object displayed to screen
Implements GameObject.
Definition at line 56 of file Water.cpp.
{
     auto default_shader = ReflexEngine::get_instance().renderer_.get_shader();
     glm::mat4 model(1.0f);
     model = glm::translate(model, m_pos);
     model = glm::scale(model, glm::vec3(100, 1, 100));
     glUniformMatrix4fv(shader->GetModelLocation(), 1, GL_FALSE,
                        glm::value_ptr(model));
     glUniform1i(shader->GetUsingTexture(), true);
     TextureManager &tm = ResourceManager::get_instance().get_texture_manager();
     const Texture &t = tm.get_texture(m_textureName);
     t.UseTexture();
     m_mesh.RenderMesh();
     m_mesh_under.RenderMesh();
 }
References ResourceManager::get_instance(), ResourceManager::get_texture_manager(), and Texture::UseTexture().
fixed_update()
void Water::fixed_update (double delta_time) inline override virtual
Updates the body object with fixed delta time.
Parameters
delta_time
Implements GameObject.
Definition at line 65 of file Water.hpp.
 {}
init()
void Water::init () override virtual
Initialises the water.
Parameters
No param
Returns
Void
Precondition
Texture must have been set
Postcondition
Water object ready to be used
Implements GameObject.
Definition at line 21 of file Water.cpp.
                  {
     float verts[] = {-10.0f, 0.0f, -10.0f, 0.0f,   0.0f,   0.0f, -1.0f, 0.0f,
                      10.0f,  0.0f, -10.0f, 100.0f, 0.0f,   0.0f, -1.0f, 0.0f,
                      -10.0f, 0.0f, 10.0f,  0.0f,   100.0f, 0.0f, -1.0f, 0.0f,
                      10.0f,  0.0f, 10.0f,  100.0f, 100.0f, 0.0f, -1.0f, 0.0f};
     uint32_t order[6] = {0u, 2u, 1u, 1u, 2u, 3u};
     m_mesh.CreateMesh(verts, order, 32, 6);
     verts[6] = 1.0f;
     verts[14] = 1.0f;
     verts[22] = 1.0f;
     verts[30] = 1.0f;
     const uint32_t orderTwo[6] = {0u, 1u, 2u, 1u, 3u, 2u};
     m_mesh_under.CreateMesh(verts, orderTwo, 32, 6);
 }
Referenced by Water().
save_object()
void Water::save_object () override virtual
Saves the object to lau file.
Parameters
No param
Returns
Void
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 92 of file Water.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "Water");
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("water");
     ObjectSaving::addValue("textureName", m_textureName, false);
     ObjectSaving::addValue("xMult", m_offsetMult.x, false);
     ObjectSaving::addValue("yMult", m_offsetMult.y, false);
     ObjectSaving::addValue("zMult", m_offsetMult.z, false);
     ObjectSaving::addValue("xIntensity", m_intensity.x, false);
     ObjectSaving::addValue("yIntensity", m_intensity.y, false);
     ObjectSaving::addValue("zIntensity", m_intensity.z, false);
     ObjectSaving::addValue("time", (float)m_time, true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::closeFile(), ObjectSaving::closeStruct(), and ObjectSaving::openFile().
setIntensity()
void Water::setIntensity (glm::vec3 scale)
Initialises the water.
Parameters
scale - Vector of intensity of water movement
Returns
Void
Precondition
Water object has been created & scale cannot be 0 on any axis
Postcondition
Intensity of water movement set
Definition at line 75 of file Water.cpp.
{
     m_intensity = scale;
     if (m_intensity.x == 0) {
         m_intensity.x = 1;
     }
     if (m_intensity.y == 0) {
         m_intensity.y = 1;
     }
     if (m_intensity.z == 0) {
         m_intensity.z = 1;
     }
 }
setOffsetMult()
void Water::setOffsetMult (glm::vec3 offMult)
Initialises the water.
Parameters
offMult - Vector of the offset multipler
Returns
Void
Precondition
Water object has been created
Postcondition
Offset of water movement set
Definition at line 88 of file Water.cpp.
 { m_offsetMult = offMult; }
setTotalTime()
void Water::setTotalTime (float time)
Definition at line 90 of file Water.cpp.
 { m_time = time; }
References m_time.
Referenced by GameAssetFactory::loadWater().
update()
void Water::update (double delta_time) override virtual
Updates the water object.
Parameters
delta_time - The time between frames
Returns
Void
Precondition
Water object has been created
Postcondition
Water position moved according to time difference
Implements GameObject.
Definition at line 38 of file Water.cpp.
{
     m_time += delta_time;
     float x = sin(m_time * m_offsetMult.x) / m_intensity.x;
     float y = sin(m_time * m_offsetMult.y) / m_intensity.y;
     float z = sin(m_time * m_offsetMult.z) / m_intensity.z;
     m_pos.x = position.x + x;
     m_pos.y = position.y + y;
     m_pos.z = position.z + z;
 }
References m_time.
Member Data Documentation
m_intensity
glm::vec3 Water::m_intensity = {5, 10, 5} private
Intensity of the water movement
Definition at line 133 of file Water.hpp.
m_mesh
Mesh Water::m_mesh private
The mesh of the water
Definition at line 148 of file Water.hpp.
m_mesh_under
Mesh Water::m_mesh_under private
Underneath mesh of the water
Definition at line 153 of file Water.hpp.
m_offsetMult
glm::vec3 Water::m_offsetMult = {1.1, 1.2, 1.7} private
Multipler for the water offset
Definition at line 138 of file Water.hpp.
m_pos
glm::vec3 Water::m_pos = {0, 0, 0} private
Position of the new water after update
Definition at line 128 of file Water.hpp.
m_textureName
std::string Water::m_textureName private
The texture of the water
Definition at line 143 of file Water.hpp.
m_time
double Water::m_time = 0 private
Total time run
Definition at line 123 of file Water.hpp.
Referenced by setTotalTime(), update(), and Water().
The documentation for this class was generated from the following files:
src/Model/GameObject/Water.hpp
src/Model/GameObject/Water.cpp