My Project: Light Class Reference
Light Class Reference
A light in the scene.
#include <Light.hpp>
Public Member Functions
Light ()
Default constructor.
Light (GLuint shadowWidth, GLuint shadowHeight, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity)
Parameterized constructor.
ShadowMap * GetShadowMap () const
Returns a pointer to the shadow map.
virtual ~Light ()
Destructor.
Protected Attributes
glm::vec3 m_color
The color of the ambient lighting.
GLfloat m_ambientIntensity
The intensity of the ambient lighting.
GLfloat m_diffuseIntensity
The intensity of the diffuse lighting.
glm::mat4 m_lightProj
The light projection.
ShadowMap * m_shadowMap
Shadow map.
Detailed Description
A light in the scene.
Definition at line 13 of file Light.hpp.
Constructor & Destructor Documentation
Light() [1/2]
Light::Light ()
Default constructor.
Definition at line 3 of file Light.cpp.
     : m_color(1.0f), m_ambientIntensity(1.0f), m_diffuseIntensity(0.0f) {}
References Light().
Referenced by DirectionalLight::DirectionalLight(), Light(), and PointLight::PointLight().
Light() [2/2]
Light::Light (GLuint shadowWidth, GLuint shadowHeight, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity)
Parameterized constructor.
Parameters
shadowWidth
shadowHeight
color
aIntensity
dIntensity
Definition at line 6 of file Light.cpp.
     : m_color(color),
       m_ambientIntensity(aIntensity),
       m_diffuseIntensity(dIntensity),
       m_lightProj(glm::mat4(0.0f)),
       m_shadowMap(new ShadowMap()) {
     m_shadowMap->Init(shadowWidth, shadowHeight);
 }
References Light(), m_shadowMap, and ShadowMap::ShadowMap().
Referenced by Light().
~Light()
Light::~Light () virtual
Destructor.
Definition at line 16 of file Light.cpp.
 {}
Member Function Documentation
GetShadowMap()
ShadowMap * Light::GetShadowMap () const
Returns a pointer to the shadow map.
Returns
ShadowMap*
Definition at line 18 of file Light.cpp.
 { return m_shadowMap; }
References m_shadowMap.
Member Data Documentation
m_ambientIntensity
GLfloat Light::m_ambientIntensity protected
The intensity of the ambient lighting.
Definition at line 49 of file Light.hpp.
m_color
glm::vec3 Light::m_color protected
The color of the ambient lighting.
Definition at line 47 of file Light.hpp.
m_diffuseIntensity
GLfloat Light::m_diffuseIntensity protected
The intensity of the diffuse lighting.
Definition at line 53 of file Light.hpp.
m_lightProj
glm::mat4 Light::m_lightProj protected
The light projection.
Definition at line 56 of file Light.hpp.
m_shadowMap
ShadowMap* Light::m_shadowMap protected
Shadow map.
Definition at line 59 of file Light.hpp.
Referenced by GetShadowMap(), and Light().
The documentation for this class was generated from the following files:
src/View/Renderer/OpenGL/Objects/Light.hpp
src/View/Renderer/OpenGL/Objects/Light.cpp