My Project: multiTextureCreator Class Reference
multiTextureCreator Class Reference
#include <multiTextureCreator.hpp>
Public Member Functions
void set_texture (std::string texture_path)
Sets the texture for the multi texture.
void set_height_map (uint8_t *height, int xSize, int zSize, bool makeIsland)
Sets the height map and if it should be an island.
void create_multi_texture ()
creates the multi texture
void set_max_height (int max)
Sets the max height of the height map.
GLuint get_multi_texture ()
Gets the multi texture texture id.
uint8_t * get_height_map ()
Private Member Functions
int get_range ()
Gets the range of height value based on number of textures.
int get_height_value (int x, int z)
Gets height value at coordinate.
void make_island (uint8_t *height)
Lowers the height map sides to make it into an island.
int get_index (int z, int x, int x_size, int bpp)
Returns an index value.
void add_height_based_lighting (unsigned char *mult_texture)
Adds height lighting to a texture.
void add_slope_based_lighting (unsigned char *mult_texture)
Adds slope lighting to a texture.
void generate_super_height_map ()
Generates super height map.
int upper_original_val (int val, int mult)
Gets upper original value.
int lower_original_val (int val, int mult)
Gets lower original value.
unsigned char original_height_map_value (int x, int z)
Gets original height map value.
int interpolate_height (int x1, int z1, int x2, int z2, int x3, int z3, int x, int z)
Interpolates a new height at point based on points on a plane.
Private Attributes
unsigned char * m_texture_ids [4]
Array of raw texture data
multiTextureFileData m_texture_param [4]
Array of texture information
bool m_make_island = false
If you want to turn the height map into an island
int m_number_of_textures = 0
The number of textures stored
GLuint m_id
The id of the multi texture
int m_max = 256
The max height value
uint8_t * m_height_map
The height map
int m_x_size = 0
The x size
int m_z_size = 0
The z size
int m_dirX = 1
Light direction x
int m_dirZ = 1
Light direction z
float m_minBrightness = 0.3
Min brightness
float m_maxBrightness = 1
Max brightness
float softness = 0.04
Softness value
bool use_better_lighting = true
Switch between slope lighting and height lighting
bool use_super_height_map = true
If you want to upscale the height map (for large multi texture)
uint8_t * m_super_height_map
Super height map
int m_super_scale = 1
Scale of super height map (2 ^ m_super_scale)
Detailed Description
Definition at line 14 of file multiTextureCreator.hpp.
Member Function Documentation
add_height_based_lighting()
void multiTextureCreator::add_height_based_lighting (unsigned char * mult_texture) private
Adds height lighting to a texture.
Parameters
*mult_texture - The multi texture to add height lighting too
Precondition
nothing
Postcondition
adds height based lighting
Definition at line 165 of file multiTextureCreator.cpp.
{
     float lightValue;
     int index;
     int bpp = 4;
     int z_size = m_z_size;
     int x_size = m_x_size;
     if (use_super_height_map) {
         z_size = z_size * pow(2, m_super_scale);
         x_size = x_size * pow(2, m_super_scale);
     }
     for (int z = 0; z < z_size; z++) {
         for (int x = 0; x < x_size; x++) {
             lightValue = (get_height_value(x, z) + 50) / (m_max * 1.0f);
             if (lightValue > 1) {
                 lightValue = 1;
             }
             // std::cout << lightValue << std::endl;
             index = get_index(z, x, x_size, bpp);
             mult_texture[index] = (int)(mult_texture[index] * lightValue);
             mult_texture[index + 1] =
                 (int)(mult_texture[index + 1] * lightValue);
             mult_texture[index + 2] =
                 (int)(mult_texture[index + 2] * lightValue);
         }
     }
 }
References get_height_value(), get_index(), m_max, m_x_size, m_z_size, and use_super_height_map.
Referenced by create_multi_texture().
add_slope_based_lighting()
void multiTextureCreator::add_slope_based_lighting (unsigned char * mult_texture) private
Adds slope lighting to a texture.
Parameters
*mult_texture - The multi texture to add slope lighting too
Precondition
nothing
Postcondition
adds slope based lighting
Definition at line 200 of file multiTextureCreator.cpp.
{
     int xl;
     int zl;
     float shade;
     int index;
     int bpp = 4;
     int z_size = m_z_size;
     int x_size = m_x_size;
     if (use_super_height_map) {
         z_size = z_size * pow(2, m_super_scale);
         x_size = x_size * pow(2, m_super_scale);
     }
     for (int z = 0; z < z_size; z++) {
         for (int x = 0; x < x_size; x++) {
             xl = x - m_dirX;
             zl = z - m_dirZ;
             if (xl < 0 || xl >= x_size || zl < 0 || zl >= z_size) {
                 shade = 1.0f;
             } else {
                 shade = 1.0f - (get_height_value(xl, zl) / (float)m_max -
                                 get_height_value(x, z) / (float)m_max) /
                                    softness;
             }
             if (shade < m_minBrightness) {
                 shade = m_minBrightness;
             } else if (shade > m_maxBrightness) {
                 shade = m_maxBrightness;
             }
             index = get_index(z, x, x_size, bpp);
             mult_texture[index] = (int)(mult_texture[index] * shade);
             mult_texture[index + 1] = (int)(mult_texture[index + 1] * shade);
             mult_texture[index + 2] = (int)(mult_texture[index + 2] * shade);
         }
     }
 }
References get_height_value(), get_index(), m_dirX, m_dirZ, m_max, m_maxBrightness, m_minBrightness, m_x_size, m_z_size, softness, and use_super_height_map.
Referenced by create_multi_texture().
create_multi_texture()
void multiTextureCreator::create_multi_texture ()
creates the multi texture
Precondition
textures & height map loaded
Postcondition
multitexture created
Definition at line 55 of file multiTextureCreator.cpp.
{
     // Processing new texture
     int range = get_range() - 5;
     float weight = 0;
     int heightValue;
     unsigned char rgb[3] = {};
     int max;
     int bpp = 4;
     int index;
     int tempX, tempZ;
     int z_size = m_z_size;
     int x_size = m_x_size;
     if (use_super_height_map) {
         generate_super_height_map();
         z_size = z_size * pow(2, m_super_scale);
         x_size = x_size * pow(2, m_super_scale);
     }
     unsigned char* mult_texture = new unsigned char[x_size * z_size * 4];
     for (int z = 0; z < z_size; z++) {
         for (int x = 0; x < x_size; x++) {
             heightValue = get_height_value(x, z);
             // std::cout << heightValue << std::endl;
             for (int count = 0; count < m_number_of_textures; count++) {
                 max = (count + 1) * range;
                 weight = (range - abs(heightValue - max)) / (float)range;
                 // weight = (range - abs(heightValue - max)) /
                 // (float)heightValue;
                 if (weight > 0) {
                     // Get correct point on texture (if texture different size
                     // to height map)
                     tempX = x * m_texture_param[count].m_width / x_size;
                     tempZ = z * m_texture_param[count].m_height / z_size;
                     index = tempZ * m_texture_param[count].m_width * 3;
                     // RED
                     rgb[0] += m_texture_ids[count][index + tempX * 3] * weight;
                     // GREEN
                     rgb[1] +=
                         m_texture_ids[count][index + tempX * 3 + 1] * weight;
                     // BLUE
                     rgb[2] +=
                         m_texture_ids[count][index + tempX * 3 + 2] * weight;
                 }
             }
             mult_texture[z * (x_size * bpp) + (x * bpp)] = rgb[0];
             mult_texture[z * (x_size * bpp) + (x * bpp) + 1] = rgb[1];
             mult_texture[z * (x_size * bpp) + (x * bpp) + 2] = rgb[2];
             mult_texture[z * (x_size * bpp) + (x * bpp) + 3] = 255;
             rgb[0] = 0;
             rgb[1] = 0;
             rgb[2] = 0;
         }
     }
     if (use_better_lighting) {
         add_slope_based_lighting(mult_texture);
     } else {
         add_height_based_lighting(mult_texture);
     }
     // Biding texture
     glGenTextures(1, &m_id);
     glBindTexture(GL_TEXTURE_2D, m_id);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, x_size, z_size, 0, GL_RGBA,
                  GL_UNSIGNED_BYTE, mult_texture);
     glGenerateMipmap(GL_TEXTURE_2D);
     glBindTexture(GL_TEXTURE_2D, 0);
     // Deleting uses textures
     for (int count = 0; count < m_number_of_textures; count++) {
         stbi_image_free(m_texture_ids[count]);
     }
     delete[] mult_texture;
     if (use_super_height_map) {
         delete[] m_super_height_map;
     }
 }
References add_height_based_lighting(), add_slope_based_lighting(), generate_super_height_map(), get_height_value(), get_range(), multiTextureFileData::m_height, m_number_of_textures, m_super_height_map, m_texture_ids, m_texture_param, multiTextureFileData::m_width, m_x_size, m_z_size, use_better_lighting, and use_super_height_map.
generate_super_height_map()
void multiTextureCreator::generate_super_height_map () private
Generates super height map.
Precondition
height map exists
Postcondition
super height map generated
Definition at line 263 of file multiTextureCreator.cpp.
{
     m_super_height_map = new unsigned char[m_x_size * pow(2, m_super_scale) *
                                            m_z_size * pow(2, (m_super_scale))];
     int z1, z2, x1, x2, interp;
     float interpX1, interpX2, interpZ1, interpZ2, sum;
     int index;
     int mult = pow(2, m_super_scale);
     int z_size = m_z_size * mult;
     int x_size = m_x_size * mult;
     std::cout << z_size << " : " << x_size << std::endl;
     std::cout << "Starting creation of super height map" << std::endl;
     for (int z = 0; z < z_size; z++) {
         for (int x = 0; x < x_size; x++) {
             z1 = upper_original_val(z, mult);
             x1 = upper_original_val(x, mult);
             z2 = lower_original_val(z, mult);
             x2 = lower_original_val(x, mult);
             if (distance(x, z, x1, z1) < distance(x, z, x2, z2)) {
                 interp = interpolate_height(x1, z1, x1, z2, x2, z1, x, z);
             } else {
                 interp = interpolate_height(x2, z2, x1, z2, x2, z1, x, z);
             }
             if (interp > 255) {
                 interp = 255;
             }
             index = get_index(z, x, x_size, 1);
             m_super_height_map[index] = interp;
         }
     }
     std::cout << "Creation of super height map is complete" << std::endl;
 }
References distance(), get_index(), interpolate_height(), lower_original_val(), m_super_height_map, m_x_size, m_z_size, and upper_original_val().
Referenced by create_multi_texture().
get_height_map()
uint8_t * multiTextureCreator::get_height_map ()
Definition at line 326 of file multiTextureCreator.cpp.
 { return m_height_map; }
References m_height_map.
get_height_value()
int multiTextureCreator::get_height_value (int x, int z) private
Gets height value at coordinate.
Parameters
x - x coord
z - z coord
Returns
int - height value at point
Precondition
height map exists
Postcondition
height value retrieved
Definition at line 156 of file multiTextureCreator.cpp.
{
     if (use_super_height_map) {
         int xSize = m_x_size * pow(2, m_super_scale);
         return m_super_height_map[z * xSize + x];
     } else {
         return m_height_map[z * m_x_size + x];
     }
 }
References m_height_map, m_super_height_map, m_x_size, and use_super_height_map.
Referenced by add_height_based_lighting(), add_slope_based_lighting(), and create_multi_texture().
get_index()
int multiTextureCreator::get_index (int z, int x, int x_size, int bpp) private
Returns an index value.
Parameters
z - The z point
x - The x point
x_size - The x size (width)
bpp - The bytes per pixel value (e.g., RGBA = 4)
Returns
int - An index value you can use
Precondition
nothing
Postcondition
index value
Definition at line 196 of file multiTextureCreator.cpp.
{
     return (z * x_size * bpp + x * bpp);
 }
Referenced by add_height_based_lighting(), add_slope_based_lighting(), and generate_super_height_map().
get_multi_texture()
GLuint multiTextureCreator::get_multi_texture ()
Gets the multi texture texture id.
Returns
GLuint - multi texture texture id
Precondition
multi texture created
Postcondition
id returned
Definition at line 145 of file multiTextureCreator.cpp.
 { return m_id; }
get_range()
int multiTextureCreator::get_range () private
Gets the range of height value based on number of textures.
Precondition
textures exists
Postcondition
height value found
Definition at line 147 of file multiTextureCreator.cpp.
{
     if (m_number_of_textures == 0) {
         return 1;
     }
     return m_max / m_number_of_textures;
 }
References m_max, and m_number_of_textures.
Referenced by create_multi_texture().
interpolate_height()
int multiTextureCreator::interpolate_height (int x1, int z1, int x2, int z2, int x3, int z3, int x, int z) private
Interpolates a new height at point based on points on a plane.
Parameters
x1 - point 1 x coord
z1 - point 1 z coord
x2 - point 2 x coord
z2 - point 2 z coord
x3 - point 3 x coord
z3 - point 3 z coord
x - x position
z - z position
Returns
int - The new height
Precondition
super height map used
Postcondition
gets new height
Definition at line 245 of file multiTextureCreator.cpp.
{
     int mult = pow(2, m_super_scale);
     int y1 = original_height_map_value(x1 / mult, z1 / mult);
     int y2 = original_height_map_value(x2 / mult, z2 / mult);
     int y3 = original_height_map_value(x3 / mult, z3 / mult);
     glm::vec3 v1 = {x1 - x2, y1 - y2, z1 - z2};
     glm::vec3 v2 = {x1 - x3, y1 - y3, z1 - z3};
     glm::vec3 crossProd;
     crossProd.x = v1.y * v2.z - v1.z * v2.y;
     crossProd.y = v1.z * v2.x - v1.x * v2.z;
     crossProd.z = v1.x * v2.y - v1.y * v2.x;
     float xCalc = -crossProd.x * (x - x1);
     float zCalc = -crossProd.z * (z - z1);
     int val = (xCalc + zCalc) / crossProd.y + y1;
     return val;
 }
References original_height_map_value().
Referenced by generate_super_height_map().
lower_original_val()
int multiTextureCreator::lower_original_val (int val, int mult) private
Gets lower original value.
Parameters
val - The value of the current coordinate (x or z)
mult - The scale of the height map
Returns
int - lower value
Precondition
super height map used
Postcondition
gets lower value
Definition at line 306 of file multiTextureCreator.cpp.
{
     int start = 0;
     while (start < val) {
         start += mult;
     }
     start -= mult;
     return start;
 }
Referenced by generate_super_height_map().
make_island()
void multiTextureCreator::make_island (uint8_t * height) private
Lowers the height map sides to make it into an island.
Parameters
height - Height map
Precondition
height map exists
Postcondition
height map sides lowered
Definition at line 25 of file multiTextureCreator.cpp.
{
     for (int z = 0; z < 10; z++) {
         for (int x = 0; x < m_x_size; x++) {
             height[z * m_x_size + x] =
                 height[z * m_x_size + x] * ((z + 0.1) / 10.0);
         }
     }
     for (int z = m_z_size - 1; z > m_z_size - 10; z--) {
         for (int x = 0; x < m_x_size; x++) {
             height[z * m_x_size + x] =
                 height[z * m_x_size + x] * ((m_z_size - z + 0.1) / 10.0);
         }
     }
     for (int x = 0; x < 10; x++) {
         for (int z = 0; z < m_x_size; z++) {
             height[z * m_x_size + x] =
                 height[z * m_x_size + x] * ((x + 0.1) / 10.0);
         }
     }
     for (int x = m_x_size - 1; x > m_x_size - 10; x--) {
         for (int z = 0; z < m_z_size; z++) {
             height[z * m_x_size + x] =
                 height[z * m_x_size + x] * ((m_x_size - x + 0.1) / 10.0);
         }
     }
 }
References m_x_size, and m_z_size.
Referenced by set_height_map().
original_height_map_value()
unsigned char multiTextureCreator::original_height_map_value (int x, int z) private
Gets original height map value.
Parameters
x - x coord
z - z coord
Precondition
height map stored
Postcondition
gets height data
Definition at line 315 of file multiTextureCreator.cpp.
{
     if (x < 0) {
         x = 0;
     }
     if (z < 0) {
         z = 0;
     }
     return m_height_map[z * m_x_size + x];
 }
References m_height_map, and m_x_size.
Referenced by interpolate_height().
set_height_map()
void multiTextureCreator::set_height_map (uint8_t * height, int xSize, int zSize, bool makeIsland)
Sets the height map and if it should be an island.
Parameters
height - The height map
xSize - x size of height map (width)
zSize - z size of height map (height)
makeIsland - If you want the height map to turn into an island
Precondition
object exists
Postcondition
height map added
Definition at line 17 of file multiTextureCreator.cpp.
{
     m_x_size = xSize;
     m_z_size = zSize;
     make_island(height);
     m_height_map = height;
 }
References m_height_map, m_x_size, m_z_size, and make_island().
set_max_height()
void multiTextureCreator::set_max_height (int max)
Sets the max height of the height map.
Precondition
objects exists
Postcondition
max height set
Definition at line 154 of file multiTextureCreator.cpp.
 { m_max = max; }
References m_max.
set_texture()
void multiTextureCreator::set_texture (std::string texture_path)
Sets the texture for the multi texture.
Parameters
texture_path - The path of the texture
Precondition
multi texture creator exists
Postcondition
texture added
Definition at line 3 of file multiTextureCreator.cpp.
{
     m_texture_ids[m_number_of_textures] = stbi_load(
         texture_path.c_str(), &m_texture_param[m_number_of_textures].m_width,
         &m_texture_param[m_number_of_textures].m_height,
         &m_texture_param[m_number_of_textures].m_bitDepth, 0);
     std::cout << texture_path << " loading for multi texture creator"
               << "\nHeight = " << m_texture_param[m_number_of_textures].m_height
               << "\nWidth = " << m_texture_param[m_number_of_textures].m_width
               << m_texture_param[m_number_of_textures].m_bitDepth << std::endl;
     m_number_of_textures++;
 }
References m_number_of_textures.
upper_original_val()
int multiTextureCreator::upper_original_val (int val, int mult) private
Gets upper original value.
Parameters
val - The value of the current coordinate (x or z)
mult - The scale of the height map
Returns
int - upper value
Precondition
super height map used
Postcondition
gets upper value
Definition at line 299 of file multiTextureCreator.cpp.
{
     int start = 0;
     while (start < val) {
         start += mult;
     }
     return start;
 }
Referenced by generate_super_height_map().
Member Data Documentation
m_dirX
int multiTextureCreator::m_dirX = 1 private
Light direction x
Definition at line 142 of file multiTextureCreator.hpp.
Referenced by add_slope_based_lighting().
m_dirZ
int multiTextureCreator::m_dirZ = 1 private
Light direction z
Definition at line 147 of file multiTextureCreator.hpp.
Referenced by add_slope_based_lighting().
m_height_map
uint8_t* multiTextureCreator::m_height_map private
The height map
Definition at line 98 of file multiTextureCreator.hpp.
Referenced by get_height_map(), get_height_value(), original_height_map_value(), and set_height_map().
m_id
GLuint multiTextureCreator::m_id private
The id of the multi texture
Definition at line 88 of file multiTextureCreator.hpp.
m_make_island
bool multiTextureCreator::m_make_island = false private
If you want to turn the height map into an island
Definition at line 78 of file multiTextureCreator.hpp.
m_max
int multiTextureCreator::m_max = 256 private
The max height value
Definition at line 93 of file multiTextureCreator.hpp.
Referenced by add_height_based_lighting(), add_slope_based_lighting(), get_range(), and set_max_height().
m_maxBrightness
float multiTextureCreator::m_maxBrightness = 1 private
Max brightness
Definition at line 157 of file multiTextureCreator.hpp.
Referenced by add_slope_based_lighting().
m_minBrightness
float multiTextureCreator::m_minBrightness = 0.3 private
Min brightness
Definition at line 152 of file multiTextureCreator.hpp.
Referenced by add_slope_based_lighting().
m_number_of_textures
int multiTextureCreator::m_number_of_textures = 0 private
The number of textures stored
Definition at line 83 of file multiTextureCreator.hpp.
Referenced by create_multi_texture(), get_range(), and set_texture().
m_super_height_map
uint8_t* multiTextureCreator::m_super_height_map private
Super height map
Definition at line 209 of file multiTextureCreator.hpp.
Referenced by create_multi_texture(), generate_super_height_map(), and get_height_value().
m_super_scale
int multiTextureCreator::m_super_scale = 1 private
Scale of super height map (2 ^ m_super_scale)
Definition at line 214 of file multiTextureCreator.hpp.
m_texture_ids
unsigned char* multiTextureCreator::m_texture_ids[4] private
Array of raw texture data
Definition at line 68 of file multiTextureCreator.hpp.
Referenced by create_multi_texture().
m_texture_param
multiTextureFileData multiTextureCreator::m_texture_param[4] private
Array of texture information
Definition at line 73 of file multiTextureCreator.hpp.
Referenced by create_multi_texture().
m_x_size
int multiTextureCreator::m_x_size = 0 private
The x size
Definition at line 103 of file multiTextureCreator.hpp.
Referenced by add_height_based_lighting(), add_slope_based_lighting(), create_multi_texture(), generate_super_height_map(), get_height_value(), make_island(), original_height_map_value(), and set_height_map().
m_z_size
int multiTextureCreator::m_z_size = 0 private
The z size
Definition at line 108 of file multiTextureCreator.hpp.
Referenced by add_height_based_lighting(), add_slope_based_lighting(), create_multi_texture(), generate_super_height_map(), make_island(), and set_height_map().
softness
float multiTextureCreator::softness = 0.04 private
Softness value
Definition at line 162 of file multiTextureCreator.hpp.
Referenced by add_slope_based_lighting().
use_better_lighting
bool multiTextureCreator::use_better_lighting = true private
Switch between slope lighting and height lighting
Definition at line 167 of file multiTextureCreator.hpp.
Referenced by create_multi_texture().
use_super_height_map
bool multiTextureCreator::use_super_height_map = true private
If you want to upscale the height map (for large multi texture)
Definition at line 204 of file multiTextureCreator.hpp.
Referenced by add_height_based_lighting(), add_slope_based_lighting(), create_multi_texture(), and get_height_value().
The documentation for this class was generated from the following files:
src/Controller/multiTextureCreator.hpp
src/Controller/multiTextureCreator.cpp