ICT397 Assignment 2: Shader Class Reference
Shader Class Reference
A shader program.
#include <Shader.hpp>
Public Member Functions
Shader ()
Construct a new Shader object.
GLuint GetProjectionLocation () const
GLuint GetModelLocation () const
GLuint GetViewLocation () const
GLuint GetEyePositionLocation () const
GLuint GetAmbientIntensityLocation () const
GLuint GetAmbientIntensityColor () const
GLuint GetDiffuseIntensityLocation () const
GLuint GetDirectionLocation () const
GLuint GetSpecularIntensityLocation () const
GLuint GetShininessLocation () const
GLuint GetOmniLightPosLocation () const
GLuint GetFarPlaneLocation () const
GLuint GetUsingTexture () const
GLuint get_using_detailmap () const
void SetDirectionalLight (const DirectionalLight &dLight)
void SetPointLights (PointLight *pLight, GLuint lightCount, GLuint textureUnit, GLuint offset)
void SetSpotLights (SpotLight *sLight, GLuint lightCount, GLuint textureUnit, GLuint offset)
void SetTexture (GLuint textureUnit)
void SetDirectionalShadowMap (GLuint textureUnit)
void set_detail_map (GLuint textureUnit)
void SetDirectionalLightTransform (const glm::mat4 &lTransform)
void SetLightMatrices (std::vector< glm::mat4 > lightmatrices)
void UseShader () const
Use the current shader.
void CompileCode (const char *vertexCode, const char *fragmentCode)
Compiles the shader code.
void CompileFile (const char *vertexPath, const char *fragmentPath)
Reads in a shader file and compiles the code.
void CompileFile (const char *vertexPath, const char *geometryPath, const char *fragmentPath)
Reads in a shader file and compiles the code.
void Validate ()
Validates the shader.
std::string ReadFile (const char *fileLocation)
Read a shader file and return the code.
void ClearShader ()
Clears the shader.
~Shader ()
Destroy the Shader object.
Private Member Functions
void AddShader (GLuint program, const char *shaderCode, GLenum shaderType)
Adds a new type of shader to the program.
void CompileShader (const char *vertexCode, const char *fragmentCode)
Compiles a vertex and fragment shader.
void CompileShader (const char *vertexCode, const char *geometryCode, const char *fragmentCode)
Compiles a vertex, geometry and fragment shader.
void CompileProgram ()
Compiles the shader program.
Private Attributes
GLuint m_shaderID = 0u
The unique id of the shader.
GLuint uniformProjection = 0u
GLuint uniformModel = 0u
GLuint uniformView = 0u
GLuint uniformEyePosition = 0u
GLuint uniformSpecularIntensity = 0u
GLuint uniformShininess = 0u
GLuint uniformTexture = 0u
GLuint uniformDirectionalLightTransform = 0u
GLuint uniformDirectionalShadowMap = 0u
GLuint uniform_detailmap = 0u
GLuint uniformOmniLightPos = 0u
GLuint uniformFarPlane = 0u
GLuint uniformLightMatrices [6]
GLuint uniformSpotLightCount = 0u
GLuint uniformPointLightCount = 0u
GLuint uniformUsingTexture = 0u
GLuint uniform_using_detailmap = 0u
int pointLightCount = 0
int spotLightCount = 0
struct {
GLuint uniformColor = 0u
GLuint uniformAmbientIntensity = 0u
GLuint uniformDiffuseIntensity = 0u
GLuint uniformDirection = 0u
} uniformDirectionalLight
struct {
GLuint uniformColor = 0u
GLuint uniformAmbientIntensity = 0u
GLuint uniformDiffuseIntensity = 0u
GLuint uniformPosition = 0u
GLuint uniformConstant = 0u
GLuint uniformLinear = 0u
GLuint uniformQuadratic = 0u
} uniformPointLights [MAX_POINT_LIGHTS]
struct {
GLuint uniformColor = 0u
GLuint uniformAmbientIntensity = 0u
GLuint uniformDiffuseIntensity = 0u
GLuint uniformPosition = 0u
GLuint uniformConstant = 0u
GLuint uniformLinear = 0u
GLuint uniformQuadratic = 0u
GLuint uniformDirection = 0u
GLuint uniformEdge = 0u
} uniformSpotLights [MAX_SPOT_LIGHTS]
struct {
GLuint shadowMap = 0u
GLfloat farPlane = 0u
} uniformOmniShadowMap [MAX_POINT_LIGHTS+MAX_SPOT_LIGHTS]
Detailed Description
A shader program.
Todo:
Refactor getters and setters.
Definition at line 24 of file Shader.hpp.
Constructor & Destructor Documentation
Shader()
Shader::Shader ()
Construct a new Shader object.
Definition at line 3 of file Shader.cpp.
 {}
Referenced by Skybox::Skybox().
~Shader()
Shader::~Shader ()
Destroy the Shader object.
Definition at line 397 of file Shader.cpp.
 { ClearShader(); }
References ClearShader().
Member Function Documentation
AddShader()
void Shader::AddShader (GLuint program, const char * shaderCode, GLenum shaderType) private
Adds a new type of shader to the program.
Parameters
program
shaderCode
shaderType
Definition at line 356 of file Shader.cpp.
{
     GLuint shader = glCreateShader(shaderType);
     const GLchar* code[1];
     code[0] = shaderCode;
     GLint codeLength[1];
     codeLength[0] = strlen(shaderCode);
     glShaderSource(shader, 1, code, codeLength);
     glCompileShader(shader);
     GLint result = 0;
     GLchar errLog[1024] = {0};
     glLinkProgram(shader);
     glGetShaderiv(shader, GL_COMPILE_STATUS, &result);
     if (!result) {
         glGetShaderInfoLog(shader, sizeof(errLog), nullptr, errLog);
         std::cout << "Error compiling the " << shaderType
                   << "shader: " << errLog << std::endl;
         return;
     }
     glAttachShader(program, shader);
 }
ClearShader()
void Shader::ClearShader ()
Clears the shader.
Definition at line 385 of file Shader.cpp.
{
     std::cout << "Cleaned shader!" << std::endl;
     if (m_shaderID != 0) {
         glDeleteProgram(m_shaderID);
         m_shaderID = 0;
     }
     uniformModel = 0;
     uniformProjection = 0;
 }
Referenced by ~Shader().
CompileCode()
void Shader::CompileCode (const char * vertexCode, const char * fragmentCode)
Compiles the shader code.
Parameters
vertexCode
fragmentCode
Definition at line 126 of file Shader.cpp.
{
     CompileShader(vertexCode, fragmentCode);
 }
References CompileShader().
CompileFile() [1/2]
void Shader::CompileFile (const char * vertexPath, const char * fragmentPath)
Reads in a shader file and compiles the code.
Parameters
vertexPath
fragmentPath
Definition at line 130 of file Shader.cpp.
{
     std::string vertexCode = ReadFile(vertexPath);
     std::string fragmentCode = ReadFile(fragmentPath);
     CompileShader(vertexCode.c_str(), fragmentCode.c_str());
 }
References CompileShader(), and ReadFile().
Referenced by Skybox::Skybox().
CompileFile() [2/2]
void Shader::CompileFile (const char * vertexPath, const char * geometryPath, const char * fragmentPath)
Reads in a shader file and compiles the code.
Parameters
vertexPath
geometryPath
fragmentPath
Definition at line 137 of file Shader.cpp.
{
     std::string vertexCode = ReadFile(vertexPath);
     std::string geometryCode = ReadFile(geometryPath);
     std::string fragmentCode = ReadFile(fragmentPath);
     CompileShader(vertexCode.c_str(), geometryCode.c_str(),
                   fragmentCode.c_str());
 }
References CompileShader(), and ReadFile().
CompileProgram()
void Shader::CompileProgram () private
Compiles the shader program.
Definition at line 208 of file Shader.cpp.
{
     GLint result = 0;
     GLchar errLog[1024] = {0};
     glLinkProgram(m_shaderID);
     glGetProgramiv(m_shaderID, GL_LINK_STATUS, &result);
     if (!result) {
         glGetProgramInfoLog(m_shaderID, sizeof(errLog), nullptr, errLog);
         std::cout << "Error linking program: " << errLog << std::endl;
         return;
     }
     uniformModel = glGetUniformLocation(m_shaderID, "model");
     uniformProjection = glGetUniformLocation(m_shaderID, "projection");
     uniformView = glGetUniformLocation(m_shaderID, "view");
     uniformEyePosition = glGetUniformLocation(m_shaderID, "eyePosition");
     uniformUsingTexture = glGetUniformLocation(m_shaderID, "isUsingTexture");
     uniform_using_detailmap =
         glGetUniformLocation(m_shaderID, "is_using_detailmap");
     uniformDirectionalLight.uniformColor =
         glGetUniformLocation(m_shaderID, "directionalLight.base.color");
     uniformDirectionalLight.uniformAmbientIntensity = glGetUniformLocation(
         m_shaderID, "directionalLight.base.ambientIntensity");
     uniformDirectionalLight.uniformDirection =
         glGetUniformLocation(m_shaderID, "directionalLight.direction");
     uniformDirectionalLight.uniformDiffuseIntensity = glGetUniformLocation(
         m_shaderID, "directionalLight.base.diffuseIntensity");
     uniformShininess = glGetUniformLocation(m_shaderID, "material.shininess");
     uniformSpecularIntensity =
         glGetUniformLocation(m_shaderID, "material.specularIntensity");
     uniformPointLightCount =
         glGetUniformLocation(m_shaderID, "pointLightCount");
     for (size_t i = 0; i < MAX_POINT_LIGHTS; ++i) {
         char locBuff[100] = {'\0'};
         snprintf(locBuff, sizeof(locBuff), "pointLights[%d].base.color", i);
         uniformPointLights[i].uniformColor =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff),
                  "pointLights[%d].base.ambientIntensity", i);
         uniformPointLights[i].uniformAmbientIntensity =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff),
                  "pointLights[%d].base.diffuseIntensity", i);
         uniformPointLights[i].uniformDiffuseIntensity =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "pointLights[%d].position", i);
         uniformPointLights[i].uniformPosition =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "pointLights[%d].constant", i);
         uniformPointLights[i].uniformConstant =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "pointLights[%d].linear", i);
         uniformPointLights[i].uniformLinear =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "pointLights[%d].exponent", i);
         uniformPointLights[i].uniformQuadratic =
             glGetUniformLocation(m_shaderID, locBuff);
     }
     uniformSpotLightCount = glGetUniformLocation(m_shaderID, "spotLightCount");
     for (size_t i = 0; i < MAX_SPOT_LIGHTS; ++i) {
         char locBuff[100] = {'\0'};
         snprintf(locBuff, sizeof(locBuff), "spotLights[%d].base.base.color", i);
         uniformSpotLights[i].uniformColor =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff),
                  "spotLights[%d].base.base.ambientIntensity", i);
         uniformSpotLights[i].uniformAmbientIntensity =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff),
                  "spotLights[%d].base.base.diffuseIntensity", i);
         uniformSpotLights[i].uniformDiffuseIntensity =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "spotLights[%d].base.position", i);
         uniformSpotLights[i].uniformPosition =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "spotLights[%d].base.constant", i);
         uniformSpotLights[i].uniformConstant =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "spotLights[%d].base.linear", i);
         uniformSpotLights[i].uniformLinear =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "spotLights[%d].base.exponent", i);
         uniformSpotLights[i].uniformQuadratic =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "spotLights[%d].direction", i);
         uniformSpotLights[i].uniformDirection =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "spotLights[%d].edge", i);
         uniformSpotLights[i].uniformEdge =
             glGetUniformLocation(m_shaderID, locBuff);
     }
     uniformTexture = glGetUniformLocation(m_shaderID, "theTexture");
     uniformDirectionalLightTransform =
         glGetUniformLocation(m_shaderID, "directionalLightTransform");
     uniformDirectionalShadowMap =
         glGetUniformLocation(m_shaderID, "directionalShadowMap");
     uniform_detailmap = glGetUniformLocation(m_shaderID, "detailmap");
     uniformOmniLightPos = glGetUniformLocation(m_shaderID, "lightPos");
     uniformFarPlane = glGetUniformLocation(m_shaderID, "farPlane");
     for (size_t i = 0; i < 6; ++i) {
         char locBuff[100] = {'\0'};
         snprintf(locBuff, sizeof(locBuff), "lightMatrices[%d]", i);
         uniformLightMatrices[i] = glGetUniformLocation(m_shaderID, locBuff);
     }
     for (size_t i = 0; i < MAX_POINT_LIGHTS + MAX_SPOT_LIGHTS; ++i) {
         char locBuff[100] = {'\0'};
         snprintf(locBuff, sizeof(locBuff), "omniShadowMaps[%d].shadowMap", i);
         uniformOmniShadowMap[i].shadowMap =
             glGetUniformLocation(m_shaderID, locBuff);
         snprintf(locBuff, sizeof(locBuff), "omniShadowMaps[%d].farPlane", i);
         uniformOmniShadowMap[i].farPlane =
             glGetUniformLocation(m_shaderID, locBuff);
     }
 }
References MAX_POINT_LIGHTS, and MAX_SPOT_LIGHTS.
Referenced by CompileShader().
CompileShader() [1/2]
void Shader::CompileShader (const char * vertexCode, const char * fragmentCode) private
Compiles a vertex and fragment shader.
Parameters
vertexCode
fragmentCode
Definition at line 165 of file Shader.cpp.
{
     m_shaderID = glCreateProgram();
     if (!m_shaderID) {
         std::cout << "Error creating shader" << std::endl;
         return;
     }
     AddShader(m_shaderID, vertexCode, GL_VERTEX_SHADER);
     AddShader(m_shaderID, fragmentCode, GL_FRAGMENT_SHADER);
     CompileProgram();
 }
References CompileProgram().
Referenced by CompileCode(), and CompileFile().
CompileShader() [2/2]
void Shader::CompileShader (const char * vertexCode, const char * geometryCode, const char * fragmentCode) private
Compiles a vertex, geometry and fragment shader.
Parameters
vertexCode
geometryCode
fragmentCode
Definition at line 179 of file Shader.cpp.
{
     m_shaderID = glCreateProgram();
     if (!m_shaderID) {
         std::cout << "Error creating shader" << std::endl;
         return;
     }
     AddShader(m_shaderID, vertexCode, GL_VERTEX_SHADER);
     AddShader(m_shaderID, geometryCode, GL_GEOMETRY_SHADER);
     AddShader(m_shaderID, fragmentCode, GL_FRAGMENT_SHADER);
     CompileProgram();
 }
References CompileProgram().
Referenced by CompileFile().
get_using_detailmap()
GLuint Shader::get_using_detailmap () const
Definition at line 41 of file Shader.cpp.
 { return uniform_using_detailmap; }
GetAmbientIntensityColor()
GLuint Shader::GetAmbientIntensityColor () const
Definition at line 17 of file Shader.cpp.
{
     return uniformDirectionalLight.uniformColor;
 }
GetAmbientIntensityLocation()
GLuint Shader::GetAmbientIntensityLocation () const
Definition at line 13 of file Shader.cpp.
{
     return uniformDirectionalLight.uniformAmbientIntensity;
 }
GetDiffuseIntensityLocation()
GLuint Shader::GetDiffuseIntensityLocation () const
Definition at line 21 of file Shader.cpp.
{
     return uniformDirectionalLight.uniformDiffuseIntensity;
 }
GetDirectionLocation()
GLuint Shader::GetDirectionLocation () const
Definition at line 25 of file Shader.cpp.
{
     return uniformDirectionalLight.uniformDirection;
 }
GetEyePositionLocation()
GLuint Shader::GetEyePositionLocation () const
Definition at line 11 of file Shader.cpp.
 { return uniformEyePosition; }
GetFarPlaneLocation()
GLuint Shader::GetFarPlaneLocation () const
Definition at line 37 of file Shader.cpp.
 { return uniformFarPlane; }
GetModelLocation()
GLuint Shader::GetModelLocation () const
Definition at line 7 of file Shader.cpp.
 { return uniformModel; }
GetOmniLightPosLocation()
GLuint Shader::GetOmniLightPosLocation () const
Definition at line 35 of file Shader.cpp.
 { return uniformOmniLightPos; }
GetProjectionLocation()
GLuint Shader::GetProjectionLocation () const
Definition at line 5 of file Shader.cpp.
 { return uniformProjection; }
GetShininessLocation()
GLuint Shader::GetShininessLocation () const
Definition at line 33 of file Shader.cpp.
 { return uniformShininess; }
GetSpecularIntensityLocation()
GLuint Shader::GetSpecularIntensityLocation () const
Definition at line 29 of file Shader.cpp.
{
     return uniformSpecularIntensity;
 }
GetUsingTexture()
GLuint Shader::GetUsingTexture () const
Definition at line 39 of file Shader.cpp.
 { return uniformUsingTexture; }
GetViewLocation()
GLuint Shader::GetViewLocation () const
Definition at line 9 of file Shader.cpp.
 { return uniformView; }
ReadFile()
std::string Shader::ReadFile (const char * fileLocation)
Read a shader file and return the code.
Parameters
fileLocation
Returns
std::string
Definition at line 147 of file Shader.cpp.
{
     std::string content;
     std::ifstream fileStream(fileLocation, std::ios::in);
     if (!fileStream) {
         std::cout << "Failed to read " << fileLocation << std::endl;
         return "";
     }
     std::string line = "";
     while (fileStream) {
         std::getline(fileStream, line);
         content.append(line + "\n");
     }
     return content;
 }
Referenced by CompileFile().
set_detail_map()
void Shader::set_detail_map (GLuint textureUnit)
Definition at line 108 of file Shader.cpp.
{
     glUniform1i(uniform_detailmap, textureUnit);
 }
SetDirectionalLight()
void Shader::SetDirectionalLight (const DirectionalLight & dLight)
Definition at line 43 of file Shader.cpp.
{
     dLight.UseLight(uniformDirectionalLight.uniformColor,
                     uniformDirectionalLight.uniformAmbientIntensity,
                     uniformDirectionalLight.uniformDirection,
                     uniformDirectionalLight.uniformDiffuseIntensity);
 }
SetDirectionalLightTransform()
void Shader::SetDirectionalLightTransform (const glm::mat4 & lTransform)
Definition at line 112 of file Shader.cpp.
{
     glUniformMatrix4fv(uniformDirectionalLightTransform, 1, GL_FALSE,
                        glm::value_ptr(lTransform));
 }
SetDirectionalShadowMap()
void Shader::SetDirectionalShadowMap (GLuint textureUnit)
Definition at line 104 of file Shader.cpp.
{
     glUniform1i(uniformDirectionalShadowMap, textureUnit);
 }
SetLightMatrices()
void Shader::SetLightMatrices (std::vector< glm::mat4 > lightmatrices)
Definition at line 117 of file Shader.cpp.
{
     for (size_t i = 0; i < 6; ++i) {
         glUniformMatrix4fv(uniformLightMatrices[i], 1, GL_FALSE,
                            glm::value_ptr(lightMatrices[i]));
     }
 }
SetPointLights()
void Shader::SetPointLights (PointLight * pLight, GLuint lightCount, GLuint textureUnit, GLuint offset)
Definition at line 50 of file Shader.cpp.
{
     if (lightCount > MAX_POINT_LIGHTS) lightCount = MAX_POINT_LIGHTS;
     glUniform1i(uniformPointLightCount, lightCount);
     for (size_t i = 0; i < lightCount; ++i) {
         pLight[i].UseLight(uniformPointLights[i].uniformColor,
                            uniformPointLights[i].uniformAmbientIntensity,
                            uniformPointLights[i].uniformDiffuseIntensity,
                            uniformPointLights[i].uniformPosition,
                            uniformPointLights[i].uniformConstant,
                            uniformPointLights[i].uniformLinear,
                            uniformPointLights[i].uniformQuadratic);
         // pLight[i].GetShadowMap()->Read(GL_TEXTURE0 + textureUnit + i);
         glUniform1i(uniformOmniShadowMap[i + offset].shadowMap,
                     textureUnit + i);
         glUniform1f(uniformOmniShadowMap[i + offset].farPlane,
                     pLight[i].GetFarPlane());
     }
 }
SetSpotLights()
void Shader::SetSpotLights (SpotLight * sLight, GLuint lightCount, GLuint textureUnit, GLuint offset)
Definition at line 74 of file Shader.cpp.
{
     if (lightCount > MAX_SPOT_LIGHTS) lightCount = MAX_SPOT_LIGHTS;
     glUniform1i(uniformSpotLightCount, lightCount);
     for (size_t i = 0; i < lightCount; ++i) {
         sLight[i].UseLight(uniformSpotLights[i].uniformColor,
                            uniformSpotLights[i].uniformAmbientIntensity,
                            uniformSpotLights[i].uniformDiffuseIntensity,
                            uniformSpotLights[i].uniformPosition,
                            uniformSpotLights[i].uniformDirection,
                            uniformSpotLights[i].uniformConstant,
                            uniformSpotLights[i].uniformLinear,
                            uniformSpotLights[i].uniformQuadratic,
                            uniformSpotLights[i].uniformEdge);
         // sLight[i].GetShadowMap()->Read(GL_TEXTURE0 + textureUnit + i);
         glUniform1i(uniformOmniShadowMap[i + offset].shadowMap,
                     textureUnit + i);
         glUniform1f(uniformOmniShadowMap[i + offset].farPlane,
                     sLight[i].GetFarPlane());
     }
 }
SetTexture()
void Shader::SetTexture (GLuint textureUnit)
Definition at line 100 of file Shader.cpp.
{
     glUniform1i(uniformTexture, textureUnit);
 }
UseShader()
void Shader::UseShader () const
Use the current shader.
Definition at line 124 of file Shader.cpp.
 { glUseProgram(m_shaderID); }
Referenced by Skybox::DrawSkybox().
Validate()
void Shader::Validate ()
Validates the shader.
Definition at line 195 of file Shader.cpp.
                       {
     GLint result = 0;
     GLchar errLog[1024] = {0};
     glValidateProgram(m_shaderID);
     glGetProgramiv(m_shaderID, GL_VALIDATE_STATUS, &result);
     if (!result) {
         glGetProgramInfoLog(m_shaderID, sizeof(errLog), nullptr, errLog);
         std::cout << "Error validating program: " << errLog << std::endl;
         return;
     }
 }
Referenced by Skybox::DrawSkybox().
Member Data Documentation
farPlane
GLfloat Shader::farPlane = 0u
Definition at line 175 of file Shader.hpp.
m_shaderID
GLuint Shader::m_shaderID = 0u private
The unique id of the shader.
Definition at line 113 of file Shader.hpp.
pointLightCount
int Shader::pointLightCount = 0 private
Definition at line 138 of file Shader.hpp.
shadowMap
GLuint Shader::shadowMap = 0u
Definition at line 174 of file Shader.hpp.
spotLightCount
int Shader::spotLightCount = 0 private
Definition at line 139 of file Shader.hpp.
uniform_detailmap
GLuint Shader::uniform_detailmap = 0u private
Definition at line 126 of file Shader.hpp.
uniform_using_detailmap
GLuint Shader::uniform_using_detailmap = 0u private
Definition at line 136 of file Shader.hpp.
uniformAmbientIntensity
GLuint Shader::uniformAmbientIntensity = 0u
Definition at line 143 of file Shader.hpp.
uniformColor
GLuint Shader::uniformColor = 0u
Definition at line 142 of file Shader.hpp.
uniformConstant
GLuint Shader::uniformConstant = 0u
Definition at line 154 of file Shader.hpp.
uniformDiffuseIntensity
GLuint Shader::uniformDiffuseIntensity = 0u
Definition at line 144 of file Shader.hpp.
uniformDirection
GLuint Shader::uniformDirection = 0u
Definition at line 145 of file Shader.hpp.
uniformDirectionalLight
struct { ... } Shader::uniformDirectionalLight
uniformDirectionalLightTransform
GLuint Shader::uniformDirectionalLightTransform = 0u private
Definition at line 123 of file Shader.hpp.
uniformDirectionalShadowMap
GLuint Shader::uniformDirectionalShadowMap = 0u private
Definition at line 124 of file Shader.hpp.
uniformEdge
GLuint Shader::uniformEdge = 0u
Definition at line 170 of file Shader.hpp.
uniformEyePosition
GLuint Shader::uniformEyePosition = 0u private
Definition at line 117 of file Shader.hpp.
uniformFarPlane
GLuint Shader::uniformFarPlane = 0u private
Definition at line 128 of file Shader.hpp.
uniformLightMatrices
GLuint Shader::uniformLightMatrices[6] private
Definition at line 130 of file Shader.hpp.
Referenced by Skybox::Skybox().
uniformLinear
GLuint Shader::uniformLinear = 0u
Definition at line 155 of file Shader.hpp.
uniformModel
GLuint Shader::uniformModel = 0u private
Definition at line 115 of file Shader.hpp.
uniformOmniLightPos
GLuint Shader::uniformOmniLightPos = 0u private
Definition at line 128 of file Shader.hpp.
uniformOmniShadowMap
struct { ... } Shader::uniformOmniShadowMap[MAX_POINT_LIGHTS + MAX_SPOT_LIGHTS]
uniformPointLightCount
GLuint Shader::uniformPointLightCount = 0u private
Definition at line 133 of file Shader.hpp.
uniformPointLights
struct { ... } Shader::uniformPointLights[MAX_POINT_LIGHTS]
uniformPosition
GLuint Shader::uniformPosition = 0u
Definition at line 153 of file Shader.hpp.
uniformProjection
GLuint Shader::uniformProjection = 0u private
Definition at line 115 of file Shader.hpp.
uniformQuadratic
GLuint Shader::uniformQuadratic = 0u
Definition at line 156 of file Shader.hpp.
uniformShininess
GLuint Shader::uniformShininess = 0u private
Definition at line 119 of file Shader.hpp.
uniformSpecularIntensity
GLuint Shader::uniformSpecularIntensity = 0u private
Definition at line 119 of file Shader.hpp.
uniformSpotLightCount
GLuint Shader::uniformSpotLightCount = 0u private
Definition at line 132 of file Shader.hpp.
uniformSpotLights
struct { ... } Shader::uniformSpotLights[MAX_SPOT_LIGHTS]
uniformTexture
GLuint Shader::uniformTexture = 0u private
Definition at line 121 of file Shader.hpp.
uniformUsingTexture
GLuint Shader::uniformUsingTexture = 0u private
Definition at line 135 of file Shader.hpp.
uniformView
GLuint Shader::uniformView = 0u private
Definition at line 115 of file Shader.hpp.
The documentation for this class was generated from the following files:
src/View/Renderer/OpenGL/Objects/Shader.hpp
src/View/Renderer/OpenGL/Objects/Shader.cpp