ICT397 Assignment 2: PointLight Class Reference
PointLight Class Reference
A point light that illuminates in a sphere.
#include <PointLight.hpp>
Public Member Functions
PointLight ()
Construct a new Point Light object.
PointLight (GLuint shadowWidth, GLuint shadowHeight, GLfloat near, GLfloat far, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity, glm::vec3 position, GLfloat constant, GLfloat linear, GLfloat quadratic)
Construct a new Point Light object.
void UseLight (GLuint ambientColorLoc, GLuint ambientIntensityLoc, GLuint diffuseIntensityLoc, GLuint positionLoc, GLuint constantLoc, GLuint linearLoc, GLuint quadraticLoc) const
Enables the light by passing uniforms to the shader.
std::vector< glm::mat4 > CalculateLightTransform () const
Calculates the light transform matrices.
GLfloat GetFarPlane () const
Get the Far Plane.
glm::vec3 GetPosition () const
Get the Position.
~PointLight ()
Destroy the Point Light object.
Public Member Functions inherited from Light
Light ()
Default constructor.
Light (GLuint shadowWidth, GLuint shadowHeight, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity)
Parameterized constructor.
ShadowMap * GetShadowMap () const
Returns a pointer to the shadow map.
virtual ~Light ()
Destructor.
Protected Attributes
glm::vec3 m_position
Position of the light.
GLfloat m_constant
Equation of the light.
GLfloat m_linear
GLfloat m_quadratic
GLfloat m_farPlane
The far plane.
Protected Attributes inherited from Light
glm::vec3 m_color
The color of the ambient lighting.
GLfloat m_ambientIntensity
The intensity of the ambient lighting.
GLfloat m_diffuseIntensity
The intensity of the diffuse lighting.
glm::mat4 m_lightProj
The light projection.
ShadowMap * m_shadowMap
Shadow map.
Detailed Description
A point light that illuminates in a sphere.
Definition at line 11 of file PointLight.hpp.
Constructor & Destructor Documentation
PointLight() [1/2]
PointLight::PointLight ()
Construct a new Point Light object.
Definition at line 3 of file PointLight.cpp.
     : Light(),
       m_position(0.0f),
       m_constant(1.0f),
       m_linear(0.0f),
       m_quadratic(0.0f) {}
References Light::Light(), and PointLight().
Referenced by PointLight(), and SpotLight::SpotLight().
PointLight() [2/2]
PointLight::PointLight (GLuint shadowWidth, GLuint shadowHeight, GLfloat near, GLfloat far, glm::vec3 color, GLfloat aIntensity, GLfloat dIntensity, glm::vec3 position, GLfloat constant, GLfloat linear, GLfloat quadratic)
Construct a new Point Light object.
Parameters
shadowWidth The width of the shadow map
shadowHeight The height of the shadow map
near The near plane of the shadow map
far The far plane of the shadow map
color The color of the light
aIntensity The ambient intensity of the light
dIntensity The diffuse intensity of the light
position The position of the light
constant The constant attenuation of the light
linear The linear attenuation of the light
quadratic The quadratic attenuation of the light
Definition at line 10 of file PointLight.cpp.
     : Light(shadowWidth, shadowHeight, color, aIntensity, dIntensity),
       m_position(position),
       m_constant(constant),
       m_linear(linear),
       m_quadratic(quadratic),
       m_farPlane(far) {
     float aspect =
         static_cast<float>(shadowWidth) / static_cast<float>(shadowHeight);
     m_lightProj = glm::perspective(glm::radians(90.0f), aspect, near, far);
     // m_shadowMap = new OmniShadowMap();
     // m_shadowMap->Init(shadowWidth, shadowHeight);
 }
References PointLight().
Referenced by PointLight().
~PointLight()
PointLight::~PointLight ()
Destroy the Point Light object.
Definition at line 81 of file PointLight.cpp.
 {}
Member Function Documentation
CalculateLightTransform()
std::vector< glm::mat4 > PointLight::CalculateLightTransform () const
Calculates the light transform matrices.
Returns
std::vector<glm::mat4>
Definition at line 44 of file PointLight.cpp.
{
     std::vector<glm::mat4> lightMatrices;
     lightMatrices.push_back(m_lightProj *
                             glm::lookAt(m_position,
                                         m_position + glm::vec3(1.0, 0.0, 0.0),
                                         glm::vec3(0.0, -1.0, 0.0)));
     lightMatrices.push_back(m_lightProj *
                             glm::lookAt(m_position,
                                         m_position + glm::vec3(-1.0, 0.0, 0.0),
                                         glm::vec3(0.0, -1.0, 0.0)));
     lightMatrices.push_back(m_lightProj *
                             glm::lookAt(m_position,
                                         m_position + glm::vec3(0.0, 1.0, 0.0),
                                         glm::vec3(0.0, 0.0, 1.0)));
     lightMatrices.push_back(m_lightProj *
                             glm::lookAt(m_position,
                                         m_position + glm::vec3(0.0, -1.0, 0.0),
                                         glm::vec3(0.0, 0.0, -1.0)));
     lightMatrices.push_back(m_lightProj *
                             glm::lookAt(m_position,
                                         m_position + glm::vec3(0.0, 0.0, 1.0),
                                         glm::vec3(0.0, -1.0, 0.0)));
     lightMatrices.push_back(m_lightProj *
                             glm::lookAt(m_position,
                                         m_position + glm::vec3(0.0, 0.0, -1.0),
                                         glm::vec3(0.0, -1.0, 0.0)));
     return lightMatrices;
 }
GetFarPlane()
GLfloat PointLight::GetFarPlane () const
Get the Far Plane.
Returns
GLfloat
Definition at line 77 of file PointLight.cpp.
 { return m_farPlane; }
GetPosition()
glm::vec3 PointLight::GetPosition () const
Get the Position.
Returns
glm::vec3
Definition at line 79 of file PointLight.cpp.
 { return m_position; }
UseLight()
void PointLight::UseLight (GLuint ambientColorLoc, GLuint ambientIntensityLoc, GLuint diffuseIntensityLoc, GLuint positionLoc, GLuint constantLoc, GLuint linearLoc, GLuint quadraticLoc) const
Enables the light by passing uniforms to the shader.
Parameters
ambientColorLoc
ambientIntensityLoc
diffuseIntensityLoc
positionLoc
constantLoc
linearLoc
quadraticLoc
Definition at line 29 of file PointLight.cpp.
{
     glUniform3f(ambientColorLoc, m_color.x, m_color.y, m_color.z);
     glUniform1f(ambientIntensityLoc, m_ambientIntensity);
     glUniform1f(diffuseIntensityLoc, m_diffuseIntensity);
     glUniform3f(positionLoc, m_position.x, m_position.y, m_position.z);
     glUniform1f(constantLoc, m_constant);
     glUniform1f(linearLoc, m_linear);
     glUniform1f(quadraticLoc, m_quadratic);
 }
Member Data Documentation
m_constant
GLfloat PointLight::m_constant protected
Equation of the light.
Definition at line 85 of file PointLight.hpp.
m_farPlane
GLfloat PointLight::m_farPlane protected
The far plane.
Definition at line 88 of file PointLight.hpp.
m_linear
GLfloat PointLight::m_linear protected
Definition at line 85 of file PointLight.hpp.
m_position
glm::vec3 PointLight::m_position protected
Position of the light.
Definition at line 82 of file PointLight.hpp.
m_quadratic
GLfloat PointLight::m_quadratic protected
Definition at line 85 of file PointLight.hpp.
The documentation for this class was generated from the following files:
src/View/Renderer/OpenGL/Objects/PointLight.hpp
src/View/Renderer/OpenGL/Objects/PointLight.cpp