ICT397 Assignment 2: Projectile Class Reference
Projectile Class Reference
#include <Projectile.hpp>
Public Member Functions
void init ()
Initializes the game object.
void update (double delta_time)
Updates the game object with delta time.
void fixed_update (double delta_time)
Updates the game object with fixed delta time.
void add_draw_call ()
Adds a draw call to the renderer.
void draw (std::shared_ptr< Shader > shader)
The draw call.
void save_object ()
Saves the object to lua file.
~Projectile ()=default
default destructor.
void freeze_projectile ()
Freeze the projectile.
void remove_colliders ()
Removes the colliders from the rigid body.
void set_time_alive_left (float time)
Set the time alive left for the projectile.
void set_damage (float damage)
Set the damage of the projectile.
void set_logic_script (const std::string &script)
Set the logic script.
void set_floor_contact (bool val)
Set the floor contact flag.
void set_to_delete (bool val)
Set to delete flag.
Public Member Functions inherited from PhysicsObject
PhysicsObject ()=default
Default constructor for physics object.
void initModel (const std::string &model_name, const std::string &material_name)
Initialised the model.
void initRB (glm::vec3 pos, glm::vec3 rotation, float angle)
Initialised the rigid body.
~PhysicsObject ()=default
default destructor
Public Member Functions inherited from BodyRigid
void createBR (glm::vec3 pos, glm::vec3 rotation, float angle)
Creates rigid body.
void set_position (glm::vec3 pos)
Sets the position of the rigid body.
void setType (int type)
Set type of rigid body.
int getType ()
Gets the type of rigid body.
void enableGravity (bool val)
Set if you want gravity.
void setLinearVelocityDamping (float val)
Movement dampining.
void setAngularVelocityDamping (float val)
Rotation dampining.
void setIfBodyCanSleep (bool val)
Sets if the body can go to sleep.
void addForce (glm::vec3 force)
Adds force to the object.
void setLinearVelocity (glm::vec3 velocity)
set force to the object
void addTorque (glm::vec3 torque)
Adds torque to the object.
void setAngularVelocity (glm::vec3 velocity)
set torque to the object
glm::vec3 getPosition ()
Gets the position vector.
glm::vec3 getRotation ()
Gets the axis of rotation vector of the rigid body.
float getAngle ()
Gets the angle around the axis of rotation of the rigid body.
glm::vec3 getLinearVelocity ()
Gets the linear velocity of the rigid body.
glm::vec3 getAngularVelocity ()
Gets the angular velocity of the rigid body.
void addBoxCollider (glm::vec3 pos, glm::vec3 halfSize, float bounciness, float friction)
Adds a box ciller to a rigid body.
void addSphereCollider (glm::vec3 pos, float radius, float bounciness, float friction)
Adds a sphere collider to a rigid body.
void addCapsuleCollider (glm::vec3 pos, float radius, float height, float bounciness, float friction)
Adds a capsule collider to a rigid body.
void addHeightFieldShape (float bounciness, float friction)=delete
Creates a height field shape collision box.
void setLinearAxisFactor (glm::vec3 factor)
Changes the linear axis factor. I.e. if set a axis to 0 it will no longer move on that axis.
void setAngularAxisFactor (glm::vec3 factor)
Changes the angular axis factor. I.e. if set a axis to 0 it will no longer rotate on that axis.
~BodyRigid ()
Destructor.
std::vector< colliderData_capsule > getCapsuleColliders ()
Public Member Functions inherited from Body
void setCreator (bool val)
Sets if the object is a creator (true) or destructor (false). A creator should be one of the fist game objects while a destoryer should be one of the last.
void physicsDebugger ()
Adds all possible physic debugger options.
void physicsWorldDestroyer ()
Destoryes physic world.
~Body ()
Destructor.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
bool to_be_deleted_ = false
The time alive left.
bool floor_contact_ = false
Floor contact flag.
float time_alive_left_ = 20.0f
The time alive left.
float damage_ = 1.0f
The damage.
bool collision_detected_ = false
The collision detection flag.
std::string lua_script_
The logic script.
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Protected Member Functions inherited from PhysicsObject
void saveSphereCollider (size_t index)
Saves the sphere collider of rb.
void saveCapsuleCollider (size_t index)
Saves the capsule collider of rb.
void saveBoxCollider (size_t index)
Saves the box collider of rb.
void saveCollider (size_t index, int type)
Saves the collider of rb.
Protected Attributes inherited from PhysicsObject
std::string model_name_
The model of the item.
std::string material_name_
The material of the item.
Protected Attributes inherited from BodyRigid
BodyRigidPhysics rb
Facaded react rigid body
int m_numOfColliders = 0
The number of colliders in the rb
std::vector< colliderData_sphere > m_sphere
List of sphere colliders. Used for storing data to file
std::vector< colliderData_capsule > m_capsule
List of capsule colliders. Used for storing data to file
std::vector< colliderData_box > m_box
List of capsule colliders. Used for storing data to file
Detailed Description
Definition at line 6 of file Projectile.hpp.
Constructor & Destructor Documentation
~Projectile()
Projectile::~Projectile () default
default destructor.
Member Function Documentation
add_draw_call()
void Projectile::add_draw_call () virtual
Adds a draw call to the renderer.
Reimplemented from PhysicsObject.
Definition at line 42 of file Projectile.cpp.
 { PhysicsObject::add_draw_call(); }
draw()
void Projectile::draw (std::shared_ptr< Shader > shader) virtual
The draw call.
Parameters
shader The shader to use.
Reimplemented from PhysicsObject.
Definition at line 44 of file Projectile.cpp.
{
     PhysicsObject::draw(shader);
 }
fixed_update()
void Projectile::fixed_update (double delta_time) virtual
Updates the game object with fixed delta time.
Parameters
delta_time The time since the last fixed tick.
Reimplemented from PhysicsObject.
Definition at line 36 of file Projectile.cpp.
{
     position = rb.getPosition();
     rotation = rb.getRotation();
     angle = rb.getAngle();
 }
freeze_projectile()
void Projectile::freeze_projectile ()
Freeze the projectile.
Definition at line 84 of file Projectile.cpp.
{
     rb.setAngularAxisFactor(glm::vec3(0));
     rb.setLinearAxisFactor(glm::vec3(0));
     rb.setLinearVelocity(glm::vec3(0));
     rb.setAngularVelocity(glm::vec3(0));
     position.y = GenericFunctions::getHeight(position.x, position.z) + 0.1;
 }
init()
void Projectile::init () virtual
Initializes the game object.
Reimplemented from BodyRigid.
Definition at line 3 of file Projectile.cpp.
 {}
remove_colliders()
void Projectile::remove_colliders ()
Removes the colliders from the rigid body.
Definition at line 92 of file Projectile.cpp.
 { rb.removeColliders(); }
save_object()
void Projectile::save_object () virtual
Saves the object to lua file.
Precondition
Object exists
Postcondition
Object saved
Reimplemented from PhysicsObject.
Definition at line 48 of file Projectile.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle + 0.01,
                                  "Projectile");
     ObjectSaving::addComma();
     ObjectSaving::addValue("modelName", model_name_, false);
     ObjectSaving::addValue("material_name", material_name_, false);
     ObjectSaving::addValue("rbType", rb.getRBType(), false);
     ObjectSaving::addValue("gravity", (int)rb.getIfGravityActive(), false);
     ObjectSaving::addValue("xForce", rb.getLinearVelocity().x, false);
     ObjectSaving::addValue("yForce", rb.getLinearVelocity().y, false);
     ObjectSaving::addValue("zForce", rb.getLinearVelocity().z, false);
     ObjectSaving::addValue("xTorque", rb.getAngularVelocity().x, false);
     ObjectSaving::addValue("yTorque", rb.getAngularVelocity().y, false);
     ObjectSaving::addValue("zTorque", rb.getAngularVelocity().z, false);
     ObjectSaving::addValue("linearDamping", rb.getLinearDamping(), false);
     ObjectSaving::addValue("angularDamping", rb.getAngularDamping(), false);
     ObjectSaving::addValue("sleep", (int)rb.getIfAllowedSleep(), false);
     ObjectSaving::addValue("numOfColliders", rb.getNumberOfColliders(), false);
     ObjectSaving::addValue("timeAliveLeft", time_alive_left_, false);
     ObjectSaving::addValue("damage", damage_, false);
     ObjectSaving::addValue("logic", lua_script_, false);
     ObjectSaving::addValue("toDelete", to_be_deleted_, false);
     ObjectSaving::addValue("floorContact", floor_contact_, true);
     ObjectSaving::closeStruct();
     for (int count = 0; count < rb.getNumberOfColliders(); count++) {
         int type = rb.getColliderType(count);
         ObjectSaving::createStruct("collider" + std::to_string(count + 1));
         saveCollider(count, type);
         ObjectSaving::closeStruct();
     }
     ObjectSaving::closeFile();
 }
References ObjectSaving::addComma(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), and ObjectSaving::openFile().
set_damage()
void Projectile::set_damage (float damage)
Set the damage of the projectile.
Parameters
damage The damage.
Definition at line 96 of file Projectile.cpp.
 { damage_ = damage; }
set_floor_contact()
void Projectile::set_floor_contact (bool val)
Set the floor contact flag.
Parameters
val
Definition at line 102 of file Projectile.cpp.
 { floor_contact_ = val; }
set_logic_script()
void Projectile::set_logic_script (const std::string & script)
Set the logic script.
Parameters
script The script.
Definition at line 98 of file Projectile.cpp.
{
     lua_script_ = script;
 }
set_time_alive_left()
void Projectile::set_time_alive_left (float time)
Set the time alive left for the projectile.
Parameters
time The time alive left.
Definition at line 94 of file Projectile.cpp.
 { time_alive_left_ = time; }
set_to_delete()
void Projectile::set_to_delete (bool val)
Set to delete flag.
Parameters
val
Definition at line 104 of file Projectile.cpp.
 { to_be_deleted_ = val; }
update()
void Projectile::update (double delta_time) virtual
Updates the game object with delta time.
Parameters
delta_time The time since the last frame.
Reimplemented from PhysicsObject.
Definition at line 5 of file Projectile.cpp.
{
     sol::state& lua = LuaManager::get_instance().get_state();
     if (position.y - 0.1 <=
         GenericFunctions::getHeight(position.x, position.z)) {
         floor_contact_ = true;
     }
     lua["remove_obj"] = remove;
     lua["to_be_deleted"] = to_be_deleted_;
     lua["floor_contact"] = floor_contact_;
     lua["time_alive_left"] = time_alive_left_;
     lua["damage"] = damage_;
     lua["delta_time"] = delta_time;
     lua["collision"] = collision_detected_;
     lua["xPos"] = position.x;
     lua["zPos"] = position.z;
     lua.set_function("remove_colliders", &Projectile::remove_colliders, this);
     lua.set_function("freeze_projectile", &Projectile::freeze_projectile, this);
     lua.script_file(lua_script_);
     remove = lua["remove_obj"];
     to_be_deleted_ = lua["to_be_deleted"];
     time_alive_left_ = lua["time_alive_left"];
     damage_ = lua["damage"];
     position.x = lua["xPos"];
     position.z = lua["zPos"];
 }
Member Data Documentation
collision_detected_
bool Projectile::collision_detected_ = false private
The collision detection flag.
Definition at line 107 of file Projectile.hpp.
damage_
float Projectile::damage_ = 1.0f private
The damage.
Definition at line 105 of file Projectile.hpp.
floor_contact_
bool Projectile::floor_contact_ = false private
Floor contact flag.
Definition at line 101 of file Projectile.hpp.
lua_script_
std::string Projectile::lua_script_ private
The logic script.
Definition at line 109 of file Projectile.hpp.
time_alive_left_
float Projectile::time_alive_left_ = 20.0f private
The time alive left.
Definition at line 103 of file Projectile.hpp.
to_be_deleted_
bool Projectile::to_be_deleted_ = false private
The time alive left.
Definition at line 99 of file Projectile.hpp.
The documentation for this class was generated from the following files:
src/Model/GameObject/Projectile.hpp
src/Model/GameObject/Projectile.cpp