My Project: ResourceManager Class Reference
ResourceManager Class Reference
#include <ResourceManager.hpp>
Public Member Functions
ModelManager & get_model_manager ()
Get the model manager.
TextureManager & get_texture_manager ()
Get the texture manager.
MaterialManager & get_material_manager ()
Get the material manager.
ResourceManager (ResourceManager &other)=delete
ResourceManager (const ResourceManager &other)=delete
void operator= (ResourceManager &&)=delete
void operator= (const ResourceManager &)=delete
Static Public Member Functions
static ResourceManager & get_instance ()
Get the instance of the Resource Manager.
Private Member Functions
ResourceManager ()
Construct a new Resource Manager object.
Private Attributes
TextureManager texture_manager_
The texture manager.
ModelManager model_manager_
The model manager.
MaterialManager material_manager_
The material manager.
Detailed Description
Definition at line 12 of file ResourceManager.hpp.
Constructor & Destructor Documentation
ResourceManager() [1/3]
ResourceManager::ResourceManager (ResourceManager & other) delete
ResourceManager() [2/3]
ResourceManager::ResourceManager (const ResourceManager & other) delete
ResourceManager() [3/3]
ResourceManager::ResourceManager () private
Construct a new Resource Manager object.
Definition at line 18 of file ResourceManager.cpp.
{
     texture_manager_.lua_access();
     model_manager_.lua_access();
     material_manager_.lua_access();
 }
Member Function Documentation
get_instance()
ResourceManager & ResourceManager::get_instance () static
Get the instance of the Resource Manager.
Returns
ResourceManager&
Definition at line 3 of file ResourceManager.cpp.
{
     static ResourceManager instance;
     return instance;
 }
Referenced by MaterialLuaController::CreateLuaAccess(), Item::draw(), PhysicsObject::draw(), Water::draw(), gui::lua_image(), and ReflexEngine::run().
get_material_manager()
MaterialManager & ResourceManager::get_material_manager ()
Get the material manager.
Returns
MaterialManager&
Definition at line 14 of file ResourceManager.cpp.
{
     return material_manager_;
 }
Referenced by Item::draw(), and PhysicsObject::draw().
get_model_manager()
ModelManager & ResourceManager::get_model_manager ()
Get the model manager.
Returns
ModelManager&
Definition at line 8 of file ResourceManager.cpp.
 { return model_manager_; }
Referenced by MaterialLuaController::CreateLuaAccess(), Item::draw(), and PhysicsObject::draw().
get_texture_manager()
TextureManager & ResourceManager::get_texture_manager ()
Get the texture manager.
Returns
TextureManager&
Definition at line 10 of file ResourceManager.cpp.
{
     return texture_manager_;
 }
Referenced by MaterialLuaController::CreateLuaAccess(), Water::draw(), and gui::lua_image().
operator=() [1/2]
void ResourceManager::operator= (const ResourceManager &) delete
operator=() [2/2]
void ResourceManager::operator= (ResourceManager &&) delete
Member Data Documentation
material_manager_
MaterialManager ResourceManager::material_manager_ private
The material manager.
Definition at line 56 of file ResourceManager.hpp.
model_manager_
ModelManager ResourceManager::model_manager_ private
The model manager.
Definition at line 53 of file ResourceManager.hpp.
texture_manager_
TextureManager ResourceManager::texture_manager_ private
The texture manager.
Definition at line 50 of file ResourceManager.hpp.
The documentation for this class was generated from the following files:
src/Controller/ResourceManager/ResourceManager.hpp
src/Controller/ResourceManager/ResourceManager.cpp