ICT397 Assignment 2: messageDispatcher Class Reference
messageDispatcher Class Reference
#include <messageDispatcher.h>
Public Member Functions
void dispatchMsg (double delay, int sender, int receiver, int msg, sol::object extraInfo)
void dispatchDelayedMessages ()
Send out any delayed messages. This method is calledeach time through the main game loop.
Private Member Functions
void discharge (NPC *pReceiver, const telegram &msg)
Private Attributes
std::set< telegram > PriorityQ
Detailed Description
Definition at line 15 of file messageDispatcher.h.
Member Function Documentation
discharge()
void messageDispatcher::discharge (NPC * pReceiver, const telegram & msg) private
Definition at line 11 of file messageDispatcher.cpp.
{
     if (!pReceiver->handleMessage(msg)) {
         std::cerr << "Message not handled" << std::endl;
     }
 }
References NPC::handleMessage().
Referenced by dispatchMsg().
dispatchDelayedMessages()
void messageDispatcher::dispatchDelayedMessages ()
Send out any delayed messages. This method is calledeach time through the main game loop.
Definition at line 51 of file messageDispatcher.cpp.
{
     // get current time
     double currentTime = EngineTime::get_time_unpaused();
     // now peek at the queue to see if any telegrams need dispatching.
     // remove all telegrams from the front of the queue that have gone
     // past their sell by date
     while (!PriorityQ.empty() &&
            (PriorityQ.begin()->dispatchTime < currentTime) &&
            (PriorityQ.begin()->dispatchTime > 0)) {
         // read the telegram from the front of the queue
         const telegram& message = *PriorityQ.begin();
         // find the recipient
         NPC* pReceiver = entityMgr.getEntityFromID(message.receiver);
         // send the telegram to the recipient
         discharge(pReceiver, message);
         // remove it from the queue
         PriorityQ.erase(PriorityQ.begin());
     }
 }
References EngineTime::get_time_unpaused().
dispatchMsg()
void messageDispatcher::dispatchMsg (double delay, int sender, int receiver, int msg, sol::object extraInfo)
@breif Send a message to anther agent. Recieving agent is referenced by ID
Parameters
delay - The dealy on the message before it should be sent
sender - The id of the send of the message
reciever - The id of the receiver of the message
msg - The message contents
extraInfo - Extra information of the message
Definition at line 23 of file messageDispatcher.cpp.
{
     // get a pointer to the receiver
     NPC* pReceiver = entityMgr.getEntityFromID(receiver);
     // make sure the receiver is valid
     if (pReceiver == NULL) {
         std::cerr << "\nWarning! No Receiver with ID of " << receiver
                   << " found" << std::endl;
         return;
     }
     // create the telegram
     telegram message(0, sender, receiver, msg, additionalInfo);
     // if there is no delay, route telegram immediately
     if (delay <= 0.0) {  // send the telegram to the recipient
         discharge(pReceiver, message);
     } else {  // else calculate the time when the telegram should be dispatched
         double currentTime = EngineTime::get_time_unpaused();
         message.dispatchTime = currentTime + delay;
         // and put it in the queue
         PriorityQ.insert(message);
     }
 }
References discharge(), telegram::dispatchTime, and EngineTime::get_time_unpaused().
Member Data Documentation
PriorityQ
std::set<telegram> messageDispatcher::PriorityQ private
a std::set is used as the container for the delayed messages because of the benefit of automatic sorting and avoidance of duplicates. Messages are sorted by their dispatch time.
Definition at line 20 of file messageDispatcher.h.
The documentation for this class was generated from the following files:
src/Controller/AI/messageDispatcher.h
src/Controller/AI/messageDispatcher.cpp