ICT397 Assignment 2: DirectionalLightObject Class Reference
DirectionalLightObject Class Reference
A directional light game object.
#include <DirectionalLightObject.hpp>
Public Member Functions
DirectionalLightObject (const DirectionalLightData &light_data)
Construct a new Directional Light Object object.
void init () override
Initializes the game object.
void update (double delta_time) override
Updates the game object with delta time.
void fixed_update (double delta_time) override
Updates the game object with fixed delta time.
void add_draw_call () override
Adds a draw call to the renderer.
void draw (std::shared_ptr< Shader > shader) override
The draw call.
void save_object () override
Saves the object to lua file.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
DirectionalLightData light_data_
The directional light data.
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Detailed Description
A directional light game object.
Definition at line 10 of file DirectionalLightObject.hpp.
Constructor & Destructor Documentation
DirectionalLightObject()
DirectionalLightObject::DirectionalLightObject (const DirectionalLightData & light_data)
Construct a new Directional Light Object object.
Parameters
light_data The light data.
Definition at line 6 of file DirectionalLightObject.cpp.
     : light_data_(light_data) {}
References DirectionalLightObject().
Referenced by DirectionalLightObject(), and GameAssetFactory::load_directional_light().
Member Function Documentation
add_draw_call()
void DirectionalLightObject::add_draw_call () override virtual
Adds a draw call to the renderer.
Implements GameObject.
Definition at line 10 of file DirectionalLightObject.cpp.
{
     auto& renderer = ReflexEngine::get_instance().renderer_;
     renderer.add_directional_light(light_data_);
 }
draw()
void DirectionalLightObject::draw (std::shared_ptr< Shader > shader) inline override virtual
The draw call.
Parameters
shader The shader to use.
Implements GameObject.
Definition at line 48 of file DirectionalLightObject.hpp.
 {}
fixed_update()
void DirectionalLightObject::fixed_update (double delta_time) inline override virtual
Updates the game object with fixed delta time.
Parameters
delta_time The time since the last fixed tick.
Implements GameObject.
Definition at line 36 of file DirectionalLightObject.hpp.
 {}
init()
void DirectionalLightObject::init () inline override virtual
Initializes the game object.
Implements GameObject.
Definition at line 22 of file DirectionalLightObject.hpp.
 {}
save_object()
void DirectionalLightObject::save_object () override virtual
Saves the object to lua file.
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 16 of file DirectionalLightObject.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle,
                                  "DirectionalLight");
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("light");
     ObjectSaving::createStruct("color");
     ObjectSaving::addValue("r", light_data_.color.x, false);
     ObjectSaving::addValue("g", light_data_.color.y, false);
     ObjectSaving::addValue("b", light_data_.color.z, true);
     ObjectSaving::closeStruct();
     ObjectSaving::addComma();
     ObjectSaving::addValue("ambient_intensity", light_data_.ambient_intensity,
                            false);
     ObjectSaving::addValue("diffuse_intensity", light_data_.diffuse_intensity,
                            false);
     ObjectSaving::createStruct("direction");
     ObjectSaving::addValue("x", light_data_.direction.x, false);
     ObjectSaving::addValue("y", light_data_.direction.y, false);
     ObjectSaving::addValue("z", light_data_.direction.z, true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::addComma(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), ObjectSaving::createStruct(), and ObjectSaving::openFile().
update()
void DirectionalLightObject::update (double delta_time) inline override virtual
Updates the game object with delta time.
Parameters
delta_time The time since the last frame.
Implements GameObject.
Definition at line 29 of file DirectionalLightObject.hpp.
 {}
Member Data Documentation
light_data_
DirectionalLightData DirectionalLightObject::light_data_ private
The directional light data.
Definition at line 60 of file DirectionalLightObject.hpp.
The documentation for this class was generated from the following files:
src/Model/GameObject/DirectionalLightObject.hpp
src/Model/GameObject/DirectionalLightObject.cpp