ICT397 Assignment 2: networkManager Class Reference
networkManager Class Reference
#include <NetworkManager.hpp>
Public Member Functions
void InitNetwork ()
Initialises Network.
void SetupClient (std::string userName)
Initialises Network for client. Also handles client username.
bool ConnectClient (char *serverIP)
Connects the client to the server. Returns true if connection was successful or false if connection was unsuccessful.
void SetupServer (std::string userName)
Initialises and begins a server session. Running on the network port number 60000. Also sets isServer to "true".
void ChangeName (std::string userName)
Changes the name of the client or server.
void MessageSend (char *inputMessage)
Sends a message across the network to the server (or from the server to all connected clients)
std::string ReceiveMessage ()
Receives a message from the network. It also handles the contents of the message.
void DestroySession ()
Ends the current session.
bool ConnectionStatus ()
Gets the status of the connection.
bool HasReceivedChatMessage ()
Gets if a chat message has been received.
char * GetName ()
Gets the username.
bool GetServer ()
Gets if the network manager is a server or client.
void ObjectPositionSend (glm::vec3 position)
Sends the position of an object.
glm::vec3 ObjectPositionReceive ()
Receives the object position across the network.
bool ObjectMissedData ()
Gets if the network manager missed getting valid data from ObjectPositionReceive.
Private Types
enum GameMessages { ID_GAME_MESSAGE_1 = ID_USER_PACKET_ENUM + 1, ID_GAME_MESSAGE_2 = ID_USER_PACKET_ENUM + 2 }
Private Member Functions
unsigned char GetPacketIdentifier (RakNet::Packet *p)
Gets the packet identifier and returns it.
Private Attributes
char message [512]
The message that was received.
char name [256]
Name given to the client/server.
bool isServer
Is the current instance a server?
bool connected
Have we connected to a server? Is there a connection to a client?
bool init
Have we initialsed the networkManager?
bool dataMissed
Have we missed any data.
int connectedClients
How many clients are we connected to? (should be 1 for clients, > 1 for servers when multiple clients)
RakNet::RakPeerInterface * peer
RakNet::Packet * packet
The packet of information sent/received by RakNet.
Detailed Description
Definition at line 18 of file NetworkManager.hpp.
Member Enumeration Documentation
GameMessages
enum networkManager::GameMessages private
Enumerator
ID_GAME_MESSAGE_1
User defined Enumeration for use in message sending
ID_GAME_MESSAGE_2
User defined Enumeration for use in object sending
Definition at line 240 of file NetworkManager.hpp.
                       {
         ID_GAME_MESSAGE_1 = ID_USER_PACKET_ENUM + 1,
         ID_GAME_MESSAGE_2 = ID_USER_PACKET_ENUM + 2
     };
Member Function Documentation
ChangeName()
void networkManager::ChangeName (std::string userName)
Changes the name of the client or server.
Parameters
userName - the username that the client or server will be using.
Returns
void
Precondition
None
Postcondition
Changes the user's network name
Definition at line 76 of file NetworkManager.cpp.
{
     std::string oldName = name;
     std::string updatedName = userName;
     userName.append(": ");
     strcpy(name, userName.c_str());
     if (connected) {
         RakNet::BitStream bsOut;
         bsOut.Write((RakNet::MessageID)ID_GAME_MESSAGE_1);
         std::string nameChangeMsg;
         char nameChangeChar[256];
         nameChangeMsg.append(oldName);
         nameChangeMsg.append(" Changed their name to ");
         nameChangeMsg.append(updatedName);
         nameChangeMsg.append("\n");
         strcpy(nameChangeChar, nameChangeMsg.c_str());
         printf("%s\n", nameChangeChar);
         bsOut.Write(nameChangeChar);
         peer->Send(&bsOut, HIGH_PRIORITY, RELIABLE_ORDERED, 0,
                    RakNet::UNASSIGNED_SYSTEM_ADDRESS, true);
     }
 }
References connected, and name.
Referenced by GenericFunctions::networkSetUsername().
ConnectClient()
bool networkManager::ConnectClient (char * serverIP)
Connects the client to the server. Returns true if connection was successful or false if connection was unsuccessful.
Parameters
serverIP
Returns
bool
Precondition
SetupClient has been run
Postcondition
Attempts connection to provided server IP using the port number 60000
Definition at line 41 of file NetworkManager.cpp.
{
     if (peer != NULL && init) {
         bool connecting;
         if (serverIP[0] == '\n') {
             strcpy(serverIP, "127.0.0.1");
         }
         connecting = peer->Connect(serverIP, SERVER_PORT, 0, 0);
         if (connecting) {
             printf("Not connected");
         } else {
             connected = true;
         }
         return (connecting);
     }
     return (false);
 }
References connected.
Referenced by GenericFunctions::networkClientConnect().
ConnectionStatus()
bool networkManager::ConnectionStatus ()
Gets the status of the connection.
Parameters
void
Returns
bool
Precondition
A session must be running (either ConnectClient or SetupServer must have been run) and connected
Postcondition
Returns the status of the connection (are you connected or not?)
Definition at line 267 of file NetworkManager.cpp.
{
     if (connectedClients > 0) {
         return (true);
     } else {
         return (false);
     }
 }
References connectedClients.
Referenced by GenericFunctions::networkConnectionStatus(), and GenericFunctions::networkPvPConnectionStatus().
DestroySession()
void networkManager::DestroySession ()
Ends the current session.
Parameters
void
Returns
void
Precondition
A session must be running (either ConnectClient or SetupServer must have been run)
Postcondition
Ends either the connection to the server or the server itself (depending on the state of the isServer boolean)
Definition at line 257 of file NetworkManager.cpp.
{
     if (init) {
         RakNet::RakPeerInterface::DestroyInstance(peer);
         printf("Killed the session\n");
         init = false;
         isServer = false;
         connectedClients = 0;
     }
 }
References connectedClients, init, and isServer.
Referenced by GenericFunctions::networkEnd().
GetName()
char * networkManager::GetName ()
Gets the username.
Parameters
void
Returns
bool
Precondition
A session must be running (either ConnectClient or SetupServer must have been run) and connected
Postcondition
Returns a username
Definition at line 284 of file NetworkManager.cpp.
 { return name; }
References name.
Referenced by GenericFunctions::networkSendMessage(), and GenericFunctions::networkSetUsername().
GetPacketIdentifier()
unsigned char networkManager::GetPacketIdentifier (RakNet::Packet * p) private
Gets the packet identifier and returns it.
Parameters
*p - the packet of network data.
Returns
unsigned char - The packet ID
Precondition
Called by HandleMessage
Postcondition
Returns the packet's ID for use in HandleMessage
Definition at line 288 of file NetworkManager.cpp.
{
     if (p == 0) return 255;
     if ((unsigned char)p->data[0] == ID_TIMESTAMP) {
         RakAssert(p->length > sizeof(RakNet::MessageID) + sizeof(RakNet::Time));
         return (unsigned char)
             p->data[sizeof(RakNet::MessageID) + sizeof(RakNet::Time)];
     } else
         return (unsigned char)p->data[0];
 }
GetServer()
bool networkManager::GetServer ()
Gets if the network manager is a server or client.
Parameters
void
Returns
bool
Precondition
A session must be running (either ConnectClient or SetupServer must have been run) and connected
Postcondition
Returns true if server, false if client
Definition at line 286 of file NetworkManager.cpp.
 { return isServer; }
References isServer.
Referenced by GenericFunctions::networkSendMessage(), and GenericFunctions::networkSetUsername().
HasReceivedChatMessage()
bool networkManager::HasReceivedChatMessage ()
Gets if a chat message has been received.
Parameters
void
Returns
bool
Precondition
A session must be running (either ConnectClient or SetupServer must have been run) and connected
Postcondition
Returns the validity of a received chat message
Definition at line 275 of file NetworkManager.cpp.
{
     for (packet = peer->Receive(); packet; packet = peer->Receive()) {
         if (GetPacketIdentifier(packet) == ID_GAME_MESSAGE_1) {
             return (true);
         }
     }
     return (false);
 }
Referenced by GenericFunctions::networkValidChatMessage().
InitNetwork()
void networkManager::InitNetwork ()
Initialises Network.
Parameters
userName - The username that the client will be using. If this is null, a default name of "Client" will be used. Also sets isServer to "false".
Returns
Void
Precondition
None
Postcondition
network instance initialised
Definition at line 21 of file NetworkManager.cpp.
{
     peer = RakNet::RakPeerInterface::GetInstance();
     init = true;
     printf("Created the network manager.\n");
 }
References init.
Referenced by GenericFunctions::createNetworkManager().
MessageSend()
void networkManager::MessageSend (char * inputMessage)
Sends a message across the network to the server (or from the server to all connected clients)
Parameters
*inputMessage - The message that will be sent (character limit of 512)
Returns
void
Precondition
Either the client has been successfully connected to a server (using ConnectClient), or SetupServer has been run (if the server)
Postcondition
Sends a message across the network
Definition at line 98 of file NetworkManager.cpp.
{
     char sendMessage[sizeof(inputMessage) + sizeof(name)];
     strcpy(sendMessage, name);
     strcat(sendMessage, inputMessage);
     RakNet::BitStream bsOut;
     bsOut.Write((RakNet::MessageID)ID_GAME_MESSAGE_1);
     bsOut.Write(sendMessage);
     peer->Send(&bsOut, HIGH_PRIORITY, RELIABLE_ORDERED, 0,
                RakNet::UNASSIGNED_SYSTEM_ADDRESS, true);
     // peer->Send(sendMessage, (int)strlen(sendMessage) + 1, HIGH_PRIORITY,
     // RELIABLE_ORDERED, 0, RakNet::UNASSIGNED_SYSTEM_ADDRESS, true);
 }
References name.
Referenced by GenericFunctions::networkSendMessage().
ObjectMissedData()
bool networkManager::ObjectMissedData () inline
Gets if the network manager missed getting valid data from ObjectPositionReceive.
Parameters
void
Returns
bool
Precondition
A session must be running (either ConnectClient or SetupServer must have been run) and connected
Postcondition
Returns true if the network manager missed data from ObjectPositionReceive
Definition at line 227 of file NetworkManager.hpp.
 { return dataMissed; }
References dataMissed.
Referenced by GenericFunctions::getReceivingData().
ObjectPositionReceive()
glm::vec3 networkManager::ObjectPositionReceive ()
Receives the object position across the network.
Parameters
void
Returns
vec3- position of a game object
Precondition
A session must be running (either ConnectClient or SetupServer must have been run) and connected. This must be run in an infinite loop (preferably the fixed update for performance optimisation)
Postcondition
Returns the position of the networked object
Definition at line 308 of file NetworkManager.cpp.
{
     packet = peer->Receive();
     if (packet) {
         switch (GetPacketIdentifier(packet)) {
             case ID_GAME_MESSAGE_2: {
                 // RakNet::RakString rs;
                 glm::vec3 tempVec3;
                 RakNet::BitStream bsIn(packet->data, packet->length, false);
                 bsIn.IgnoreBytes(sizeof(RakNet::MessageID));
                 bsIn.Read(tempVec3);
                 // printf("%f %f %f NM\n", tempVec3.x, tempVec3.y, tempVec3.z);
                 bsIn.Reset();
                 dataMissed = false;
                 return (tempVec3);
                 break;
             }
             case ID_CONNECTION_REQUEST_ACCEPTED: {
                 connectedClients++;
                 break;
             }
             case ID_CONNECTION_LOST: {
                 connectedClients--;
                 break;
             }
             case ID_DISCONNECTION_NOTIFICATION: {
                 connectedClients--;
                 break;
             }
         }
     }
     peer->DeallocatePacket(packet);
     //printf("Did not read vector correctly\n");
     dataMissed = true;
     return (glm::vec3(0, 0, 0));
     }
References dataMissed.
ObjectPositionSend()
void networkManager::ObjectPositionSend (glm::vec3 position)
Sends the position of an object.
Parameters
vec3 - position of a game object
Returns
void
Precondition
A session must be running (either ConnectClient or SetupServer must have been run) and connected
Postcondition
Sends the position of an object across the network
Definition at line 299 of file NetworkManager.cpp.
{
     RakNet::BitStream bsOut;
     bsOut.Write((RakNet::MessageID)ID_GAME_MESSAGE_2);
     bsOut.Write(position);
     //printf("%f %f %f NM\n", position.x, position.y, position.z);
     peer->Send(&bsOut, HIGH_PRIORITY, UNRELIABLE_SEQUENCED, 0,
                RakNet::UNASSIGNED_SYSTEM_ADDRESS, true);
 }
ReceiveMessage()
std::string networkManager::ReceiveMessage ()
Receives a message from the network. It also handles the contents of the message.
Parameters
void
Returns
char * - The message
Precondition
This must be run in a while loop for the network manager to receive messages.
Postcondition
Returns the received message to another part of the game engine (notably the gui interface)
Definition at line 111 of file NetworkManager.cpp.
{
     packet = peer->Receive();
     connected = true;
     if (packet) {
         if (isServer) {
             switch (GetPacketIdentifier(packet)) {
                 case ID_REMOTE_DISCONNECTION_NOTIFICATION:
                     return ("Another client has disconnected\n");
                     break;
                 case ID_REMOTE_CONNECTION_LOST:
                     return ("Another client has lost the connection\n");
                     break;
                 case ID_REMOTE_NEW_INCOMING_CONNECTION:
                     printf("Another Connection is incoming\n");
                     connectedClients++;
                     return ("Another client has connected\n");
                     break;
                 case ID_CONNECTION_REQUEST_ACCEPTED:
                     printf("We have connected\n");
                     return ("Our connection request has been accepted\n");
                     break;
                 case ID_NEW_INCOMING_CONNECTION:
                     printf("A Connection is incoming\n");
                     connectedClients++;
                     return ("A connection is incoming\n");
                     break;
                 case ID_NO_FREE_INCOMING_CONNECTIONS:
                     return ("The server is full\n");
                     break;
                 case ID_DISCONNECTION_NOTIFICATION:
                     if (isServer) {
                         connected = false;
                         connectedClients--;
                         return ("A client has disconnected\n");
                     } else {
                         return ("We have been disconnected\n");
                     }
                     break;
                 case ID_CONNECTION_LOST:
                     if (isServer) {
                         connected = false;
                         connectedClients--;
                         RakNet::BitStream bsIn;
                         bsIn.Write((RakNet::MessageID)ID_GAME_MESSAGE_1);
                         bsIn.Write("\nA client has lost connection\n");
                         peer->Send(&bsIn, HIGH_PRIORITY, RELIABLE_ORDERED, 0,
                                    RakNet::UNASSIGNED_SYSTEM_ADDRESS,
                                    true);  // This sends
                                            // the message to everyone
                         return ("\nA client lost the connection\n");
                     } else {
                         return ("Connection lost\n");
                     }
                     break;
                 case ID_GAME_MESSAGE_1: {
                     RakNet::RakString rs;
                     RakNet::BitStream bsIn(packet->data, packet->length, false);
                     bsIn.IgnoreBytes(sizeof(RakNet::MessageID));
                     bsIn.Read(rs);
                     std::string newMessage = static_cast<std::string>(rs);
                     peer->Send(&bsIn, HIGH_PRIORITY, RELIABLE_ORDERED, 0,
                                RakNet::UNASSIGNED_SYSTEM_ADDRESS,
                                true);  // This sends
                                        // the message to everyone
                     bsIn.Reset();
                     return (newMessage);
                     // return (reinterpret_cast<char*>(packet->data));
                 }
                 default:
                     RakNet::RakString rs;
                     RakNet::BitStream bsIn(packet->data, packet->length, false);
                     bsIn.IgnoreBytes(sizeof(RakNet::MessageID));
                     bsIn.Read(rs);
                     peer->Send(&bsIn, HIGH_PRIORITY, RELIABLE_ORDERED, 0,
                                RakNet::UNASSIGNED_SYSTEM_ADDRESS,
                                true);  // This sends
                                        // the message to everyone
                     return static_cast<std::string>(rs);
                     break;
             }
         } else {
             switch (GetPacketIdentifier(packet)) {
                 case ID_REMOTE_DISCONNECTION_NOTIFICATION:
                     return ("Another client has disconnected\n");
                     break;
                 case ID_REMOTE_CONNECTION_LOST:
                     return ("Another client has lost the connection\n");
                     break;
                 case ID_REMOTE_NEW_INCOMING_CONNECTION:
                     printf("Another Connection is incoming\n");
                     return ("Another client has connected\n");
                     break;
                 case ID_CONNECTION_REQUEST_ACCEPTED:
                     printf("We have connected\n");
                     connectedClients++;
                     return ("Our connection request has been accepted\n");
                     break;
                 case ID_NEW_INCOMING_CONNECTION:
                     printf("A Connection is incoming\n");
                     return ("A connection is incoming\n");
                     break;
                 case ID_NO_FREE_INCOMING_CONNECTIONS:
                     return ("The server is full\n");
                     break;
                 case ID_DISCONNECTION_NOTIFICATION:
                     if (isServer) {
                         connected = false;
                         connectedClients--;
                         return ("\nA client has disconnected\n");
                     } else {
                         connected = false;
                         connectedClients--;
                         return ("\nWe have been disconnected\n");
                     }
                     break;
                 case ID_CONNECTION_LOST:
                     if (isServer) {
                         return ("\nA client lost the connection\n");
                     } else {
                         connected = false;
                         connectedClients--;
                         return ("Connection lost\n");
                     }
                     break;
                 case ID_GAME_MESSAGE_1: {
                     RakNet::RakString rs;
                     RakNet::BitStream bsIn(packet->data, packet->length, false);
                     bsIn.IgnoreBytes(sizeof(RakNet::MessageID));
                     bsIn.Read(rs);
                     // printf("%s NM\n", rs.C_String());
                     bsIn.Reset();
                     return static_cast<std::string>(rs);
                     // bsIn.Reset();
                 } break;
                 default:
                     // printf("%s\n", packet->data);
                     return " ";
                     break;
             }
         }
         peer->DeallocatePacket(packet);
     }
     return " ";
 }
References connected, and isServer.
Referenced by GenericFunctions::networkUpdate().
SetupClient()
void networkManager::SetupClient (std::string userName)
Initialises Network for client. Also handles client username.
Parameters
userName - The username that the client will be using. If this is null, a default name of "Client" will be used. Also sets isServer to "false".
Returns
Void
Precondition
string username
Postcondition
network initialised for client
Definition at line 27 of file NetworkManager.cpp.
{
     if (peer != NULL && init) {
         RakNet::SocketDescriptor sd;
         peer->Startup(1, &sd, 1);
         isServer = false;
         if (userName != " ") {
             userName.append(": ");
             strcat(name, userName.c_str());
         } else {
             strcat(name, "Client: ");
         }
     }
 }
References isServer, and name.
Referenced by GenericFunctions::networkClientConnect().
SetupServer()
void networkManager::SetupServer (std::string userName)
Initialises and begins a server session. Running on the network port number 60000. Also sets isServer to "true".
Parameters
username - The username that the server will be using. Defaults to 'Server' if empty.
Returns
void
Precondition
string username
Postcondition
Starts up the server
Definition at line 58 of file NetworkManager.cpp.
{
     if (peer != NULL && init && !isServer) {
         RakNet::SocketDescriptor sd(SERVER_PORT, 0);
         peer->Startup(MAX_CLIENTS, &sd, 1);
         isServer = true;
         if (userName != " ") {
             userName.append(": ");
             strcpy(name, userName.c_str());
         } else {
             strcpy(name, "Server: ");
         }
         peer->SetMaximumIncomingConnections(MAX_CLIENTS);
         printf("Server Running...\n");
         connected = true;
         connectedClients++;  // Server itself is a client
     }
 }
References connected, connectedClients, isServer, and name.
Referenced by GenericFunctions::startNetworkServer().
Member Data Documentation
connected
bool networkManager::connected private
Have we connected to a server? Is there a connection to a client?
Definition at line 30 of file NetworkManager.hpp.
Referenced by ChangeName(), ConnectClient(), ReceiveMessage(), and SetupServer().
connectedClients
int networkManager::connectedClients private
How many clients are we connected to? (should be 1 for clients, > 1 for servers when multiple clients)
Definition at line 39 of file NetworkManager.hpp.
Referenced by ConnectionStatus(), DestroySession(), and SetupServer().
dataMissed
bool networkManager::dataMissed private
Have we missed any data.
Definition at line 36 of file NetworkManager.hpp.
Referenced by ObjectMissedData(), and ObjectPositionReceive().
init
bool networkManager::init private
Have we initialsed the networkManager?
Definition at line 33 of file NetworkManager.hpp.
Referenced by DestroySession(), and InitNetwork().
isServer
bool networkManager::isServer private
Is the current instance a server?
Definition at line 27 of file NetworkManager.hpp.
Referenced by DestroySession(), GetServer(), ReceiveMessage(), SetupClient(), and SetupServer().
message
char networkManager::message[512] private
The message that was received.
Definition at line 21 of file NetworkManager.hpp.
name
char networkManager::name[256] private
Name given to the client/server.
Definition at line 24 of file NetworkManager.hpp.
Referenced by ChangeName(), GetName(), MessageSend(), SetupClient(), and SetupServer().
packet
RakNet::Packet* networkManager::packet private
The packet of information sent/received by RakNet.
Definition at line 46 of file NetworkManager.hpp.
peer
RakNet::RakPeerInterface* networkManager::peer private
The general connection information provided by RakNet. Used for initialisation, sending and receiving data.
Definition at line 43 of file NetworkManager.hpp.
The documentation for this class was generated from the following files:
src/NetworkManager.hpp
src/NetworkManager.cpp