My Project: BttController Class Reference
BttController Class Reference
#include <BttController.hpp>
Public Member Functions
void render (std::shared_ptr< Shader > shader) override
Renders the terrain.
bool load_mesh () override
Reads the heightmap and loads the mesh.
BttController ()
Default contructor for BttController.
~BttController ()
Decontructor for BttController.
void getCameraPosition (const glm::vec3 &pos)
Stores the psoition of the camera within the BttController for later use.
void CreateTerrain (int chunkSize, int chunkDetail, int n)
Initialises the BTT grid by generating vertices, creating BTT structures defining centers and generating LOD distances.
void checkTJunction ()
Searches through BTT and determines if a BTT needs to increase its LOD to remove potential T-Junction (NOT IMPLEMENTED)
void Update (glm::vec3 player)
Updates the mesh when the player moves position.
void getAllIndices (glm::vec3 pos)
Calculates the meshes new indices for all BTTs and stores them for later use.
void set_height_map_size (float size)
Sets the size of the heightmap.
bool load_texture (const char *file_name)
Reads the texture image file and loads the texture.
bool load_detailmap (const char *file_name)
Reads an image file as a detail map.
void render (std::shared_ptr< Shader > shader) override
Renders the terrain.
bool load_mesh () override
Reads the heightmap and loads the mesh.
BttController ()
~BttController ()
void getCameraPosition (const glm::vec3 &pos)
void AddHeightMap (std::vector< float > hmap)
void AddHeightMap (GLfloat *hmap)
void CreateTerrain (int chunkSize, int chunkDetail, int n)
void TestThings ()
void Update (glm::vec3 player)
void getAllIndices (glm::vec3 pos)
const std::vector< glm::vec2 > & getCenters ()
void set_height_map_size (float size)
void set_texture_id (GLuint id)
bool load_texture (const char *file_name)
Reads the texture image file and loads the texture.
bool load_detailmap (const char *file_name)
Reads an image file as a detail map.
Public Member Functions inherited from Terrain
bool load_heightfield (const char *file_name)
Load an image as a heightmap.
bool gen_faultformation (int iterations, size_t size, int min_height, int max_height, float weight)
Generate terrain by the fault formation method.
glm::vec3 get_origin () const
Get the offset to origin of the terrain.
glm::vec3 get_scale () const
Get the scale of the terrain.
float get_height (int x, int z) const
Get the height in terrain space given the x and z coordinates.
float get_height_world (float x, float z) const
Get the height in worldspace given the x and z coordinates.
uint8_t get_height_color (int x, int z) const
Get the height color.
size_t get_width () const
Get the width.
size_t get_length () const
Get the width.
uint8_t * get_height_map ()
Get the height map.
void set_height_map (uint8_t *map)
void set_scale (glm::vec3 scale)
Set the scale.
virtual ~Terrain ()
Destroy the Terrain object.
Private Member Functions
const std::vector< glm::vec2 > & getCenters ()
Gets the array of BTT tile centers.
void GenerateVertices (int chunkSize, int chunkDetail)
Generate all vertices for terrain.
const GLuint findLOD (glm::vec3 pos, glm::vec2 center)
based off player position, determines a BTT's level of detail
void GenerateVertices (int chunkSize, int chunkDetail)
const GLuint findLOD (glm::vec3 pos, glm::vec2 center)
GLuint * convertInt (const std::vector< glm::vec3 > &temp)
GLfloat * convertFloat (const std::vector< glm::vec3 > &temp)
Private Attributes
std::vector< std::vector< Btt > > bttMap
std::vector< glm::vec2 > bttCenters
All binary triangle trees.
std::vector< GLfloat > vertices
All centers for BTT tiles (hypotenuse-adjacent BTTs)
std::vector< GLuint > indices
All the vertices for the terrain.
glm::vec3 cam
All the currently used indices for terrain.
std::vector< GLfloat > distances
Stored position for camera.
std::shared_ptr< Mesh > mesh_ = nullptr
Distances from player for changes in LOD for tile.
bool firstRun
Container for mesh data;.
glm::vec3 prev_pos
Determines if first time of mesh generation.
GLuint current_total_indices
Saves the players previous position.
GLuint chunk_size
Number of current total indices being used.
GLuint chunk_detail
The length/width of BTT grid.
int height_map_size = 0
The length/width of a given tile (vertice number)
std::shared_ptr< Texture > texture_ = nullptr
the length/width of height map
std::shared_ptr< Texture > detailmap = nullptr
Storage for texture.
bool b = true
Additional Inherited Members
Protected Member Functions inherited from Terrain
glm::vec3 calculate_terrain_normal (int x, int z) const
Calculates the normals for the terrain given x and z coordinates.
Protected Attributes inherited from Terrain
uint8_t * heightmap_ = nullptr
An unsigned char array containing the heightmap.
glm::vec3 scale_ = {1.0f, 1.0f, 1.0f}
The scale of the heightmap.
Detailed Description
Definition at line 15 of file BttController.hpp.
Constructor & Destructor Documentation
BttController() [1/2]
BttController::BttController ()
Default contructor for BttController.
Definition at line 5 of file BttController.cpp.
{
     prev_pos = glm::vec3(0, 0, 0);
     current_total_indices = 0;
     chunk_size = 0;
     chunk_detail = 0;
     firstRun = true;
 }
References firstRun.
~BttController() [1/2]
BttController::~BttController ()
Decontructor for BttController.
Definition at line 13 of file BttController.cpp.
{
     for (int i = 0; i < bttMap.size(); ++i) {
         bttMap.at(i).clear();
     }
     bttMap.clear();
     bttCenters.clear();
     vertices.clear();
     distances.clear();
     current_total_indices = 0;
     chunk_size = 0;
     chunk_detail = 0;
 }
BttController() [2/2]
BttController::BttController ()
~BttController() [2/2]
BttController::~BttController ()
Member Function Documentation
AddHeightMap() [1/2]
void BttController::AddHeightMap (GLfloat * hmap)
AddHeightMap() [2/2]
void BttController::AddHeightMap (std::vector< float > hmap)
checkTJunction()
void BttController::checkTJunction ()
Searches through BTT and determines if a BTT needs to increase its LOD to remove potential T-Junction (NOT IMPLEMENTED)
Returns
void
Definition at line 111 of file BttController.cpp.
{
     bool canThing = false;
     for (int i = 0; i < chunk_size; ++i) {
         int iu = i + 1;  // sw triangle, down side check
         int id = i - 1;  // ne triangle, up side check
         for (int j = 0; j < chunk_size; ++j) {
             int jl = (j * 2) - 1;  // sw triangle, left side check
             int jr = (j * 2) + 1;  // ne triangle, right side check
             if (bttMap.at(i).at(j).getLOD() % 2 == 0)
                 canThing = true;
             else
                 canThing = false;
             // out of bounds checking
             // sw triangle
             if (jl >= 0) {
                 if (bttMap.at(i).at(jl).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing)  // check left
                 {
                     bttMap.at(i).at(j * 2).addLeft();
                 }
             }
             if (id >= 0) {
                 if (bttMap.at(id).at(j).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing) {  // check down
                     bttMap.at(i).at(j * 2).addRight();
                 }
             }
             // ne triangle
             if (jr >= chunk_size * 2) {
                 if (bttMap.at(i).at(jr).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing) {  // check right
                     bttMap.at(i).at(j * 2 - 1).addLeft();
                 }
             }
             if (iu >= chunk_size * 2) {
                 if (bttMap.at(iu).at(j).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing) {  // check up
                     bttMap.at(i).at(j * 2 - 1).addRight();
                 }
             }
             // std::cout << "Tile " << i << j << "| left: " << i << jl
             //         << " right: " << i << jr << " up: " << iu << j * 2
             //       << " down: " << id << j * 2 + 1 << std::endl;
         }
     }
 }
convertFloat()
GLfloat * BttController::convertFloat (const std::vector< glm::vec3 > & temp) private
Definition at line 216 of file BttController.cpp.
{
     GLuint size = temp.size() * GLuint(3);
     GLfloat* buffer{new GLfloat[size]{}};
     std::cout << "VERTEX COUNT:  " << temp.size() << std::endl;
     for (int i = 0; i < temp.size(); ++i) {
         for (int j = 0; j < 3; ++j) {
             buffer[(3 * i) + j] = temp.at(i)[j];
         }
     }
     return buffer;
 }
convertInt()
GLuint * BttController::convertInt (const std::vector< glm::vec3 > & temp) private
Definition at line 204 of file BttController.cpp.
{
     GLuint size = temp.size() * GLuint(3);
     GLuint* buffer{new GLuint[size]{}};
     std::cout << "INDEX COUNT:  " << temp.size() << std::endl;
     for (int i = 0; i < temp.size(); ++i) {
         for (int j = 0; j < 3; ++j) {
             buffer[(3 * i) + j] = temp.at(i)[j];
         }
     }
     return buffer;
 }
CreateTerrain() [1/2]
void BttController::CreateTerrain (int chunkSize, int chunkDetail, int n)
CreateTerrain() [2/2]
void BttController::CreateTerrain (int chunkSize, int chunkDetail, int n)
Initialises the BTT grid by generating vertices, creating BTT structures defining centers and generating LOD distances.
Parameters
chunkSize - The length of the grid i.e chunkSize * chunkSize is equal to number of tiles displayed
chunkDetail - The amount of vertices per row of a tile i.e chunkDetail * chunkDetail is equal to total number of vertice sper tile
n - Factor that determining tile detail i.e chunkDetail must be equal to 2^n + 1
Returns
void
Definition at line 57 of file BttController.cpp.
{
     std::vector<Btt> temp;
     int offset = 0;
     bool addOn = true;
     chunk_size = chunkSize;
     chunk_detail = chunkDetail;
     GenerateVertices(chunkSize, chunkDetail);
     std::cout << "PASSED VERTICES GENEREATION" << std::endl;
     GLuint nsize = (chunkSize - 1);
     GLuint dsize = (chunkDetail - 1);
     GLuint baseOrigin = (chunkDetail + ((dsize) * (nsize))) * dsize;
     for (int i = 0; i < chunkSize; ++i) {
         for (int j = 0; j < chunkSize; ++j) {
             Btt temp_btt_sw = Btt();
             Btt temp_btt_ne = Btt();
             GLuint origin = baseOrigin + (j * dsize) + (i * baseOrigin);
             glm::vec3 vector_temp_sw;
             glm::vec3 vector_temp_ne;
             // temp_btt.Insert(chunkDetail, flip);
             vector_temp_sw = glm::vec3(origin, (baseOrigin * i) + (j * dsize),
                                        origin + dsize);
             temp_btt_sw.Insert(vector_temp_sw, chunkDetail, false);
             temp.push_back(temp_btt_sw);
             vector_temp_ne =
                 glm::vec3((baseOrigin * i) + (j * dsize) + dsize,
                           origin + dsize, (baseOrigin * i) + (j * dsize));
             temp_btt_ne.Insert(vector_temp_ne, chunkDetail, true);
             temp.push_back(temp_btt_ne);
             // along the z-axis
             bttCenters.push_back(
                 glm::vec2(((chunkDetail - 1) * i) + ((chunkDetail - 1) / 2),
                           ((chunkDetail - 1) * j) + ((chunkDetail - 1) / 2)));
         }
         // adds to the y-axis
         bttMap.push_back(temp);
         temp.clear();
     }
     std::cout << "\n\nPASSED INDICES GENEREATION\n\n" << std::endl;
     for (int k = 0; k < (n * 2 + 1); ++k) {
         distances.push_back(chunkDetail * 2.5 * (k + 1));
         std::cout << "Distance " << k << ": " << distances.at(k) << std::endl;
     }
 }
References Btt::Btt(), and GenerateVertices().
findLOD() [1/2]
const GLuint BttController::findLOD (glm::vec3 pos, glm::vec2 center) private
findLOD() [2/2]
const GLuint BttController::findLOD (glm::vec3 pos, glm::vec2 center) private
based off player position, determines a BTT's level of detail
Parameters
pos - The players position in world coordinates
center - The center of a tile in world coordinates
Returns
the level of detail calculated
Definition at line 167 of file BttController.cpp.
{
     // GLfloat dist =
     //     glm::distance(center, glm::vec2(pos.x + height_map_size, pos.z));
     GLfloat dist = abs((pos.x + height_map_size) - center.x);
     // GLfloat dist =
     //    glm::distance(center, glm::vec2(pos.x + height_map_size, pos.z));
     //  std::cout << dist << std::endl;
     //    std::cout << " Center x: " << center.x << " z: " << center.y
     //              << "    Pos x: " << pos.x << " z: " << pos.z << std::endl;
     for (int i = 0; i < distances.size(); ++i) {
         if (dist < distances.at(i)) {
             return (distances.size() - i);
         }
     }
     return 1;
 }
GenerateVertices() [1/2]
void BttController::GenerateVertices (int chunkSize, int chunkDetail) private
Referenced by CreateTerrain().
GenerateVertices() [2/2]
void BttController::GenerateVertices (int chunkSize, int chunkDetail) private
Generate all vertices for terrain.
Parameters
chunkSize - Determines the gridsize of BTTs
chunkDetail - Determines the no of vertices per BTT
Returns
void
Definition at line 255 of file BttController.cpp.
{
     int length = (chunkSize * chunkDetail) - (chunkSize - 1);
     if (!heightmap_) {
         std::cout << "No heightmap detected!" << std::endl;
     }
     try {
         for (int i = 0; i < length; ++i) {
             for (int j = 0; j < length; ++j) {
                 // vertices
                 vertices.push_back((GLfloat)i);
                 vertices.push_back((GLfloat)heightmap_[(j * length) + i]);
                 vertices.push_back((GLfloat)j);
                 // Texture coordinates
                 vertices.push_back(i / static_cast<GLfloat>(length));
                 vertices.push_back(j / static_cast<GLfloat>(length));
                 glm::vec3 normal = calculate_terrain_normal(i, j);
                 // Normals
                 vertices.push_back(-normal.x);
                 vertices.push_back(-normal.y);
                 vertices.push_back(-normal.z);
             }
         }
     } catch (std::bad_alloc& exception) {
         std::cerr << "bad_alloc detected: " << exception.what();
     }
 }
References Terrain::heightmap_.
getAllIndices() [1/2]
void BttController::getAllIndices (glm::vec3 pos)
getAllIndices() [2/2]
void BttController::getAllIndices (glm::vec3 pos)
Calculates the meshes new indices for all BTTs and stores them for later use.
Parameters
pos - The players position in world coordinates
Returns
void
Definition at line 186 of file BttController.cpp.
{
     std::vector<glm::vec3> stored;
     current_total_indices = 0;
     indices.clear();
     // TestThings();
     // float total_time = glfwGetTime();
     // float time_in_lod = 0, tempTime;
     // float time_in_get_indices = 0;
     // float constructor_time = 0, constructor_temp_time;
     GLuint lod;
     int add;
     for (int i = 0; i < chunk_size; ++i) {
         // std::cout << "Break!" << std::endl;
         for (int j = 0; j < chunk_size * 2; ++j) {
             // constructor_temp_time = glfwGetTime();
             // constructor_time += glfwGetTime() - constructor_temp_time;
             if (chunk_size != 1)
                 add = int(j / chunk_size);
             else
                 add = 0;
             // std::cout << "ADD: " << add << std::endl;
             // tempTime = glfwGetTime();
             lod = findLOD(pos, bttCenters.at((i * chunk_size) + add));
             // time_in_lod += glfwGetTime() - tempTime;
             // tempTime = glfwGetTime();
             //    0.01 seconds --> 0.007
             stored = bttMap.at(i).at(j).getIndices(lod);
             // time_in_get_indices += glfwGetTime() - tempTime;
             // 0.005 seconds
             for (int k = 0; k < stored.size(); ++k) {
                 indices.emplace_back(stored.at(k).x);
                 indices.emplace_back(stored.at(k).y);
                 indices.emplace_back(stored.at(k).z);
             }
         }
     }
     // std::cout << "total time: " << glfwGetTime() - total_time <<
     // std::endl; std::cout << "lod time: " << time_in_lod << std::endl;
     // std::cout << "get indicies time: " << time_in_get_indices << std::endl;
     // std::endl; std::cout << "constructor time: " << constructor_time <<
     // std::endl;
     current_total_indices += indices.size();
     // std::cout << "SIZE: " << indices.size() << std::endl;
 }
getCameraPosition() [1/2]
void BttController::getCameraPosition (const glm::vec3 & pos)
getCameraPosition() [2/2]
void BttController::getCameraPosition (const glm::vec3 & pos)
Stores the psoition of the camera within the BttController for later use.
Parameters
pos - The position of the camera
Definition at line 44 of file BttController.cpp.
 { cam = pos; }
getCenters() [1/2]
const std::vector<glm::vec2>& BttController::getCenters ()
getCenters() [2/2]
const std::vector< glm::vec2 > & BttController::getCenters () private
Gets the array of BTT tile centers.
Returns
a list of vector2
Definition at line 184 of file BttController.cpp.
 { return bttCenters; }
load_detailmap() [1/2]
bool BttController::load_detailmap (const char * file_name)
Reads an image file as a detail map.
Parameters
file_name
Returns
true
false
load_detailmap() [2/2]
bool BttController::load_detailmap (const char * file_name)
Reads an image file as a detail map.
Parameters
file_name
Returns
true
false
Definition at line 294 of file BttController.cpp.
{
     detailmap = std::make_shared<Texture>(file_name);
     detailmap->set_texture_unit(GL_TEXTURE3);
     return detailmap->LoadTexture();
 }
load_mesh() [1/2]
bool BttController::load_mesh () override virtual
Reads the heightmap and loads the mesh.
Returns
true
false
Implements Terrain.
load_mesh() [2/2]
bool BttController::load_mesh () override virtual
Reads the heightmap and loads the mesh.
Returns
true
false
Implements Terrain.
Definition at line 46 of file BttController.cpp.
{
     if (!heightmap_) {
         std::cout << "Heightmap not loaded!" << std::endl;
         return false;
     }
     Update(cam);
     return true;
 }
References Terrain::heightmap_.
load_texture() [1/2]
bool BttController::load_texture (const char * file_name)
Reads the texture image file and loads the texture.
Parameters
file_name
Returns
true
false
load_texture() [2/2]
bool BttController::load_texture (const char * file_name)
Reads the texture image file and loads the texture.
Parameters
file_name
Returns
true
false
Definition at line 289 of file BttController.cpp.
{
     texture_ = std::make_shared<Texture>(file_name);
     return texture_->LoadTextureA();
 }
render() [1/2]
void BttController::render (std::shared_ptr< Shader > shader) override virtual
Renders the terrain.
Parameters
shader
Implements Terrain.
render() [2/2]
void BttController::render (std::shared_ptr< Shader > shader) override virtual
Renders the terrain.
Parameters
shader
Implements Terrain.
Definition at line 26 of file BttController.cpp.
{
     if (!mesh_) return;
     glm::mat4 model = glm::mat4(1.0f);
     model = glm::translate(model, get_origin());
     model = glm::scale(model, scale_);
     glUniformMatrix4fv(shader->GetModelLocation(), 1, GL_FALSE,
                        glm::value_ptr(model));
     glUniform1i(shader->GetUsingTexture(), false);
     glUniform1i(shader->get_using_detailmap(), true);
     texture_->UseTexture();
     detailmap->UseTexture();
     mesh_->RenderMesh();
 }
set_height_map_size() [1/2]
void BttController::set_height_map_size (float size)
set_height_map_size() [2/2]
void BttController::set_height_map_size (float size)
Sets the size of the heightmap.
Parameters
size - Sets length and width of heightmap
Returns
void
Definition at line 287 of file BttController.cpp.
 { height_map_size = size; }
References height_map_size.
set_texture_id()
void BttController::set_texture_id (GLuint id) inline
Definition at line 46 of file BttController.hpp.
{
         texture_ = std::make_shared<Texture>();
         texture_->set_texture_id(id);
     }
TestThings()
void BttController::TestThings ()
Definition at line 131 of file BttController.cpp.
{
     bool canThing = false;
     for (int i = 0; i < chunk_size; ++i) {
         int iu = i + 1;  // sw triangle, down side check
         int id = i - 1;  // ne triangle, up side check
         for (int j = 0; j < chunk_size; ++j) {
             int jl = (j * 2) - 1;  // sw triangle, left side check
             int jr = (j * 2) + 1;  // ne triangle, right side check
             if (bttMap.at(i).at(j).getLOD() % 2 == 0)
                 canThing = true;
             else
                 canThing = false;
             // out of bounds checking
             // sw triangle
             if (jl >= 0) {
                 if (bttMap.at(i).at(jl).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing)  // check left
                 {
                     bttMap.at(i).at(j * 2).addLeft();
                 }
             }
             if (id >= 0) {
                 if (bttMap.at(id).at(j).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing) {  // check down
                     bttMap.at(i).at(j * 2).addRight();
                 }
             }
             // ne triangle
             if (jr >= chunk_size * 2) {
                 if (bttMap.at(i).at(jr).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing) {  // check right
                     bttMap.at(i).at(j * 2 - 1).addLeft();
                 }
             }
             if (iu >= chunk_size * 2) {
                 if (bttMap.at(iu).at(j).getLOD() ==
                         bttMap.at(i).at(j).getLOD() + 1 &&
                     canThing) {  // check up
                     bttMap.at(i).at(j * 2 - 1).addRight();
                 }
             }
             // std::cout << "Tile " << i << j << "| left: " << i << jl
             //         << " right: " << i << jr << " up: " << iu << j * 2
             //       << " down: " << id << j * 2 + 1 << std::endl;
         }
     }
 }
Update() [1/2]
void BttController::Update (glm::vec3 player)
Update() [2/2]
void BttController::Update (glm::vec3 player)
Updates the mesh when the player moves position.
Parameters
player - The players position in world coordinates
Returns
void
Definition at line 240 of file BttController.cpp.
{
     if (firstRun) {
         position.x += 0.1;
         firstRun = false;
     }
     if (position.x != prev_pos.x || position.z != prev_pos.z) {
         mesh_ = std::make_shared<Mesh>();
         getAllIndices(position);
         mesh_->CreateMesh(vertices.data(), indices.data(), vertices.size(),
                           indices.size());
     }
     prev_pos = position;
 }
References firstRun.
Member Data Documentation
b
bool BttController::b = true private
Definition at line 88 of file BttController.hpp.
bttCenters
std::vector< glm::vec2 > BttController::bttCenters private
All binary triangle trees.
Definition at line 145 of file BttController.hpp.
bttMap
std::vector< std::vector< Btt > > BttController::bttMap private
Definition at line 144 of file BttController.hpp.
cam
glm::vec3 BttController::cam private
All the currently used indices for terrain.
Definition at line 148 of file BttController.hpp.
chunk_detail
GLuint BttController::chunk_detail private
The length/width of BTT grid.
Definition at line 159 of file BttController.hpp.
chunk_size
GLuint BttController::chunk_size private
Number of current total indices being used.
Definition at line 158 of file BttController.hpp.
current_total_indices
GLuint BttController::current_total_indices private
Saves the players previous position.
Definition at line 157 of file BttController.hpp.
detailmap
std::shared_ptr< Texture > BttController::detailmap = nullptr private
Storage for texture.
The detailmap.
Definition at line 164 of file BttController.hpp.
distances
std::vector< GLfloat > BttController::distances private
Stored position for camera.
Definition at line 150 of file BttController.hpp.
firstRun
bool BttController::firstRun private
Container for mesh data;.
Definition at line 154 of file BttController.hpp.
Referenced by BttController(), and Update().
height_map_size
int BttController::height_map_size = 0 private
The length/width of a given tile (vertice number)
Definition at line 161 of file BttController.hpp.
Referenced by set_height_map_size().
indices
std::vector< GLuint > BttController::indices private
All the vertices for the terrain.
Definition at line 147 of file BttController.hpp.
mesh_
std::shared_ptr< Mesh > BttController::mesh_ = nullptr private
Distances from player for changes in LOD for tile.
Definition at line 153 of file BttController.hpp.
prev_pos
glm::vec3 BttController::prev_pos private
Determines if first time of mesh generation.
Definition at line 156 of file BttController.hpp.
texture_
std::shared_ptr< Texture > BttController::texture_ = nullptr private
the length/width of height map
The texture.
Definition at line 163 of file BttController.hpp.
vertices
std::vector< GLfloat > BttController::vertices private
All centers for BTT tiles (hypotenuse-adjacent BTTs)
Definition at line 146 of file BttController.hpp.
The documentation for this class was generated from the following files:
src/Controller/Terrain/BttController.hpp
src/Controller/Terrain/BttController.cpp