ICT397 Assignment 2: Btt Class Reference
Btt Class Reference
#include <BTT.hpp>
Public Member Functions
Btt ()
Default constructor.
Btt (const Btt &other)
Default constructor.
Btt & operator= (const Btt &treeCopy)
Copy constructor for BTT.
~Btt ()
equals operator overloader for BTT
void Insert (const glm::vec3 &temp, unsigned int size, bool isFlip)
Deconstructor for BTT.
const std::vector< glm::vec3 > & getIndices (const int level)
Returns all indices needed for a given level of detail.
const GLuint getIndexSize ()
Gets the size of current indices.
unsigned int getLOD ()
Gets the current level of detail.
void destroyTree ()
Destroys a node of tree.
const std::vector< glm::vec3 > & getCurrentIndices ()
Gets all the current indices stored in BTT.
void addLeft ()
Adds lower levels of detail triangles that touch left edges to current indices, used for removing t-junctions.
void addRight ()
Adds lower levels of detail triangles that touch left edges to current indices, used for removing t-junctions.
Private Member Functions
Node * createNode (const unsigned int &lod, const glm::vec3 &data)
Creates a node to add into BTT.
void copyTree (Node *&nodeCopy, Node *node)
Searches through tree and creates copies of nodes.
void Insert (Node *node)
Inserts a node into BTT.
const void getIndices (Node *node, int level)
Gets the indices for a given node and adds to current indices.
void destroyTree (Node *node)
Deletes a given node of a tree.
GLuint findMid (unsigned int p1, unsigned int p2)
Finds the midpoint between two indices.
void addToLeft (Node *node, const int &i)
Checks if a triangle should be added to left side triangles.
void addToRight (Node *node, const int &i)
Checks if a triangle should be added to left side triangles.
Private Attributes
Node * bttNode
Btt * leftTriangle
Holds indices for all triangles.
Btt * rightTriangle
BTT touching left side of main triangle (origin and left)
std::vector< glm::vec3 > leftSideTriangles
BTT touching right side of main triangle (origin and right)
std::vector< glm::vec3 > rightSideTriangles
Stores triangles touching left side (only stores for certain LOD)
std::vector< glm::vec3 > currentIndices
Stores triangles touching right side (only stores for certain LOD)
std::vector< int > bigLeftTriangles
Current indices being used.
std::vector< int > bigRightTriangles
Holds indexs for left side triangles inside current indices.
unsigned int currentLod
Holds indexs for right side triangles inside current indices.
unsigned int depth
The current level of detail.
bool isFlipped
Stores total depth.
Detailed Description
Definition at line 22 of file BTT.hpp.
Constructor & Destructor Documentation
Btt() [1/2]
Btt::Btt ()
Default constructor.
Definition at line 3 of file BTT.cpp.
 {
     bttNode = nullptr;
     leftTriangle = nullptr;
     rightTriangle = nullptr;
     isFlipped = false;
     depth = 0;
     currentLod = 0;
 }
References bttNode, currentLod, depth, isFlipped, leftTriangle, and rightTriangle.
Referenced by BttController::CreateTerrain().
Btt() [2/2]
Btt::Btt (const Btt & other)
Default constructor.
Definition at line 31 of file BTT.cpp.
{
     this->depth = treeCopy.depth;
     this->currentLod = treeCopy.currentLod;
     this->isFlipped = treeCopy.isFlipped;
     this->leftSideTriangles = treeCopy.leftSideTriangles;
     this->rightSideTriangles = treeCopy.rightSideTriangles;
     if (treeCopy.bttNode == nullptr)
         bttNode = nullptr;
     else {
         copyTree(bttNode, treeCopy.bttNode);
     }
 }
References bttNode, copyTree(), currentLod, depth, and isFlipped.
~Btt()
Btt::~Btt ()
equals operator overloader for BTT
Definition at line 13 of file BTT.cpp.
 { destroyTree(); }
References destroyTree().
Member Function Documentation
addLeft()
void Btt::addLeft ()
Adds lower levels of detail triangles that touch left edges to current indices, used for removing t-junctions.
Returns
void
Definition at line 139 of file BTT.cpp.
                   {
     for (int i = 0; i < bigLeftTriangles.size(); ++i) {
         currentIndices.erase(currentIndices.begin() + bigLeftTriangles.at(i));
     }
     for (int j = 0; j < leftSideTriangles.size(); ++j) {
         currentIndices.push_back(leftSideTriangles.at(j));
     }
 }
addRight()
void Btt::addRight ()
Adds lower levels of detail triangles that touch left edges to current indices, used for removing t-junctions.
Returns
void
Definition at line 148 of file BTT.cpp.
                    {
     for (int i = 0; i < bigRightTriangles.size(); ++i) {
         currentIndices.erase(currentIndices.begin() + bigRightTriangles.at(i));
     }
     for (int j = 0; j < rightSideTriangles.size(); ++j) {
         currentIndices.push_back(rightSideTriangles.at(j));
     }
 }
addToLeft()
void Btt::addToLeft (Node * node, const int & i) private
Checks if a triangle should be added to left side triangles.
Parameters
node - current node being used
i - the index of node in current indices
Returns
void
Definition at line 175 of file BTT.cpp.
{
     GLuint diff;
     if (!isFlipped) {
         diff = (bttNode->point.x - bttNode->point.y) / (depth - 1);
         if ((int)node->point.y % (int)diff == 0 &&
             (int)node->point.z % (int)diff == 0) {
             leftSideTriangles.push_back(node->point);
             bigLeftTriangles.push_back(i);
         }
     } else {
         diff = (bttNode->point.y - bttNode->point.x) / (depth - 1);
         if (((int)(node->point.y - (depth - 1)) % (int)diff == 0) &&
             ((int)(node->point.z - (depth - 1)) % (int)diff == 0)) {
             leftSideTriangles.push_back(node->point);
             bigLeftTriangles.push_back(i);
         }
     }
 }
References isFlipped.
addToRight()
void Btt::addToRight (Node * node, const int & i) private
Checks if a triangle should be added to left side triangles.
Parameters
node - current node being used
i - the index of node in current indices
Returns
void
Definition at line 198 of file BTT.cpp.
{
     int min;
     int max;
     if (!isFlipped) {
         min = int(bttNode->point.z - (depth - 1));
         max = int(bttNode->point.z);
     } else {
         min = int(bttNode->point.z);
         max = int(bttNode->point.z + (depth - 1));
     }
     if ((int(node->point.y) >= min && int(node->point.y) < max) &&
         (int(node->point.z) >= min && int(node->point.z) < max)) {
         rightSideTriangles.push_back(node->point);
         bigRightTriangles.push_back(i);
     }
 }
References isFlipped.
copyTree()
void Btt::copyTree (Node *& nodeCopy, Node * node) private
Searches through tree and creates copies of nodes.
Parameters
nodeCopy - pointer address of original node
node - pointer to new tree/tree nodes being created
Returns
void
Definition at line 57 of file BTT.cpp.
{
     if (node == nullptr) {
         nodeCopy = nullptr;
     } else {
         nodeCopy = createNode(node->lod - 1, node->point);
         copyTree(nodeCopy->left, node->left);
         copyTree(nodeCopy->right, node->right);
     }
 }
References copyTree(), Node::left, and Node::right.
Referenced by Btt(), copyTree(), and operator=().
createNode()
Node * Btt::createNode (const unsigned int & lod, const glm::vec3 & data) private
Creates a node to add into BTT.
Parameters
lod - level of detail
data - indices for a given triangle
Returns
pointer to created node
Definition at line 102 of file BTT.cpp.
{
     Node* temp = new Node();
     temp->point = data;
     temp->lod = lod + 1;
     return temp;
 }
References Node::lod.
destroyTree() [1/2]
void Btt::destroyTree ()
Destroys a node of tree.
Returns
void
Definition at line 15 of file BTT.cpp.
                       {
     destroyTree(bttNode);
     leftSideTriangles.clear();
     rightSideTriangles.clear();
     leftTriangle = nullptr;
     rightTriangle = nullptr;
 }
References bttNode, destroyTree(), leftTriangle, and rightTriangle.
Referenced by ~Btt().
destroyTree() [2/2]
void Btt::destroyTree (Node * node) private
Deletes a given node of a tree.
Parameters
node - current node being used
Returns
void
Definition at line 23 of file BTT.cpp.
{
     if (node != nullptr) {
         destroyTree(node->left);
         destroyTree(node->right);
         delete node;
     }
 }
References destroyTree(), Node::left, and Node::right.
Referenced by destroyTree(), and operator=().
findMid()
GLuint Btt::findMid (unsigned int p1, unsigned int p2) private
Finds the midpoint between two indices.
Parameters
p1 - left most indice
p2 - right most indice
Returns
void
Definition at line 100 of file BTT.cpp.
 { return (p1 + p2) / 2; }
getCurrentIndices()
const std::vector< glm::vec3 > & Btt::getCurrentIndices ()
Gets all the current indices stored in BTT.
Returns
all of the currently used indices
Definition at line 113 of file BTT.cpp.
{
     return currentIndices;
 }
getIndexSize()
const GLuint Btt::getIndexSize ()
Gets the size of current indices.
Returns
size of current indices
Definition at line 111 of file BTT.cpp.
 { return currentIndices.size(); }
getIndices() [1/2]
const std::vector< glm::vec3 > & Btt::getIndices (const int level)
Returns all indices needed for a given level of detail.
Parameters
level - Level of detail needed for BTT
Returns
vector of indices for triangles
Definition at line 116 of file BTT.cpp.
{
     currentIndices.clear();
     leftSideTriangles.clear();
     rightSideTriangles.clear();
     currentLod = level;
     if (level > depth) {
         std::cout << "ERROR: level exceeds depth" << std::endl;
         return currentIndices;
     } else if (level <= 0) {
         std::cout << "ERROR: level is zero or less" << std::endl;
         return currentIndices;
     }
     if (bttNode->lod == level) {
         currentIndices.push_back(bttNode->point);
     } else {
         getIndices(bttNode, level);
     }
     return currentIndices;
 }
References bttNode, currentLod, depth, getIndices(), and Node::lod.
getIndices() [2/2]
const void Btt::getIndices (Node * node, int level) private
Gets the indices for a given node and adds to current indices.
Parameters
node - current node being used
level - level of detail being used for extraction
Returns
void
Definition at line 157 of file BTT.cpp.
{
     if ((node->lod + 1) < level) {
         getIndices(node->left, level);
         getIndices(node->right, level);
     } else {
         currentIndices.push_back(node->left->point);
         currentIndices.push_back(node->right->point);
         if (((int)node->lod + 1) % 2 == 0) {
             addToLeft(node->left, currentIndices.size() - 1);
             addToLeft(node->right, currentIndices.size() - 1);
             addToRight(node->left, currentIndices.size());
             addToRight(node->right, currentIndices.size());
         }
     }
 }
References getIndices(), Node::left, Node::lod, and Node::right.
Referenced by getIndices().
getLOD()
unsigned int Btt::getLOD ()
Gets the current level of detail.
Returns
returns current level of detail
Definition at line 84 of file BTT.cpp.
 { return currentLod; }
References currentLod.
Insert() [1/2]
void Btt::Insert (const glm::vec3 & temp, unsigned int size, bool isFlip)
Deconstructor for BTT.
Creates a BTT based of given indices, detail size and whether BTT is North-East type or South-West type (i.e is it flipped)
Parameters
temp - starting indices, indices of largest triangle (level of detail 1)
size - length/width of a tile (in vertices)
isFlip - indicates whether given BTT is North-East or South-West triangle type triangle type or South-West triangle type
Returns
void
Definition at line 67 of file BTT.cpp.
{
     if (size < 1) return;
     if (bttNode != nullptr) return;
     isFlipped = isFlip;
     bttNode = new Node();
     // Order: Origin (point opposite hypotenus), Left, Right
     bttNode->point = glm::vec3(temp.x, temp.y, temp.z);
     depth = size;
     bttNode->lod = 1;
     if (bttNode->lod < depth) {
         Insert(bttNode);
     }
 }
References bttNode, depth, Insert(), isFlipped, and Node::lod.
Insert() [2/2]
void Btt::Insert (Node * node) private
Inserts a node into BTT.
Parameters
node - current node being used
Returns
void
Definition at line 86 of file BTT.cpp.
{
     // find midpoint of hypotenus
     GLuint mid = findMid(node->point.y, node->point.z);
     node->left =
         createNode(node->lod, glm::vec3(mid, node->point.x, node->point.y));
     node->right =
         createNode(node->lod, glm::vec3(mid, node->point.z, node->point.x));
     if (node->lod + 1 < depth) {
         Insert(node->left);
         Insert(node->right);
     }
 }
References depth, Insert(), Node::left, Node::lod, and Node::right.
Referenced by Insert().
operator=()
Btt & Btt::operator= (const Btt & treeCopy)
Copy constructor for BTT.
Definition at line 45 of file BTT.cpp.
{
     if (this != &treeCopy) {
         if (bttNode != nullptr) destroyTree(bttNode);
         if (treeCopy.bttNode == nullptr)
             bttNode = nullptr;
         else
             copyTree(bttNode, treeCopy.bttNode);
     }
     return *this;
 }
References bttNode, copyTree(), and destroyTree().
Member Data Documentation
bigLeftTriangles
std::vector<int> Btt::bigLeftTriangles private
Current indices being used.
Definition at line 187 of file BTT.hpp.
bigRightTriangles
std::vector<int> Btt::bigRightTriangles private
Holds indexs for left side triangles inside current indices.
Definition at line 188 of file BTT.hpp.
bttNode
Node* Btt::bttNode private
Definition at line 178 of file BTT.hpp.
Referenced by Btt(), destroyTree(), getIndices(), Insert(), and operator=().
currentIndices
std::vector<glm::vec3> Btt::currentIndices private
Stores triangles touching right side (only stores for certain LOD)
Definition at line 186 of file BTT.hpp.
currentLod
unsigned int Btt::currentLod private
Holds indexs for right side triangles inside current indices.
Definition at line 190 of file BTT.hpp.
Referenced by Btt(), getIndices(), and getLOD().
depth
unsigned int Btt::depth private
The current level of detail.
Definition at line 191 of file BTT.hpp.
Referenced by Btt(), getIndices(), and Insert().
isFlipped
bool Btt::isFlipped private
Stores total depth.
Definition at line 192 of file BTT.hpp.
Referenced by addToLeft(), addToRight(), Btt(), and Insert().
leftSideTriangles
std::vector<glm::vec3> Btt::leftSideTriangles private
BTT touching right side of main triangle (origin and right)
Definition at line 184 of file BTT.hpp.
leftTriangle
Btt* Btt::leftTriangle private
Holds indices for all triangles.
Definition at line 180 of file BTT.hpp.
Referenced by Btt(), and destroyTree().
rightSideTriangles
std::vector<glm::vec3> Btt::rightSideTriangles private
Stores triangles touching left side (only stores for certain LOD)
Definition at line 185 of file BTT.hpp.
rightTriangle
Btt* Btt::rightTriangle private
BTT touching left side of main triangle (origin and left)
Definition at line 181 of file BTT.hpp.
Referenced by Btt(), and destroyTree().
The documentation for this class was generated from the following files:
src/Controller/Terrain/BTT.hpp
src/Controller/Terrain/BTT.cpp