My Project: Player Class Reference
Player Class Reference
The player game object.
#include <Player.hpp>
Public Member Functions
void init () override
Initialize the game object.
void update (float delta_time) override
Updates the game object.
void fixed_update (float delta_time) override
Updates the body object with fixed delta time.
void add_draw_call () override
Adds the draw call to the renderer.
void draw (std::shared_ptr< Shader > shader) override
The draw call function.
void save_object () override
Save the object to a lua script.
void set_move_speed (float move_speed)
Set the move speed.
void set_height (float height)
Set the height.
void set_collider_radius (float radius)
Set the collider radius.
void set_lua_script (std::string script)
Sets the script for the player.
Public Member Functions inherited from BodyRigid
void createBR (glm::vec3 pos, glm::vec3 rotation, float angle)
Creates rigid body.
void set_position (glm::vec3 pos)
Sets the position of the rigid body.
void setType (int type)
Set type of rigid body.
void enableGravity (bool val)
Set if you want gravity.
void setLinearVelocityDamping (float val)
Movement dampining.
void setAngularVelocityDamping (float val)
Rotation dampining.
void setIfBodyCanSleep (bool val)
Sets if the body can go to sleep.
void addForce (glm::vec3 force)
Adds force to the object.
void setLinearVelocity (glm::vec3 velocity)
set force to the object
void addTorque (glm::vec3 torque)
Adds torque to the object.
void setAngularVelocity (glm::vec3 velocity)
set torque to the object
glm::vec3 getPosition ()
Gets the position vector.
glm::vec3 getRotation ()
Gets the axis of rotation vector of the rigid body.
float getAngle ()
Gets the angle around the axis of rotation of the rigid body.
glm::vec3 getLinearVelocity ()
Gets the linear velocity of the rigid body.
glm::vec3 getAngularVelocity ()
Gets the angular velocity of the rigid body.
void addBoxCollider (glm::vec3 pos, glm::vec3 halfSize, float bounciness, float friction)
Adds a box ciller to a rigid body.
void addSphereCollider (glm::vec3 pos, float radius, float bounciness, float friction)
Adds a sphere collider to a rigid body.
void addCapsuleCollider (glm::vec3 pos, float radius, float height, float bounciness, float friction)
Adds a capsule collider to a rigid body.
void addHeightFieldShape (float bounciness, float friction)=delete
Creates a height field shape collision box.
~BodyRigid ()
Destructor.
Public Member Functions inherited from Body
void setCreator (bool val)
Sets if the object is a creator (true) or destructor (false). A creator should be one of the fist game objects while a destoryer should be one of the last.
void physicsDebugger ()
Adds all possible physic debugger options.
void physicsWorldDestroyer ()
Destoryes physic world.
~Body ()
Destructor.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
std::string lua_script_
Player script.
float move_speed_ = 0.0f
The move speed.
float height_ = 0.0f
The height.
float collider_radius_ = 0.0f
The collider radius.
SpotLight flashlight_
The flashlight.
Additional Inherited Members
Public Attributes inherited from GameObject
struct {
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01
};
Protected Attributes inherited from BodyRigid
BodyRigidPhysics rb
Facaded react rigid body
int m_numOfColliders = 0
The number of colliders in the rb
std::vector< colliderData_sphere > m_sphere
List of sphere colliders. Used for storing data to file
std::vector< colliderData_capsule > m_capsule
List of capsule colliders. Used for storing data to file
std::vector< colliderData_box > m_box
List of capsule colliders. Used for storing data to file
Detailed Description
The player game object.
Definition at line 10 of file Player.hpp.
Member Function Documentation
add_draw_call()
void Player::add_draw_call () override virtual
Adds the draw call to the renderer.
Reimplemented from BodyRigid.
Definition at line 44 of file Player.cpp.
{
     auto& renderer = ReflexEngine::get_instance().renderer_;
     renderer.add_spot_light(flashlight_);
 }
draw()
void Player::draw (std::shared_ptr< Shader > shader) inline override virtual
The draw call function.
Parameters
shader
Reimplemented from BodyRigid.
Definition at line 41 of file Player.hpp.
 {}
fixed_update()
void Player::fixed_update (float delta_time) override virtual
Updates the body object with fixed delta time.
Parameters
delta_time
Reimplemented from BodyRigid.
Definition at line 32 of file Player.cpp.
{
     auto& camera = ReflexEngine::get_instance().camera_;
     glm::vec3 direction = camera.get_move_direction();
     glm::vec3 move = direction * move_speed_;
     rb.setLinearVelocity(move);
     position = rb.getPosition();
     camera.set_position(position);
 }
init()
void Player::init () override virtual
Initialize the game object.
Reimplemented from BodyRigid.
Definition at line 23 of file Player.cpp.
                   {
     position.y = 10;
     flashlight_ =
         SpotLight(1024, 1024, 0.01f, 100.0f, glm::vec3(1.0f, 1.0f, 1.0f), 0.0f,
                   2.0f, glm::vec3(0.0f, 0.0f, 0.0f),
                   glm::vec3(0.0f, -1.0f, 0.0f), 1.0f, 0.0f, 0.0f, 20.0f);
 }
Referenced by GameAssetFactory::load_player().
save_object()
void Player::save_object () override virtual
Save the object to a lua script.
Reimplemented from BodyRigid.
Definition at line 52 of file Player.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "Player");
     ObjectSaving::addComma();
     ObjectSaving::addValue("move_speed", move_speed_, true);
     ObjectSaving::closeStruct();
     ObjectSaving::addValue("script", lua_script_, true);
     ObjectSaving::createStruct("collider1");
     ObjectSaving::addValue("colliderType", "Capsule", false);
     ObjectSaving::addValue("xPos", rb.getLocalColliderPos(0).x, false);
     ObjectSaving::addValue("yPos", rb.getLocalColliderPos(0).y, false);
     ObjectSaving::addValue("zPos", rb.getLocalColliderPos(0).z, false);
     ObjectSaving::addValue("height", height_, false);
     ObjectSaving::addValue("radius", collider_radius_, false);
     ObjectSaving::addValue("bounciness", rb.getBounciness(0), false);
     ObjectSaving::addValue("friction", rb.getFriction(0), true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::addComma(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), and ObjectSaving::openFile().
set_collider_radius()
void Player::set_collider_radius (float radius)
Set the collider radius.
Parameters
radius
Definition at line 76 of file Player.cpp.
 { collider_radius_ = radius; }
References collider_radius_.
Referenced by GameAssetFactory::load_player().
set_height()
void Player::set_height (float height)
Set the height.
Parameters
height
Definition at line 74 of file Player.cpp.
 { height_ = height; }
References height_.
Referenced by GameAssetFactory::load_player().
set_lua_script()
void Player::set_lua_script (std::string script)
Sets the script for the player.
Parameters
script - The lua script
Definition at line 50 of file Player.cpp.
 { lua_script_ = script; }
set_move_speed()
void Player::set_move_speed (float move_speed)
Set the move speed.
Parameters
move_speed
Definition at line 72 of file Player.cpp.
 { move_speed_ = speed; }
References move_speed_.
update()
void Player::update (float delta_time) override virtual
Updates the game object.
Parameters
delta_time
Reimplemented from BodyRigid.
Definition at line 5 of file Player.cpp.
{
     sol::state& lua = LuaManager::get_instance().get_state();
     lua.script_file(lua_script_);
     position = rb.getPosition();
     position.y = GenericFunctions::getHeight(position.x, position.z) + height_;
     rb.set_position(position);
     const auto& camera = ReflexEngine::get_instance().camera_;
     glm::vec3 lower_light = camera.get_position();
     lower_light.y -= 0.3f;
     glm::vec3 cam_direction = camera.get_direction();
     flashlight_.SetFlash(lower_light, cam_direction);
 }
Member Data Documentation
collider_radius_
float Player::collider_radius_ = 0.0f private
The collider radius.
Definition at line 84 of file Player.hpp.
Referenced by set_collider_radius().
flashlight_
SpotLight Player::flashlight_ private
The flashlight.
Definition at line 87 of file Player.hpp.
height_
float Player::height_ = 0.0f private
The height.
Definition at line 82 of file Player.hpp.
Referenced by set_height().
lua_script_
std::string Player::lua_script_ private
Player script.
Definition at line 78 of file Player.hpp.
move_speed_
float Player::move_speed_ = 0.0f private
The move speed.
Definition at line 80 of file Player.hpp.
Referenced by set_move_speed().
The documentation for this class was generated from the following files:
src/Model/GameObject/Player.hpp
src/Model/GameObject/Player.cpp