ICT397 Assignment 2: Mesh Class Reference
Mesh Class Reference
A mesh class representing vertices, texture coordinates, normals, and its indices.
#include <Mesh.hpp>
Public Member Functions
Mesh ()
Construct a new Mesh object.
void CreateMesh (const GLfloat *vertices, const GLuint *indices, GLuint noOfVerts, GLuint noOfIndices)
Takes in an array of vertices, texture coordinates, normals, and indices and passing it to the GPU using VBO, VAO, and IBO.
void CreateColorMesh (const GLfloat *vertices, const GLuint *indices, GLuint noOfVerts, GLuint noOfIndices)
Takes in an array of vertices, texture coordinates, normals, and indices and passing it to the GPU using VBO, VAO, and IBO.
void RenderMesh ()
Binds the VAO and IBO and renders the mesh.
void ClearMesh ()
Clears the mesh.
bool has_color () const
Returns a boolean whether the mesh is colored.
~Mesh ()
Destroy the Mesh object.
Private Attributes
GLuint VAO
Vertex array object, specifying the layout of the mesh.
GLuint VBO
Vertex buffer object, containing the data of the mesh.
GLuint IBO
Index buffer object, containing the indices of the mesh.
GLsizei indexCount
The number of indices in the mesh.
bool has_color_ = false
Boolean to check whether it is a colored mesh.
Detailed Description
A mesh class representing vertices, texture coordinates, normals, and its indices.
Todo:
Add in color meshes.
Definition at line 11 of file Mesh.hpp.
Constructor & Destructor Documentation
Mesh()
Mesh::Mesh ()
Construct a new Mesh object.
Definition at line 5 of file Mesh.cpp.
 : VAO(0), VBO(0), IBO(0), indexCount(0) {}
Referenced by Model::LoadMesh().
~Mesh()
Mesh::~Mesh ()
Destroy the Mesh object.
Definition at line 117 of file Mesh.cpp.
 { ClearMesh(); }
References ClearMesh().
Member Function Documentation
ClearMesh()
void Mesh::ClearMesh ()
Clears the mesh.
Definition at line 96 of file Mesh.cpp.
                      {
     if (IBO != 0) {
         glDeleteBuffers(1, &IBO);
         IBO = 0;
     }
     if (VBO != 0) {
         glDeleteBuffers(1, &VBO);
         VBO = 0;
     }
     if (VAO != 0) {
         glDeleteVertexArrays(1, &VAO);
         VAO = 0;
     }
     indexCount = 0;
 }
Referenced by ~Mesh().
CreateColorMesh()
void Mesh::CreateColorMesh (const GLfloat * vertices, const GLuint * indices, GLuint noOfVerts, GLuint noOfIndices)
Takes in an array of vertices, texture coordinates, normals, and indices and passing it to the GPU using VBO, VAO, and IBO.
Parameters
vertices The vertices, texture coordinates, and normals.
indices The indices of the mesh.
noOfVerts The number of vertices.
noOfIndices The number of indices.
Definition at line 41 of file Mesh.cpp.
{
     indexCount = noOfIndices;
     glGenVertexArrays(1, &VAO);
     glBindVertexArray(VAO);
     glGenBuffers(1, &IBO);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, IBO);
     glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(indices[0]) * noOfIndices,
                  indices, GL_STATIC_DRAW);
     glGenBuffers(1, &VBO);
     glBindBuffer(GL_ARRAY_BUFFER, VBO);
     glBufferData(GL_ARRAY_BUFFER, sizeof(vertices[0]) * noOfVerts, vertices,
                  GL_STATIC_DRAW);
     // Vertices
     glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(vertices[0]) * 11,
                           (void*)0);
     glEnableVertexAttribArray(0);
     // Texture coords
     glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, sizeof(vertices[0]) * 11,
                           (void*)(sizeof(vertices[0]) * 3));
     glEnableVertexAttribArray(1);
     // Normals
     glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, sizeof(vertices[0]) * 11,
                           (void*)(sizeof(vertices[0]) * 5));
     glEnableVertexAttribArray(2);
     // Colors
     glVertexAttribPointer(3, 3, GL_FLOAT, GL_FALSE, sizeof(vertices[0]) * 11,
                           (void*)(sizeof(vertices[0]) * 8));
     glEnableVertexAttribArray(3);
     glBindBuffer(GL_ARRAY_BUFFER, 0);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
     glBindVertexArray(0);
     has_color_ = true;
 }
References has_color_.
CreateMesh()
void Mesh::CreateMesh (const GLfloat * vertices, const GLuint * indices, GLuint noOfVerts, GLuint noOfIndices)
Takes in an array of vertices, texture coordinates, normals, and indices and passing it to the GPU using VBO, VAO, and IBO.
Parameters
vertices The vertices, texture coordinates, and normals.
indices The indices of the mesh.
noOfVerts The number of vertices.
noOfIndices The number of indices.
Definition at line 7 of file Mesh.cpp.
{
     indexCount = noOfIndices;
     glGenVertexArrays(1, &VAO);
     glBindVertexArray(VAO);
     glGenBuffers(1, &IBO);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, IBO);
     glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(indices[0]) * noOfIndices,
                  indices, GL_STATIC_DRAW);
     glGenBuffers(1, &VBO);
     glBindBuffer(GL_ARRAY_BUFFER, VBO);
     glBufferData(GL_ARRAY_BUFFER, sizeof(vertices[0]) * noOfVerts, vertices,
                  GL_STATIC_DRAW);
     glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(vertices[0]) * 8, 0);
     glEnableVertexAttribArray(0);
     glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, sizeof(vertices[0]) * 8,
                           (void*)(sizeof(vertices[0]) * 3));
     glEnableVertexAttribArray(1);
     glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, sizeof(vertices[0]) * 8,
                           (void*)(sizeof(vertices[0]) * 5));
     glEnableVertexAttribArray(2);
     glBindBuffer(GL_ARRAY_BUFFER, 0);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
     glBindVertexArray(0);
 }
has_color()
bool Mesh::has_color () const
Returns a boolean whether the mesh is colored.
Returns
bool
Definition at line 115 of file Mesh.cpp.
 { return has_color_; }
References has_color_.
RenderMesh()
void Mesh::RenderMesh ()
Binds the VAO and IBO and renders the mesh.
Definition at line 86 of file Mesh.cpp.
                       {
     glBindVertexArray(VAO);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, IBO);
     glDrawElements(GL_TRIANGLES, indexCount, GL_UNSIGNED_INT, 0);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
     glBindVertexArray(0);
 }
Member Data Documentation
has_color_
bool Mesh::has_color_ = false private
Boolean to check whether it is a colored mesh.
Definition at line 76 of file Mesh.hpp.
Referenced by CreateColorMesh(), and has_color().
IBO
GLuint Mesh::IBO private
Index buffer object, containing the indices of the mesh.
Definition at line 70 of file Mesh.hpp.
indexCount
GLsizei Mesh::indexCount private
The number of indices in the mesh.
Definition at line 73 of file Mesh.hpp.
VAO
GLuint Mesh::VAO private
Vertex array object, specifying the layout of the mesh.
Definition at line 66 of file Mesh.hpp.
VBO
GLuint Mesh::VBO private
Vertex buffer object, containing the data of the mesh.
Definition at line 68 of file Mesh.hpp.
The documentation for this class was generated from the following files:
src/View/Renderer/OpenGL/Objects/Mesh.hpp
src/View/Renderer/OpenGL/Objects/Mesh.cpp