ICT397 Assignment 2: NetworkedItem Class Reference
NetworkedItem Class Reference
#include <NetworkedItem.hpp>
Public Member Functions
NetworkedItem (const std::string &model_name, const std::string &texture_name)
Construct a new Networked Item object with a model name and a texture name.
void init () override
Initializes the item with a model, a texture, and a material.
void update (double delta_time) override
Updates the Networked Item with delta time.
void fixed_update (double delta_time) override
Updates the body object with fixed delta time.
void add_draw_call () override
Adds the draw call to the renderer.
void draw (std::shared_ptr< Shader > shader) override
The draw call for the Networked Item.
void save_object () override
Saves the object to lua file.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
std::string model_name_
The model of the Networked Item.
std::string material_name_
The material of the Networked Item.
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Detailed Description
Definition at line 17 of file NetworkedItem.hpp.
Constructor & Destructor Documentation
NetworkedItem()
NetworkedItem::NetworkedItem (const std::string & model_name, const std::string & texture_name)
Construct a new Networked Item object with a model name and a texture name.
Parameters
model_name
texture_name
Definition at line 5 of file NetworkedItem.cpp.
{
     model_name_ = model_name;
     material_name_ = texture_name;
 }
References material_name_, and model_name_.
Member Function Documentation
add_draw_call()
void NetworkedItem::add_draw_call () override virtual
Adds the draw call to the renderer.
Implements GameObject.
Definition at line 10 of file NetworkedItem.cpp.
{
     DrawCall draw_call = [=](std::shared_ptr<Shader> shader) { draw(shader); };
     //
     ReflexEngine::get_instance().renderer_.add_draw_call(draw_call);
 }
draw()
void NetworkedItem::draw (std::shared_ptr< Shader > shader) override virtual
The draw call for the Networked Item.
Parameters
shader
Implements GameObject.
Definition at line 25 of file NetworkedItem.cpp.
{
     auto default_shader = ReflexEngine::get_instance().renderer_.get_shader();
     glm::mat4 model(1.0f);
     model = glm::translate(model, glm::vec3(position.x, position.y, position.z));
     model = glm::rotate(model, glm::radians(angle),
                         glm::vec3(rotation.x, rotation.y, rotation.z));
     model = glm::scale(model, glm::vec3(scale.x, scale.y, scale.z));
     glUniformMatrix4fv(shader->GetModelLocation(), 1, GL_FALSE,
                        glm::value_ptr(model));
     glUniform1i(shader->GetUsingTexture(), true);
     auto& material_m = ResourceManager::get_instance().get_material_manager();
     material_m.get_material(material_name_)
         .UseMaterial(default_shader->GetShininessLocation(),
                      default_shader->GetSpecularIntensityLocation());
     auto& mm = ResourceManager::get_instance().get_model_manager();
     mm.get_model(model_name_).RenderModel();
 }
References ResourceManager::get_instance(), ResourceManager::get_material_manager(), ResourceManager::get_model_manager(), model_name_, and Model::RenderModel().
fixed_update()
void NetworkedItem::fixed_update (double delta_time) inline override virtual
Updates the body object with fixed delta time.
Parameters
delta_time
Implements GameObject.
Definition at line 44 of file NetworkedItem.hpp.
 {}
init()
void NetworkedItem::init () inline override virtual
Initializes the item with a model, a texture, and a material.
Implements GameObject.
Definition at line 30 of file NetworkedItem.hpp.
 {}
save_object()
void NetworkedItem::save_object () override virtual
Saves the object to lua file.
Parameters
No param
Returns
Void
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 47 of file NetworkedItem.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "NetworkedItem");
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("networkeditem");
     ObjectSaving::addValue("modelName", model_name_, false);
     ObjectSaving::addValue("material_name", material_name_, true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::addValue(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), ObjectSaving::createStruct(), material_name_, model_name_, and ObjectSaving::openFile().
update()
void NetworkedItem::update (double delta_time) override virtual
Updates the Networked Item with delta time.
Parameters
delta_time
Implements GameObject.
Definition at line 17 of file NetworkedItem.cpp.
{
     if (GenericFunctions::getReceivingData()) {
         position.x = GenericFunctions::getNetworkPosX();
         position.y = GenericFunctions::getNetworkPosY();
         position.z = GenericFunctions::getNetworkPosZ();
     }
 }
References GenericFunctions::getReceivingData().
Member Data Documentation
material_name_
std::string NetworkedItem::material_name_ private
The material of the Networked Item.
Definition at line 72 of file NetworkedItem.hpp.
Referenced by NetworkedItem(), and save_object().
model_name_
std::string NetworkedItem::model_name_ private
The model of the Networked Item.
Definition at line 70 of file NetworkedItem.hpp.
Referenced by draw(), NetworkedItem(), and save_object().
The documentation for this class was generated from the following files:
src/Model/GameObject/NetworkedItem.hpp
src/Model/GameObject/NetworkedItem.cpp