My Project: ReflexEngine Class Reference
ReflexEngine Class Reference
The game engine.
#include <ReflexEngine.hpp>
Public Member Functions
ReflexEngine (ReflexEngine &other)=delete
ReflexEngine (const ReflexEngine &other)=delete
void operator= (ReflexEngine &&)=delete
void operator= (const ReflexEngine &)=delete
Static Public Member Functions
static void run ()
Runs the engine.
static ReflexEngine & get_instance ()
Get an instance of the engine.
Public Attributes
Window window_ = {}
Window class.
Camera camera_ = {}
The camera.
OpenGL renderer_ = {}
The renderer of the engine.
std::stack< std::shared_ptr< Scene > > scenes_ = {}
A stack of the current Scene, used to switch between Scenes.
Private Member Functions
void update_delta_time ()
Updates the delta times.
ReflexEngine ()
The default constructor is private as a singleton pattern is used, preventing multiple instances.
Private Attributes
float prev_time_ = 0.0f
The previous time.
float delta_time_ = 0.0f
The delta time.
float fixed_delta_time_ = 0.0f
The fixed delta time.
Detailed Description
The game engine.
Definition at line 16 of file ReflexEngine.hpp.
Constructor & Destructor Documentation
ReflexEngine() [1/3]
ReflexEngine::ReflexEngine (ReflexEngine & other) delete
ReflexEngine() [2/3]
ReflexEngine::ReflexEngine (const ReflexEngine & other) delete
ReflexEngine() [3/3]
ReflexEngine::ReflexEngine () private
The default constructor is private as a singleton pattern is used, preventing multiple instances.
Definition at line 9 of file ReflexEngine.cpp.
{
     if (window_.Init() == 1) return;
 }
Member Function Documentation
get_instance()
ReflexEngine & ReflexEngine::get_instance () static
Get an instance of the engine.
Returns
ReflexEngine&
Definition at line 80 of file ReflexEngine.cpp.
{
     static ReflexEngine instance;
     return instance;
 }
Referenced by OpenGL::init(), OpenGL::render_pass(), and run().
operator=() [1/2]
void ReflexEngine::operator= (const ReflexEngine &) delete
operator=() [2/2]
void ReflexEngine::operator= (ReflexEngine &&) delete
run()
void ReflexEngine::run () static
Runs the engine.
Definition at line 13 of file ReflexEngine.cpp.
{
     auto& engine = ReflexEngine::get_instance();
     ResourceManager::get_instance();
     engine.camera_ = Camera(glm::vec3(0.0f), glm::vec3(0.0f, 1.0f, 0.0f),
                             -90.0f, 0.0f, 5.0f, 0.2f);
     engine.renderer_.init();
     gui::init(ReflexEngine::get_instance().window_.get_window(),
               "#version 410");
     guiLuaAccess::exposeGui();
     engine.scenes_.emplace(std::make_shared<TestScene>());
     engine.scenes_.top()->init();
     auto& input_manager = InputManager::get_instance();
     glfwSetInputMode(ReflexEngine::get_instance().window_.get_window(),
                      GLFW_CURSOR, GLFW_CURSOR_NORMAL);
     while (!engine.window_.IsShouldClose()) {
         engine.update_delta_time();
         glfwPollEvents();
         input_manager.read_keys(engine.window_.get_window());
         gui::mainLoopStart();
         engine.scenes_.top()->key_controls(engine.delta_time_);
         if (GenericFunctions::getIfPaused()) {
             engine.delta_time_ = 0;
         } else {
             engine.scenes_.top()->mouse_controls(engine.window_.GetXOffset(),
                                                  engine.window_.GetYOffset());
         }
         if (GenericFunctions::getIfLoad())
             engine.scenes_.top()->loadSavedGameObjects();
         else if (GenericFunctions::getIfSave())
             engine.scenes_.top()->saveGameObjects();
         else {
             if (engine.fixed_delta_time_ >= time_step) {
                 engine.scenes_.top()->fixed_update(engine.fixed_delta_time_);
                 engine.fixed_delta_time_ = 0.0f;
             }
             engine.scenes_.top()->update(engine.delta_time_);
             engine.scenes_.top()->add_draw_call();
             engine.renderer_.draw();
         }
         gui::mainLoopEnd();
         engine.window_.SwapBuffers();
     }
     gui::shutdown();
 }
References guiLuaAccess::exposeGui(), ResourceManager::get_instance(), InputManager::get_instance(), get_instance(), and gui::shutdown().
Referenced by main().
update_delta_time()
void ReflexEngine::update_delta_time () private
Updates the delta times.
Definition at line 73 of file ReflexEngine.cpp.
{
     float curr_time = glfwGetTime();
     delta_time_ = curr_time - prev_time_;
     fixed_delta_time_ += delta_time_;
     prev_time_ = curr_time;
 }
References delta_time_, fixed_delta_time_, and prev_time_.
Member Data Documentation
camera_
Camera ReflexEngine::camera_ = {}
The camera.
Definition at line 22 of file ReflexEngine.hpp.
delta_time_
float ReflexEngine::delta_time_ = 0.0f private
The delta time.
Definition at line 52 of file ReflexEngine.hpp.
Referenced by update_delta_time().
fixed_delta_time_
float ReflexEngine::fixed_delta_time_ = 0.0f private
The fixed delta time.
Definition at line 54 of file ReflexEngine.hpp.
Referenced by update_delta_time().
prev_time_
float ReflexEngine::prev_time_ = 0.0f private
The previous time.
Definition at line 50 of file ReflexEngine.hpp.
Referenced by update_delta_time().
renderer_
OpenGL ReflexEngine::renderer_ = {}
The renderer of the engine.
Definition at line 25 of file ReflexEngine.hpp.
scenes_
std::stack<std::shared_ptr<Scene> > ReflexEngine::scenes_ = {}
A stack of the current Scene, used to switch between Scenes.
Definition at line 28 of file ReflexEngine.hpp.
window_
Window ReflexEngine::window_ = {}
Window class.
Definition at line 19 of file ReflexEngine.hpp.
The documentation for this class was generated from the following files:
src/Controller/ReflexEngine/ReflexEngine.hpp
src/Controller/ReflexEngine/ReflexEngine.cpp