My Project: Item Class Reference
Item Class Reference
An item in the scene. (JUST FOR TESTING NOW)
#include <Item.hpp>
Public Member Functions
Item (const std::string &model_name, const std::string &texture_name)
Construct a new Item object with a model name and a texture name.
void init () override
Initializes the item with a model, a texture, and a material.
void update (float delta_time) override
Updates the item with delta time.
void fixed_update (float delta_time) override
Updates the body object with fixed delta time.
void add_draw_call () override
Adds the draw call to the renderer.
void draw (std::shared_ptr< Shader > shader) override
The draw call for the item.
void save_object () override
Saves the object to lau file.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
std::string model_name_
The model of the item.
std::string material_name_
The material of the item.
Additional Inherited Members
Public Attributes inherited from GameObject
struct {
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01
};
Detailed Description
An item in the scene. (JUST FOR TESTING NOW)
Definition at line 16 of file Item.hpp.
Constructor & Destructor Documentation
Item()
Item::Item (const std::string & model_name, const std::string & texture_name)
Construct a new Item object with a model name and a texture name.
Parameters
model_name
texture_name
Definition at line 5 of file Item.cpp.
{
     model_name_ = model_name;
     material_name_ = texture_name;
 }
References material_name_, and model_name_.
Member Function Documentation
add_draw_call()
void Item::add_draw_call () override virtual
Adds the draw call to the renderer.
Implements GameObject.
Definition at line 10 of file Item.cpp.
{
     DrawCall draw_call = [=](std::shared_ptr<Shader> shader) { draw(shader); };
     //
     ReflexEngine::get_instance().renderer_.add_draw_call(draw_call);
 }
draw()
void Item::draw (std::shared_ptr< Shader > shader) override virtual
The draw call for the item.
Parameters
shader
Implements GameObject.
Definition at line 16 of file Item.cpp.
{
     auto default_shader = ReflexEngine::get_instance().renderer_.get_shader();
     glm::mat4 model(1.0f);
     model =
         glm::translate(model, glm::vec3(position.x, position.y, position.z));
     model = glm::rotate(model, glm::radians(angle),
                         glm::vec3(rotation.x, rotation.y, rotation.z));
     model = glm::scale(model, glm::vec3(scale.x, scale.y, scale.z));
     glUniformMatrix4fv(shader->GetModelLocation(), 1, GL_FALSE,
                        glm::value_ptr(model));
     glUniform1i(shader->GetUsingTexture(), true);
     auto& material_m = ResourceManager::get_instance().get_material_manager();
     material_m.get_material(material_name_)
         .UseMaterial(default_shader->GetShininessLocation(),
                      default_shader->GetSpecularIntensityLocation());
     auto& mm = ResourceManager::get_instance().get_model_manager();
     mm.get_model(model_name_).RenderModel();
 }
References ResourceManager::get_instance(), ResourceManager::get_material_manager(), ResourceManager::get_model_manager(), model_name_, and Model::RenderModel().
fixed_update()
void Item::fixed_update (float delta_time) inline override virtual
Updates the body object with fixed delta time.
Parameters
delta_time
Implements GameObject.
Definition at line 43 of file Item.hpp.
 {}
init()
void Item::init () inline override virtual
Initializes the item with a model, a texture, and a material.
Implements GameObject.
Definition at line 29 of file Item.hpp.
 {}
save_object()
void Item::save_object () override virtual
Saves the object to lau file.
Parameters
No param
Returns
Void
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 39 of file Item.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "Item");
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("item");
     ObjectSaving::addValue("modelName", model_name_, false);
     ObjectSaving::addValue("material_name", material_name_, true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::addValue(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), ObjectSaving::createStruct(), material_name_, model_name_, and ObjectSaving::openFile().
update()
void Item::update (float delta_time) inline override virtual
Updates the item with delta time.
Parameters
delta_time
Implements GameObject.
Definition at line 36 of file Item.hpp.
 {}
Member Data Documentation
material_name_
std::string Item::material_name_ private
The material of the item.
Definition at line 71 of file Item.hpp.
Referenced by Item(), and save_object().
model_name_
std::string Item::model_name_ private
The model of the item.
Definition at line 69 of file Item.hpp.
Referenced by draw(), Item(), and save_object().
The documentation for this class was generated from the following files:
src/Model/GameObject/Item.hpp
src/Model/GameObject/Item.cpp