ICT397 Assignment 2: NPC Class Reference
NPC Class Reference
#include <NPC.hpp>
Public Member Functions
NPC (const std::string &model_name, const std::string &texture_name, bool is_animated, bool is_loop_)
Constructor.
~NPC ()
Destructor.
void init () override
Initialises the game object.
void update (double delta_time) override
Updates the game object.
void fixed_update (double delta_time) override
Updates the game object on a fixed update loop.
void add_draw_call () override
adds a draw call, so it will be rendered
void draw (std::shared_ptr< Shader > shader) override
Draws the object.
void save_object () override
Saves the object.
bool handleMessage (const telegram &msg)
Handles incomming messages.
void set_id (int new_id)
(DANGEROUS) Sets the NPC's identification (DANGEROUS) AUTOMATIC ID IS USED BY DEFAULT, TO ENSURE NO DUPLICATES, USE AT OWN RISK.
int get_id ()
NPC's identificaiton.
void kill_npc (bool kill)
if you should kill the NPC
bool is_dead ()
Gets if NPC is dead.
void set_health (float new_health)
Sets health of NPC.
float get_health ()
Gets the NPC's health.
void set_power (float new_power)
Sets the power of the NPC.
float get_power ()
Gets the power of the NPC.
void set_pos (vector2D pos)
Sets the position of the NPC.
float get_pos_x ()
Gets the NPC's x position.
float get_pos_y ()
Gets the NPC's y position.
float get_pos_z ()
Gets the NPC's z position.
int get_waypoint_count ()
Gets the number of wayponts currently stored.
void add_waypointGLM (glm::vec2 waypoint)
Adds a new waypoint of type glm::vec2.
void add_waypoint (float x, float z)
Adds a new waypoint.
void use_pathfinding (float x1, float z1, float x2, float z2)
Uses pathfinding algorithm to create set of waypoints.
void add_waypoints (const std::queue< glm::vec2 > &new_waypoints)
Sets a queue of new waypoints and clears existing waypoints.
void remove_waypoints ()
Removes all the currently stored waypoints.
void new_state (std::string new_state)
Sets a new state for the FSM.
stateMachine< NPC > * get_FSM ()
Gets FSM for the NPC.
void set_faction (int new_faction)
Sets the NPC's faction.
int get_faction ()
Gets the NPC's faction they are alligned with.
void set_enemy_target (float x, float z)
Sets the enemy targets position.
vector2D get_enemy_target ()
Gets the enemy target position.
void set_target_id (int new_target)
Sets the ID of the NPC's target.
int get_target_id ()
Gets the current target's ID.
void set_move_speed (float new_speed)
Sets the new NPC's move speed.
float get_move_speed ()
Gets the NPC's move speed.
bool waypoint_follow (bool gen_new)
Follows a given waypoint.
bool move_NPC (float x, float z, float offset)
Moves current NPC to position or within offset.
bool watch_for_enemy ()
Searches for an enemy based on a distance of 10. If it sees an enemy will set its target ID & return true.
bool watch_for_enemyVal (float range)
Searches for an enemy based on a max distance. If it sees an enemy will set its target ID & return true.
bool move_to_enemy (float offset)
Moves to a targeted enemy.
void send_message (double time, int sender, int reciever, int msg, sol::object extra)
Sends a message to another AI agent.
void send_group_message (double time, int faction, float range, int reciever, int msg, sol::object extra)
Sends a group message to a AI faction in range.
void freezeNPC ()
Sets the linear velocity to 0.
ModelData & get_animation ()
Gets the animation data.
void setSetup (std::string set)
Sets the setup finite state machine to call.
Public Member Functions inherited from PhysicsObject
PhysicsObject ()=default
Default constructor for physics object.
void initModel (const std::string &model_name, const std::string &material_name)
Initialised the model.
void initRB (glm::vec3 pos, glm::vec3 rotation, float angle)
Initialised the rigid body.
~PhysicsObject ()=default
default destructor
Public Member Functions inherited from BodyRigid
void createBR (glm::vec3 pos, glm::vec3 rotation, float angle)
Creates rigid body.
void set_position (glm::vec3 pos)
Sets the position of the rigid body.
void setType (int type)
Set type of rigid body.
int getType ()
Gets the type of rigid body.
void enableGravity (bool val)
Set if you want gravity.
void setLinearVelocityDamping (float val)
Movement dampining.
void setAngularVelocityDamping (float val)
Rotation dampining.
void setIfBodyCanSleep (bool val)
Sets if the body can go to sleep.
void addForce (glm::vec3 force)
Adds force to the object.
void setLinearVelocity (glm::vec3 velocity)
set force to the object
void addTorque (glm::vec3 torque)
Adds torque to the object.
void setAngularVelocity (glm::vec3 velocity)
set torque to the object
glm::vec3 getPosition ()
Gets the position vector.
glm::vec3 getRotation ()
Gets the axis of rotation vector of the rigid body.
float getAngle ()
Gets the angle around the axis of rotation of the rigid body.
glm::vec3 getLinearVelocity ()
Gets the linear velocity of the rigid body.
glm::vec3 getAngularVelocity ()
Gets the angular velocity of the rigid body.
void addBoxCollider (glm::vec3 pos, glm::vec3 halfSize, float bounciness, float friction)
Adds a box ciller to a rigid body.
void addSphereCollider (glm::vec3 pos, float radius, float bounciness, float friction)
Adds a sphere collider to a rigid body.
void addCapsuleCollider (glm::vec3 pos, float radius, float height, float bounciness, float friction)
Adds a capsule collider to a rigid body.
void addHeightFieldShape (float bounciness, float friction)=delete
Creates a height field shape collision box.
void setLinearAxisFactor (glm::vec3 factor)
Changes the linear axis factor. I.e. if set a axis to 0 it will no longer move on that axis.
void setAngularAxisFactor (glm::vec3 factor)
Changes the angular axis factor. I.e. if set a axis to 0 it will no longer rotate on that axis.
~BodyRigid ()
Destructor.
std::vector< colliderData_capsule > getCapsuleColliders ()
Public Member Functions inherited from Body
void setCreator (bool val)
Sets if the object is a creator (true) or destructor (false). A creator should be one of the fist game objects while a destoryer should be one of the last.
void physicsDebugger ()
Adds all possible physic debugger options.
void physicsWorldDestroyer ()
Destoryes physic world.
~Body ()
Destructor.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
int m_id
NPC's unique identifier.
int m_faction = 0
NPC's faction.
float m_health = 15
NPC's health.
bool m_dead = false
If they are dead.
float m_power = 1
The power of their attacks or whatever you want to use it for.
float m_move_speed = 1
The move speed.
std::queue< glm::vec2 > m_waypoints
The waypoints stored.
float m_AI_update_delay = 1 / 20
The update delay.
float m_AI_time_elapsed = 0
The time elapsed since last AI update.
stateMachine< NPC > * m_NPC_FSM
NPC's finite state machine.
vector2D m_target_pos
NPC's target position.
int m_target_id
NPC's target ID.
std::string m_setup
std::string m_model_texture
ModelData m_animation
Data for animating.
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Protected Member Functions inherited from PhysicsObject
void saveSphereCollider (size_t index)
Saves the sphere collider of rb.
void saveCapsuleCollider (size_t index)
Saves the capsule collider of rb.
void saveBoxCollider (size_t index)
Saves the box collider of rb.
void saveCollider (size_t index, int type)
Saves the collider of rb.
Protected Attributes inherited from PhysicsObject
std::string model_name_
The model of the item.
std::string material_name_
The material of the item.
Protected Attributes inherited from BodyRigid
BodyRigidPhysics rb
Facaded react rigid body
int m_numOfColliders = 0
The number of colliders in the rb
std::vector< colliderData_sphere > m_sphere
List of sphere colliders. Used for storing data to file
std::vector< colliderData_capsule > m_capsule
List of capsule colliders. Used for storing data to file
std::vector< colliderData_box > m_box
List of capsule colliders. Used for storing data to file
Detailed Description
Definition at line 13 of file NPC.hpp.
Constructor & Destructor Documentation
NPC()
NPC::NPC (const std::string & model_name, const std::string & texture_name, bool is_animated, bool is_loop_)
Constructor.
Parameters
model_name - The name of the model to use
texture_name - the texture name the model uses
is_animated - if the NPC is animated
is_loop_ - if the animation loops by default
Definition at line 5 of file NPC.cpp.
     : m_animation(model_name, texture_name, is_animated, is_loop_) {
     m_NPC_FSM = new stateMachine<NPC>(this);
     m_animation.set_animation(md2::animation_type::JUMP);
     m_id = idMgr.increment_count();
     m_model_texture = texture_name;
 }
References NPC().
Referenced by NPC().
~NPC()
NPC::~NPC ()
Destructor.
Definition at line 14 of file NPC.cpp.
           {
     m_NPC_FSM->free_memory();
     delete m_NPC_FSM;
 }
References m_NPC_FSM.
Member Function Documentation
add_draw_call()
void NPC::add_draw_call () override virtual
adds a draw call, so it will be rendered
Reimplemented from PhysicsObject.
Definition at line 37 of file NPC.cpp.
{
     DrawCall draw_call = [=](std::shared_ptr<Shader> shader) { draw(shader); };
     ReflexEngine::get_instance().renderer_.add_draw_call(draw_call);
 }
add_waypoint()
void NPC::add_waypoint (float x, float z)
Adds a new waypoint.
Parameters
x - x position of waypoint
z - z position of waypoint
Definition at line 129 of file NPC.cpp.
 { add_waypointGLM(glm::vec2(x, z)); }
add_waypointGLM()
void NPC::add_waypointGLM (glm::vec2 waypoint)
Adds a new waypoint of type glm::vec2.
Parameters
waypont - The new waypoint to add
Definition at line 128 of file NPC.cpp.
 { m_waypoints.push(waypoint); }
add_waypoints()
void NPC::add_waypoints (const std::queue< glm::vec2 > & new_waypoints)
Sets a queue of new waypoints and clears existing waypoints.
Parameters
new_waypoints - The new waypoints
Definition at line 130 of file NPC.cpp.
{
     remove_waypoints();
     m_waypoints = new_waypoints;
 }
References remove_waypoints().
draw()
void NPC::draw (std::shared_ptr< Shader > shader) override virtual
Draws the object.
Parameters
shader - The shader
Reimplemented from PhysicsObject.
Definition at line 43 of file NPC.cpp.
{
     auto default_shader = ReflexEngine::get_instance().renderer_.get_shader();
     glm::mat4 model(1.0f);
     model =
         glm::translate(model, glm::vec3(position.x, position.y, position.z));
     model = glm::rotate(model, glm::radians(-angle),
                         glm::vec3(rotation.x, rotation.y, rotation.z));
     model =
         glm::rotate(model, glm::radians(-90.0f), glm::vec3(1.0f, 0.0f, 0.0f));
     model =
         glm::rotate(model, glm::radians(90.0f), glm::vec3(0.0f, 0.0f, 1.0f));
     model = glm::scale(model, glm::vec3(scale.x, scale.y, scale.z));
     glUniformMatrix4fv(shader->GetModelLocation(), 1, GL_FALSE,
                        glm::value_ptr(model));
     glUniform1i(shader->GetUsingTexture(), true);
     auto& material_m = ResourceManager::get_instance().get_material_manager();
     material_m.get_material(material_name_)
         .UseMaterial(default_shader->GetShininessLocation(),
                      default_shader->GetSpecularIntensityLocation());
     // auto& model_m = ResourceManager::get_instance().get_md2_model_manager();
     // model_m.get_md2_model(model_name_);
     m_animation.render(EngineTime::get_delta_time());
 }
References ResourceManager::get_instance(), and ResourceManager::get_material_manager().
fixed_update()
void NPC::fixed_update (double delta_time) override virtual
Updates the game object on a fixed update loop.
Parameters
delta_time - The change in time since it was last called
Reimplemented from PhysicsObject.
Definition at line 23 of file NPC.cpp.
{
     if (!EngineTime::is_paused()) {
         m_AI_time_elapsed += delta_time;
         if (m_AI_time_elapsed > m_AI_update_delay) {
             m_NPC_FSM->update();
             position = rb.getPosition();
             position.y = GenericFunctions::getHeight(position.x, position.z);
             rb.set_position(glm::vec3(position.x, position.y, position.z));
             m_AI_time_elapsed = 0.0f;
         }
     }
 }
References EngineTime::is_paused(), m_AI_time_elapsed, and m_AI_update_delay.
freezeNPC()
void NPC::freezeNPC ()
Sets the linear velocity to 0.
Definition at line 284 of file NPC.cpp.
 { rb.setLinearVelocity(glm::vec3(0)); }
get_animation()
ModelData & NPC::get_animation ()
Gets the animation data.
Returns
ModelDate - The animation data for the NPC
Definition at line 286 of file NPC.cpp.
 { return m_animation; }
get_enemy_target()
vector2D NPC::get_enemy_target ()
Gets the enemy target position.
Returns
glm::vec2 - Target position
Definition at line 154 of file NPC.cpp.
 { return m_target_pos; }
get_faction()
int NPC::get_faction ()
Gets the NPC's faction they are alligned with.
Returns
int - the faction it identifies with
Definition at line 151 of file NPC.cpp.
 { return m_faction; }
References m_faction.
Referenced by watch_for_enemyVal().
get_FSM()
stateMachine< NPC > * NPC::get_FSM ()
Gets FSM for the NPC.
Returns
stateMachine<NPC> - The FSM of the NPC
Definition at line 148 of file NPC.cpp.
 { return m_NPC_FSM; }
References m_NPC_FSM.
get_health()
float NPC::get_health ()
Gets the NPC's health.
Returns
float - health of NPC
Definition at line 122 of file NPC.cpp.
 { return m_health; }
References m_health.
get_id()
int NPC::get_id ()
NPC's identificaiton.
Returns
Returns the NPC's id (int)
Definition at line 116 of file NPC.cpp.
 { return m_id; }
References m_id.
get_move_speed()
float NPC::get_move_speed ()
Gets the NPC's move speed.
Returns
float - move speed
Definition at line 160 of file NPC.cpp.
 { return m_move_speed; }
References m_move_speed.
get_pos_x()
float NPC::get_pos_x ()
Gets the NPC's x position.
Returns
float - x position
Definition at line 168 of file NPC.cpp.
 { return position.x; }
get_pos_y()
float NPC::get_pos_y ()
Gets the NPC's y position.
Returns
float - y position
Definition at line 169 of file NPC.cpp.
 { return position.y; }
get_pos_z()
float NPC::get_pos_z ()
Gets the NPC's z position.
Returns
float - z position
Definition at line 170 of file NPC.cpp.
 { return position.z; }
get_power()
float NPC::get_power ()
Gets the power of the NPC.
Returns
float - Power of NPC
Definition at line 125 of file NPC.cpp.
 { return m_power; }
References m_power.
get_target_id()
int NPC::get_target_id ()
Gets the current target's ID.
Returns
int - the target's ID
Definition at line 157 of file NPC.cpp.
 { return m_target_id; }
References m_target_id.
get_waypoint_count()
int NPC::get_waypoint_count ()
Gets the number of wayponts currently stored.
Returns
int - number of waypoints
Definition at line 127 of file NPC.cpp.
 { return m_waypoints.size(); }
handleMessage()
bool NPC::handleMessage (const telegram & msg)
Handles incomming messages.
Parameters
msg - The message to be handled
Definition at line 111 of file NPC.cpp.
{
     return m_NPC_FSM->handleMessage(msg);
 }
Referenced by messageDispatcher::discharge().
init()
void NPC::init () override virtual
Initialises the game object.
Reimplemented from BodyRigid.
Definition at line 19 of file NPC.cpp.
 {}
is_dead()
bool NPC::is_dead ()
Gets if NPC is dead.
Returns
bool - True if NPC is dead
Definition at line 119 of file NPC.cpp.
 { return m_dead; }
References m_dead.
Referenced by move_to_enemy(), and watch_for_enemyVal().
kill_npc()
void NPC::kill_npc (bool kill)
if you should kill the NPC
Parameters
kill - True to kill NPC
Definition at line 118 of file NPC.cpp.
 { m_dead = kill; }
References m_dead.
move_NPC()
bool NPC::move_NPC (float x, float z, float offset)
Moves current NPC to position or within offset.
Parameters
x - x position to move to
z - z position to move to
offset - stop within an offset of this value
Returns
bool - true if at destination
Definition at line 193 of file NPC.cpp.
{
     glm::vec2 new_pos = glm::vec2(x, z);
     glm::vec2 newPos = glm::vec2(position.x, position.z);
     bool ret = ai_movement::moveTo(newPos, new_pos, glm::vec2(1, 1),
                                    m_AI_time_elapsed, offset);
     if (ret == false) {
         glm::vec2 lookAt;
         lookAt.x = new_pos.x - newPos.x;
         lookAt.y = new_pos.y - newPos.y;
         lookAt = glm::normalize(lookAt);
         angle = atan2(lookAt.y, lookAt.x) * 180 / 3.151f;
         lookAt = lookAt * glm::vec2(m_move_speed, m_move_speed);
         rb.setLinearVelocity(glm::vec3(lookAt.x, 0, lookAt.y));
     }
     return ret;
 }
move_to_enemy()
bool NPC::move_to_enemy (float offset)
Moves to a targeted enemy.
Parameters
offset - The offset to stop at
Returns
bool - True if at destination or enemy is dead
Definition at line 249 of file NPC.cpp.
{
     NPC* npc = entityMgr.getEntityFromID(m_target_id);
     if (npc->is_dead()) {
         return false;
     }
     return move_NPC(npc->position.x, npc->position.z, offset);
 }
References is_dead().
new_state()
void NPC::new_state (std::string new_state)
Sets a new state for the FSM.
Parameters
new_state - new state
Definition at line 144 of file NPC.cpp.
{
     m_NPC_FSM->changeState(new_state);
 }
remove_waypoints()
void NPC::remove_waypoints ()
Removes all the currently stored waypoints.
Definition at line 134 of file NPC.cpp.
{
     if (m_waypoints.size() != 0) {
         m_waypoints.empty();
     }
 }
Referenced by add_waypoints(), and use_pathfinding().
save_object()
void NPC::save_object () override virtual
Saves the object.
Reimplemented from PhysicsObject.
Definition at line 70 of file NPC.cpp.
                       {
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "NPC");
     ObjectSaving::addComma();
     ObjectSaving::addValue("modelName", model_name_, false);
     ObjectSaving::addValue("model_texture", m_model_texture, false);
     ObjectSaving::addValue("material_name", material_name_, false);
     ObjectSaving::addValue("animate", m_animation.get_is_animated(), false);
     ObjectSaving::addValue("loopAnimation", m_animation.get_loop(), false);
     ObjectSaving::addValue("rbType", rb.getRBType(), false);
     ObjectSaving::addValue("gravity", (int)rb.getIfGravityActive(), false);
     ObjectSaving::addValue("xForce", rb.getLinearVelocity().x, false);
     ObjectSaving::addValue("yForce", rb.getLinearVelocity().y, false);
     ObjectSaving::addValue("zForce", rb.getLinearVelocity().z, false);
     ObjectSaving::addValue("xTorque", rb.getAngularVelocity().x, false);
     ObjectSaving::addValue("yTorque", rb.getAngularVelocity().y, false);
     ObjectSaving::addValue("zTorque", rb.getAngularVelocity().z, false);
     ObjectSaving::addValue("linearDamping", rb.getLinearDamping(), false);
     ObjectSaving::addValue("angularDamping", rb.getAngularDamping(), false);
     ObjectSaving::addValue("sleep", (int)rb.getIfAllowedSleep(), false);
     ObjectSaving::addValue("numOfColliders", rb.getNumberOfColliders(), true);
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("AI");
     ObjectSaving::addValue("setUpFSM", m_setup, false);
     ObjectSaving::addValue("faction", m_faction, false);
     ObjectSaving::addValue("health", m_health, false);
     ObjectSaving::addValue("power", m_power, false);
     ObjectSaving::addValue("moveSpeed", m_move_speed, true);
     ObjectSaving::closeStruct();
     for (int count = 0; count < rb.getNumberOfColliders(); count++) {
         int type = rb.getColliderType(count);
         ObjectSaving::createStruct("collider" + std::to_string(count + 1));
         saveCollider(count, type);
         ObjectSaving::closeStruct();
     }
     ObjectSaving::closeFile();
 }
References ObjectSaving::addComma(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), and ObjectSaving::openFile().
send_group_message()
void NPC::send_group_message (double time, int faction, float range, int reciever, int msg, sol::object extra)
Sends a group message to a AI faction in range.
Parameters
time - delay before sending the message
faction - the faction to send the message too
range - the range of the message
reciever - the recievers ID
msg - the message
extra - extra info in the message
Definition at line 263 of file NPC.cpp.
{
     glm::vec3 temp;
     float distance;
     for (int count = 0; count < entityMgr.numberOfEntities(); count++) {
         if (entityMgr.getEntityByIndex(count)->m_faction != faction ||
             sender == entityMgr.getEntityByIndex(count)->m_id) {
             continue;
         }
         temp = entityMgr.getEntityByIndex(count)->position;
         distance = glm::length(temp - position);
         if (distance < range) {
             messageMgr.dispatchMsg(time, sender,
                                    entityMgr.getEntityByIndex(count)->m_id, msg,
                                    extra);
         }
     }
 }
send_message()
void NPC::send_message (double time, int sender, int reciever, int msg, sol::object extra)
Sends a message to another AI agent.
Parameters
time - delay before sending the message
sender - the senders ID
reciever - the recievers ID
msg - the message
extra - extra info in the message
Definition at line 258 of file NPC.cpp.
{
     messageMgr.dispatchMsg(time, sender, reciever, msg, extra);
 }
set_enemy_target()
void NPC::set_enemy_target (float x, float z)
Sets the enemy targets position.
Parameters
x - The target's x position
z - The target's z position
Definition at line 153 of file NPC.cpp.
 { m_target_pos.set(x, z); }
set_faction()
void NPC::set_faction (int new_faction)
Sets the NPC's faction.
Parameters
new_faction - The faction for the NPC
Definition at line 150 of file NPC.cpp.
 { m_faction = new_faction; }
References m_faction.
Referenced by GameAssetFactory::loadNPCObject().
set_health()
void NPC::set_health (float new_health)
Sets health of NPC.
Parameters
new_health - The new health of the NPC
Definition at line 121 of file NPC.cpp.
 { m_health = new_health; }
References m_health.
Referenced by GameAssetFactory::loadNPCObject().
set_id()
void NPC::set_id (int new_id)
(DANGEROUS) Sets the NPC's identification (DANGEROUS) AUTOMATIC ID IS USED BY DEFAULT, TO ENSURE NO DUPLICATES, USE AT OWN RISK.
Parameters
new_id - New NPC identification (DANGEROUS)
Definition at line 115 of file NPC.cpp.
 { m_id = new_id; }
References m_id.
set_move_speed()
void NPC::set_move_speed (float new_speed)
Sets the new NPC's move speed.
Parameters
new_speed - new NPC's move speed
Definition at line 159 of file NPC.cpp.
 { m_move_speed = new_speed; }
References m_move_speed.
set_pos()
void NPC::set_pos (vector2D pos)
Sets the position of the NPC.
Parameters
pos - The new position you want
Definition at line 162 of file NPC.cpp.
{
     position.x = pos.getX();
     position.z = pos.getY();
     position.y = GenericFunctions::getHeight(position.x, position.z);
     rb.set_position(glm::vec3(position.x, position.y, position.z));
 }
set_power()
void NPC::set_power (float new_power)
Sets the power of the NPC.
Parameters
new_power - New power of the NPC
Definition at line 124 of file NPC.cpp.
 { m_power = new_power; }
References m_power.
Referenced by GameAssetFactory::loadNPCObject().
set_target_id()
void NPC::set_target_id (int new_target)
Sets the ID of the NPC's target.
Parameters
new_target - The new target ID
Definition at line 156 of file NPC.cpp.
 { m_target_id = new_target; }
References m_target_id.
setSetup()
void NPC::setSetup (std::string set)
Sets the setup finite state machine to call.
Parameters
set - The lua function which sets up the AI FSM
Definition at line 288 of file NPC.cpp.
 { m_setup = set; }
update()
void NPC::update (double delta_time) override virtual
Updates the game object.
Parameters
delta_time - The change in time since it was last called
Reimplemented from PhysicsObject.
Definition at line 21 of file NPC.cpp.
 {}
use_pathfinding()
void NPC::use_pathfinding (float x1, float z1, float x2, float z2)
Uses pathfinding algorithm to create set of waypoints.
Parameters
x1 - current x position
z1 - current z position
x2 - target x position
z2 - target z position
Definition at line 139 of file NPC.cpp.
{
     remove_waypoints();
     m_waypoints = gameWorld.pathFinding(x1, z1, x2, z2);
 }
References remove_waypoints().
watch_for_enemy()
bool NPC::watch_for_enemy ()
Searches for an enemy based on a distance of 10. If it sees an enemy will set its target ID & return true.
Returns
bool - true if it finds an enemy
Definition at line 213 of file NPC.cpp.
 { return watch_for_enemyVal(10); }
References watch_for_enemyVal().
watch_for_enemyVal()
bool NPC::watch_for_enemyVal (float range)
Searches for an enemy based on a max distance. If it sees an enemy will set its target ID & return true.
Parameters
range - The distance to watch from
Returns
bool - true if it finds an enemy
Definition at line 215 of file NPC.cpp.
{
     int size = entityMgr.numberOfEntities();
     NPC* npc;
     glm::vec2 lookAt = glm::vec2(-1, 0);
     glm::vec3 pos;
     for (int count = 0; count < size; count++) {
         npc = entityMgr.getEntityByIndex(count);
         if (m_faction != npc->get_faction()) {
             if (!npc->is_dead()) {
                 pos = npc->position;
                 lookAt.x = cos(angle / 180 * 3.151f);
                 lookAt.y = sin(angle / 180 * 3.151f);
                 if (ai_movement::seeTarget(glm::vec2(position.x, position.z),
                                            glm::vec2(pos.x, pos.z), lookAt,
                                            range, 160)) {
                     m_target_id = npc->m_id;
                     // Sets new angle of rotation, so NPC looks at target
                     lookAt.x = pos.x - position.x;
                     lookAt.y = pos.z - position.z;
                     lookAt = glm::normalize(lookAt);
                     angle = atan2(lookAt.y, lookAt.x) * 180 / 3.151f;
                     // std::cout << "Angle: " << angle << " look at: " <<
                     // lookAt.x
                     //           << " : " << lookAt.y << std::endl;
                     return true;  // target spotted
                 }
             }
         }
     }
     return false;
 }
References get_faction(), is_dead(), m_faction, m_id, and m_target_id.
Referenced by watch_for_enemy().
waypoint_follow()
bool NPC::waypoint_follow (bool gen_new)
Follows a given waypoint.
Parameters
gen_new - If it should generate new wayponts if there is none (not currently implemented)
Returns
bool - Finished following a waypont (could have more to follow)
Definition at line 172 of file NPC.cpp.
{
     if (m_waypoints.size() == 0 && gen_new) {
         // std::cout << "waypoints empty & gen new" << std::endl;
         rb.setLinearVelocity(glm::vec3(0, 0, 0));
         return true;
     } else if (m_waypoints.size() == 0) {
         // std::cout << "waypoints empty" << std::endl;
         rb.setLinearVelocity(glm::vec3(0, 0, 0));
         return true;
     }
     if (move_NPC(m_waypoints.front().x, m_waypoints.front().y, 0.5)) {
         // std::cout << "removing: " << m_waypoints.front().x << " : "
         //           << m_waypoints.front().y << std::endl;
         m_waypoints.pop();
         return true;
     }
     return false;
 }
Member Data Documentation
m_AI_time_elapsed
float NPC::m_AI_time_elapsed = 0 private
The time elapsed since last AI update.
Definition at line 342 of file NPC.hpp.
Referenced by fixed_update().
m_AI_update_delay
float NPC::m_AI_update_delay = 1 / 20 private
The update delay.
Definition at line 340 of file NPC.hpp.
Referenced by fixed_update().
m_animation
ModelData NPC::m_animation private
Data for animating.
Definition at line 354 of file NPC.hpp.
m_dead
bool NPC::m_dead = false private
If they are dead.
Definition at line 330 of file NPC.hpp.
Referenced by is_dead(), and kill_npc().
m_faction
int NPC::m_faction = 0 private
NPC's faction.
Definition at line 326 of file NPC.hpp.
Referenced by get_faction(), set_faction(), and watch_for_enemyVal().
m_health
float NPC::m_health = 15 private
NPC's health.
Definition at line 328 of file NPC.hpp.
Referenced by get_health(), and set_health().
m_id
int NPC::m_id private
NPC's unique identifier.
Definition at line 324 of file NPC.hpp.
Referenced by get_id(), set_id(), and watch_for_enemyVal().
m_model_texture
std::string NPC::m_model_texture private
Definition at line 351 of file NPC.hpp.
m_move_speed
float NPC::m_move_speed = 1 private
The move speed.
Definition at line 334 of file NPC.hpp.
Referenced by get_move_speed(), and set_move_speed().
m_NPC_FSM
stateMachine<NPC>* NPC::m_NPC_FSM private
NPC's finite state machine.
Definition at line 344 of file NPC.hpp.
Referenced by get_FSM(), and ~NPC().
m_power
float NPC::m_power = 1 private
The power of their attacks or whatever you want to use it for.
Definition at line 332 of file NPC.hpp.
Referenced by get_power(), and set_power().
m_setup
std::string NPC::m_setup private
Definition at line 350 of file NPC.hpp.
m_target_id
int NPC::m_target_id private
NPC's target ID.
Definition at line 348 of file NPC.hpp.
Referenced by get_target_id(), set_target_id(), and watch_for_enemyVal().
m_target_pos
vector2D NPC::m_target_pos private
NPC's target position.
Definition at line 346 of file NPC.hpp.
m_waypoints
std::queue<glm::vec2> NPC::m_waypoints private
The waypoints stored.
Definition at line 337 of file NPC.hpp.
The documentation for this class was generated from the following files:
src/Model/GameObject/NPC.hpp
src/Model/GameObject/NPC.cpp