My Project: TestScene Class Reference
TestScene Class Reference
A test scene for testing purposes.
#include <TestScene.hpp>
Public Member Functions
TestScene ()=default
Default constructor.
void init () override
Initializes the scene.
void addGameObject (std::string luaScript) override
Adds a game object.
void key_controls (float delta_time) override
The function to specify controls for the keyboard.
void mouse_controls (float xpos, float ypos) override
The function to specify controls for the mouse.
void update (float delta_time) override
The update loop of the scene.
void fixed_update (float delta_time)
The fixed update loop of the scene.
void add_draw_call () override
Add draw calls to the renderer.
void saveGameObjects () override
Saves game objects.
void loadSavedGameObjects () override
loads game objects
void add_game_object_during_run (std::string luaScript)
Adds a new game object during run time.
void add_new_game_objects ()
Add new game objects during run time.
void garbage_collection ()
Deleted game objects which are considered finished.
Public Member Functions inherited from Scene
virtual ~Scene ()=default
Virtual destructor.
Private Attributes
DirectionalLight directional_light_ = {}
A directional light.
std::vector< std::string > to_add_
Scripts for game objects to be added.
Additional Inherited Members
Protected Attributes inherited from Scene
std::vector< std::shared_ptr< GameObject > > game_objects_
A vector of game objects in the scene.
Detailed Description
A test scene for testing purposes.
Definition at line 21 of file TestScene.hpp.
Constructor & Destructor Documentation
TestScene()
TestScene::TestScene () default
Default constructor.
Member Function Documentation
add_draw_call()
void TestScene::add_draw_call () override virtual
Add draw calls to the renderer.
Implements Scene.
Definition at line 89 of file TestScene.cpp.
{
     auto& renderer = ReflexEngine::get_instance().renderer_;
     renderer.add_directional_light(directional_light_);
     for (auto& game_object : game_objects_) {
         game_object->add_draw_call();
     }
 }
add_game_object_during_run()
void TestScene::add_game_object_during_run (std::string luaScript)
Adds a new game object during run time.
Parameters
luaScript
Definition at line 22 of file TestScene.cpp.
{
     to_add_.push_back(luaScript);
 }
add_new_game_objects()
void TestScene::add_new_game_objects ()
Add new game objects during run time.
Precondition
Added game objects stored in list
Postcondition
Game objects loaded and stored
Definition at line 146 of file TestScene.cpp.
{
     for (int count = 0; count < to_add_.size(); count++) {
         std::cout << "Adding during runtime = " << to_add_[count] << std::endl;
         game_objects_.emplace_back(GameAssetFactory::create(to_add_[count]));
     }
     to_add_.clear();
 }
addGameObject()
void TestScene::addGameObject (std::string luaScript) override virtual
Adds a game object.
Parameters
luaScript - a lua script to add
Precondition
Nothing
Postcondition
Object added
Implements Scene.
Definition at line 26 of file TestScene.cpp.
{
     if (glfwGetTime() > (double)0.5) {
         add_game_object_during_run(luaScript);
     } else {
         std::cout << luaScript << std::endl;
         game_objects_.emplace_back(GameAssetFactory::create(luaScript));
     }
 }
fixed_update()
void TestScene::fixed_update (float delta_time) virtual
The fixed update loop of the scene.
Parameters
delta_time
Implements Scene.
Definition at line 109 of file TestScene.cpp.
{
     for (auto& game_object : game_objects_) {
         game_object->fixed_update(delta_time);
     }
 }
garbage_collection()
void TestScene::garbage_collection ()
Deleted game objects which are considered finished.
Precondition
Game objects exists
Postcondition
Removed bad game objects
Definition at line 135 of file TestScene.cpp.
{
     int size = game_objects_.size();
     for (int count = 0; count < size; count++) {
         if (game_objects_[count]->position.y < -5000) {
             game_objects_.erase(game_objects_.begin() + count);
             size--;
             count--;
         }
     }
 }
init()
void TestScene::init () override virtual
Initializes the scene.
Implements Scene.
Definition at line 7 of file TestScene.cpp.
                      {
     directional_light_ =
         DirectionalLight(2048, 2048, glm::vec3(1.0f, 0.53f, 0.3f), 0.2f,
                          glm::vec3(-10.0f, -12.0f, 18.5f), 0.9f);
     sol::state& lua = LuaManager::get_instance().get_state();
     GenericFunctions::lua_access();
     lua.script_file("scripts/_Materials.lua");
     lua.set_function("addGameObject", &TestScene::addGameObject, this);
     lua.script_file("scripts/_MasterCreation.lua");
     InputManager::get_instance().load_lua_bindings("scripts/controls.lua");
 }
References InputManager::get_instance(), InputManager::load_lua_bindings(), and GenericFunctions::lua_access().
key_controls()
void TestScene::key_controls (float delta_time) override virtual
The function to specify controls for the keyboard.
Parameters
delta_time - The time between frames
Implements Scene.
Definition at line 35 of file TestScene.cpp.
{
     auto& camera = ReflexEngine::get_instance().camera_;
     auto& input_manager = InputManager::get_instance();
     if (input_manager.get_key_state(Input::quit).is_key_pressed())
         GenericFunctions::set_if_credits_active(
             !GenericFunctions::get_if_credits_active());
     camera.set_move_direction(glm::vec3(0, 0, 0));
     if (!(input_manager.get_key_state(Input::move_forward).is_key_hold() &&
           input_manager.get_key_state(Input::move_backward).is_key_hold())) {
         if (input_manager.get_key_state(Input::move_forward).is_key_hold())
             camera.calculate_direction(Movement::forward);
         if (input_manager.get_key_state(Input::move_backward).is_key_hold())
             camera.calculate_direction(Movement::backward);
     }
     if (!(input_manager.get_key_state(Input::move_left).is_key_hold() &&
           input_manager.get_key_state(Input::move_right).is_key_hold())) {
         if (input_manager.get_key_state(Input::move_left).is_key_hold())
             camera.calculate_direction(Movement::left);
         if (input_manager.get_key_state(Input::move_right).is_key_hold())
             camera.calculate_direction(Movement::right);
     }
     if (input_manager.get_key_state(Input::toggle_wireframe).is_key_pressed())
         ReflexEngine::get_instance().renderer_.toggle_wireframe();
     if (input_manager.get_key_state(Input::toggle_noclip).is_key_pressed())
         camera.toggle_noclip();
     if (input_manager.get_key_state(Input::pause_game).is_key_pressed())
         GenericFunctions::setIfPaused(!GenericFunctions::getIfPaused());
     if (input_manager.get_key_state(Input::help_menu).is_key_pressed())
         GenericFunctions::setifHelpMenuActive(
             !GenericFunctions::getIfHelpMenuActive());
     if (input_manager.get_key_state(Input::network_menu).is_key_pressed()) {
         GenericFunctions::setNetworkMenuActive(
             !GenericFunctions::getNetworkMenuActive());
     }
     if (input_manager.get_key_state(Input::shoot).is_key_pressed()) {
         GenericFunctions::setIfShouldShoot(true);
     }
 }
References GenericFunctions::get_if_credits_active(), InputManager::get_instance(), InputManager::get_key_state(), GenericFunctions::getIfHelpMenuActive(), GenericFunctions::getIfPaused(), GenericFunctions::getNetworkMenuActive(), help_menu, InputState::is_key_hold(), InputState::is_key_pressed(), move_backward, move_forward, move_left, move_right, network_menu, pause_game, quit, GenericFunctions::set_if_credits_active(), GenericFunctions::setifHelpMenuActive(), GenericFunctions::setIfPaused(), GenericFunctions::setIfShouldShoot(), GenericFunctions::setNetworkMenuActive(), and shoot.
loadSavedGameObjects()
void TestScene::loadSavedGameObjects () override virtual
loads game objects
Precondition
Game objects exists in files
Postcondition
Game objects added to scene
Implements Scene.
Definition at line 125 of file TestScene.cpp.
{
     game_objects_.clear();
     sol::state& lua = LuaManager::get_instance().get_state();
     lua.script_file("scripts/save/_MasterCreation.lua");
     GenericFunctions::setIfLoad(false);
     return;
 }
References GenericFunctions::setIfLoad().
mouse_controls()
void TestScene::mouse_controls (float xpos, float ypos) override virtual
The function to specify controls for the mouse.
Parameters
xpos - X position of mouse on screen
ypos - Y position of mouse on screen
Implements Scene.
Definition at line 83 of file TestScene.cpp.
{
     auto& camera = ReflexEngine::get_instance().camera_;
     camera.mouse_move(xpos, ypos);
 }
saveGameObjects()
void TestScene::saveGameObjects () override virtual
Saves game objects.
Precondition
Game objects exists
Postcondition
Game objects saved
Implements Scene.
Definition at line 115 of file TestScene.cpp.
{
     for (auto& game_object : game_objects_) {
         game_object->save_object();
     }
     GenericFunctions::setIfSave(false);
     std::cout << "done saving" << std::endl;
     ObjectSaving::setFreshSave();
     return;
 }
References ObjectSaving::setFreshSave(), and GenericFunctions::setIfSave().
update()
void TestScene::update (float delta_time) override virtual
The update loop of the scene.
Parameters
delta_time - The time between frames
Implements Scene.
Definition at line 99 of file TestScene.cpp.
{
     garbage_collection();
     add_new_game_objects();
     for (auto& game_object : game_objects_) {
         game_object->update(delta_time);
     }
     GenericFunctions::networkUpdate();
 }
References GenericFunctions::networkUpdate().
Member Data Documentation
directional_light_
DirectionalLight TestScene::directional_light_ = {} private
A directional light.
Definition at line 117 of file TestScene.hpp.
to_add_
std::vector<std::string> TestScene::to_add_ private
Scripts for game objects to be added.
Definition at line 120 of file TestScene.hpp.
The documentation for this class was generated from the following files:
src/Game/TestScene.hpp
src/Game/TestScene.cpp