ICT397 Assignment 2: PhysicsObject Class Reference
PhysicsObject Class Reference
#include <PhysicsObject.hpp>
Public Member Functions
PhysicsObject ()=default
Default constructor for physics object.
void initModel (const std::string &model_name, const std::string &material_name)
Initialised the model.
void initRB (glm::vec3 pos, glm::vec3 rotation, float angle)
Initialised the rigid body.
void update (double delta_time) override
Updates the object.
void fixed_update (double delta_time) override
Updates the body object with fixed delta time.
void add_draw_call () override
Adds draw call of object.
void draw (std::shared_ptr< Shader > shader) override
Draws the object.
void save_object () override
Saves the object to lau file.
~PhysicsObject ()=default
default destructor
Public Member Functions inherited from BodyRigid
void init () override
Basic initialiser for engine to call. Does nothing.
void createBR (glm::vec3 pos, glm::vec3 rotation, float angle)
Creates rigid body.
void set_position (glm::vec3 pos)
Sets the position of the rigid body.
void setType (int type)
Set type of rigid body.
int getType ()
Gets the type of rigid body.
void enableGravity (bool val)
Set if you want gravity.
void setLinearVelocityDamping (float val)
Movement dampining.
void setAngularVelocityDamping (float val)
Rotation dampining.
void setIfBodyCanSleep (bool val)
Sets if the body can go to sleep.
void addForce (glm::vec3 force)
Adds force to the object.
void setLinearVelocity (glm::vec3 velocity)
set force to the object
void addTorque (glm::vec3 torque)
Adds torque to the object.
void setAngularVelocity (glm::vec3 velocity)
set torque to the object
glm::vec3 getPosition ()
Gets the position vector.
glm::vec3 getRotation ()
Gets the axis of rotation vector of the rigid body.
float getAngle ()
Gets the angle around the axis of rotation of the rigid body.
glm::vec3 getLinearVelocity ()
Gets the linear velocity of the rigid body.
glm::vec3 getAngularVelocity ()
Gets the angular velocity of the rigid body.
void addBoxCollider (glm::vec3 pos, glm::vec3 halfSize, float bounciness, float friction)
Adds a box ciller to a rigid body.
void addSphereCollider (glm::vec3 pos, float radius, float bounciness, float friction)
Adds a sphere collider to a rigid body.
void addCapsuleCollider (glm::vec3 pos, float radius, float height, float bounciness, float friction)
Adds a capsule collider to a rigid body.
void addHeightFieldShape (float bounciness, float friction)=delete
Creates a height field shape collision box.
void setLinearAxisFactor (glm::vec3 factor)
Changes the linear axis factor. I.e. if set a axis to 0 it will no longer move on that axis.
void setAngularAxisFactor (glm::vec3 factor)
Changes the angular axis factor. I.e. if set a axis to 0 it will no longer rotate on that axis.
~BodyRigid ()
Destructor.
std::vector< colliderData_capsule > getCapsuleColliders ()
Public Member Functions inherited from Body
void setCreator (bool val)
Sets if the object is a creator (true) or destructor (false). A creator should be one of the fist game objects while a destoryer should be one of the last.
void physicsDebugger ()
Adds all possible physic debugger options.
void physicsWorldDestroyer ()
Destoryes physic world.
~Body ()
Destructor.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Protected Member Functions
void saveSphereCollider (size_t index)
Saves the sphere collider of rb.
void saveCapsuleCollider (size_t index)
Saves the capsule collider of rb.
void saveBoxCollider (size_t index)
Saves the box collider of rb.
void saveCollider (size_t index, int type)
Saves the collider of rb.
Protected Attributes
std::string model_name_
The model of the item.
std::string material_name_
The material of the item.
Protected Attributes inherited from BodyRigid
BodyRigidPhysics rb
Facaded react rigid body
int m_numOfColliders = 0
The number of colliders in the rb
std::vector< colliderData_sphere > m_sphere
List of sphere colliders. Used for storing data to file
std::vector< colliderData_capsule > m_capsule
List of capsule colliders. Used for storing data to file
std::vector< colliderData_box > m_box
List of capsule colliders. Used for storing data to file
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Detailed Description
Definition at line 9 of file PhysicsObject.hpp.
Constructor & Destructor Documentation
PhysicsObject()
PhysicsObject::PhysicsObject () default
Default constructor for physics object.
Precondition
Nothing
Postcondition
Object created
Referenced by GameAssetFactory::loadPhysicsObject().
~PhysicsObject()
PhysicsObject::~PhysicsObject () default
default destructor
Member Function Documentation
add_draw_call()
void PhysicsObject::add_draw_call () override virtual
Adds draw call of object.
Precondition
Model initialised
Postcondition
Draw call added
Reimplemented from BodyRigid.
Reimplemented in NPC, and Projectile.
Definition at line 26 of file PhysicsObject.cpp.
{
     DrawCall draw_call = [=](std::shared_ptr<Shader> shader) { draw(shader); };
     ReflexEngine::get_instance().renderer_.add_draw_call(draw_call);
 }
draw()
void PhysicsObject::draw (std::shared_ptr< Shader > shader) override virtual
Draws the object.
Parameters
shader - The shader
Precondition
Model initialised
Postcondition
Model drawn
Reimplemented from BodyRigid.
Reimplemented in NPC, and Projectile.
Definition at line 32 of file PhysicsObject.cpp.
{
     auto default_shader = ReflexEngine::get_instance().renderer_.get_shader();
     glm::mat4 model(1.0f);
     model =
         glm::translate(model, glm::vec3(position.x, position.y, position.z));
     model = glm::rotate(model, glm::radians(angle),
                         glm::vec3(rotation.x, rotation.y, rotation.z));
     model = glm::scale(model, glm::vec3(scale.x, scale.y, scale.z));
     glUniformMatrix4fv(shader->GetModelLocation(), 1, GL_FALSE,
                        glm::value_ptr(model));
     glUniform1i(shader->GetUsingTexture(), true);
     auto& material_m = ResourceManager::get_instance().get_material_manager();
     material_m.get_material(material_name_)
         .UseMaterial(default_shader->GetShininessLocation(),
                      default_shader->GetSpecularIntensityLocation());
     auto& model_m = ResourceManager::get_instance().get_model_manager();
     model_m.get_model(model_name_).RenderModel();
 }
References ResourceManager::get_instance(), ResourceManager::get_material_manager(), and ResourceManager::get_model_manager().
fixed_update()
void PhysicsObject::fixed_update (double delta_time) override virtual
Updates the body object with fixed delta time.
Parameters
delta_time
Reimplemented from BodyRigid.
Reimplemented in NPC, and Projectile.
Definition at line 21 of file PhysicsObject.cpp.
{
     // position.y = GenericFunctions::getHeight(position.x, position.z);
     // rb.set_position(position);
 }
initModel()
void PhysicsObject::initModel (const std::string & model_name, const std::string & material_name)
Initialised the model.
Parameters
model_name name of model
material_name name of material
Precondition
Object exists
Postcondition
model initialised
Definition at line 5 of file PhysicsObject.cpp.
{
     model_name_ = model_name;
     material_name_ = material_name;
 }
initRB()
void PhysicsObject::initRB (glm::vec3 pos, glm::vec3 rotation, float angle)
Initialised the rigid body.
Parameters
pos - position of the rigid body
rotation - axis of rotation of the rigid body
angle - Rotation around axis of rotation of rigid body
Precondition
Object exists
Postcondition
rigid body initialised
Definition at line 11 of file PhysicsObject.cpp.
{
     rb.init(pos, rotation, angle);
 }
save_object()
void PhysicsObject::save_object () override virtual
Saves the object to lau file.
Precondition
Object exists
Postcondition
Object saved
Reimplemented from BodyRigid.
Reimplemented in NPC, and Projectile.
Definition at line 124 of file PhysicsObject.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle + 0.01,
                                  "PhysicsObject");
     ObjectSaving::addComma();
     ObjectSaving::addValue("modelName", model_name_, false);
     ObjectSaving::addValue("material_name", material_name_, false);
     ObjectSaving::addValue("rbType", rb.getRBType(), false);
     ObjectSaving::addValue("gravity", (int)rb.getIfGravityActive(), false);
     ObjectSaving::addValue("xForce", rb.getLinearVelocity().x, false);
     ObjectSaving::addValue("yForce", rb.getLinearVelocity().y, false);
     ObjectSaving::addValue("zForce", rb.getLinearVelocity().z, false);
     ObjectSaving::addValue("xTorque", rb.getAngularVelocity().x, false);
     ObjectSaving::addValue("yTorque", rb.getAngularVelocity().y, false);
     ObjectSaving::addValue("zTorque", rb.getAngularVelocity().z, false);
     ObjectSaving::addValue("linearDamping", rb.getLinearDamping(), false);
     ObjectSaving::addValue("angularDamping", rb.getAngularDamping(), false);
     ObjectSaving::addValue("sleep", (int)rb.getIfAllowedSleep(), false);
     ObjectSaving::addValue("numOfColliders", rb.getNumberOfColliders(), true);
     ObjectSaving::closeStruct();
     for (size_t count = 0; count < rb.getNumberOfColliders(); count++) {
         int type = rb.getColliderType(count);
         ObjectSaving::createStruct("collider" + std::to_string(count + 1));
         saveCollider(count, type);
         ObjectSaving::closeStruct();
     }
     ObjectSaving::closeFile();
 }
References ObjectSaving::addComma(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), and ObjectSaving::openFile().
saveBoxCollider()
void PhysicsObject::saveBoxCollider (size_t index) protected
Saves the box collider of rb.
Parameters
index - Which collider to save
Precondition
Collider exists
Postcondition
Collider stored
Definition at line 74 of file PhysicsObject.cpp.
{
     for (const auto& box : m_box) {
         if (box.m_colliderStored == index) {
             ObjectSaving::addValue("xBox", box.m_size.x, false);
             ObjectSaving::addValue("yBox", box.m_size.y, false);
             ObjectSaving::addValue("zBox", box.m_size.z, false);
             return;
         }
     }
 }
Referenced by saveCollider().
saveCapsuleCollider()
void PhysicsObject::saveCapsuleCollider (size_t index) protected
Saves the capsule collider of rb.
Parameters
index - Which collider to save
Precondition
Collider exists
Postcondition
Collider stored
Definition at line 64 of file PhysicsObject.cpp.
{
     for (const auto& capsule : m_capsule) {
         if (capsule.m_colliderStored == index) {
             ObjectSaving::addValue("radius", capsule.m_radius, false);
             ObjectSaving::addValue("height", capsule.m_height, false);
             return;
         }
     }
 }
Referenced by saveCollider().
saveCollider()
void PhysicsObject::saveCollider (size_t index, int type) protected
Saves the collider of rb.
Parameters
index - Which collider to save
type - The type of collider
Precondition
Collider exists
Postcondition
Collider stored
Definition at line 85 of file PhysicsObject.cpp.
{
     std::string typeString;
     switch (type) {
         case 1:
             typeString = "Sphere";
             break;
         case 2:
             typeString = "Capsule";
             break;
         case 3:
             typeString = "Box";
             break;
         default:
             break;
     }
     ObjectSaving::addValue("colliderType", typeString, false);
     ObjectSaving::addValue("xPos", rb.getLocalColliderPos(index).x, false);
     ObjectSaving::addValue("yPos", rb.getLocalColliderPos(index).y, false);
     ObjectSaving::addValue("zPos", rb.getLocalColliderPos(index).z, false);
     switch (type) {
         case 1:
             saveSphereCollider(index);
             break;
         case 2:
             saveCapsuleCollider(index);
             break;
         case 3:
             saveBoxCollider(index);
             break;
         default:
             break;
     }
     ObjectSaving::addValue("bounciness", rb.getBounciness(index), false);
     ObjectSaving::addValue("friction", rb.getFriction(index), true);
 }
References saveBoxCollider(), saveCapsuleCollider(), and saveSphereCollider().
saveSphereCollider()
void PhysicsObject::saveSphereCollider (size_t index) protected
Saves the sphere collider of rb.
Parameters
index - Which collider to save
Precondition
Collider exists
Postcondition
Collider stored
Definition at line 55 of file PhysicsObject.cpp.
{
     for (const auto& sphere : m_sphere) {
         if (sphere.m_colliderStored == index) {
             ObjectSaving::addValue("radius", sphere.m_radius, false);
             return;
         }
     }
 }
Referenced by saveCollider().
update()
void PhysicsObject::update (double delta_time) override virtual
Updates the object.
Parameters
delta_time - Time since last frame
Precondition
rigid body initialised
Postcondition
Object updated
Reimplemented from BodyRigid.
Reimplemented in NPC, and Projectile.
Definition at line 15 of file PhysicsObject.cpp.
{
     position = rb.getPosition();
     rotation = rb.getRotation();
     angle = rb.getAngle();
 }
Member Data Documentation
material_name_
std::string PhysicsObject::material_name_ protected
The material of the item.
Definition at line 91 of file PhysicsObject.hpp.
model_name_
std::string PhysicsObject::model_name_ protected
The model of the item.
Definition at line 89 of file PhysicsObject.hpp.
The documentation for this class was generated from the following files:
src/Model/GameObject/PhysicsObject.hpp
src/Model/GameObject/PhysicsObject.cpp