ICT397 Assignment 2: OpenGL Class Reference
OpenGL Class Reference
The OpenGL renderer.
#include <OpenGL.hpp>
Public Member Functions
OpenGL ()=default
Default constructor.
void init () override
Initializes OpenGL, shaders, camera and the skybox.
void draw () override
Draws the scene.
void toggle_wireframe () override
Toggles between normal and wireframe rendering.
std::shared_ptr< Shader > get_shader ()
Getter for the default shader object.
void set_skybox (const std::vector< std::string > &faces)
Set the skybox with given texture paths to faces.
void add_directional_light (const DirectionalLightData &light_data)
Adds a directional light to the renderer.
void add_point_light (const PointLightData &light_data)
Adds a point light to the renderer.
void add_spot_light (const SpotLightData &light_data)
Adds a spot light to the renderer.
void add_draw_call (const DrawCall &draw_call)
Adds a draw call to the renderer.
Public Member Functions inherited from Renderer
virtual ~Renderer ()=default
Destructor.
Private Member Functions
void render_scene (std::shared_ptr< Shader > shader)
Renders the draw calls using the shader given by parameter.
void render_lights ()
Enable and render lights.
void render_pass ()
The default render pass using the default shader.
void directional_shadow_pass (const DirectionalLight &d_light)
The directional shadow pass using the directional shadow shader.
Private Attributes
bool is_wireframe_ = false
A boolean to toggle between wireframe and normal rendering.
Skybox skybox_ = {}
The skybox.
std::vector< DirectionalLight > directional_lights_
A vector of directional lights.
std::vector< PointLight > point_lights_
An vector of point lights.
std::vector< SpotLight > spot_lights_
An vector of spot lights.
std::vector< DrawCall > draw_calls_ = {}
A vector of draw calls.
std::shared_ptr< Shader > shader_ = nullptr
The default shader.
std::shared_ptr< Shader > directional_shadow_shader_ = nullptr
The directional shadow shader.
std::shared_ptr< Shader > omni_shadow_shader_ = nullptr
The directional shadow map.
Detailed Description
The OpenGL renderer.
Definition at line 20 of file OpenGL.hpp.
Constructor & Destructor Documentation
OpenGL()
OpenGL::OpenGL () default
Default constructor.
Member Function Documentation
add_directional_light()
void OpenGL::add_directional_light (const DirectionalLightData & light_data)
Adds a directional light to the renderer.
Parameters
light_data
Definition at line 137 of file OpenGL.cpp.
{
     directional_lights_.emplace_back(
         DirectionalLight(2048, 2048, light.color, light.ambient_intensity,
                          light.direction, light.diffuse_intensity));
 }
add_draw_call()
void OpenGL::add_draw_call (const DrawCall & draw_call)
Adds a draw call to the renderer.
Parameters
draw_call
Definition at line 163 of file OpenGL.cpp.
{
     draw_calls_.emplace_back(draw_call);
 }
add_point_light()
void OpenGL::add_point_light (const PointLightData & light_data)
Adds a point light to the renderer.
Parameters
light_data
Definition at line 143 of file OpenGL.cpp.
{
     if (point_lights_.size() < MAX_POINT_LIGHTS) {
         point_lights_.emplace_back(PointLight(
             2048, 2048, 0.01f, 100.0f, light_data.color,
             light_data.ambient_intensity, light_data.diffuse_intensity,
             light_data.position, light_data.constant, light_data.linear,
             light_data.quadratic));
     }
 }
add_spot_light()
void OpenGL::add_spot_light (const SpotLightData & light_data)
Adds a spot light to the renderer.
Parameters
light_data
Definition at line 153 of file OpenGL.cpp.
{
     if (spot_lights_.size() < MAX_SPOT_LIGHTS) {
         spot_lights_.emplace_back(SpotLight(
             2048, 2048, 0.01f, 100.0f, light_data.color,
             light_data.ambient_intensity, light_data.diffuse_intensity,
             light_data.position, light_data.direction, light_data.constant,
             light_data.linear, light_data.quadratic, light_data.edge));
     }
 }
directional_shadow_pass()
void OpenGL::directional_shadow_pass (const DirectionalLight & d_light) private
The directional shadow pass using the directional shadow shader.
Parameters
d_light
Definition at line 103 of file OpenGL.cpp.
{
     directional_shadow_shader_->UseShader();
     glViewport(0, 0, d_light.GetShadowMap()->GetShadowWidth(),
                d_light.GetShadowMap()->GetShadowHeight());
     d_light.GetShadowMap()->Write();
     glClear(GL_DEPTH_BUFFER_BIT);
     directional_shadow_shader_->SetDirectionalLightTransform(
         d_light.CalculateLightTransform());
     directional_shadow_shader_->Validate();
     render_scene(directional_shadow_shader_);
     glBindFramebuffer(GL_FRAMEBUFFER, 0);
 }
draw()
void OpenGL::draw () override virtual
Draws the scene.
Implements Renderer.
Definition at line 40 of file OpenGL.cpp.
                   {
     render_pass();
     directional_lights_.clear();
     point_lights_.clear();
     spot_lights_.clear();
     draw_calls_.clear();
 }
References render_pass().
get_shader()
std::shared_ptr< Shader > OpenGL::get_shader ()
Getter for the default shader object.
Returns
std::shared_ptr<Shader>
Definition at line 131 of file OpenGL.cpp.
 { return shader_; }
init()
void OpenGL::init () override virtual
Initializes OpenGL, shaders, camera and the skybox.
Implements Renderer.
Definition at line 5 of file OpenGL.cpp.
                   {
     auto& engine = ReflexEngine::get_instance();
     if (!gladLoadGLLoader(reinterpret_cast<GLADloadproc>(glfwGetProcAddress))) {
         std::cout << "Failed to initialize GLAD" << std::endl;
     }
     glViewport(0, 0, engine.window_.get_buffer_width(),
                engine.window_.get_buffer_height());
     //
     // Enable depth testing.
     glEnable(GL_DEPTH_TEST);
     // Enable face culling.
     glEnable(GL_CULL_FACE);
     // Enable blending. (For transparency)
     glEnable(GL_BLEND);
     glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     // Default shader.
     shader_ = std::make_shared<Shader>();
     shader_->CompileFile("shaders/shader.vert", "shaders/shader.frag");
     // Directional shadow shader.
     directional_shadow_shader_ = std::make_shared<Shader>();
     directional_shadow_shader_->CompileFile(
         "shaders/directional_shadow_map.vert",
         "shaders/directional_shadow_map.frag");
     // Omni shadow shader.
     omni_shadow_shader_ = std::make_shared<Shader>();
     omni_shadow_shader_->CompileFile("shaders/omni_shadow_map.vert",
                                      "shaders/omni_shadow_map.geom",
                                      "shaders/omni_shadow_map.frag");
 }
References ReflexEngine::get_instance().
render_lights()
void OpenGL::render_lights () private
Enable and render lights.
Definition at line 88 of file OpenGL.cpp.
{
     for (const auto& d_light : directional_lights_) {
         shader_->SetDirectionalLight(d_light);
     }
     shader_->SetPointLights(point_lights_.data(), point_lights_.size(), 3, 0);
     shader_->SetSpotLights(spot_lights_.data(), spot_lights_.size(),
                            3 + point_lights_.size(), point_lights_.size());
     shader_->SetTexture(1);
     shader_->SetDirectionalShadowMap(2);
     shader_->set_detail_map(3);
 }
Referenced by render_pass().
render_pass()
void OpenGL::render_pass () private
The default render pass using the default shader.
Definition at line 55 of file OpenGL.cpp.
{
     auto& engine = ReflexEngine::get_instance();
     glViewport(0, 0, engine.window_.get_buffer_width(),
                engine.window_.get_buffer_height());
     glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     glm::mat4 projection = glm::perspective(
         glm::radians(60.0f), engine.window_.get_ratio(), 0.1f, 1000.0f);
     glm::mat4 view = engine.camera_.calc_view_matrix();
     // Creates projection matrix mode
     glUniformMatrix4fv(shader_->GetProjectionLocation(), 1, GL_FALSE,
                        glm::value_ptr(projection));
     // Create view matrix mode
     glUniformMatrix4fv(shader_->GetViewLocation(), 1, GL_FALSE,
                        glm::value_ptr(view));
     skybox_.DrawSkybox(projection, view);
     shader_->UseShader();
     render_lights();
     shader_->Validate();
     render_scene(shader_);
 }
References ReflexEngine::get_instance(), and render_lights().
Referenced by draw().
render_scene()
void OpenGL::render_scene (std::shared_ptr< Shader > shader) private
Renders the draw calls using the shader given by parameter.
Parameters
shader
Definition at line 49 of file OpenGL.cpp.
{
     for (const auto& draw_call : draw_calls_) {
         draw_call(shader);
     }
 }
set_skybox()
void OpenGL::set_skybox (const std::vector< std::string > & faces)
Set the skybox with given texture paths to faces.
Parameters
faces
Definition at line 133 of file OpenGL.cpp.
{
     skybox_ = Skybox(faces);
 }
toggle_wireframe()
void OpenGL::toggle_wireframe () override virtual
Toggles between normal and wireframe rendering.
Implements Renderer.
Definition at line 122 of file OpenGL.cpp.
{
     is_wireframe_ = !is_wireframe_;
     if (is_wireframe_)
         glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
     else
         glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
 }
References is_wireframe_.
Member Data Documentation
directional_lights_
std::vector<DirectionalLight> OpenGL::directional_lights_ private
A vector of directional lights.
Definition at line 116 of file OpenGL.hpp.
directional_shadow_shader_
std::shared_ptr<Shader> OpenGL::directional_shadow_shader_ = nullptr private
The directional shadow shader.
Definition at line 131 of file OpenGL.hpp.
draw_calls_
std::vector<DrawCall> OpenGL::draw_calls_ = {} private
A vector of draw calls.
Definition at line 125 of file OpenGL.hpp.
is_wireframe_
bool OpenGL::is_wireframe_ = false private
A boolean to toggle between wireframe and normal rendering.
Definition at line 110 of file OpenGL.hpp.
Referenced by toggle_wireframe().
omni_shadow_shader_
std::shared_ptr<Shader> OpenGL::omni_shadow_shader_ = nullptr private
The directional shadow map.
Definition at line 134 of file OpenGL.hpp.
point_lights_
std::vector<PointLight> OpenGL::point_lights_ private
An vector of point lights.
Definition at line 119 of file OpenGL.hpp.
shader_
std::shared_ptr<Shader> OpenGL::shader_ = nullptr private
The default shader.
Definition at line 128 of file OpenGL.hpp.
skybox_
Skybox OpenGL::skybox_ = {} private
The skybox.
Definition at line 113 of file OpenGL.hpp.
spot_lights_
std::vector<SpotLight> OpenGL::spot_lights_ private
An vector of spot lights.
Definition at line 122 of file OpenGL.hpp.
The documentation for this class was generated from the following files:
src/View/Renderer/OpenGL/OpenGL.hpp
src/View/Renderer/OpenGL/OpenGL.cpp