ICT397 Assignment 2: ScriptableObject Class Reference
ScriptableObject Class Reference
#include <ScriptableObject.hpp>
Public Member Functions
ScriptableObject (const std::string &script)
Default constructor.
void init () override
initialisation of game object. Not needed
void update (double delta_time) override
Updates the object by running the lua script.
void fixed_update (double delta_time) override
Updates the body object with fixed delta time.
void add_draw_call () override
Adds a draw call. Not used.
void draw (std::shared_ptr< Shader > shader) override
Draws the object. Not used.
void save_object () override
Saves the object to lau file.
~ScriptableObject ()
Destructor.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
std::string scriptPath
Lua script to run every update frame
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Detailed Description
Definition at line 7 of file ScriptableObject.hpp.
Constructor & Destructor Documentation
ScriptableObject()
ScriptableObject::ScriptableObject (const std::string & script)
Default constructor.
Parameters
script - The script to run every update frame
Precondition
Nothing
Postcondition
Script added to run
Definition at line 3 of file ScriptableObject.cpp.
{
     scriptPath = script;
 }
References scriptPath.
~ScriptableObject()
ScriptableObject::~ScriptableObject () inline
Destructor.
Precondition
Object exists
Postcondition
Object deleted
Definition at line 73 of file ScriptableObject.hpp.
 {};
Member Function Documentation
add_draw_call()
void ScriptableObject::add_draw_call () inline override virtual
Adds a draw call. Not used.
Precondition
object exists
Postcondition
Nothing
Implements GameObject.
Definition at line 48 of file ScriptableObject.hpp.
 {}
draw()
void ScriptableObject::draw (std::shared_ptr< Shader > shader) inline override virtual
Draws the object. Not used.
Parameters
shader - The shader
Precondition
Object exists
Postcondition
Nothing
Implements GameObject.
Definition at line 57 of file ScriptableObject.hpp.
 {}
fixed_update()
void ScriptableObject::fixed_update (double delta_time) inline override virtual
Updates the body object with fixed delta time.
Parameters
delta_time The time since the last fixed tick.
Implements GameObject.
Definition at line 40 of file ScriptableObject.hpp.
 {}
init()
void ScriptableObject::init () inline override virtual
initialisation of game object. Not needed
Precondition
object exists
Postcondition
Nothing
Implements GameObject.
Definition at line 24 of file ScriptableObject.hpp.
 {}
save_object()
void ScriptableObject::save_object () override virtual
Saves the object to lau file.
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 13 of file ScriptableObject.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle,
                                  "ScriptableObject");
     ObjectSaving::closeStruct();
     ObjectSaving::addValue("script", scriptPath, true);
     ObjectSaving::closeFile();
 }
References ObjectSaving::addValue(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), ObjectSaving::openFile(), and scriptPath.
update()
void ScriptableObject::update (double delta_time) override virtual
Updates the object by running the lua script.
Parameters
delta_time - The time between frames
Precondition
lua script stored
Postcondition
Script run
Implements GameObject.
Definition at line 7 of file ScriptableObject.cpp.
{
     sol::state& lua = LuaManager::get_instance().get_state();
     lua.script_file(scriptPath);
 }
Member Data Documentation
scriptPath
std::string ScriptableObject::scriptPath private
Lua script to run every update frame
Definition at line 73 of file ScriptableObject.hpp.
Referenced by save_object(), and ScriptableObject().
The documentation for this class was generated from the following files:
src/Model/GameObject/ScriptableObject.hpp
src/Model/GameObject/ScriptableObject.cpp