ICT397 Assignment 2: InputManager Class Reference
InputManager Class Reference
A singleton class that manages input bindings.
#include <InputManager.hpp>
Public Member Functions
void load_lua_bindings (const std::string &file_path)
Load the bindings from a Lua file.
void bind_key (Input input, int key)
Bind an input action to a key.
void read_keys (GLFWwindow *window)
Read the key states.
InputState get_key_state (Input input)
Return the key state of an input action.
InputManager (InputManager &other)=delete
InputManager (const InputManager &other)=delete
void operator= (InputManager &&)=delete
void operator= (const InputManager &)=delete
Static Public Member Functions
static InputManager & get_instance ()
Get the instance.
Private Member Functions
void init_bind_map ()
Initialize bind map.
void init_action_map ()
Initialize action map.
InputManager ()
Construct a new Input Manager object.
Private Attributes
std::unordered_map< Input, int > key_map
A map of input actions to keys.
std::unordered_map< std::string, Input > action_map
A map of lua action to input actions.
std::unordered_map< std::string, int > bind_map
A map of lua keys to GLFW keys.
InputState key_states [GLFW_KEY_LAST]
A boolean array of key states.
Detailed Description
A singleton class that manages input bindings.
Definition at line 14 of file InputManager.hpp.
Constructor & Destructor Documentation
InputManager() [1/3]
InputManager::InputManager (InputManager & other) delete
InputManager() [2/3]
InputManager::InputManager (const InputManager & other) delete
InputManager() [3/3]
InputManager::InputManager () private
Construct a new Input Manager object.
Definition at line 81 of file InputManager.cpp.
{
     init_bind_map();
     init_action_map();
 }
References init_action_map(), and init_bind_map().
Member Function Documentation
bind_key()
void InputManager::bind_key (Input input, int key)
Bind an input action to a key.
Parameters
input The input
key The key to bind
Definition at line 34 of file InputManager.cpp.
 { key_map[input] = key; }
get_instance()
InputManager & InputManager::get_instance () static
Get the instance.
Returns
InputManager&
Definition at line 7 of file InputManager.cpp.
{
     static InputManager instance;
     return instance;
 }
Referenced by TestScene::key_controls(), and ReflexEngine::run().
get_key_state()
InputState InputManager::get_key_state (Input input)
Return the key state of an input action.
Parameters
input Input
Returns
InputState
Definition at line 46 of file InputManager.cpp.
{
     return key_states[key_map[input]];
 }
Referenced by TestScene::key_controls().
init_action_map()
void InputManager::init_action_map () private
Initialize action map.
Definition at line 64 of file InputManager.cpp.
{
     action_map["quit"] = Input::quit;
     action_map["move_forward"] = Input::move_forward;
     action_map["move_backward"] = Input::move_backward;
     action_map["move_left"] = Input::move_left;
     action_map["move_right"] = Input::move_right;
     action_map["sprint"] = Input::sprint;
     action_map["crouch"] = Input::crouch;
     action_map["shoot"] = Input::shoot;
     action_map["toggle_wireframe"] = Input::toggle_wireframe;
     action_map["toggle_noclip"] = Input::toggle_noclip;
     action_map["pause_game"] = Input::pause_game;
     action_map["help_menu"] = Input::help_menu;
     action_map["network_menu"] = Input::network_menu;
     action_map["network_pvp_menu"] = Input::network_pvp_menu;
 }
Referenced by InputManager().
init_bind_map()
void InputManager::init_bind_map () private
Initialize bind map.
Definition at line 50 of file InputManager.cpp.
{
     bind_map["escape"] = GLFW_KEY_ESCAPE;
     bind_map["mouse1"] = GLFW_MOUSE_BUTTON_LEFT;
     bind_map["mouse2"] = GLFW_MOUSE_BUTTON_2;
     bind_map["mouse3"] = GLFW_MOUSE_BUTTON_3;
     bind_map["lshift"] = GLFW_KEY_LEFT_SHIFT;
     bind_map["rshift"] = GLFW_KEY_RIGHT_SHIFT;
     bind_map["lctrl"] = GLFW_KEY_LEFT_CONTROL;
     bind_map["rctrl"] = GLFW_KEY_RIGHT_CONTROL;
     bind_map["lalt"] = GLFW_KEY_LEFT_ALT;
     bind_map["ralt"] = GLFW_KEY_RIGHT_ALT;
     bind_map["space"] = GLFW_KEY_SPACE;
 }
Referenced by InputManager().
load_lua_bindings()
void InputManager::load_lua_bindings (const std::string & file_path)
Load the bindings from a Lua file.
Parameters
file_path The path to the Lua script.
Definition at line 12 of file InputManager.cpp.
{
     auto& lua = LuaManager::get_instance().get_state();
     lua.script_file(file_path);
     sol::table bindings = lua["Bindings"];
     for (const auto& binding : bindings) {
         std::string action = binding.first.as<std::string>();
         std::string bind = binding.second.as<std::string>();
         Input input = action_map[action];
         if (bind.length() > 1) {
             int key = bind_map[bind];
             bind_key(input, key);
         } else {
             int key = toupper(bind[0]);
             bind_key(input, key);
         }
     }
 }
Referenced by ReflexEngine::run().
operator=() [1/2]
void InputManager::operator= (const InputManager &) delete
operator=() [2/2]
void InputManager::operator= (InputManager &&) delete
read_keys()
void InputManager::read_keys (GLFWwindow * window)
Read the key states.
Parameters
window The window
Definition at line 36 of file InputManager.cpp.
{
     for (const auto& binding : key_map) {
         if (glfwGetKey(window, binding.second) == GLFW_PRESS) {
             key_states[key_map[binding.first]].set_key_state(GLFW_PRESS);
         } else if (glfwGetKey(window, binding.second) == GLFW_RELEASE) {
             key_states[key_map[binding.first]].set_key_state(GLFW_RELEASE);
         }
     }
 }
Member Data Documentation
action_map
std::unordered_map<std::string, Input> InputManager::action_map private
A map of lua action to input actions.
Definition at line 79 of file InputManager.hpp.
bind_map
std::unordered_map<std::string, int> InputManager::bind_map private
A map of lua keys to GLFW keys.
Definition at line 82 of file InputManager.hpp.
key_map
std::unordered_map<Input, int> InputManager::key_map private
A map of input actions to keys.
Definition at line 76 of file InputManager.hpp.
key_states
InputState InputManager::key_states[GLFW_KEY_LAST] private
A boolean array of key states.
Definition at line 85 of file InputManager.hpp.
The documentation for this class was generated from the following files:
src/Controller/Input/InputManager.hpp
src/Controller/Input/InputManager.cpp