ICT397 Assignment 2: SpotLightObject Class Reference
SpotLightObject Class Reference
A spot light game object.
#include <SpotLightObject.hpp>
Public Member Functions
SpotLightObject (const SpotLightData &light_data)
Construct a new Directional Light Object object.
void init () override
Initializes the game object.
void update (double delta_time) override
Updates the game object with delta time.
void fixed_update (double delta_time) override
Updates the game object with fixed delta time.
void add_draw_call () override
Adds a draw call to the renderer.
void draw (std::shared_ptr< Shader > shader) override
The draw call.
void save_object () override
Saves the object to lua file.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
SpotLightData light_data_
The spot light data.
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Detailed Description
A spot light game object.
Definition at line 10 of file SpotLightObject.hpp.
Constructor & Destructor Documentation
SpotLightObject()
SpotLightObject::SpotLightObject (const SpotLightData & light_data)
Construct a new Directional Light Object object.
Parameters
light_data The light data.
Definition at line 6 of file SpotLightObject.cpp.
     : light_data_(light_data) {}
References light_data_.
Referenced by GameAssetFactory::load_spot_light().
Member Function Documentation
add_draw_call()
void SpotLightObject::add_draw_call () override virtual
Adds a draw call to the renderer.
Implements GameObject.
Definition at line 9 of file SpotLightObject.cpp.
{
     auto& renderer = ReflexEngine::get_instance().renderer_;
     renderer.add_spot_light(light_data_);
 }
draw()
void SpotLightObject::draw (std::shared_ptr< Shader > shader) inline override virtual
The draw call.
Parameters
shader The shader to use.
Implements GameObject.
Definition at line 48 of file SpotLightObject.hpp.
 {}
fixed_update()
void SpotLightObject::fixed_update (double delta_time) inline override virtual
Updates the game object with fixed delta time.
Parameters
delta_time The time since the last fixed tick.
Implements GameObject.
Definition at line 36 of file SpotLightObject.hpp.
 {}
init()
void SpotLightObject::init () inline override virtual
Initializes the game object.
Implements GameObject.
Definition at line 22 of file SpotLightObject.hpp.
 {}
save_object()
void SpotLightObject::save_object () override virtual
Saves the object to lua file.
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 15 of file SpotLightObject.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "SpotLight");
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("light");
     ObjectSaving::createStruct("color");
     ObjectSaving::addValue("r", light_data_.color.x, false);
     ObjectSaving::addValue("g", light_data_.color.y, false);
     ObjectSaving::addValue("b", light_data_.color.z, true);
     ObjectSaving::closeStruct();
     ObjectSaving::addComma();
     ObjectSaving::addValue("ambient_intensity", light_data_.ambient_intensity,
                            false);
     ObjectSaving::addValue("diffuse_intensity", light_data_.diffuse_intensity,
                            false);
     ObjectSaving::createStruct("position");
     ObjectSaving::addValue("x", light_data_.position.x, false);
     ObjectSaving::addValue("y", light_data_.position.y, false);
     ObjectSaving::addValue("z", light_data_.position.z, true);
     ObjectSaving::closeStruct();
     ObjectSaving::addComma();
     ObjectSaving::addValue("constant", light_data_.constant, false);
     ObjectSaving::addValue("linear", light_data_.linear, false);
     ObjectSaving::addValue("quadratic", light_data_.quadratic, false);
     ObjectSaving::createStruct("direction");
     ObjectSaving::addValue("x", light_data_.direction.x, false);
     ObjectSaving::addValue("y", light_data_.direction.y, false);
     ObjectSaving::addValue("z", light_data_.direction.z, true);
     ObjectSaving::closeStruct();
     ObjectSaving::addComma();
     ObjectSaving::addValue("edge", light_data_.edge, true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::addComma(), ObjectSaving::addValue(), LightData::ambient_intensity, GameObject::angle, ObjectSaving::closeFile(), ObjectSaving::closeStruct(), LightData::color, PointLightData::constant, ObjectSaving::createStruct(), LightData::diffuse_intensity, SpotLightData::direction, SpotLightData::edge, light_data_, PointLightData::linear, ObjectSaving::openFile(), GameObject::position, PointLightData::position, PointLightData::quadratic, GameObject::rotation, ObjectSaving::saveGameObject(), and GameObject::scale.
update()
void SpotLightObject::update (double delta_time) inline override virtual
Updates the game object with delta time.
Parameters
delta_time The time since the last frame.
Implements GameObject.
Definition at line 29 of file SpotLightObject.hpp.
 {}
Member Data Documentation
light_data_
SpotLightData SpotLightObject::light_data_ private
The spot light data.
Definition at line 60 of file SpotLightObject.hpp.
Referenced by save_object(), and SpotLightObject().
The documentation for this class was generated from the following files:
src/Model/GameObject/SpotLightObject.hpp
src/Model/GameObject/SpotLightObject.cpp