ICT397 Assignment 2: world Class Reference
world Class Reference
#include <world.hpp>
Public Member Functions
void setWorld (TexturedTerrain *tt)
Sets the world.
void show_world ()
Prints the current pathfinding grid to the terrminal.
void setMinMaxHeight (float min, float max)
Sets the min & max height for the playable area for the NPC's.
void create_sphere_obstruction (float posX, float posZ, float radius)
Create a sphere obstruction on the pathfinding grid.
void create_box_obstruction (float posX, float posZ, float xSize, float zSize)
Create a box obstruction on the pathfinding grid.
float get_height (float x, float z)
Gets the height (y) coordinate based on x & z.
std::queue< glm::vec2 > pathFinding (float currX, float currZ, float targetX, float targetZ)
Generates a queue of vector 2 using the pathfinding algorithm between two points.
~world ()
Destructor.
Private Member Functions
void create_grid (std::vector< std::vector< int >> &grid)
Creates the grid for the pathfinding algorithm.
Private Attributes
AStar m_aStar
The a* interface whch holds the level's grid.
TexturedTerrain * m_tt
The textures terrain used as a base (NOT USED CURRENTLY)
float m_min_height = 2.5
The minimum height allowed.
float m_max_height = 9999
The maximum height allowed.
Detailed Description
Definition at line 11 of file world.hpp.
Constructor & Destructor Documentation
~world()
world::~world ()
Destructor.
Definition at line 160 of file world.cpp.
               {  // delete m_tt;
 }
Member Function Documentation
create_box_obstruction()
void world::create_box_obstruction (float posX, float posZ, float xSize, float zSize)
Create a box obstruction on the pathfinding grid.
Parameters
posX - The x position of the object
posZ - The z position of the object
xSize - The HALF size of the box in the x direction
zSize - The HALF size of the box in the z direction
Definition at line 73 of file world.cpp.
{
     std::vector<std::vector<int>> grid = m_aStar.getGrid();
     glm::vec2 pos =
         glm::vec2(posX / m_tt->get_scale().x, posZ / m_tt->get_scale().z);
     xSize = std::ceil(xSize / m_tt->get_scale().x);
     zSize = std::ceil(zSize / m_tt->get_scale().z);
     int startY = pos.y - zSize;
     int endY = pos.y + zSize;
     if (startY < 0) {
         startY = 0;
     }
     if (endY > m_tt->get_length() - 1) {
         endY = m_tt->get_length() - 1;
     }
     int startX = pos.x - xSize;
     int endX = pos.x + xSize;
     if (startX < 0) {
         startX = 0;
     }
     if (endX > m_tt->get_width() - 1) {
         startX = m_tt->get_length() - 1;
     }
     for (int y = startY; y < endY; y++) {
         for (int x = startX; x < endX; x++) {
             grid[y][x] = 1;
         }
     }
     m_aStar.setGrid(grid);
 }
create_grid()
void world::create_grid (std::vector< std::vector< int >> & grid) private
Creates the grid for the pathfinding algorithm.
Definition at line 163 of file world.cpp.
{
     float height = 0;
     int gridValue = 0;
     std::vector<int> gridRow;
     for (int z = 0; z < m_tt->get_length(); z++) {
         gridRow.clear();
         for (int x = 0; x < m_tt->get_width(); x++) {
             gridValue = 0;
             height = GenericFunctions::getHeight(x, z);
             // Check if within min & max heights
             if (height < m_min_height || height > m_max_height) {
                 gridValue = 1;
             } else {
                 // Also check for objects
                 // gridValue = checkIfNotInObject(x, z);
             }
             // std::cout << gridValue;
             gridRow.push_back(gridValue);
         }
         // std::cout << std::endl;
         grid.push_back(gridRow);
     }
 }
create_sphere_obstruction()
void world::create_sphere_obstruction (float posX, float posZ, float radius)
Create a sphere obstruction on the pathfinding grid.
Parameters
posX - The x position of the object
posZ - The z position of the object
radius - The radius of the object
Definition at line 34 of file world.cpp.
{
     std::vector<std::vector<int>> grid = m_aStar.getGrid();
     float checkRadius = radius / m_tt->get_scale().x;
     glm::vec2 pos =
         glm::vec2(posX / m_tt->get_scale().x, posZ / m_tt->get_scale().z);
     float distance = 0;
     checkRadius = std::ceil(checkRadius);
     int startY = pos.y - checkRadius;
     int endY = pos.y + checkRadius;
     if (startY < 0) {
         startY = 0;
     }
     if (endY > m_tt->get_length() - 1) {
         endY = m_tt->get_length() - 1;
     }
     int startX = pos.x - checkRadius;
     int endX = pos.x + checkRadius;
     if (startX < 0) {
         startX = 0;
     }
     if (endX > m_tt->get_width() - 1) {
         startX = m_tt->get_length() - 1;
     }
     for (int y = startY; y < endY; y++) {
         for (int x = startX; x < endX; x++) {
             distance = glm::length(pos - glm::vec2(x, y));
             if (distance < radius) {
                 grid[y][x] = 1;
             }
         }
     }
     m_aStar.setGrid(grid);
 }
get_height()
float world::get_height (float x, float z)
Gets the height (y) coordinate based on x & z.
Parameters
x - The x position
z - The z position
Definition at line 109 of file world.cpp.
 { return m_tt->get_height(x, z); }
pathFinding()
std::queue< glm::vec2 > world::pathFinding (float currX, float currZ, float targetX, float targetZ)
Generates a queue of vector 2 using the pathfinding algorithm between two points.
Parameters
currX - The current x position
currZ - The current z position
targetX - The x target position
targetZ - The z target position
Definition at line 111 of file world.cpp.
{
     std::queue<glm::vec2> path;
     std::vector<glm::vec2> inversePath;
     std::vector<std::vector<DistanceNode>> rawPath;
     try {
         rawPath = m_aStar.findPath((int)currX, (int)currZ, (int)targetX,
                                    (int)targetZ);
     } catch (AStarExceptions error) {
         // m_aStar.printAstarException(error);
         return path;
     }
     glm::vec2 end = glm::vec2(targetX, targetZ);
     int temp;
     int numberOfIt = 0;
     bool running = true;
     while (running) {
         if ((int)currX == end.x && (int)currZ == end.y) {
             running = false;
         } else if (numberOfIt == 10000) {
             std::cout << "failed a*pathfinding" << std::endl;
             return path;
         }
         // std::cout << "Node: y = " << targetZ << " x = " << targetX
         //           << " cost = " << rawPath[end.y][end.x].f
         //           << " Parent: y: " << rawPath[end.y][end.x].parentNode.y
         //           << " x: " << rawPath[end.y][end.x].parentNode.x <<
         //           std::endl;
         inversePath.push_back(glm::vec2(end.x * m_tt->get_scale().x,
                                         end.y * m_tt->get_scale().z));
         temp = end.x;
         end.x = rawPath[end.y][end.x].parentNode.x;
         end.y = rawPath[end.y][temp].parentNode.y;
         numberOfIt++;
     }
     for (int count = inversePath.size() - 2; count >= 0; count--) {
         path.push(inversePath[count]);
     }
     return path;
 }
setMinMaxHeight()
void world::setMinMaxHeight (float min, float max)
Sets the min & max height for the playable area for the NPC's.
Parameters
min - The min height allowed e.g., set lower limit above water.
max - The max height allowed
Definition at line 24 of file world.cpp.
{
     m_min_height = min;
     m_max_height = max;
     if (m_min_height > m_max_height) {
         std::cerr << "world - setMinMaxHeight - min is greater than max - "
                   << m_min_height << " vs " << m_max_height;
     }
 }
References m_max_height, and m_min_height.
setWorld()
void world::setWorld (TexturedTerrain * tt)
Sets the world.
Parameters
tt - The texture terrain to use as a grid base
Definition at line 3 of file world.cpp.
{
     m_tt = tt;
     std::vector<std::vector<int>> grid;
     create_grid(grid);
     m_aStar.setGrid(grid);
     m_aStar.setAllowDiagonalMovement(true);
     m_aStar.setHeuristicsCostScale(1.5);
     m_aStar.setMaxDistance(100);
 }
References m_aStar, m_tt, AStar::setAllowDiagonalMovement(), AStar::setHeuristicsCostScale(), and AStar::setMaxDistance().
show_world()
void world::show_world ()
Prints the current pathfinding grid to the terrminal.
Definition at line 14 of file world.cpp.
{
     std::vector<std::vector<int>> gsa = m_aStar.getGrid();
     for (int count = gsa.size() - 1; count >= 0; count--) {
         for (int x = gsa[count].size() - 1; x >= 0; x--) {
             std::cout << gsa[count][x];
         }
         std::cout << std::endl;
     }
 }
Member Data Documentation
m_aStar
AStar world::m_aStar private
The a* interface whch holds the level's grid.
Definition at line 74 of file world.hpp.
Referenced by setWorld().
m_max_height
float world::m_max_height = 9999 private
The maximum height allowed.
Definition at line 81 of file world.hpp.
Referenced by setMinMaxHeight().
m_min_height
float world::m_min_height = 2.5 private
The minimum height allowed.
Definition at line 79 of file world.hpp.
Referenced by setMinMaxHeight().
m_tt
TexturedTerrain* world::m_tt private
The textures terrain used as a base (NOT USED CURRENTLY)
Definition at line 76 of file world.hpp.
Referenced by setWorld().
The documentation for this class was generated from the following files:
src/Controller/Pathfinding/world.hpp
src/Controller/Pathfinding/world.cpp