My Project: Model Class Reference
Model Class Reference
A model class representing a Mesh with a texture. Models are loaded in using the 3D object library Assimp.
#include <Model.hpp>
Public Member Functions
Model ()
Construct a new Model object.
bool LoadModel (const std::string &fileName)
Loads a new model from a 3D object file format.
void RenderModel () const
Renders the model.
void ClearModel ()
Clears the model.
~Model ()
Destroy the Model object.
Private Member Functions
void LoadNode (aiNode *node, const aiScene *scene)
Recursive function to traverse the node and load the meshes.
void LoadMesh (aiMesh *mesh, const aiScene *scene)
Loads in a mesh.
void LoadMaterials (const aiScene *scene)
Loads in the material/texture.
Private Attributes
std::vector< Mesh * > m_meshVec
A vector of the meshes.
std::vector< Texture * > m_textureVec
A vector of the textures.
std::vector< GLuint > m_meshToTex
A vector of the mesh to texture mapping.
Detailed Description
A model class representing a Mesh with a texture. Models are loaded in using the 3D object library Assimp.
Definition at line 18 of file Model.hpp.
Constructor & Destructor Documentation
Model()
Model::Model ()
Construct a new Model object.
Definition at line 3 of file Model.cpp.
 {}
Referenced by ModelManager::load_model().
~Model()
Model::~Model ()
Destroy the Model object.
Definition at line 136 of file Model.cpp.
 { ClearModel(); }
References ClearModel().
Member Function Documentation
ClearModel()
void Model::ClearModel ()
Clears the model.
Definition at line 120 of file Model.cpp.
{
     for (auto& mesh : m_meshVec) {
         if (mesh) {
             delete mesh;
             mesh = nullptr;
         }
     }
     for (auto& texture : m_textureVec) {
         if (texture) {
             delete texture;
             texture = nullptr;
         }
     }
 }
Referenced by ~Model().
LoadMaterials()
void Model::LoadMaterials (const aiScene * scene) private
Loads in the material/texture.
Parameters
scene
Definition at line 86 of file Model.cpp.
{
     m_textureVec.resize(scene->mNumMaterials);
     for (size_t i = 0; i < scene->mNumMaterials; ++i) {
         aiMaterial* material = scene->mMaterials[i];
         m_textureVec[i] = nullptr;
         if (material->GetTextureCount(aiTextureType_DIFFUSE)) {
             aiString path;
             if (material->GetTexture(aiTextureType_DIFFUSE, 0, &path) ==
                 AI_SUCCESS) {
                 int idx = std::string(path.data).rfind("\\");
                 std::string fileName = std::string(path.data).substr(idx + 1);
                 std::string texPath = std::string("Textures/") + fileName;
                 m_textureVec[i] = new Texture(texPath.c_str());
                 if (!m_textureVec[i]->LoadTexture()) {
                     std::cout << "Failed to load texture at " << texPath;
                     delete m_textureVec[i];
                     m_textureVec[i] = nullptr;
                 }
             }
         }
         if (!m_textureVec[i]) {
             m_textureVec[i] = new Texture("Textures/plain.png");
             m_textureVec[i]->LoadTextureA();
         }
     }
 }
LoadMesh()
void Model::LoadMesh (aiMesh * mesh, const aiScene * scene) private
Loads in a mesh.
Parameters
mesh
scene
Definition at line 46 of file Model.cpp.
{
     std::vector<GLfloat> vertices;
     std::vector<GLuint> indices;
     for (size_t i = 0; i < mesh->mNumVertices; ++i) {
         // Vertices
         vertices.insert(
             vertices.end(),
             {mesh->mVertices[i].x, mesh->mVertices[i].y, mesh->mVertices[i].z});
         // Texture coordinates
         if (mesh->mTextureCoords[0]) {
             vertices.insert(vertices.end(), {mesh->mTextureCoords[0][i].x,
                                              mesh->mTextureCoords[0][i].y});
         } else {
             vertices.insert(vertices.end(), {0.0f, 0.0f});
         }
         // Normals
         vertices.insert(
             vertices.end(),
             {-mesh->mNormals[i].x, -mesh->mNormals[i].y, -mesh->mNormals[i].z});
     }
     for (size_t i = 0; i < mesh->mNumFaces; ++i) {
         aiFace face = mesh->mFaces[i];
         for (size_t j = 0; j < face.mNumIndices; ++j) {
             indices.push_back(face.mIndices[j]);
         }
     }
     Mesh* newMesh = new Mesh();
     newMesh->CreateMesh(&vertices[0], &indices[0], vertices.size(),
                         indices.size());
     m_meshVec.push_back(newMesh);
     m_meshToTex.push_back(mesh->mMaterialIndex);
 }
References Mesh::Mesh().
LoadModel()
bool Model::LoadModel (const std::string & fileName)
Loads a new model from a 3D object file format.
Parameters
fileName
Definition at line 5 of file Model.cpp.
{
     Assimp::Importer importer;
     const aiScene* scene =
         importer.ReadFile(fileName, aiProcess_Triangulate | aiProcess_FlipUVs |
                                         aiProcess_GenSmoothNormals |
                                         aiProcess_JoinIdenticalVertices);
     if (!scene) {
         std::cout << "Model (" << fileName
                   << ") failed to load: " << importer.GetErrorString();
         return false;
     }
     LoadNode(scene->mRootNode, scene);
     LoadMaterials(scene);
     return true;
 }
Referenced by ModelManager::load_model().
LoadNode()
void Model::LoadNode (aiNode * node, const aiScene * scene) private
Recursive function to traverse the node and load the meshes.
Parameters
node
scene
Definition at line 38 of file Model.cpp.
{
     for (size_t i = 0; i < node->mNumMeshes; ++i)
         LoadMesh(scene->mMeshes[node->mMeshes[i]], scene);
     for (size_t i = 0; i < node->mNumChildren; ++i)
         LoadNode(node->mChildren[i], scene);
 }
RenderModel()
void Model::RenderModel () const
Renders the model.
Definition at line 25 of file Model.cpp.
{
     for (size_t i = 0; i < m_meshVec.size(); ++i) {
         GLuint materialIndex = m_meshToTex[i];
         if (materialIndex < m_textureVec.size() &&
             m_textureVec[materialIndex]) {
             m_textureVec[materialIndex]->UseTexture();
         }
         m_meshVec[i]->RenderMesh();
     }
 }
Referenced by Item::draw().
Member Data Documentation
m_meshToTex
std::vector<GLuint> Model::m_meshToTex private
A vector of the mesh to texture mapping.
Definition at line 78 of file Model.hpp.
m_meshVec
std::vector<Mesh*> Model::m_meshVec private
A vector of the meshes.
Definition at line 72 of file Model.hpp.
m_textureVec
std::vector<Texture*> Model::m_textureVec private
A vector of the textures.
Definition at line 75 of file Model.hpp.
The documentation for this class was generated from the following files:
src/View/Renderer/OpenGL/Objects/Model.hpp
src/View/Renderer/OpenGL/Objects/Model.cpp