ICT397 Assignment 2: Physics Class Reference
Physics Class Reference
#include <Physics.hpp>
Static Public Member Functions
static void createWorld ()
Creates the world for the physic objects.
static void updateWorld (double delta_time)
Updates the world for the physic objects.
static void setDebuggerToActive (bool val)
Sets which debugger to active.
static void setDebuggerValues (int type, bool val)
Can set different debug values to be returned.
static void destroyWorld ()
Creates the world for the physic objects.
static PhysicsCommon & getPhysicsCommon ()
Returns physics common game object.
static PhysicsWorld * getPhysicsWorld ()
Returns physics world game object.
static bool WorldExists ()
Returns if the physics world is created or not.
Static Private Attributes
static bool created = false
static PhysicsCommon physicsCommon
static PhysicsWorld * world = nullptr
Detailed Description
Definition at line 8 of file Physics.hpp.
Member Function Documentation
createWorld()
void Physics::createWorld () static
Creates the world for the physic objects.
Precondition
Nothing
Postcondition
World is created & ready to use
Definition at line 7 of file Physics.cpp.
{
     if (!created) {
         world = physicsCommon.createPhysicsWorld();
         created = true;
     }
 }
References created.
Referenced by ReflexEngine::run().
destroyWorld()
void Physics::destroyWorld () static
Creates the world for the physic objects.
Precondition
World is created
Postcondition
World is destoryed
Definition at line 37 of file Physics.cpp.
{
     if (created) {
         physicsCommon.destroyPhysicsWorld(world);
         created = false;
     }
 }
References created.
Referenced by ReflexEngine::run().
getPhysicsCommon()
PhysicsCommon & Physics::getPhysicsCommon () static
Returns physics common game object.
Returns
&PhysicsCommon - The physics common object
Precondition
Nothing
Postcondition
Nothing
Definition at line 44 of file Physics.cpp.
 { return physicsCommon; }
getPhysicsWorld()
PhysicsWorld * Physics::getPhysicsWorld () static
Returns physics world game object.
Returns
*PhysicsWorld - The physics world
Precondition
Nothing
Postcondition
Nothing
Definition at line 46 of file Physics.cpp.
 { return world; }
setDebuggerToActive()
void Physics::setDebuggerToActive (bool val) static
Sets which debugger to active.
Parameters
val - true if you want it activated
Precondition
World has been created
Postcondition
Debugger activated/deactivated
Definition at line 21 of file Physics.cpp.
{
     if (!created) {
         return;
     }
     world->setIsDebugRenderingEnabled(val);
 }
References created.
setDebuggerValues()
void Physics::setDebuggerValues (int type, bool val) static
Can set different debug values to be returned.
Collider AABB = 1 Collider Broadphase AABB = 2 Collision Shape = 4 Contact Normal = 16 Contact Point = 8
Parameters
type - The type of debugger to add
val - true if you want to add it / use it
Precondition
Nothing
Postcondition
Debugger will use/not use the value
Definition at line 28 of file Physics.cpp.
{
     if (!created) {
         return;
     }
     DebugRenderer& debugRenderer = world->getDebugRenderer();
     debugRenderer.setIsDebugItemDisplayed(
         static_cast<DebugRenderer::DebugItem>(type), val);
 }
References created.
updateWorld()
void Physics::updateWorld (double delta_time) static
Updates the world for the physic objects.
Parameters
delta_time - Time since the last update
Precondition
World has been created
Postcondition
World has been updated
Definition at line 14 of file Physics.cpp.
{
     if (!created) {
         return;
     }
     world->update(delta_time);
 }
References created.
WorldExists()
bool Physics::WorldExists () static
Returns if the physics world is created or not.
Returns
bool - If the physics world exsists
Precondition
Nothing
Postcondition
Nothing
Definition at line 48 of file Physics.cpp.
 { return created; }
References created.
Referenced by BodyRigidPhysics::~BodyRigidPhysics().
Member Data Documentation
created
bool Physics::created = false static private
Definition at line 88 of file Physics.hpp.
Referenced by createWorld(), destroyWorld(), setDebuggerToActive(), setDebuggerValues(), updateWorld(), and WorldExists().
physicsCommon
PhysicsCommon Physics::physicsCommon static private
Definition at line 89 of file Physics.hpp.
world
PhysicsWorld * Physics::world = nullptr static private
Definition at line 90 of file Physics.hpp.
The documentation for this class was generated from the following files:
src/Controller/Physics/Physics.hpp
src/Controller/Physics/Physics.cpp