ICT397 Assignment 2: ObjectSaving Class Reference
ObjectSaving Class Reference
Class that writes the data of the game objects to a lua script, so it can be used to load the game objects into the scene.
#include <ObjectSaving.hpp>
Static Public Member Functions
static void setFreshSave ()
Resets the number counter for the file name to 0.
static void appendCreationFile ()
On first call, opens the creation script file. And then adds the save files in number order into the creation script.
static void openFile ()
Opens a file to save data too.
static void saveGameObject (glm::vec3 pos, glm::vec3 rot, glm::vec3 scale, float angle, std::string type)
Saves a base game object to a file.
static void addComma ()
Adds a comma to the file.
static void addValue (std::string varName, int val, bool endStruct)
Adds a value to the file.
static void addValue (std::string varName, float val, bool endStruct)
Adds a value to the file.
static void addValue (std::string varName, std::string val, bool endStruct)
Adds a value to the file.
static void createStruct (std::string structName)
Creates a struct in the file.
static void closeStruct ()
Closes the struct in the file.
static void closeFile ()
Closes the file.
static void addPrint ()
Adds a print line in the script (for debugging)
Static Private Attributes
static std::ofstream outfile
static std::ofstream creationScript
static int number = 0
Detailed Description
Class that writes the data of the game objects to a lua script, so it can be used to load the game objects into the scene.
Definition at line 11 of file ObjectSaving.hpp.
Member Function Documentation
addComma()
void ObjectSaving::addComma () static
Adds a comma to the file.
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
comma added
Definition at line 39 of file ObjectSaving.cpp.
 { outfile << ",\n"; }
Referenced by Projectile::save_object(), Player::save_object(), DirectionalLightObject::save_object(), PointLightObject::save_object(), SpotLightObject::save_object(), NPC::save_object(), and PhysicsObject::save_object().
addPrint()
void ObjectSaving::addPrint () static
Adds a print line in the script (for debugging)
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
print added
Definition at line 74 of file ObjectSaving.cpp.
 { outfile << "print(\"Here\")\n"; }
addValue() [1/3]
void ObjectSaving::addValue (std::string varName, float val, bool endStruct) static
Adds a value to the file.
Parameters
varName - The name to store with the value
val - The value
endStruct - If in struct and not at end put true. Just adds comma
Returns
Void
Precondition
file is open
Postcondition
value added
Definition at line 49 of file ObjectSaving.cpp.
{
     outfile << varName << " = " << val;
     if (endStruct == false) {
         outfile << ",";
     }
     outfile << "\n";
 }
Referenced by PointLightObject::save_object(), and SpotLightObject::save_object().
addValue() [2/3]
void ObjectSaving::addValue (std::string varName, int val, bool endStruct) static
Adds a value to the file.
Parameters
varName - The name to store with the value
val - The value
endStruct - If in struct and not at end put true. Just adds comma
Returns
Void
Precondition
file is open
Postcondition
value added
Definition at line 41 of file ObjectSaving.cpp.
{
     outfile << varName << " = " << val;
     if (endStruct == false) {
         outfile << ",";
     }
     outfile << "\n";
 }
addValue() [3/3]
void ObjectSaving::addValue (std::string varName, std::string val, bool endStruct) static
Adds a value to the file.
Parameters
varName - The name to store with the value
val - The value
endStruct - If in struct and not at end put true. Just adds comma
Returns
Void
Precondition
file is open
Postcondition
value added
Definition at line 57 of file ObjectSaving.cpp.
{
     outfile << varName << " = \"" << val << "\"";
     if (endStruct == false) {
         outfile << ",";
     }
     outfile << "\n";
 }
Referenced by Item::save_object(), ScriptableObject::save_object(), and NetworkedItem::save_object().
appendCreationFile()
void ObjectSaving::appendCreationFile () static
On first call, opens the creation script file. And then adds the save files in number order into the creation script.
Definition at line 9 of file ObjectSaving.cpp.
{
     if (number == 0) {
         creationScript.open("scripts/save/_MasterCreation.lua");
     } else {
         creationScript.open("scripts/save/_MasterCreation.lua",
                             std::ios_base::app);
     }
     creationScript << "addGameObject(\"scripts/save/" + std::to_string(number) +
                           ".lua\")\n";
     creationScript.close();
     number++;
 }
References number.
Referenced by openFile().
closeFile()
void ObjectSaving::closeFile () static
Closes the file.
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
file closed
Definition at line 72 of file ObjectSaving.cpp.
 { outfile.close(); }
Referenced by Projectile::save_object(), Player::save_object(), SkyboxObject::save_object(), SpotLightObject::save_object(), DirectionalLightObject::save_object(), PointLightObject::save_object(), NPC::save_object(), Item::save_object(), ScriptableObject::save_object(), NetworkedItem::save_object(), PhysicsObject::save_object(), and Water::save_object().
closeStruct()
void ObjectSaving::closeStruct () static
Closes the struct in the file.
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
end of struct added
Definition at line 70 of file ObjectSaving.cpp.
 { outfile << "}\n\n"; }
Referenced by Projectile::save_object(), Player::save_object(), SkyboxObject::save_object(), SpotLightObject::save_object(), DirectionalLightObject::save_object(), PointLightObject::save_object(), NPC::save_object(), Item::save_object(), ScriptableObject::save_object(), NetworkedItem::save_object(), PhysicsObject::save_object(), and Water::save_object().
createStruct()
void ObjectSaving::createStruct (std::string structName) static
Creates a struct in the file.
Parameters
structName - The name of the struct
Returns
Void
Precondition
file is open
Postcondition
start of struct added
Definition at line 66 of file ObjectSaving.cpp.
{
     outfile << structName << " = {\n";
 }
Referenced by SkyboxObject::save_object(), DirectionalLightObject::save_object(), PointLightObject::save_object(), SpotLightObject::save_object(), Item::save_object(), and NetworkedItem::save_object().
openFile()
void ObjectSaving::openFile () static
Opens a file to save data too.
Parameters
No param
Returns
Void
Precondition
nothing
Postcondition
file opened
Definition at line 34 of file ObjectSaving.cpp.
{
     outfile.open("scripts/save/" + std::to_string(number) + ".lua");
     appendCreationFile();
 }
References appendCreationFile().
Referenced by Projectile::save_object(), Player::save_object(), SkyboxObject::save_object(), SpotLightObject::save_object(), DirectionalLightObject::save_object(), PointLightObject::save_object(), NPC::save_object(), ScriptableObject::save_object(), Item::save_object(), NetworkedItem::save_object(), PhysicsObject::save_object(), and Water::save_object().
saveGameObject()
void ObjectSaving::saveGameObject (glm::vec3 pos, glm::vec3 rot, glm::vec3 scale, float angle, std::string type) static
Saves a base game object to a file.
Parameters
pos - The position of the base object
rot - The axis of rotation of the base object
scale - The scale of the base object
angle - The angle of rotation of the base object
type - The type of the object (e.g,. ScriptableObject)
Returns
Void
Precondition
file is open
Postcondition
base object paramaters saved
Definition at line 23 of file ObjectSaving.cpp.
{
     outfile << "baseObject = {\n"
             << "type = \"" << type << "\",\nxPos = " << pos.x
             << ",\nyPos = " << pos.y << ",\nzPos = " << pos.z
             << ",\nxRotation = " << rot.x << ",\nyRotation = " << rot.y
             << ",\nzRotation = " << rot.z << ",\nangle = " << angle
             << ",\nxScale = " << scale.x << ",\nyScale = " << scale.y
             << ",\nzScale = " << scale.z;
 }
Referenced by PointLightObject::save_object(), and SpotLightObject::save_object().
setFreshSave()
void ObjectSaving::setFreshSave () static
Resets the number counter for the file name to 0.
Parameters
No param
Returns
Void
Precondition
nothing
Postcondition
counter reset
Definition at line 7 of file ObjectSaving.cpp.
 { number = 0; }
References number.
Referenced by TestScene::saveGameObjects().
Member Data Documentation
creationScript
std::ofstream ObjectSaving::creationScript static private
Definition at line 145 of file ObjectSaving.hpp.
number
int ObjectSaving::number = 0 static private
Definition at line 146 of file ObjectSaving.hpp.
Referenced by appendCreationFile(), and setFreshSave().
outfile
std::ofstream ObjectSaving::outfile static private
Definition at line 144 of file ObjectSaving.hpp.
The documentation for this class was generated from the following files:
src/Controller/ResourceManager/ObjectSaving.hpp
src/Controller/ResourceManager/ObjectSaving.cpp