ICT397 Assignment 2: SkyboxObject Class Reference
SkyboxObject Class Reference
#include <SkyboxObject.hpp>
Public Member Functions
SkyboxObject ()
Construct a new Skybox Object.
void init () override
Initializes the skybox object.
void update (double delta_time) override
Updates the object with delta time.
void fixed_update (double delta_time) override
Updates the object with fixed delta time.
void add_draw_call () override
Adds a draw call to the renderer.
void draw (std::shared_ptr< Shader > shader) override
The draw call.
void save_object () override
Saves the object to lua file.
void set_face (SkyboxFaces face, const std::string &texture_path)
Set the face of the skybox with a texture path.
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
std::vector< std::string > faces_
The faces of the skybox.
Additional Inherited Members
Public Attributes inherited from GameObject
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01f
The angle of rotation.
bool remove = false
Whether the game object should be removed.
Detailed Description
Definition at line 10 of file SkyboxObject.hpp.
Constructor & Destructor Documentation
SkyboxObject()
SkyboxObject::SkyboxObject ()
Construct a new Skybox Object.
Definition at line 5 of file SkyboxObject.cpp.
 { faces_.resize(6); }
Referenced by GameAssetFactory::load_skybox().
Member Function Documentation
add_draw_call()
void SkyboxObject::add_draw_call () inline override virtual
Adds a draw call to the renderer.
Implements GameObject.
Definition at line 39 of file SkyboxObject.hpp.
 {}
draw()
void SkyboxObject::draw (std::shared_ptr< Shader > shader) inline override virtual
The draw call.
Parameters
shader The shader to use.
Implements GameObject.
Definition at line 46 of file SkyboxObject.hpp.
 {}
fixed_update()
void SkyboxObject::fixed_update (double delta_time) inline override virtual
Updates the object with fixed delta time.
Parameters
delta_time The time since the last fixed tick.
Implements GameObject.
Definition at line 34 of file SkyboxObject.hpp.
 {}
init()
void SkyboxObject::init () override virtual
Initializes the skybox object.
Implements GameObject.
Definition at line 7 of file SkyboxObject.cpp.
{
     auto& renderer = ReflexEngine::get_instance().renderer_;
     renderer.set_skybox(faces_);
 }
Referenced by GameAssetFactory::load_skybox().
save_object()
void SkyboxObject::save_object () override virtual
Saves the object to lua file.
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 12 of file SkyboxObject.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle, "Skybox");
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("skybox_faces");
     ObjectSaving::addValue("right_face", faces_.at(0), false);
     ObjectSaving::addValue("left_face", faces_.at(1), false);
     ObjectSaving::addValue("top_face", faces_.at(2), false);
     ObjectSaving::addValue("bottom_face", faces_.at(3), false);
     ObjectSaving::addValue("back_face", faces_.at(4), false);
     ObjectSaving::addValue("front_face", faces_.at(5), true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::closeFile(), ObjectSaving::closeStruct(), ObjectSaving::createStruct(), and ObjectSaving::openFile().
set_face()
void SkyboxObject::set_face (SkyboxFaces face, const std::string & texture_path)
Set the face of the skybox with a texture path.
Parameters
face
texture_path
Definition at line 27 of file SkyboxObject.cpp.
{
     faces_.at(static_cast<int>(face)) = texture_path;
 }
update()
void SkyboxObject::update (double delta_time) inline override virtual
Updates the object with delta time.
Parameters
delta_time The time since the last frame.
Implements GameObject.
Definition at line 27 of file SkyboxObject.hpp.
 {}
Member Data Documentation
faces_
std::vector<std::string> SkyboxObject::faces_ private
The faces of the skybox.
Definition at line 66 of file SkyboxObject.hpp.
The documentation for this class was generated from the following files:
src/Model/GameObject/SkyboxObject.hpp
src/Model/GameObject/SkyboxObject.cpp