My Project: TerrainObject Class Reference
TerrainObject Class Reference
#include <TerrainObject.hpp>
Public Member Functions
TerrainObject ()
void init ()
Initializes the game object.
void fixed_update (float delta_time) override
Updates the game object with fixed delta time.
void update (float delta_time) override
Updates the game object with delta time.
void add_draw_call () override
Adds a draw call to the renderer.
void draw (std::shared_ptr< Shader > shader) override
The draw call.
void save_object () override
Saves the object to lua file.
void add_texture (std::string file_name)
void add_height_map (uint8_t *heightmap, int xSize, int ySize, bool island)
void add_detail_map (std::string file_name)
void create_terrain (int chunckSize, int chunkDetail, int n, int heightSize, glm::vec3 scale)
uint8_t * get_height_map ()
void add_storage_text (std::string text, int n)
Public Member Functions inherited from GameObject
virtual ~GameObject ()=default
Virtual destructor.
Private Attributes
BttController bttControl
multiTextureCreator mtc
float lastUpdate = -1
std::string m_text [6]
Additional Inherited Members
Public Attributes inherited from GameObject
struct {
glm::vec3 position = {0.0f, 0.0f, 0.0f}
The position of the game object.
glm::vec3 rotation = {0.0f, 1.0f, 0.0f}
The rotation of the game object.
glm::vec3 scale = {1.0f, 1.0f, 1.0f}
The scale of the game object.
float angle = 0.01
};
Detailed Description
Definition at line 8 of file TerrainObject.hpp.
Constructor & Destructor Documentation
TerrainObject()
TerrainObject::TerrainObject ()
Definition at line 4 of file TerrainObject.cpp.
 { position = glm::vec3(0.0f); }
Referenced by GameAssetFactory::loadTerrainObject().
Member Function Documentation
add_detail_map()
void TerrainObject::add_detail_map (std::string file_name)
Definition at line 61 of file TerrainObject.cpp.
{
     bttControl.load_detailmap(fileName.c_str());
 }
add_draw_call()
void TerrainObject::add_draw_call () override virtual
Adds a draw call to the renderer.
Implements GameObject.
Definition at line 15 of file TerrainObject.cpp.
{
     DrawCall draw_call = [=](std::shared_ptr<Shader> shader) { draw(shader); };
     ReflexEngine::get_instance().renderer_.add_draw_call(draw_call);
 }
add_height_map()
void TerrainObject::add_height_map (uint8_t * heightmap, int xSize, int ySize, bool island)
Definition at line 53 of file TerrainObject.cpp.
{
     mtc.set_height_map(heightmap, xSize, ySize, island);
     mtc.create_multi_texture();
     bttControl.set_texture_id(mtc.get_multi_texture());
     bttControl.set_height_map(mtc.get_height_map());
 }
add_storage_text()
void TerrainObject::add_storage_text (std::string text, int n)
Definition at line 24 of file TerrainObject.cpp.
{
     m_text[n] = text;
 }
References m_text.
add_texture()
void TerrainObject::add_texture (std::string file_name)
Definition at line 49 of file TerrainObject.cpp.
{
     mtc.set_texture(fileName);
 }
create_terrain()
void TerrainObject::create_terrain (int chunckSize, int chunkDetail, int n, int heightSize, glm::vec3 scale)
Definition at line 65 of file TerrainObject.cpp.
{
     bttControl.set_scale(scale);
     bttControl.CreateTerrain(chunckSize, chunkDetail, n);
 }
draw()
void TerrainObject::draw (std::shared_ptr< Shader > shader) override virtual
The draw call.
Parameters
shader
Implements GameObject.
Definition at line 20 of file TerrainObject.cpp.
{
     bttControl.render(shader);
 }
fixed_update()
void TerrainObject::fixed_update (float delta_time) override virtual
Updates the game object with fixed delta time.
Parameters
delta_time
Implements GameObject.
Definition at line 8 of file TerrainObject.cpp.
{
     if (glfwGetTime() - lastUpdate > 0.2) {
         bttControl.Update(ReflexEngine::get_instance().camera_.get_position());
         lastUpdate = glfwGetTime();
     }
 }
get_height_map()
uint8_t * TerrainObject::get_height_map ()
Definition at line 71 of file TerrainObject.cpp.
 { return mtc.get_height_map(); }
init()
void TerrainObject::init () virtual
Initializes the game object.
Implements GameObject.
Definition at line 6 of file TerrainObject.cpp.
 { bttControl.set_scale(glm::vec3(1, 0.1, 1)); }
save_object()
void TerrainObject::save_object () override virtual
Saves the object to lua file.
Precondition
Object exists
Postcondition
Object saved
Implements GameObject.
Definition at line 28 of file TerrainObject.cpp.
{
     ObjectSaving::openFile();
     ObjectSaving::saveGameObject(position, rotation, scale, angle,
                                  "TerrainObject");
     ObjectSaving::closeStruct();
     ObjectSaving::createStruct("terrain");
     ObjectSaving::addValue("text1", m_text[0], false);
     ObjectSaving::addValue("text2", m_text[1], false);
     ObjectSaving::addValue("text3", m_text[2], false);
     ObjectSaving::addValue("text4", m_text[3], false);
     ObjectSaving::addValue("detailMap", m_text[5], false);
     ObjectSaving::addValue("heightMap", m_text[4], false);
     ObjectSaving::addValue("heightSize", 241, false);
     ObjectSaving::addValue("chunkSize", 30, false);
     ObjectSaving::addValue("chunkDetail", 9, false);
     ObjectSaving::addValue("n", 3, false);
     ObjectSaving::addValue("island", true, true);
     ObjectSaving::closeStruct();
     ObjectSaving::closeFile();
 }
References ObjectSaving::addValue(), ObjectSaving::closeFile(), ObjectSaving::closeStruct(), ObjectSaving::createStruct(), m_text, and ObjectSaving::openFile().
update()
void TerrainObject::update (float delta_time) inline override virtual
Updates the game object with delta time.
Parameters
delta_time
Implements GameObject.
Definition at line 16 of file TerrainObject.hpp.
 {};
Member Data Documentation
bttControl
BttController TerrainObject::bttControl private
Definition at line 38 of file TerrainObject.hpp.
lastUpdate
float TerrainObject::lastUpdate = -1 private
Definition at line 40 of file TerrainObject.hpp.
m_text
std::string TerrainObject::m_text[6] private
Definition at line 41 of file TerrainObject.hpp.
Referenced by add_storage_text(), and save_object().
mtc
multiTextureCreator TerrainObject::mtc private
Definition at line 39 of file TerrainObject.hpp.
The documentation for this class was generated from the following files:
src/Model/GameObject/TerrainObject.hpp
src/Model/GameObject/TerrainObject.cpp