ICT397 Assignment 2: BodyRigidPhysics Class Reference
BodyRigidPhysics Class Reference
#include <BodyRigidPhysics.hpp>
Public Member Functions
BodyRigidPhysics ()
Default constructor. DOES NOTHING.
void init (glm::vec3 pos, glm::vec3 rotation, float angle)
Creates rigid body.
void set_position (glm::vec3 pos)
Set the rb position object.
void setType (int type)
Set type of rigid body.
void enableGravity (bool val)
Set if you want gravity.
void setLinearVelocityDamping (float val)
Movement dampining.
void setAngularVelocityDamping (float val)
Rotation dampining.
void setIfBodyCanSleep (bool val)
Sets if the body can go to sleep.
void addForce (glm::vec3 force)
Adds force to the object.
void setLinearVelocity (glm::vec3 velocity)
set force to the object
void addTorque (glm::vec3 torque)
Adds torque to the object.
void setAngularVelocity (glm::vec3 velocity)
set torque to the object
glm::vec3 getPosition ()
Gets the position vector.
glm::vec3 getRotation ()
Gets the axis of rotation vector of the rigid body.
float getAngle ()
Gets the angle around the axis of rotation of the rigid body.
glm::vec3 getLinearVelocity ()
Gets the linear velocity of the rigid body.
glm::vec3 getAngularVelocity ()
Gets the angular velocity of the rigid body.
void addBoxCollider (glm::vec3 pos, glm::vec3 halfSize, float bounciness, float friction)
Adds a box ciller to a rigid body.
void addSphereCollider (glm::vec3 pos, float radius, float bounciness, float friction)
Adds a sphere collider to a rigid body.
void addCapsuleCollider (glm::vec3 pos, float radius, float height, float bounciness, float friction)
Adds a capsule collider to a rigid body.
void addHeightFieldShape (glm::vec3 pos, float bounciness, float friction, int nColumns, int nRows, int minHeight, int maxHeight, unsigned char *heightValues)
Creates a height field shape collision box.
bool getIfGravityActive ()
Gets if gravity is allowed in the rb (rigid body)
int getRBType ()
Retrieves the rigid body type.
int getNumberOfColliders ()
Gets the number of colliders attached to the rigid body.
float getLinearDamping ()
Gets the linear damping value of the object.
float getAngularDamping ()
Gets the angular damping value of the object.
bool getIfAllowedSleep ()
Gets it the object can go to sleep (performce improvement)
int getColliderType (int index)
Gets the type of collider (sphere, box, capsule)
float getBounciness (int index)
Gets a collders bounciness value.
float getFriction (int index)
Gets a colliders friction value.
glm::vec3 getLocalColliderPos (int index)
Gets the local position of the collider attached to the rb.
void setLinearAxisFactor (glm::vec3 factor)
Changes the linear axis factor. I.e. if set a axis to 0 it will no longer move on that axis.
void setAngularAxisFactor (glm::vec3 factor)
Changes the angular axis factor. I.e. if set a axis to 0 it will no longer rotate on that axis.
void removeColliders ()
Removes the colliders from the rigid body.
void turnIntoTrigger (bool val)
Turns rigid body into a trigger (i.e will loose collision resolution but will notify when collision occurs)
~BodyRigidPhysics ()
Destructor.
Private Attributes
bool created = false
True if created, else false
RigidBody * rb
React rigid body of the object
Detailed Description
Definition at line 44 of file BodyRigidPhysics.hpp.
Constructor & Destructor Documentation
BodyRigidPhysics()
BodyRigidPhysics::BodyRigidPhysics ()
Default constructor. DOES NOTHING.
Precondition
Nothing
Postcondition
Object created
Definition at line 3 of file BodyRigidPhysics.cpp.
 {}
~BodyRigidPhysics()
BodyRigidPhysics::~BodyRigidPhysics ()
Destructor.
Precondition
Object was created
Postcondition
Object deleted
Definition at line 122 of file BodyRigidPhysics.cpp.
{
     if (created == false || Physics::WorldExists() == false) {
         return;
     }
     Physics::getPhysicsWorld()->destroyRigidBody(rb);
     created = false;
 }
References created, and Physics::WorldExists().
Member Function Documentation
addBoxCollider()
void BodyRigidPhysics::addBoxCollider (glm::vec3 pos, glm::vec3 halfSize, float bounciness, float friction)
Adds a box ciller to a rigid body.
Parameters
pos - The local position of the collision box
halfSize - The size of each size if it were halved
bounciness - The bounciness of the collision box
friction - The friction of the collision box
Precondition
Rigid body exists
Postcondition
Box collider added
Definition at line 130 of file BodyRigidPhysics.cpp.
{
     if (bounciness < 0) {
         bounciness = 0;
     } else if (bounciness > 1) {
         bounciness = 1;
     }
     if (friction < 0) {
         friction = 0;
     } else if (friction > 1) {
         friction = 1;
     }
     BoxShape* boxShape = Physics::getPhysicsCommon().createBoxShape(
         Vector3(halfSize.x, halfSize.y, halfSize.z));
     Transform t = Transform::identity();
     t.setPosition(Vector3(pos.x, pos.y, pos.z));
     Collider* collider;
     collider = rb->addCollider(boxShape, t);
     Material& mat = collider->getMaterial();
     mat.setBounciness(bounciness);
     mat.setFrictionCoefficient(friction);
 }
addCapsuleCollider()
void BodyRigidPhysics::addCapsuleCollider (glm::vec3 pos, float radius, float height, float bounciness, float friction)
Adds a capsule collider to a rigid body.
Parameters
pos - The local position of the collision box
radius - The radius of the capsule
height - The height of the capsule
bounciness - The bounciness of the collision box
friction - The friction of the collision box
Precondition
Rigid body exists
Postcondition
Capsule collider added
Definition at line 188 of file BodyRigidPhysics.cpp.
{
     if (bounciness < 0) {
         bounciness = 0;
     } else if (bounciness > 1) {
         bounciness = 1;
     }
     if (friction < 0) {
         friction = 0;
     } else if (friction > 1) {
         friction = 1;
     }
     CapsuleShape* capsuleShape =
         Physics::getPhysicsCommon().createCapsuleShape(radius, height);
     Transform t = Transform::identity();
     t.setPosition(Vector3(pos.x, pos.y, pos.z));
     Collider* collider;
     collider = rb->addCollider(capsuleShape, t);
     Material& mat = collider->getMaterial();
     mat.setBounciness(bounciness);
     mat.setFrictionCoefficient(friction);
 }
addForce()
void BodyRigidPhysics::addForce (glm::vec3 force)
Adds force to the object.
Parameters
force - Force to add
Precondition
Rigid body exists
Postcondition
Force added
Definition at line 65 of file BodyRigidPhysics.cpp.
{
     Vector3 f(force.x, force.y, force.z);
     rb->applyLocalForceAtCenterOfMass(f);
 }
addHeightFieldShape()
void BodyRigidPhysics::addHeightFieldShape (glm::vec3 pos, float bounciness, float friction, int nColumns, int nRows, int minHeight, int maxHeight, unsigned char * heightValues)
Creates a height field shape collision box.
NOT CURRENTLY IMPLEMENTED
Parameters
pos - The local position of the collision box
bounciness - The bounciness of the collision box
friction - The friction of the collision box
Precondition
Rigid body exists
Postcondition
Height field added
Definition at line 218 of file BodyRigidPhysics.cpp.
{
     /*
     if (bounciness < 0) {
         bounciness = 0;
     } else if (bounciness > 1) {
         bounciness = 1;
     }
     if (friction < 0) {
         friction = 0;
     } else if (friction > 1) {
         friction = 1;
     }
     int* values = new int[nColumns * nRows];
     for (int x = 0; x < nColumns; x++) {
         for (int y = 0; y < nRows; y++) {
             values[y * nColumns + x] = (int)heightValues[y * nColumns + x];
         }
     }
     HeightFieldShape* heightFieldShape =
         Physics::getPhysicsCommon().createHeightFieldShape(
             nColumns, nRows, minHeight, maxHeight, values,
             HeightFieldShape::HeightDataType::HEIGHT_INT_TYPE);
     Transform t = Transform::identity();
     t.setPosition(Vector3(pos.x, pos.y, pos.z));
     Collider* collider;
     collider = rb->addCollider(heightFieldShape, t);
     Material& mat = collider->getMaterial();
     mat.setBounciness(bounciness);
     mat.setFrictionCoefficient(friction);
     */
 }
addSphereCollider()
void BodyRigidPhysics::addSphereCollider (glm::vec3 pos, float radius, float bounciness, float friction)
Adds a sphere collider to a rigid body.
Parameters
pos - The local position of the collision box
radius - The radius of the sphere
bounciness - The bounciness of the collision box
friction - The friction of the collision box
Precondition
Rigid body exists
Postcondition
Sphere collider added
Definition at line 159 of file BodyRigidPhysics.cpp.
{
     if (bounciness < 0) {
         bounciness = 0;
     } else if (bounciness > 1) {
         bounciness = 1;
     }
     if (friction < 0) {
         friction = 0;
     } else if (friction > 1) {
         friction = 1;
     }
     SphereShape* sphereShape =
         Physics::getPhysicsCommon().createSphereShape(radius);
     Transform t = Transform::identity();
     t.setPosition(Vector3(pos.x, pos.y, pos.z));
     Collider* collider;
     collider = rb->addCollider(sphereShape, t);
     Material& mat = collider->getMaterial();
     mat.setBounciness(bounciness);
     mat.setFrictionCoefficient(friction);
 }
addTorque()
void BodyRigidPhysics::addTorque (glm::vec3 torque)
Adds torque to the object.
Parameters
torque - Torque to add
Precondition
Rigid body exists
Postcondition
Torque added
Definition at line 75 of file BodyRigidPhysics.cpp.
{
     Vector3 t(torque.x, torque.y, torque.z);
     rb->applyLocalTorque(t);
 }
enableGravity()
void BodyRigidPhysics::enableGravity (bool val)
Set if you want gravity.
Parameters
val - True = allow gravity
Precondition
Rigid body exists
Postcondition
Gravity set
Definition at line 51 of file BodyRigidPhysics.cpp.
 { rb->enableGravity(val); }
getAngle()
float BodyRigidPhysics::getAngle ()
Gets the angle around the axis of rotation of the rigid body.
Returns
float - Angle around axis of rotation
Precondition
Rigid body exists
Postcondition
Angle retrieved
Definition at line 102 of file BodyRigidPhysics.cpp.
{
     Transform t = rb->getTransform();
     Quaternion q = t.getOrientation();
     Vector3 v;
     float angle;
     q.getRotationAngleAxis(angle, v);
     angle = angle * 180 / PI_RP3D;
     return angle;
 }
getAngularDamping()
float BodyRigidPhysics::getAngularDamping ()
Gets the angular damping value of the object.
Returns
float - The angular damping value
Precondition
rb exists
Postcondition
angular damping retrieved
Definition at line 269 of file BodyRigidPhysics.cpp.
 { return rb->getAngularDamping(); }
getAngularVelocity()
glm::vec3 BodyRigidPhysics::getAngularVelocity ()
Gets the angular velocity of the rigid body.
Returns
glm::vec3 - angular velocity
Precondition
Rigid body exists
Postcondition
angular velocity retrieved
Definition at line 117 of file BodyRigidPhysics.cpp.
{
     Vector3 v3 = rb->getAngularVelocity();
     return glm::vec3(v3.x, v3.y, v3.z);
 }
getBounciness()
float BodyRigidPhysics::getBounciness (int index)
Gets a collders bounciness value.
Parameters
index - The index of the collider in question
Returns
float - The bounciness of the collider
Precondition
collider & rb exist
Postcondition
collider bounciness retrieved
Definition at line 278 of file BodyRigidPhysics.cpp.
{
     Collider* c = rb->getCollider(index);
     return c->getMaterial().getBounciness();
 }
getColliderType()
int BodyRigidPhysics::getColliderType (int index)
Gets the type of collider (sphere, box, capsule)
Parameters
index - The index of the collider in question
Returns
int - the colliders type
Precondition
collider & rb exist
Postcondition
collider type retrieved
Definition at line 273 of file BodyRigidPhysics.cpp.
{
     Collider* c = rb->getCollider(index);
     return (int)c->getCollisionShape()->getName();
 }
getFriction()
float BodyRigidPhysics::getFriction (int index)
Gets a colliders friction value.
Parameters
index - The index of the collider in question
Returns
float - The friction of the collider
Precondition
collider & rb exist
Postcondition
Friction value returned
Definition at line 283 of file BodyRigidPhysics.cpp.
{
     Collider* c = rb->getCollider(index);
     return c->getMaterial().getBounciness();
 }
getIfAllowedSleep()
bool BodyRigidPhysics::getIfAllowedSleep ()
Gets it the object can go to sleep (performce improvement)
Returns
bool - true if object can go to sleep
Precondition
rb exists
Postcondition
allowed to sleep retrieved
Definition at line 271 of file BodyRigidPhysics.cpp.
 { return rb->isSleeping(); }
getIfGravityActive()
bool BodyRigidPhysics::getIfGravityActive ()
Gets if gravity is allowed in the rb (rigid body)
Returns
bool - True if gravity is allowed on rb
Precondition
rb exists
Postcondition
if gravity allowed retrieved
Definition at line 261 of file BodyRigidPhysics.cpp.
 { return rb->isGravityEnabled(); }
getLinearDamping()
float BodyRigidPhysics::getLinearDamping ()
Gets the linear damping value of the object.
Returns
float - the linear damping value
Precondition
rb exists
Postcondition
linear damping retrieved
Definition at line 267 of file BodyRigidPhysics.cpp.
 { return rb->getLinearDamping(); }
getLinearVelocity()
glm::vec3 BodyRigidPhysics::getLinearVelocity ()
Gets the linear velocity of the rigid body.
Returns
glm::vec3 - linear velocity
Precondition
Rigid body exists
Postcondition
linear velocity retrieved
Definition at line 112 of file BodyRigidPhysics.cpp.
{
     Vector3 v3 = rb->getLinearVelocity();
     return glm::vec3(v3.x, v3.y, v3.z);
 }
getLocalColliderPos()
glm::vec3 BodyRigidPhysics::getLocalColliderPos (int index)
Gets the local position of the collider attached to the rb.
Parameters
index - The index of the collider in question
Returns
glm::vec3 - The position of the collider in relation to the rb
Precondition
Collider & rb exist
Postcondition
Local coordinates returned
Definition at line 288 of file BodyRigidPhysics.cpp.
{
     Collider* c = rb->getCollider(index);
     Transform t = c->getLocalToBodyTransform();
     return glm::vec3(t.getPosition().x, t.getPosition().y, t.getPosition().z);
 }
getNumberOfColliders()
int BodyRigidPhysics::getNumberOfColliders ()
Gets the number of colliders attached to the rigid body.
Returns
int - Number of colliders
Precondition
rb & colliders exist
Postcondition
Collider number retrieved
Definition at line 265 of file BodyRigidPhysics.cpp.
 { return rb->getNbColliders(); }
getPosition()
glm::vec3 BodyRigidPhysics::getPosition ()
Gets the position vector.
Returns
glm::vec3 - The position of the rigid body
Precondition
Rigid body exists
Postcondition
Position retrieved
Definition at line 85 of file BodyRigidPhysics.cpp.
{
     Transform t = rb->getTransform();
     Vector3 v = t.getPosition();
     glm::vec3 pos(v.x, v.y, v.z);
     return pos;
 }
getRBType()
int BodyRigidPhysics::getRBType ()
Retrieves the rigid body type.
Returns
int - The type of rigid body
Precondition
rb exists
Postcondition
rigid body type retrieved
Definition at line 263 of file BodyRigidPhysics.cpp.
 { return (int)rb->getType(); }
getRotation()
glm::vec3 BodyRigidPhysics::getRotation ()
Gets the axis of rotation vector of the rigid body.
Returns
glm::vec3 - The axis of rotation vector
Precondition
Rigid body exists
Postcondition
Rotation retrieved
Definition at line 92 of file BodyRigidPhysics.cpp.
{
     Transform t = rb->getTransform();
     Quaternion q = t.getOrientation();
     Vector3 v;
     float angle;
     q.getRotationAngleAxis(angle, v);
     glm::vec3 rot(v.x, v.y, v.z);
     return rot;
 }
init()
void BodyRigidPhysics::init (glm::vec3 pos, glm::vec3 rotation, float angle)
Creates rigid body.
Parameters
pos - Position of the body
rotation - axis of rotation of the body
angle - angle around axis of rotation
Precondition
Physics world exists
Postcondition
Rigid body initialised
Definition at line 5 of file BodyRigidPhysics.cpp.
{
     Vector3 position(pos.x, pos.y, pos.z);
     Quaternion o = Quaternion::identity();
     angle = angle / (180 / PI_RP3D);
     float x = rotation.x * sin(angle / 2);
     float y = rotation.y * sin(angle / 2);
     float z = rotation.z * sin(angle / 2);
     float w = cos(angle / 2);
     float normal = sqrt(pow(cos(angle / 2), 2) +
                         pow(rotation.x, 2) * pow(sin(angle / 2), 2) +
                         pow(rotation.y, 2) * pow(sin(angle / 2), 2) +
                         pow(rotation.z, 2) * pow(sin(angle / 2), 2));
     o.setAllValues(x / normal, y / normal, z / normal, w / normal);
     Transform t(position, o);
     rb = Physics::getPhysicsWorld()->createRigidBody(t);
     setType(2);
     created = true;
 }
References created, and setType().
removeColliders()
void BodyRigidPhysics::removeColliders ()
Removes the colliders from the rigid body.
Precondition
Colliders exist
Postcondition
Colliders removed
Definition at line 304 of file BodyRigidPhysics.cpp.
{
     int size = rb->getNbColliders();
     Collider* collider;
     for (int count = 0; count < size; count++) {
         collider = rb->getCollider(count);
         rb->removeCollider(collider);
         size--;
         count--;
     }
 }
set_position()
void BodyRigidPhysics::set_position (glm::vec3 pos)
Set the rb position object.
Parameters
pos
Definition at line 29 of file BodyRigidPhysics.cpp.
{
     Transform transform = rb->getTransform();
     transform.setPosition(Vector3(pos.x, pos.y, pos.z));
     rb->setTransform(transform);
 }
setAngularAxisFactor()
void BodyRigidPhysics::setAngularAxisFactor (glm::vec3 factor)
Changes the angular axis factor. I.e. if set a axis to 0 it will no longer rotate on that axis.
Parameters
factor - The factor you want for each axis. i.e. 1, 0, 1, stops y rotation.
Precondition
Rigid body exists
Postcondition
Angular axis factor changed
Definition at line 299 of file BodyRigidPhysics.cpp.
{
     rb->setAngularLockAxisFactor(
         reactphysics3d::Vector3(factor.x, factor.y, factor.z));
 }
setAngularVelocity()
void BodyRigidPhysics::setAngularVelocity (glm::vec3 velocity)
set torque to the object
Parameters
velocity - velocity to set
Precondition
Rigid body exists
Postcondition
Torque added
Definition at line 80 of file BodyRigidPhysics.cpp.
{
     Vector3 vel(velocity.x, velocity.y, velocity.z);
     rb->setAngularVelocity(vel);
 }
setAngularVelocityDamping()
void BodyRigidPhysics::setAngularVelocityDamping (float val)
Rotation dampining.
Parameters
val - higher value increaes rotation dampining
Precondition
Rigid body exists
Postcondition
angular dampining set
Definition at line 57 of file BodyRigidPhysics.cpp.
{
     rb->setAngularDamping(val);
 }
setIfBodyCanSleep()
void BodyRigidPhysics::setIfBodyCanSleep (bool val)
Sets if the body can go to sleep.
Parameters
val - true = body can go to sleep if inactive
Precondition
Rigid body exists
Postcondition
Rigid body can sleep
Definition at line 61 of file BodyRigidPhysics.cpp.
{
     rb->setIsAllowedToSleep(val);
 }
setLinearAxisFactor()
void BodyRigidPhysics::setLinearAxisFactor (glm::vec3 factor)
Changes the linear axis factor. I.e. if set a axis to 0 it will no longer move on that axis.
Parameters
factor - The factor you want for each axis. i.e. 1, 0, 1, stops y movement.
Precondition
Rigid body exists
Postcondition
Linear axis factor changed
Definition at line 294 of file BodyRigidPhysics.cpp.
{
     rb->setLinearLockAxisFactor(
         reactphysics3d::Vector3(factor.x, factor.y, factor.z));
 }
setLinearVelocity()
void BodyRigidPhysics::setLinearVelocity (glm::vec3 velocity)
set force to the object
Parameters
velocity - velocity to set
Precondition
Rigid body exists
Postcondition
Force added
Definition at line 70 of file BodyRigidPhysics.cpp.
{
     Vector3 vel(velocity.x, velocity.y, velocity.z);
     rb->setLinearVelocity(vel);
 }
setLinearVelocityDamping()
void BodyRigidPhysics::setLinearVelocityDamping (float val)
Movement dampining.
Parameters
val - higher value increaes velocity dampining
Precondition
Rigid body exists
Postcondition
linear dampining set
Definition at line 53 of file BodyRigidPhysics.cpp.
{
     rb->setLinearDamping(val);
 }
setType()
void BodyRigidPhysics::setType (int type)
Set type of rigid body.
Parameters
type - type of body. 0 = static, 1 = kinematic, 2 = dynamic
Precondition
Rigid body exists
Postcondition
Type set
Definition at line 37 of file BodyRigidPhysics.cpp.
{
     switch (type) {
         case 0:
             rb->setType(BodyType::STATIC);
             break;
         case 1:
             rb->setType(BodyType::KINEMATIC);
             break;
         case 2:
             rb->setType(BodyType::DYNAMIC);
             break;
     }
 }
Referenced by init().
turnIntoTrigger()
void BodyRigidPhysics::turnIntoTrigger (bool val)
Turns rigid body into a trigger (i.e will loose collision resolution but will notify when collision occurs)
Parameters
val - True if trigger
Precondition
Rigid body exist
Postcondition
trigger added
Definition at line 315 of file BodyRigidPhysics.cpp.
{
     int size = rb->getNbColliders();
     Collider* collider;
     for (int count = 0; count < size; count++) {
         collider = rb->getCollider(count);
         collider->setIsTrigger(val);
     }
 }
Member Data Documentation
created
bool BodyRigidPhysics::created = false private
True if created, else false
Definition at line 397 of file BodyRigidPhysics.hpp.
Referenced by init(), and ~BodyRigidPhysics().
rb
RigidBody* BodyRigidPhysics::rb private
React rigid body of the object
Definition at line 402 of file BodyRigidPhysics.hpp.
The documentation for this class was generated from the following files:
src/Controller/Physics/BodyRigidPhysics.hpp
src/Controller/Physics/BodyRigidPhysics.cpp