My Project: ObjectSaving Namespace Reference
ObjectSaving Namespace Reference
Functions
void setFreshSave ()
Resets the number counter for the file name to 0.
void openFile ()
Opens a file to save data too.
void saveGameObject (glm::vec3 pos, glm::vec3 rot, glm::vec3 scale, float angle, std::string type)
Saves a base game object to a file.
void addComma ()
Adds a comma to the file.
void addValue (std::string varName, int val, bool endStruct)
Adds a value to the file.
void addValue (std::string varName, float val, bool endStruct)
Adds a value to the file.
void addValue (std::string varName, std::string val, bool endStruct)
Adds a value to the file.
void createStruct (std::string structName)
Creates a struct in the file.
void closeStruct ()
Closes the struct in the file.
void closeFile ()
Closes the file.
void addPrint ()
Adds a print line in the script (for debugging)
Function Documentation
addComma()
void ObjectSaving::addComma ()
Adds a comma to the file.
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
comma added
Definition at line 39 of file ObjectSaving.cpp.
 { outfile << ",\n"; }
Referenced by Player::save_object(), PhysicsObject::save_object(), and Body::save_object().
addPrint()
void ObjectSaving::addPrint ()
Adds a print line in the script (for debugging)
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
print added
Definition at line 74 of file ObjectSaving.cpp.
 { outfile << "print(\"Here\")\n"; }
addValue() [1/3]
void ObjectSaving::addValue (std::string varName, float val, bool endStruct)
Adds a value to the file.
Parameters
varName - The name to store with the value
val - The value
endStruct - If in struct and not at end put true. Just adds comma
Returns
Void
Precondition
file is open
Postcondition
value added
Definition at line 49 of file ObjectSaving.cpp.
{
     outfile << varName << " = " << val;
     if (endStruct == false) {
         outfile << ",";
     }
     outfile << "\n";
 }
addValue() [2/3]
void ObjectSaving::addValue (std::string varName, int val, bool endStruct)
Adds a value to the file.
Parameters
varName - The name to store with the value
val - The value
endStruct - If in struct and not at end put true. Just adds comma
Returns
Void
Precondition
file is open
Postcondition
value added
Definition at line 41 of file ObjectSaving.cpp.
{
     outfile << varName << " = " << val;
     if (endStruct == false) {
         outfile << ",";
     }
     outfile << "\n";
 }
Referenced by TerrainObject::save_object(), and Body::save_object().
addValue() [3/3]
void ObjectSaving::addValue (std::string varName, std::string val, bool endStruct)
Adds a value to the file.
Parameters
varName - The name to store with the value
val - The value
endStruct - If in struct and not at end put true. Just adds comma
Returns
Void
Precondition
file is open
Postcondition
value added
Definition at line 57 of file ObjectSaving.cpp.
{
     outfile << varName << " = \"" << val << "\"";
     if (endStruct == false) {
         outfile << ",";
     }
     outfile << "\n";
 }
Referenced by TerrainObject::save_object(), Item::save_object(), and ScriptableObject::save_object().
closeFile()
void ObjectSaving::closeFile ()
Closes the file.
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
file closed
Definition at line 72 of file ObjectSaving.cpp.
 { outfile.close(); }
Referenced by TerrainObject::save_object(), Player::save_object(), Item::save_object(), ScriptableObject::save_object(), PhysicsObject::save_object(), Body::save_object(), and Water::save_object().
closeStruct()
void ObjectSaving::closeStruct ()
Closes the struct in the file.
Parameters
No param
Returns
Void
Precondition
file is open
Postcondition
end of struct added
Definition at line 70 of file ObjectSaving.cpp.
 { outfile << "}\n\n"; }
Referenced by TerrainObject::save_object(), Player::save_object(), Item::save_object(), ScriptableObject::save_object(), PhysicsObject::save_object(), Body::save_object(), and Water::save_object().
createStruct()
void ObjectSaving::createStruct (std::string structName)
Creates a struct in the file.
Parameters
structName - The name of the struct
Returns
Void
Precondition
file is open
Postcondition
start of struct added
Definition at line 66 of file ObjectSaving.cpp.
{
     outfile << structName << " = {\n";
 }
Referenced by TerrainObject::save_object(), and Item::save_object().
openFile()
void ObjectSaving::openFile ()
Opens a file to save data too.
Parameters
No param
Returns
Void
Precondition
nothing
Postcondition
file opened
Definition at line 34 of file ObjectSaving.cpp.
{
     outfile.open("scripts/save/" + std::to_string(number) + ".lua");
     appendCreationFile();
 }
References appendCreationFile().
Referenced by TerrainObject::save_object(), Player::save_object(), ScriptableObject::save_object(), Item::save_object(), PhysicsObject::save_object(), Body::save_object(), and Water::save_object().
saveGameObject()
void ObjectSaving::saveGameObject (glm::vec3 pos, glm::vec3 rot, glm::vec3 scale, float angle, std::string type)
Saves a base game object to a file.
Parameters
pos - The position of the base object
rot - The axis of rotation of the base object
scale - The scale of the base object
angle - The angle of rotation of the base object
type - The type of the object (e.g,. ScriptableObject)
Returns
Void
Precondition
file is open
Postcondition
base object paramaters saved
Definition at line 23 of file ObjectSaving.cpp.
{
     outfile << "baseObject = {\n"
             << "type = \"" << type << "\",\nxPos = " << pos.x
             << ",\nyPos = " << pos.y << ",\nzPos = " << pos.z
             << ",\nxRotation = " << rot.x << ",\nyRotation = " << rot.y
             << ",\nzRotation = " << rot.z << ",\nangle = " << angle
             << ",\nxScale = " << scale.x << ",\nyScale = " << scale.y
             << ",\nzScale = " << scale.z;
 }
setFreshSave()
void ObjectSaving::setFreshSave ()
Resets the number counter for the file name to 0.
Parameters
No param
Returns
Void
Precondition
nothing
Postcondition
counter reset
Definition at line 7 of file ObjectSaving.cpp.
 { number = 0; }
References number.
Referenced by TestScene::saveGameObjects().