My Project: aStar Namespace Reference
aStar Namespace Reference
Functions
std::vector< std::vector< DistanceNode > > aStarSearch (const std::vector< std::vector< int >> grid, const float movementCost[3], const float heuristicsCostScale, const int gridSize[2], const node start, const node goal, const float maxDistance)
The heart of the A star search algorithm.
void InitDefaultGrid (std::vector< std::vector< DistanceNode >> &grid, const int gridSize[2], const node start)
Sets up the inital grid with default values.
float ManhattanHeuristic (const float movementCost, node pos, const node goal)
Estimates distance between the current position and the goal using manhattan heuristic. I.e. cannot go diagonal.
float DiagonalHeuristic (const float movementCostManhattan, const float movementCostDiagonal, node pos, const node goal)
Estimates distance between the current position and the goal using diagonal heuristic. I.e. Can go diagonal.
bool IsDestination (node pos, const node goal)
Checks if the position is at the goal.
bool ValidPosition (node pos, int xSize, int ySize)
Checks that the position is inside the grid.
bool CellNotBlocked (node pos, const std::vector< std::vector< int >> &grid)
Checks that the cell is not blocked and can be moved into.
int FindLowestCost (std::vector< DistanceNode > &nodesToCheck)
Finds the nodes with the smallest distance cost and processes it.
Function Documentation
aStarSearch()
std::vector< std::vector< DistanceNode > > aStar::aStarSearch (const std::vector< std::vector< int >> grid, const float movementCost[3], const float heuristicsCostScale, const int gridSize[2], const node start, const node goal, const float maxDistance)
The heart of the A star search algorithm.
Parameters
grid - The grid of the area you are trying to move through
movementCost - [0] - horizontal movement cost [1] - diagonal movement cost [2] - allow diagonal movement
heuristicsCostScale - Change importance of speed or accuracy
gridSize - The size of the grid [0] - x size, [1] - y size
start - The starting position
goal - The goal position
maxDistance - The max distance the path can be
Exceptions
AStarException
Returns
An 2D distance node array to the grid size which has the path.
Definition at line 9 of file AStar.cpp.
{
     // Init grid used to store path
     std::vector<std::vector<DistanceNode>> distanceGrid;
     // Init grid default values & starting node
     InitDefaultGrid(distanceGrid, gridSize, start);
     // Make sure nodes are available
     if (IsDestination(start, goal) == true) throw(ALREADY_AT_DESTINATION);
     if (ValidPosition(start, gridSize[1], gridSize[0]) == false)
         throw(START_OUT_OF_BOUNDS);
     if (ValidPosition(goal, gridSize[1], gridSize[0]) == false)
         throw(GOAL_OUT_OF_BOUNDS);
     if (CellNotBlocked(start, grid) == false) throw(START_BLOCKED);
     if (CellNotBlocked(goal, grid) == false) throw(GOAL_BLOCKED);
     // Nodes which need to be checked for a shorter path
     std::vector<DistanceNode> nodesToCheck;
     // The nodes which have been already processed - set them to default false
     std::vector<std::vector<bool>> nodesChecked;
     std::vector<bool> row;
     for (int count = 0; count < gridSize[1]; count++) {
         row.push_back(false);
     }
     for (int count = 0; count < gridSize[0]; count++) {
         nodesChecked.push_back(row);
     }
     // Initialise nodeToCheck with inital node
     DistanceNode tempDistanceNode;
     tempDistanceNode.parentNode.x = start.x;
     tempDistanceNode.parentNode.y = start.y;
     tempDistanceNode.f = 0;
     nodesToCheck.push_back(tempDistanceNode);
     // If destination has been reached
     bool pathFound = false;
     DistanceNode distanceNodeChoosen, toAdd;
     int smallestIndex;
     node pos;
     int i = start.x, j = start.y;
     float gNew, hNew, fNew;
     // std::cout << "Movement Cost: " << movementCost[0] << ' ' <<
     // movementCost[1] << ' ' << movementCost[2] << std::endl;
     while (!nodesToCheck.empty() && pathFound == false) {
         // Finds smallest nodes in nodesToCheck and removes it from list and
         // processes it
         smallestIndex = FindLowestCost(nodesToCheck);
         distanceNodeChoosen = nodesToCheck[smallestIndex];
         if (distanceNodeChoosen.f > maxDistance) {
             throw(MAX_DISTANCE_REACHED);
         }
         // std::cout << "\n==ParentNode " << distanceNodeChoosen.parentNode.y <<
         // " " << distanceNodeChoosen.parentNode.x << std::endl;
         nodesToCheck.erase(nodesToCheck.begin() + smallestIndex);
         nodesChecked[distanceNodeChoosen.parentNode.y]
                     [distanceNodeChoosen.parentNode.x] = true;
         i = distanceNodeChoosen.parentNode.x;
         j = distanceNodeChoosen.parentNode.y;
         // Processes all nodes next to the choosen node which was found above
         for (int y = -1; y < 2; y++) {
             for (int x = -1; x < 2; x++) {
                 if (y == 0 && x == 0) {
                     continue;
                 }
                 if (movementCost[2] ==
                     0)  // Do not use diagonal if movementCost[2] == 0
                 {
                     if (y != 0 && x != 0) {
                         continue;
                     }
                 }
                 pos.x = i + x;
                 pos.y = j + y;
                 if (!ValidPosition(pos, gridSize[1], gridSize[0])) {
                     continue;
                 }
                 // std::cout << "POS" << pos.y << ' ' << pos.x << ' ';
                 if (IsDestination(pos, goal)) {
                     pathFound = true;
                     distanceGrid[pos.y][pos.x].parentNode.x = i;
                     distanceGrid[pos.y][pos.x].parentNode.y = j;
                     break;
                 } else if (nodesChecked[pos.y][pos.x] == false &&
                            CellNotBlocked(pos, grid)) {
                     if (y != 0 && x != 0) {
                         gNew = distanceGrid[j][i].g + movementCost[1];
                     }  // diagonal movement exact
                     else {
                         gNew = distanceGrid[j][i].g + movementCost[0];
                     }  // non-diagonal movement exact
                     if (movementCost[2] == 1) {
                         hNew = DiagonalHeuristic(movementCost[0],
                                                  movementCost[1], pos, goal);
                     }  // diagonal movement estimate
                     else {
                         hNew = ManhattanHeuristic(movementCost[0], pos, goal);
                     }  // non-diagonal movement estimate
                     fNew = gNew + (heuristicsCostScale * hNew);
                     // std::cout << " gNew: " << gNew << " - hNew: " << hNew <<
                     // " - fNew: " << fNew << std::endl;
                     if (distanceGrid[pos.y][pos.x].f == baseCost ||
                         distanceGrid[pos.y][pos.x].f > fNew) {
                         toAdd.parentNode.x = pos.x;
                         toAdd.parentNode.y = pos.y;
                         toAdd.f = fNew;
                         nodesToCheck.push_back(toAdd);
                         distanceGrid[pos.y][pos.x].f = fNew;
                         distanceGrid[pos.y][pos.x].h = hNew;
                         distanceGrid[pos.y][pos.x].g = gNew;
                         distanceGrid[pos.y][pos.x].parentNode.x = i;
                         distanceGrid[pos.y][pos.x].parentNode.y = j;
                     }
                 }
             }
             if (pathFound) {
                 break;
             }
         }
     }
     if (pathFound == false) throw(NO_PATH_FOUND);
     return distanceGrid;
 }
References ALREADY_AT_DESTINATION, CellNotBlocked(), DiagonalHeuristic(), DistanceNode::f, FindLowestCost(), DistanceNode::g, GOAL_BLOCKED, GOAL_OUT_OF_BOUNDS, DistanceNode::h, InitDefaultGrid(), IsDestination(), ManhattanHeuristic(), MAX_DISTANCE_REACHED, NO_PATH_FOUND, DistanceNode::parentNode, START_BLOCKED, START_OUT_OF_BOUNDS, ValidPosition(), node::x, and node::y.
Referenced by AStar::findPath().
CellNotBlocked()
bool aStar::CellNotBlocked (node pos, const std::vector< std::vector< int >> & grid)
Checks that the cell is not blocked and can be moved into.
Parameters
pos - The position of the node you want to check
&grid - The grid
Returns
true if not blocked else false
Definition at line 239 of file AStar.cpp.
{
     if (grid[pos.y][pos.x] == 0) return true;
     return false;
 }
Referenced by aStarSearch().
DiagonalHeuristic()
float aStar::DiagonalHeuristic (const float movementCostManhattan, const float movementCostDiagonal, node pos, const node goal)
Estimates distance between the current position and the goal using diagonal heuristic. I.e. Can go diagonal.
Parameters
movementCostManhattan - The movementCost to move horizontally
movementCostDiagonal - The movementCost to move diagonally
pos - The location of the position to start from
goal - The location of the position of the goal
Returns
The shortest estimated difference from the current position and goal
Definition at line 193 of file AStar.cpp.
{
     float dx = abs(pos.x - goal.x);
     float dy = abs(pos.y - goal.y);
     float min;
     if (dx < dy) {
         min = dx;
     } else {
         min = dy;
     }
     return movementCostManhattan * (dx + dy) +
            (movementCostDiagonal - 2 * movementCostManhattan) * min;
 }
References node::x, and node::y.
Referenced by aStarSearch().
FindLowestCost()
int aStar::FindLowestCost (std::vector< DistanceNode > & nodesToCheck)
Finds the nodes with the smallest distance cost and processes it.
Parameters
nodesToCheck - A 2D vector which stores all the nodes that need to be processed
Returns
int - A value of the index with the lowest cost
Definition at line 213 of file AStar.cpp.
{
     int size = nodesToCheck.size();
     int smallest = 0;
     for (int count = 1; count < size; count++) {
         if (nodesToCheck[smallest].f > nodesToCheck[count].f) smallest = count;
     }
     return smallest;
 }
References DistanceNode::f.
Referenced by aStarSearch().
InitDefaultGrid()
void aStar::InitDefaultGrid (std::vector< std::vector< DistanceNode >> & grid, const int gridSize[2], const node start)
Sets up the inital grid with default values.
Parameters
&grid - The grid
gridSize - The size of the grid
start - The starting position node
Definition at line 158 of file AStar.cpp.
                       {
     DistanceNode defaultDistanceNode;
     defaultDistanceNode.parentNode.x = baseParent;
     defaultDistanceNode.parentNode.y = baseParent;
     defaultDistanceNode.f = baseCost;
     defaultDistanceNode.g = baseCost;
     defaultDistanceNode.h = baseCost;
     std::vector<DistanceNode> row;
     for (int count = 0; count < gridSize[1]; count++) {
         row.push_back(defaultDistanceNode);
     }
     for (int count = 0; count < gridSize[0]; count++) {
         distanceGrid.push_back(row);
     }
     distanceGrid[start.y][start.x].parentNode.x = start.x;
     distanceGrid[start.y][start.x].parentNode.y = start.y;
     distanceGrid[start.y][start.x].f = 0;
     distanceGrid[start.y][start.x].g = 0;
     distanceGrid[start.y][start.x].h = 0;
     return;
 }
References DistanceNode::f, DistanceNode::g, DistanceNode::h, DistanceNode::parentNode, node::x, and node::y.
Referenced by aStarSearch().
IsDestination()
bool aStar::IsDestination (node pos, const node goal)
Checks if the position is at the goal.
Parameters
pos - The location of the position to start from
goal - The location of the position of the goal
Returns
True if position is at the goal else false
Definition at line 224 of file AStar.cpp.
{
     if (pos.x == goal.x && pos.y == goal.y) {
         return true;
     } else {
         return false;
     }
 }
References node::x, and node::y.
Referenced by aStarSearch().
ManhattanHeuristic()
float aStar::ManhattanHeuristic (const float movementCost, node pos, const node goal)
Estimates distance between the current position and the goal using manhattan heuristic. I.e. cannot go diagonal.
Parameters
movementCost - The movementCost to move horizontally
pos - The location of the position to start from
goal - The location of the position of the goal
Returns
The shortest estimated difference from the current position and goal
Definition at line 188 of file AStar.cpp.
{
     return movementCost * (abs(pos.x - goal.x) + abs(pos.y - goal.y));
 }
References node::x, and node::y.
Referenced by aStarSearch().
ValidPosition()
bool aStar::ValidPosition (node pos, int xSize, int ySize)
Checks that the position is inside the grid.
Parameters
pos - The position of the node you want to check
xSize - The size of the grid in the x direction
ySize - The size of the grid in the y direction
Returns
true if inside else false
Definition at line 232 of file AStar.cpp.
{
     if (pos.x >= xSize || pos.x < 0) return false;
     if (pos.y >= ySize || pos.y < 0) return false;
     return true;
 }
References node::x, and node::y.
Referenced by aStarSearch().