ICT397 Assignment 2: gui Namespace Reference
gui Namespace Reference
Enumerations
enum { SET_WINDOW_CONSTRAINTS_ALWAYS = 1, SET_WINDOW_CONSTRAINTS_ON_EXECUTION = 2, SET_WINDOW_CONSTRAINT_ON_FIRST_USE_EVER = 4, SET_WINDOW_CONSTRAINTS_WHEN_ACTIVATED = 8 }
Functions
void init (GLFWwindow *window, const std::string &openglVersion)
Initialises gui.
void lua_access ()
void mainLoopStart ()
Does per frame initialise for gui. Should be placed after glClear & glClearColor in the main loop.
void mainLoopEnd ()
Renders gui. Should be placed at the end of the main loop.
void shutdown ()
Shuts down gui.
void begin (const std::string &title)
Begins a window. Sandwich inside gui window methods between begin and end.
void end ()
Ends the window. Sandwich inside gui window methods between begin and end.
void setWindowPos (int xPos, int yPos, int constraint)
Sets the windows position.
void setWindowSize (int xSize, int ySize, int constraint)
Sets the windows size.
void text (const std::string &text)
Displays text in the gui window.
void checkbox (const std::string &name, bool *option)
A checkbox which changes a boolean variable between true & false. Not lua ready.
bool luaCheckBox (const std::string &name, bool state)
A checkbox which changes a boolean variable between true & false. Lua ready.
void sliderFloat (const std::string &name, float *value, float min, float max)
A slider which changes a float variable between min & max.
void sliderInt (const std::string &name, int *value, int min, int max)
A slider which changes an integer variable between min & max.
void sliderAngle (const std::string &name, float *angle, float min, float max)
A slider which changes an angle variable between min & max.
void colourEdit3 (const std::string &name, float colour[3])
Can change values independently or use a colour picker.
void colourEdit4 (const std::string &name, float colour[4])
Can change values independently or use a colour picker.
void lua_image (const std::string &texture_name)
Creates an image using a texture name.
void image (uint32_t texture_id, int width, int height)
Adds an image to the gui using a texture.
bool button (const std::string &name, int xSize, int ySize)
Creates a button.
std::string luaInputText (const std::string &name)
User can enter text into box and submit it with enter. Lua script ready.
bool inputText (const std::string &name, char *buffer, int size)
User can enter text into box and submit it with enter. Not lua script ready.
bool collapsingHeader (const std::string &name)
Creates a collapsing header (essentially a checkbox)
void plotLines (const std::string &name, const float *values, int numOfEntries)
Creates a plot line.
void plotLines (const std::string &name, const float *values, int numOfEntries, float xWindowSize, float yWindowSize)
Creates a plot line.
void plotLines (const std::string &name, const float *values, int numOfEntries, float minVal, float maxVal, float xWindowSize, float yWindowSize)
Creates a plot line.
void progressBar (float percentage)
Create a progress bar.
float guiFrameRate ()
Returns the gui framerate.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SET_WINDOW_CONSTRAINTS_ALWAYS
Window constraints always enforced. I.e., window size & pos
SET_WINDOW_CONSTRAINTS_ON_EXECUTION
Window constraints enforced on program execution. I.e., window size & pos
SET_WINDOW_CONSTRAINT_ON_FIRST_USE_EVER
Window constraints enforced on first ever launch. I.e., window size & pos
SET_WINDOW_CONSTRAINTS_WHEN_ACTIVATED
Window constraints enforced when window appears. I.e., window size & pos
Definition at line 312 of file guiManager.hpp.
      {
     SET_WINDOW_CONSTRAINTS_ALWAYS = 1,
     SET_WINDOW_CONSTRAINTS_ON_EXECUTION = 2,
     SET_WINDOW_CONSTRAINT_ON_FIRST_USE_EVER = 4,
     SET_WINDOW_CONSTRAINTS_WHEN_ACTIVATED = 8,
 };
Function Documentation
begin()
void gui::begin (const std::string & title)
Begins a window. Sandwich inside gui window methods between begin and end.
Parameters
title - The title of the window
Precondition
rui running
Postcondition
window created
Definition at line 58 of file guiManager.cpp.
 { ImGui::Begin(title.c_str()); }
button()
bool gui::button (const std::string & name, int xSize, int ySize)
Creates a button.
Parameters
name - The name of the button
xSize - The x size of the button (width)
ySize - The y size of the button (height)
Returns
bool - If it has been pressed
Precondition
window created
Postcondition
module added
Definition at line 124 of file guiManager.cpp.
{
     return ImGui::Button(name.c_str(), ImVec2(xSize, ySize));
 }
checkbox()
void gui::checkbox (const std::string & name, bool * option)
A checkbox which changes a boolean variable between true & false. Not lua ready.
Parameters
name - The name of the value you are changing
*option - The boolean which is being changed
Precondition
window created
Postcondition
module added
Definition at line 72 of file guiManager.cpp.
{
     ImGui::Checkbox(name.c_str(), option);
 }
collapsingHeader()
bool gui::collapsingHeader (const std::string & name)
Creates a collapsing header (essentially a checkbox)
Parameters
name - The name of the collapsing header
Returns
bool - If it is open or closed
Precondition
window created
Postcondition
module added
Definition at line 148 of file guiManager.cpp.
{
     return ImGui::CollapsingHeader(name.c_str());
 }
colourEdit3()
void gui::colourEdit3 (const std::string & name, float colour[3])
Can change values independently or use a colour picker.
Parameters
name - The name of the value you are changing
colour - Float of 3 different variables
Precondition
window created
Postcondition
module added
Definition at line 95 of file guiManager.cpp.
{
     ImGui::ColorEdit3(name.c_str(), colour);
 }
colourEdit4()
void gui::colourEdit4 (const std::string & name, float colour[4])
Can change values independently or use a colour picker.
Parameters
name - The name of the value you are changing
colour - Float of 4 different variables
Precondition
window created
Postcondition
module added
Definition at line 99 of file guiManager.cpp.
{
     ImGui::ColorEdit4(name.c_str(), colour);
 }
end()
void gui::end ()
Ends the window. Sandwich inside gui window methods between begin and end.
Precondition
window created
Postcondition
window ended
Definition at line 60 of file guiManager.cpp.
 { ImGui::End(); }
guiFrameRate()
float gui::guiFrameRate ()
Returns the gui framerate.
Parameters
No param
Returns
float - The frame rate
Precondition
gui running
Postcondition
framerate returned
Definition at line 122 of file guiManager.cpp.
 { return ImGui::GetIO().Framerate; }
image()
void gui::image (uint32_t texture_id, int width, int height)
Adds an image to the gui using a texture.
Parameters
texture_id
width
height
Definition at line 113 of file guiManager.cpp.
{
     ImGui::Image((void*)(intptr_t)texture_id, ImVec2(width, height));
 }
init()
void gui::init (GLFWwindow * window, const std::string & openglVersion)
Initialises gui.
Parameters
window - The GLFW window
openglVersion - String of opengl version. I.e., OpenGL 4.6 uses "#version 460", check imGUI documentation if unsure
Precondition
GLFW window & correct opengl version
Postcondition
gui initialised
Definition at line 6 of file guiManager.cpp.
{
     IMGUI_CHECKVERSION();
     ImGui::CreateContext();
     ImGuiIO& io = ImGui::GetIO();
     (void)io;
     ImGui::StyleColorsDark();
     ImGui_ImplGlfw_InitForOpenGL(window, true);
     ImGui_ImplOpenGL3_Init(openglVersion.c_str());
     lua_access();
 }
References lua_access().
inputText()
bool gui::inputText (const std::string & name, char * buffer, int size)
User can enter text into box and submit it with enter. Not lua script ready.
Parameters
name - The name of the input text
*buffer - Where to store the text input
size - The size of the buffer
Returns
bool - If it contains a character
Precondition
window created
Postcondition
module added
Definition at line 144 of file guiManager.cpp.
{
     return ImGui::InputText(name.c_str(), buffer, size);
 }
lua_access()
void gui::lua_access ()
Definition at line 18 of file guiManager.cpp.
                      {
     auto& lua = LuaManager::get_instance().get_state();
     lua.set_function("gui_begin", gui::begin);
     lua.set_function("gui_end", gui::end);
     lua.set_function("gui_text", gui::text);
     lua.set_function("gui_setWindowPos", gui::setWindowPos);
     lua.set_function("gui_setWindowSize", gui::setWindowSize);
     lua.set_function("gui_luaCheckbox", gui::luaCheckBox);
     lua.set_function("gui_sliderFloat", gui::sliderFloat);
     lua.set_function("gui_sliderInt", gui::sliderInt);
     lua.set_function("gui_sliderAngle", gui::sliderAngle);
     lua.set_function("gui_colourEdit3", gui::colourEdit3);
     lua.set_function("gui_colourEdit4", gui::colourEdit4);
     lua.set_function("gui_luaInputText", gui::luaInputText);
     lua.set_function("gui_collapsingHeader", gui::collapsingHeader);
     lua.set_function("gui_progressBar", gui::progressBar);
     lua.set_function("gui_guiFrameRate", gui::guiFrameRate);
     lua.set_function("gui_button", gui::button);
     lua.set_function("gui_image", gui::lua_image);
     //  lua.set_function("gui_plotLines", gui::plotLines);
 }
Referenced by init().
lua_image()
void gui::lua_image (const std::string & texture_name)
Creates an image using a texture name.
Parameters
texture_name
Definition at line 103 of file guiManager.cpp.
{
     auto& texture_manager =
         ResourceManager::get_instance().get_texture_manager();
     const auto& texture = texture_manager.get_texture(texture_name);
     gui::image(texture.get_texture_id(), texture.get_width(),
                texture.get_height());
 }
References ResourceManager::get_instance(), TextureManager::get_texture(), and ResourceManager::get_texture_manager().
luaCheckBox()
bool gui::luaCheckBox (const std::string & name, bool state)
A checkbox which changes a boolean variable between true & false. Lua ready.
Parameters
name - The name of the value you are changing
state - current state of checkbox
Returns
bool - Current checkbox state
Precondition
window created
Postcondition
module added
Definition at line 76 of file guiManager.cpp.
{
     static std::map<std::string, bool> checkBoxes;
     if (checkBoxes.find(name) == checkBoxes.end()) {
         checkBoxes.insert(std::pair<std::string, bool>(name, state));
     }
     ImGui::Checkbox(name.c_str(), &checkBoxes[name]);
     return checkBoxes[name];
 }
luaInputText()
std::string gui::luaInputText (const std::string & name)
User can enter text into box and submit it with enter. Lua script ready.
Parameters
name - The name of the input text
Returns
std::stirng - String of the current buffer
Precondition
window created
Postcondition
module added
Definition at line 128 of file guiManager.cpp.
{
     char newBuffer[30] =
         {};  // Could make this static to fix it but its such a crappy way to do
              // it (as you can only have one InputText really)
     ImGui::InputText(name.c_str(), newBuffer, 30);
     /*
     if (ret) {
         std::string savedBuffer(newBuffer);
         return savedBuffer;
     } else {
         return newBuffer;
     }
     */
     return newBuffer;
 }
mainLoopEnd()
void gui::mainLoopEnd ()
Renders gui. Should be placed at the end of the main loop.
Precondition
mainLoopStart has been run
Postcondition
ends gui frame
Definition at line 47 of file guiManager.cpp.
                       {
     ImGui::Render();
     ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
 }
mainLoopStart()
void gui::mainLoopStart ()
Does per frame initialise for gui. Should be placed after glClear & glClearColor in the main loop.
Precondition
Init has been run for the window
Postcondition
start gui frame
Definition at line 41 of file guiManager.cpp.
{
     ImGui_ImplOpenGL3_NewFrame();
     ImGui_ImplGlfw_NewFrame();
     ImGui::NewFrame();
 }
plotLines() [1/3]
void gui::plotLines (const std::string & name, const float * values, int numOfEntries)
Creates a plot line.
Parameters
name - The name to be displayed
*values - The list of values
numOfEntries - The number of values
Precondition
window created
Postcondition
module added
Definition at line 152 of file guiManager.cpp.
{
     ImGui::PlotLines(name.c_str(), values, numOfEntries);
 }
plotLines() [2/3]
void gui::plotLines (const std::string & name, const float * values, int numOfEntries, float minVal, float maxVal, float xWindowSize, float yWindowSize)
Creates a plot line.
Parameters
name - The name to be displayed
*values - The list of values
numOfEntries - The number of values
minVal - The minimum value (where graph ends)
maxVal - The maximum value (where graph ends)
xWindowSize - Size of window in x direction
yWindowSize - Size of window in y direction
Precondition
window created
Postcondition
module added
Definition at line 162 of file guiManager.cpp.
{
     ImGui::PlotLines(name.c_str(), values, numOfEntries, 0, "", minVal, maxVal,
                      ImVec2(xWindowSize, yWindowSize));
 }
plotLines() [3/3]
void gui::plotLines (const std::string & name, const float * values, int numOfEntries, float xWindowSize, float yWindowSize)
Creates a plot line.
Parameters
name - The name to be displayed
*values - The list of values
numOfEntries - The number of values
xWindowSize - Size of window in x direction
yWindowSize - Size of window in y direction
Precondition
window created
Postcondition
module added
Definition at line 157 of file guiManager.cpp.
{
     plotLines(name, values, numOfEntries, xWindowSize, yWindowSize);
 }
References plotLines().
Referenced by plotLines().
progressBar()
void gui::progressBar (float percentage)
Create a progress bar.
Parameters
percentage - The percentage (0 - 100)
Precondition
window created
Postcondition
module added
Definition at line 169 of file guiManager.cpp.
{
     ImGui::ProgressBar(percentage / 100);
 }
setWindowPos()
void gui::setWindowPos (int xPos, int yPos, int constraint)
Sets the windows position.
Parameters
xPos - x position of the window
yPos - y position of the window
constraint - The constraint of the window
Precondition
window created
Postcondition
window position adjusted
Definition at line 62 of file guiManager.cpp.
{
     ImGui::SetNextWindowPos(ImVec2(xPos, yPos), constraint);
 }
setWindowSize()
void gui::setWindowSize (int xSize, int ySize, int constraint)
Sets the windows size.
Parameters
xSize - x size of the window
ySize - y size of the window
constraint - The constraint of the window
Precondition
window created
Postcondition
window size adjusted
Definition at line 66 of file guiManager.cpp.
{
     ImGui::SetNextWindowSize(ImVec2(xSize, ySize), constraint);
 }
shutdown()
void gui::shutdown ()
Shuts down gui.
Precondition
gui running
Postcondition
gui stopped
Definition at line 52 of file guiManager.cpp.
                    {
     ImGui_ImplOpenGL3_Shutdown();
     ImGui_ImplGlfw_Shutdown();
     ImGui::DestroyContext();
 }
Referenced by ReflexEngine::run().
sliderAngle()
void gui::sliderAngle (const std::string & name, float * angle, float min, float max)
A slider which changes an angle variable between min & max.
Parameters
name - The name of the value you are changing
*angle - The angle you want to change
min - The minimum angle
max - The maximum angle
Precondition
window created
Postcondition
module added
Definition at line 117 of file guiManager.cpp.
{
     ImGui::SliderAngle(name.c_str(), angle, min, max);
 }
sliderFloat()
void gui::sliderFloat (const std::string & name, float * value, float min, float max)
A slider which changes a float variable between min & max.
Parameters
name - The name of the value you are changing
*value - The value being changed
min - The minimum value of the value
max - The maximum value of the value
Precondition
window created
Postcondition
module added
Definition at line 86 of file guiManager.cpp.
{
     ImGui::SliderFloat(name.c_str(), value, min, max);
 }
sliderInt()
void gui::sliderInt (const std::string & name, int * value, int min, int max)
A slider which changes an integer variable between min & max.
Parameters
name - The name of the value you are changing
*value - The value being changed
min - The minimum value of the value
max - The maximum value of the value
Precondition
window created
Postcondition
module added
Definition at line 91 of file guiManager.cpp.
{
     ImGui::SliderInt(name.c_str(), value, min, max);
 }
text()
void gui::text (const std::string & text)
Displays text in the gui window.
Parameters
text - The text you want to display
Precondition
window created
Postcondition
module added
Definition at line 70 of file guiManager.cpp.
 { ImGui::Text(text.c_str()); }