ICT397 Assignment 2: GenericFunctions Namespace Reference
GenericFunctions Namespace Reference
Functions
void lua_access ()
Exposes generic functions methods to lua.
int get_window_width ()
Get the window width.
int get_window_height ()
Get the window height.
void init_random (int seed, bool useSeed)
Initialises rand.
int get_random (int min, int max)
Gets a random number.
bool getIfSave ()
gets if the game should be saved
void setIfSave (bool val)
Sets if the game should be saved.
void resetSaveSinceLastSave ()
Resets the time since the last save.
int timeAtLastSave ()
Gets time when the game was last saved.
int timeAtLastLoad ()
Gets time when the game was last loaded.
int get_time ()
Gets time.
bool getIfLoad ()
Gets if the game should load game objects from save.
void setIfLoad (bool val)
Set if game should load objects from save.
bool getIfFullLoad ()
Gets if the game should load game objects from scratch.
void setIfFullLoad (bool val)
Set if game should load objects from scratch.
bool getIfPaused ()
Gets if the game should be paused.
void setIfPaused (bool val)
Sets if the game should be paused.
void exitEngine ()
Exits the game.
void setifHelpMenuActive (bool val)
Sets if the game should show the help menu.
bool getIfHelpMenuActive ()
gets if the game should show the help menu
void set_if_credits_active (bool val)
Set the if credits active.
bool get_if_credits_active ()
Get the if credits active.
float luaCamPosX ()
gets camera x position
float luaCamPosY ()
gets camera y position
float luaCamPosZ ()
gets camera z position
float luaCamLookX ()
gets camera x look
float luaCamLookY ()
gets camera y look
float luaCamLookZ ()
gets camera z look
void setLastShot ()
Sets when the last shoot was fired (time of this function being called)
void setShotDelay (float delay)
Sets delay between shots.
void setIfShouldShoot (bool val)
Sets if the player should shoot.
bool getIfShouldShoot ()
Gets if the player should shoot.
void setPlayableArea (uint8_t *heightmap, TexturedTerrain *tt, float scale, int size)
float getHeight (float x, float z)
uint8_t * get_height_map ()
void createNetworkManager (bool create)
Creates the network manager.
void setNetworkMenuActive (bool active)
Sets the network menu to be active or not.
bool getNetworkMenuActive ()
Gets the active state of the network menu.
void startNetworkServer (bool active)
Starts up the network server.
void networkClientConnect ()
Connects the client to a server.
void networkEnd ()
Ends the connection to the network (if client)/Kills the server (if server)
void networkUpdate ()
Updates the networkManager (primary used for sending/receiving data). Current use is for connected clients and connection status.
bool networkConnectionStatus ()
Gets the connection status of the network (if it is connected to either a client or server)
void networkRetainIP (std::string savedIP)
Retains the IP address entered by the user (catches input that the user has entered with guiManager)
void networkRetainMessage (std::string savedMessage)
Retains the message entered by the user (catches input that the user has entered with guiManager)
std::string networkReturnRetainedMessage ()
Returns the message saved by networkRetainMessage.
void networkSendMessage ()
Sends the message saved in networkRetainMessage across the network.
std::string networkGetMessage ()
Gets a message received across the network.
bool networkValidChatMessage ()
Checks if the chat message in networkGetMessage is valid or not.
bool networkConnectedSafe ()
Checks if the network has connected.
void networkRetainUsername (std::string savedUsername)
Checks if the chat message in networkGetMessage is valid or not.
void networkSetUsername ()
Sets the username of the player.
std::string networkReturnUsername ()
Returns the username saved in networkRetainUsername.
void setPvPNetworkMenuActive (bool active)
Sets the pvp network menu to be active or inactive.
bool getPvPNetworkMenuActive ()
Gets if the pvp network menu is active.
float getNetworkPosX ()
Gets the network position of the other player.
float getNetworkPosY ()
Gets the network position of the other player.
float getNetworkPosZ ()
Gets the network position of the other player.
bool getReceivingData ()
Checks if the pvp network manager is receiving data.
bool networkPvPConnectionStatus ()
Gets the connection status for the pvp network manager.
void networkFixedUpdate ()
Fixed update loop for the network manager. Primarily used for object replication to improve network performance.
std::string networkReturnRetainedIP ()
Returns the IP address saved by networkRetainIP.
float getLength (float x, float y)
Function Documentation
createNetworkManager()
void GenericFunctions::createNetworkManager (bool create)
Creates the network manager.
Parameters
create - if you want to create it
Precondition
Nothing
Postcondition
Creates the network manager
Definition at line 241 of file GenericFunctions.cpp.
{
     if (createNetwork != true && !networkMenuPvP) {
         createNetwork = true;
         network.InitNetwork();
     } else if (createPvPNetwork != true) {
         createPvPNetwork = true;
         networkPvP.InitNetwork();
     }
 }
References createNetwork, createPvPNetwork, networkManager::InitNetwork(), network, networkMenuPvP, and networkPvP.
exitEngine()
void GenericFunctions::exitEngine ()
Exits the game.
Precondition
Nothing
Postcondition
Exits engine
Definition at line 182 of file GenericFunctions.cpp.
{
     ReflexEngine::get_instance().window_.set_should_close(true);
 }
get_height_map()
uint8_t * GenericFunctions::get_height_map ()
Definition at line 239 of file GenericFunctions.cpp.
 { return m_tt->get_height_map(); }
get_if_credits_active()
bool GenericFunctions::get_if_credits_active ()
Get the if credits active.
Returns
true
false
Definition at line 192 of file GenericFunctions.cpp.
 { return credits; }
References credits.
Referenced by TestScene::key_controls().
get_random()
int GenericFunctions::get_random (int min, int max)
Gets a random number.
Parameters
min - The minimum value
max - The maximum value
Returns
int - The value generated
Precondition
Nothing
Postcondition
gets random number
Definition at line 129 of file GenericFunctions.cpp.
{
     if (m_initRandom == false) {
         init_random(0, true);
     }
     return rand() % max + min;
 }
References init_random(), and m_initRandom.
get_time()
int GenericFunctions::get_time ()
Gets time.
Returns
int - The time
Definition at line 136 of file GenericFunctions.cpp.
 { return glfwGetTime(); }
get_window_height()
int GenericFunctions::get_window_height ()
Get the window height.
Returns
int
Definition at line 125 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().window_.get_buffer_height();
 }
get_window_width()
int GenericFunctions::get_window_width ()
Get the window width.
Returns
int
Definition at line 121 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().window_.get_buffer_width();
 }
getHeight()
float GenericFunctions::getHeight (float x, float z)
Definition at line 233 of file GenericFunctions.cpp.
{
     return m_tt->get_height_world(x - m_playable_floor_size / 2,
                                   z - m_playable_floor_size / 2) *
            m_playable_floor_y_scale;
 }
getIfFullLoad()
bool GenericFunctions::getIfFullLoad ()
Gets if the game should load game objects from scratch.
Returns
bool - If it should load
Precondition
Nothing
Postcondition
retrieves value
Definition at line 164 of file GenericFunctions.cpp.
 { return shouldFullLoad; }
References shouldFullLoad.
Referenced by TestScene::loadSavedGameObjects().
getIfHelpMenuActive()
bool GenericFunctions::getIfHelpMenuActive ()
gets if the game should show the help menu
Returns
bool - True if should show help menu
Precondition
Nothing
Postcondition
gets value
Definition at line 188 of file GenericFunctions.cpp.
 { return helpMenu; }
References helpMenu.
Referenced by TestScene::key_controls().
getIfLoad()
bool GenericFunctions::getIfLoad ()
Gets if the game should load game objects from save.
Returns
bool - If it should load
Precondition
Nothing
Postcondition
retrieves value
Definition at line 155 of file GenericFunctions.cpp.
 { return shouldLoad; }
References shouldLoad.
getIfPaused()
bool GenericFunctions::getIfPaused ()
Gets if the game should be paused.
Returns
bool - True if game is paused
Precondition
Nothing
Postcondition
retrieves value
Definition at line 168 of file GenericFunctions.cpp.
 { return EngineTime::is_paused(); }
References EngineTime::is_paused().
Referenced by TestScene::key_controls().
getIfSave()
bool GenericFunctions::getIfSave ()
gets if the game should be saved
Returns
bool - true if it should be saved
Precondition
Nothing
Postcondition
retrieves value
Definition at line 138 of file GenericFunctions.cpp.
 { return shouldSave; }
References shouldSave.
getIfShouldShoot()
bool GenericFunctions::getIfShouldShoot ()
Gets if the player should shoot.
Returns
bool - true if should shoot
Precondition
Nothing
Postcondition
gets value
Definition at line 223 of file GenericFunctions.cpp.
 { return shouldShoot; }
References shouldShoot.
getLength()
float GenericFunctions::getLength (float x, float y)
Definition at line 435 of file GenericFunctions.cpp.
{
     return sqrt(pow(x, 2) + pow(y, 2));
 }
getNetworkMenuActive()
bool GenericFunctions::getNetworkMenuActive ()
Gets the active state of the network menu.
Returns
bool - if active
Precondition
Nothing
Postcondition
Gets the active state of the network menu
Definition at line 335 of file GenericFunctions.cpp.
 { return (networkMenu); }
References networkMenu.
Referenced by TestScene::key_controls().
getNetworkPosX()
float GenericFunctions::getNetworkPosX ()
Gets the network position of the other player.
Returns
float - get x coordinate position
Precondition
Nothing
Postcondition
Returns the x coordinate of the networked object
Definition at line 426 of file GenericFunctions.cpp.
 { return opponentPos.x; }
getNetworkPosY()
float GenericFunctions::getNetworkPosY ()
Gets the network position of the other player.
Returns
float - get y coordinate position
Precondition
Nothing
Postcondition
Returns the y coordinate of the networked object
Definition at line 428 of file GenericFunctions.cpp.
 { return opponentPos.y; }
getNetworkPosZ()
float GenericFunctions::getNetworkPosZ ()
Gets the network position of the other player.
Returns
float - get z coordinate position
Precondition
Nothing
Postcondition
Returns the z coordinate of the networked object
Definition at line 430 of file GenericFunctions.cpp.
 { return opponentPos.z; }
getPvPNetworkMenuActive()
bool GenericFunctions::getPvPNetworkMenuActive ()
Gets if the pvp network menu is active.
Returns
bool
Precondition
Nothing
Postcondition
Returns true if the pvp network menu is active
Definition at line 424 of file GenericFunctions.cpp.
 { return networkMenuPvP; }
References networkMenuPvP.
Referenced by TestScene::key_controls().
getReceivingData()
bool GenericFunctions::getReceivingData ()
Checks if the pvp network manager is receiving data.
Returns
bool
Precondition
Nothing
Postcondition
Returns true if the network manager is receiving valid data and it is not invalid
Definition at line 432 of file GenericFunctions.cpp.
{
     return !networkPvP.ObjectMissedData();
 }
References networkPvP, and networkManager::ObjectMissedData().
Referenced by networkFixedUpdate(), and NetworkedItem::update().
init_random()
void GenericFunctions::init_random (int seed, bool useSeed)
Initialises rand.
Parameters
seed - The seed of the random generator
useSeed - If you want to use the seed or just use time
Precondition
Nothing
Postcondition
initialises rand
Definition at line 41 of file GenericFunctions.cpp.
{
     m_useSeed = useSeed;
     m_seed = seed;
     if (m_useSeed == true) {
         srand(m_seed);
     } else {
         srand(time(nullptr));
     }
     m_initRandom = true;
 }
References m_initRandom, m_seed, and m_useSeed.
Referenced by get_random(), and TestScene::loadSavedGameObjects().
lua_access()
void GenericFunctions::lua_access ()
Exposes generic functions methods to lua.
Precondition
Nothing
Postcondition
Exposes funciton to lua
Definition at line 53 of file GenericFunctions.cpp.
{
     sol::state& lua = LuaManager::get_instance().get_state();
     lua.set_function("window_width", get_window_width);
     lua.set_function("window_height", get_window_height);
     lua.set_function("random_generator", get_random);
     lua.set_function("current_time", get_time);
     lua.set_function("save_game", setIfSave);
     lua.set_function("resetSaveTime", resetSaveSinceLastSave);
     lua.set_function("load_game", setIfLoad);
     lua.set_function("get_load", getIfLoad);
     lua.set_function("load_from_scratch", setIfFullLoad);
     lua.set_function("time_since_last_save", timeAtLastSave);
     lua.set_function("time_since_last_load", timeAtLastLoad);
     lua.set_function("set_pause_game", setIfPaused);
     lua.set_function("get_pause_game", getIfPaused);
     lua.set_function("exit_game", exitEngine);
     lua.set_function("set_help_menu", setifHelpMenuActive);
     lua.set_function("get_help_menu", getIfHelpMenuActive);
     lua.set_function("set_credits", set_if_credits_active);
     lua.set_function("get_credits", get_if_credits_active);
     lua.set_function("camera_pos_x", luaCamPosX);
     lua.set_function("camera_pos_y", luaCamPosY);
     lua.set_function("camera_pos_z", luaCamPosZ);
     lua.set_function("camera_look_x", luaCamLookX);
     lua.set_function("camera_look_y", luaCamLookY);
     lua.set_function("camera_look_z", luaCamLookZ);
     // For general network functionality
     lua.set_function("create_network_manager", createNetworkManager);
     lua.set_function("exit_network_menu", setNetworkMenuActive);
     lua.set_function("get_network_menu", getNetworkMenuActive);
     lua.set_function("start_server", startNetworkServer);
     lua.set_function("network_client_connect", networkClientConnect);
     lua.set_function("network_terminate", networkEnd);
     lua.set_function("network_connection_status", networkConnectionStatus);
     lua.set_function("network_retain_IP", networkRetainIP);
     lua.set_function("network_return_IP", networkReturnRetainedIP);
     // For network chat functionality
     lua.set_function("network_retain_message", networkRetainMessage);
     lua.set_function("network_return_message", networkReturnRetainedMessage);
     lua.set_function("network_send_message", networkSendMessage);
     lua.set_function("network_get_message", networkGetMessage);
     lua.set_function("network_has_valid_message", networkValidChatMessage);
     lua.set_function("network_connected", networkConnectedSafe);
     lua.set_function("network_retain_username", networkRetainUsername);
     lua.set_function("network_return_username", networkReturnUsername);
     lua.set_function("network_set_username", networkSetUsername);
     // For network replication functionality
     lua.set_function("exit_pvp_network_menu", setPvPNetworkMenuActive);
     lua.set_function("get_pvp_network_menu", getPvPNetworkMenuActive);
     lua.set_function("get_network_pos_x", getNetworkPosX);
     lua.set_function("get_network_pos_y", getNetworkPosY);
     lua.set_function("get_network_pos_z", getNetworkPosZ);
     lua.set_function("get_receiving_data", getReceivingData);
     lua.set_function("network_pvp_connection_status",
                      networkPvPConnectionStatus);
     lua.set_function("set_last_shot", setLastShot);
     lua.set_function("set_shot_delay", setShotDelay);
     lua.set_function("set_if_should_shoot", setIfShouldShoot);
     lua.set_function("get_if_should_shoot", getIfShouldShoot);
     lua.set_function("get_y_coord_on_floor", getHeight);
     lua.set_function("vector2Length", getLength);
 }
Referenced by ReflexEngine::run().
luaCamLookX()
float GenericFunctions::luaCamLookX ()
gets camera x look
Returns
float - x look
Precondition
Nothing
Postcondition
gets value
Definition at line 204 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().camera_.get_direction().x;
 }
luaCamLookY()
float GenericFunctions::luaCamLookY ()
gets camera y look
Returns
float - y look
Precondition
Nothing
Postcondition
gets value
Definition at line 207 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().camera_.get_direction().y;
 }
luaCamLookZ()
float GenericFunctions::luaCamLookZ ()
gets camera z look
Returns
float - z look
Precondition
Nothing
Postcondition
gets value
Definition at line 210 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().camera_.get_direction().z;
 }
luaCamPosX()
float GenericFunctions::luaCamPosX ()
gets camera x position
Returns
float - x position
Precondition
Nothing
Postcondition
gets value
Definition at line 194 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().camera_.get_position().x;
 }
luaCamPosY()
float GenericFunctions::luaCamPosY ()
gets camera y position
Returns
float - y position
Precondition
Nothing
Postcondition
gets value
Definition at line 197 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().camera_.get_position().y;
 }
luaCamPosZ()
float GenericFunctions::luaCamPosZ ()
gets camera z position
Returns
float - z position
Precondition
Nothing
Postcondition
gets value
Definition at line 200 of file GenericFunctions.cpp.
{
     return ReflexEngine::get_instance().camera_.get_position().z;
 }
networkClientConnect()
void GenericFunctions::networkClientConnect ()
Connects the client to a server.
Precondition
CreateNetworkManager called (for initialisation)
Postcondition
Connects the client to a server using provided IP
Definition at line 272 of file GenericFunctions.cpp.
{
     if (!networkMenuPvP) {
         char serverIPChar[30];
         strcpy(serverIPChar, currentIPAddress.c_str());
         printf("This Runs\n");
         printf("%s\n", currentIPAddress.c_str());
         network.SetupClient(username);
         networkConnected = !network.ConnectClient(
             serverIPChar);  // Flipped as it returns true if you are NOT
                             // connected (which is weird I know)
     } else {
         char serverIPChar[30];
         strcpy(serverIPChar, currentIPAddress.c_str());
         printf("This Runs\n");
         printf("%s\n", currentIPAddress.c_str());
         networkPvP.SetupClient(username);
         pvpNetworkConnected = !networkPvP.ConnectClient(
             serverIPChar);  // Flipped as it returns true if you are NOT
                             // connected (which is weird I know)
     }
 }
References networkManager::ConnectClient(), currentIPAddress, network, networkConnected, networkMenuPvP, networkPvP, pvpNetworkConnected, networkManager::SetupClient(), and username.
networkConnectedSafe()
bool GenericFunctions::networkConnectedSafe ()
Checks if the network has connected.
Returns
bool
Precondition
Nothing
Postcondition
Returns if the network has successfully connected
Definition at line 384 of file GenericFunctions.cpp.
{
     return (createNetwork && networkConnected);
 }
References createNetwork, and networkConnected.
networkConnectionStatus()
bool GenericFunctions::networkConnectionStatus ()
Gets the connection status of the network (if it is connected to either a client or server)
Returns
bool - true if connected
Precondition
Nothing
Postcondition
returns the connection status of the network
Definition at line 337 of file GenericFunctions.cpp.
{
     bool networkStatus = network.ConnectionStatus();
     return (networkStatus);
 }
References networkManager::ConnectionStatus(), and network.
networkEnd()
void GenericFunctions::networkEnd ()
Ends the connection to the network (if client)/Kills the server (if server)
Precondition
Nothing
Postcondition
Gets the active state of the network menu
Definition at line 294 of file GenericFunctions.cpp.
{
     if (createNetwork && !networkMenuPvP) {
         network.DestroySession();
         createNetwork = false;
         networkConnected = false;
     } else if (createPvPNetwork) {
         networkPvP.DestroySession();
         pvpNetworkConnected = false;
         createPvPNetwork = false;
     }
 }
References createNetwork, createPvPNetwork, networkManager::DestroySession(), network, networkConnected, networkMenuPvP, networkPvP, and pvpNetworkConnected.
networkFixedUpdate()
void GenericFunctions::networkFixedUpdate ()
Fixed update loop for the network manager. Primarily used for object replication to improve network performance.
Precondition
Nothing
Postcondition
Update the network on the engine's fixed update loop
Definition at line 315 of file GenericFunctions.cpp.
{
     if (createPvPNetwork && pvpNetworkConnected) {
         if (glm::vec3(luaCamPosX(), luaCamPosY(), luaCamPosZ()) !=
                 previousPos &&
             networkPvP.ConnectionStatus()) {  // This should reduce how often
                                               // the position is updated, thus
                                               // reducing how much data the
                                               // client and/or server receives
             networkPvP.ObjectPositionSend(
                 glm::vec3(luaCamPosX(), luaCamPosY(), luaCamPosZ()));
             previousPos = glm::vec3(luaCamPosX(), luaCamPosY(), luaCamPosZ());
         }
         prevOpponentPos = opponentPos;
         opponentPos = networkPvP.ObjectPositionReceive();
         if (!getReceivingData()) {
             opponentPos = prevOpponentPos;
         }
     }
 }
References createPvPNetwork, getReceivingData(), and pvpNetworkConnected.
Referenced by TestScene::fixed_update().
networkGetMessage()
std::string GenericFunctions::networkGetMessage ()
Gets a message received across the network.
Returns
string - The message received by the network manager
Precondition
Nothing
Postcondition
Sends the retained message across the network
Definition at line 378 of file GenericFunctions.cpp.
 { return incomingMessage; }
References incomingMessage.
Referenced by networkSendMessage(), and networkSetUsername().
networkPvPConnectionStatus()
bool GenericFunctions::networkPvPConnectionStatus ()
Gets the connection status for the pvp network manager.
Returns
bool
Precondition
Nothing
Postcondition
Returns true if the pvp network manager has successfully connected (automatic success for the server)
Definition at line 341 of file GenericFunctions.cpp.
{
     bool networkPvPStatus = networkPvP.ConnectionStatus();
     return (networkPvPStatus);
 }
References networkManager::ConnectionStatus(), and networkPvP.
networkRetainIP()
void GenericFunctions::networkRetainIP (std::string savedIP)
Retains the IP address entered by the user (catches input that the user has entered with guiManager)
Parameters
savedIP - ip address to retain
Precondition
Nothing
Postcondition
Retains the IP address that has been entered by the user
Definition at line 346 of file GenericFunctions.cpp.
{
     if (savedIP != "") {
         currentIPAddress = savedIP;
     }
 }
References currentIPAddress.
networkRetainMessage()
void GenericFunctions::networkRetainMessage (std::string savedMessage)
Retains the message entered by the user (catches input that the user has entered with guiManager)
Parameters
savedMessage - message to retain
Precondition
Nothing
Postcondition
Retains the message that has been entered by the user
Definition at line 352 of file GenericFunctions.cpp.
{
     if (savedMessage != "") {
         message = savedMessage;
     }
 }
References message.
networkRetainUsername()
void GenericFunctions::networkRetainUsername (std::string savedUsername)
Checks if the chat message in networkGetMessage is valid or not.
Returns
bool - if the chat message is valid or not
Precondition
Nothing
Postcondition
Sends the retained message across the network
Definition at line 388 of file GenericFunctions.cpp.
{
     if (savedUsername != "") {
         username = savedUsername;
     }
 }
References username.
networkReturnRetainedIP()
std::string GenericFunctions::networkReturnRetainedIP ()
Returns the IP address saved by networkRetainIP.
Returns
string - Returns the retained IP address
Precondition
Nothing
Postcondition
Returns the retained IP address
Definition at line 409 of file GenericFunctions.cpp.
{
     return (currentIPAddress);
 }
References currentIPAddress.
networkReturnRetainedMessage()
std::string GenericFunctions::networkReturnRetainedMessage ()
Returns the message saved by networkRetainMessage.
Returns
string - Returns the retained message
Precondition
Nothing
Postcondition
Returns the retained message
Definition at line 358 of file GenericFunctions.cpp.
{
     return (message);
 }
References message.
networkReturnUsername()
std::string GenericFunctions::networkReturnUsername ()
Returns the username saved in networkRetainUsername.
Returns
string - the username saved by networkRetainUsername
Precondition
Nothing
Postcondition
Returns the username stored by networkRetainUsername
Definition at line 407 of file GenericFunctions.cpp.
 { return (username); }
References username.
networkSendMessage()
void GenericFunctions::networkSendMessage ()
Sends the message saved in networkRetainMessage across the network.
Precondition
Nothing
Postcondition
Sends the retained message across the network
Definition at line 362 of file GenericFunctions.cpp.
{
     char messageChar[512];
     if (network.GetServer()) {
         strcpy(messageChar, message.c_str());
         strcat(messageChar, "\n");
         network.MessageSend(messageChar);
         incomingMessage = network.GetName();
         incomingMessage.append(messageChar);
     } else {
         strcpy(messageChar, message.c_str());
         strcat(messageChar, "\n");
         network.MessageSend(messageChar);
     }
     networkGetMessage();
 }
References networkManager::GetName(), networkManager::GetServer(), incomingMessage, message, networkManager::MessageSend(), network, and networkGetMessage().
networkSetUsername()
void GenericFunctions::networkSetUsername ()
Sets the username of the player.
Precondition
Nothing
Postcondition
Sets the username of the player using the retained username
Definition at line 394 of file GenericFunctions.cpp.
{
     char messageChar[512];
     if (network.GetServer()) {
         strcpy(messageChar, "Changed their name to ");
         strcat(messageChar, username.c_str());
         incomingMessage = network.GetName();
         incomingMessage.append(messageChar);
         incomingMessage.append("\n");
         networkGetMessage();
     }
     network.ChangeName(username);
 }
References networkManager::ChangeName(), networkManager::GetName(), networkManager::GetServer(), incomingMessage, network, networkGetMessage(), and username.
networkUpdate()
void GenericFunctions::networkUpdate ()
Updates the networkManager (primary used for sending/receiving data). Current use is for connected clients and connection status.
Precondition
Nothing
Postcondition
Updates the network manager so that it can send/receive data packets (primary use is for receiving data packets).
Definition at line 306 of file GenericFunctions.cpp.
{
     if (createNetwork && networkConnected) {
         incomingMessage = network.ReceiveMessage();
         if (incomingMessage != " ") {
             // printf("%s Update\n", incomingMessage);
         }
     }
 }
References createNetwork, incomingMessage, network, networkConnected, and networkManager::ReceiveMessage().
Referenced by TestScene::update().
networkValidChatMessage()
bool GenericFunctions::networkValidChatMessage ()
Checks if the chat message in networkGetMessage is valid or not.
Returns
bool - if the chat message is valid or not
Precondition
Nothing
Postcondition
Returns true of the chat message was a valid message
Definition at line 380 of file GenericFunctions.cpp.
{
     return network.HasReceivedChatMessage();
 }
References networkManager::HasReceivedChatMessage(), and network.
resetSaveSinceLastSave()
void GenericFunctions::resetSaveSinceLastSave ()
Resets the time since the last save.
Definition at line 147 of file GenericFunctions.cpp.
{
     last_save_time_ = glfwGetTime();
 }
set_if_credits_active()
void GenericFunctions::set_if_credits_active (bool val)
Set the if credits active.
Parameters
val
Definition at line 190 of file GenericFunctions.cpp.
 { credits = val; }
References credits.
Referenced by TestScene::key_controls().
setIfFullLoad()
void GenericFunctions::setIfFullLoad (bool val)
Set if game should load objects from scratch.
Parameters
val - If it should load objects from scratch
Precondition
Nothing
Postcondition
sets value
Definition at line 166 of file GenericFunctions.cpp.
 { shouldFullLoad = val; }
References shouldFullLoad.
Referenced by TestScene::loadSavedGameObjects().
setifHelpMenuActive()
void GenericFunctions::setifHelpMenuActive (bool val)
Sets if the game should show the help menu.
Parameters
val - set true to show help menu
Precondition
Nothing
Postcondition
sets value
Definition at line 186 of file GenericFunctions.cpp.
 { helpMenu = val; }
References helpMenu.
Referenced by TestScene::key_controls().
setIfLoad()
void GenericFunctions::setIfLoad (bool val)
Set if game should load objects from save.
Parameters
val - If it should load objects from save
Precondition
Nothing
Postcondition
sets value
Definition at line 157 of file GenericFunctions.cpp.
{
     shouldLoad = val;
     if (val) {
         last_load_time_ = glfwGetTime();
     }
 }
References shouldLoad.
Referenced by TestScene::loadSavedGameObjects().
setIfPaused()
void GenericFunctions::setIfPaused (bool val)
Sets if the game should be paused.
Parameters
val - set true to pause game
Precondition
Nothing
Postcondition
sets value
Definition at line 170 of file GenericFunctions.cpp.
{
     EngineTime::set_pause(val);
     if (val) {
         glfwSetInputMode(ReflexEngine::get_instance().window_.get_window(),
                          GLFW_CURSOR, GLFW_CURSOR_NORMAL);
     } else {
         glfwSetInputMode(ReflexEngine::get_instance().window_.get_window(),
                          GLFW_CURSOR, GLFW_CURSOR_DISABLED);
     }
 }
References EngineTime::set_pause().
Referenced by TestScene::key_controls().
setIfSave()
void GenericFunctions::setIfSave (bool val)
Sets if the game should be saved.
Parameters
val - If the game should be saved
Precondition
Nothing
Postcondition
sets value
Definition at line 140 of file GenericFunctions.cpp.
{
     shouldSave = val;
     if (val) {
         last_save_time_ = glfwGetTime();
     }
 }
References shouldSave.
Referenced by TestScene::saveGameObjects().
setIfShouldShoot()
void GenericFunctions::setIfShouldShoot (bool val)
Sets if the player should shoot.
Parameters
val - True if the player should shoot
Precondition
Nothing
Postcondition
gets value
Definition at line 216 of file GenericFunctions.cpp.
{
     if (lastShot < glfwGetTime() - shot_delay) {
         shouldShoot = val;
     } else if (val == false) {
         shouldShoot = val;
     }
 }
References shouldShoot.
Referenced by TestScene::key_controls().
setLastShot()
void GenericFunctions::setLastShot ()
Sets when the last shoot was fired (time of this function being called)
Precondition
Nothing
Postcondition
sets last shoot
Definition at line 214 of file GenericFunctions.cpp.
 { lastShot = glfwGetTime(); }
setNetworkMenuActive()
void GenericFunctions::setNetworkMenuActive (bool active)
Sets the network menu to be active or not.
Parameters
active - true if menu should be shown
Precondition
Nothing
Postcondition
Creates/destroys the network menu
Definition at line 251 of file GenericFunctions.cpp.
{
     networkMenu = active;
     if (networkMenu) {
         glfwSetInputMode(ReflexEngine::get_instance().window_.get_window(),
                          GLFW_CURSOR, GLFW_CURSOR_NORMAL);
     } else if (!networkMenu && !EngineTime::is_paused()) {
         glfwSetInputMode(ReflexEngine::get_instance().window_.get_window(),
                          GLFW_CURSOR, GLFW_CURSOR_DISABLED);
     }
 }
References EngineTime::is_paused(), and networkMenu.
Referenced by TestScene::key_controls().
setPlayableArea()
void GenericFunctions::setPlayableArea (uint8_t * heightmap, TexturedTerrain * tt, float scale, int size)
Definition at line 225 of file GenericFunctions.cpp.
{
     // m_heightmap = heightmap;
     m_tt = tt;
     m_playable_floor_size = size;
     m_playable_floor_y_scale = scale;
 }
References m_playable_floor_size, m_playable_floor_y_scale, and m_tt.
setPvPNetworkMenuActive()
void GenericFunctions::setPvPNetworkMenuActive (bool active)
Sets the pvp network menu to be active or inactive.
Parameters
active - true if changing the pvp network menu to be active
Returns
void
Precondition
Nothing
Postcondition
Sets the pvp network menu to be active or inactive
Definition at line 413 of file GenericFunctions.cpp.
{
     networkMenuPvP = active;
     if (networkMenuPvP) {
         glfwSetInputMode(ReflexEngine::get_instance().window_.get_window(),
                          GLFW_CURSOR, GLFW_CURSOR_NORMAL);
     } else if (!networkMenuPvP && !EngineTime::is_paused()) {
         glfwSetInputMode(ReflexEngine::get_instance().window_.get_window(),
                          GLFW_CURSOR, GLFW_CURSOR_DISABLED);
     }
 }
References EngineTime::is_paused(), and networkMenuPvP.
Referenced by TestScene::key_controls().
setShotDelay()
void GenericFunctions::setShotDelay (float delay)
Sets delay between shots.
Parameters
delay - The delay between shots
Precondition
Nothing
Postcondition
sets delay
Definition at line 215 of file GenericFunctions.cpp.
 { shot_delay = delay; }
References shot_delay.
startNetworkServer()
void GenericFunctions::startNetworkServer (bool active)
Starts up the network server.
Parameters
active - true if starting the network server
Precondition
CreateNetworkManager called (for initialisation)
Postcondition
Server started
Definition at line 262 of file GenericFunctions.cpp.
{
     if (active && !networkMenuPvP) {
         network.SetupServer(username);
         networkConnected = true;
     } else if (active) {
         networkPvP.SetupServer(username);
         pvpNetworkConnected = true;
     }
 }
References network, networkConnected, networkMenuPvP, networkPvP, pvpNetworkConnected, networkManager::SetupServer(), and username.
timeAtLastLoad()
int GenericFunctions::timeAtLastLoad ()
Gets time when the game was last loaded.
Returns
int - When the game was last loaded
Definition at line 153 of file GenericFunctions.cpp.
 { return last_load_time_; }
References last_load_time_.
timeAtLastSave()
int GenericFunctions::timeAtLastSave ()
Gets time when the game was last saved.
Returns
int - When the game was last saved
Definition at line 151 of file GenericFunctions.cpp.
 { return last_save_time_; }
References last_save_time_.